### ISSUE TITLE
Only one stage of bonsai tree able to be put on table.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1000]
For consistency sake either no bonsai tree variants should be put on the table or the rest of them should be able to be put on table (preference to make them all go on tables over removing one.)

https://onetech.info/1815-Wet-Young-Yew-Bonsai-in-Bowl Goes on table while every other bonsai item cannot.

**Comment by HimitsuGato** [comment]
I am team "bonsai trees go on tables" If you've even grown, or been to a showcase of bonsai they are almost exclusively displayed and trained on tables or benches. 
![image](https://github.com/jasonrohrer/OneLifeData7/assets/46429268/de56a44a-2d3b-4d97-ae46-ca6db66965fe)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/46429268/47e3b70f-efff-4687-96a2-c15071ac80ba)
