### ISSUE TITLE
Invulnerable on horse from hostile animals

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1001]
I think it makes sense that cars/trucks/planes/ protect you from bears/wolves/boars but I feel like having attack transitions for at least bears to attack horse carts would be fine. Lazy trolls like to lure bears with horses so if people are gonna grief with horses it should have some sort of risk involved.

A car/truck/plane are going to be much harder to grab because they're stored so they either risk being attacked on foot or horse. This could be used to grief horse carts but this is already something that can be done in game via snakes in the desert.

**Comment by jasonrohrer** [comment]
My only concern here is that long-distance travel is supposed to be pretty care-free on horses, etc.  You don't need to be scared about a boar hiding behind a tree or whatever.

I'm tempted to make only bears attack horses to deal with this.

Though it does make sense that metal vehicles are even more care-free than a horse for long-distance travel.

Also, I might be missing something... but isn't it true that not even a road can protect you when you're on a horse (or running on the road)?  So if a boar crosses the road at the right moment, you can be killed even when auto-running down the road?

**Comment by Wotte** [comment]
Maybe one solution could be to make the bear only chasing people by foot ? and not people on the horse ( or in a car ) Witch solve both problem : People can't bring too much bear at once like Tarr explain and bear wont chase you on the road ( still have no luck if a bear is on road and you hit him, but that make sense to die if you run into a bear right ? ahah )

I get hit by a boar and wolf on the road so many time, but i think it's part of the deal, if you intend to solve this, for make road safer maybe people can build something to make the road secure like a wall for prevent to be attack by anything but people can walk thought it and not the wolf, bear and boar, so people have to make a bit of effort to built it and secure the road. But the major problem on this solution is that people will probably build it all around the city.

ps: Thanks for all the update you made ! :D
And sorry for my terrible English ^^
