### ISSUE TITLE
Waste Problem: Big City, Big Straw 

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#1006]
The longer a town lives, the more straw piles becomes a problem.

This picture below is from random city 2 weeks ago. 
(source: onemap. https://onemap.wondible.com/#x=-370219&y=120&z=30&s=17&t=1683862482)

![image](https://github.com/jasonrohrer/OneLife/assets/61180955/4c732147-0a71-43ef-b06a-0916442a582c)

There are over 40 piles in the picture. 
If you zoom out (onemap link provided above), you can see that there's more than 15 more straw piles in the town.

==============

This picture below is from Content town (the current longest living family line).
(source: onemap. https://onemap.wondible.com/#x=-324572&y=271&z=28&s=17&t=1676243304)
![image](https://github.com/jasonrohrer/OneLife/assets/61180955/9ab91f1c-3273-465f-9e77-bf648b990e50)

It's NOT a problem of people not making enough compost. 

As you can see in the picture, there are at least 70 tiles of compost.

There's also over 90 piles of straw.

=========

Straw is a problem for big cities. 

Currently, there are a couple of ways to deal with it. There's only so much compost you can make.

NONE of them are fun.

1. Turn them into baskets.
- very tiring, repetitive. does not get rid of the problem. since you do not need 100s of baskets. but makes the tile walkable/passable by people.

2. Use a horse cart or truck to haul it away.
- gets old quick. 

3. Dump them in the town edges.
- what usually happens. still annoying to do and clutters the town up. also makes a part of the town unwalkable.

=========

But the problem is that when you make a solution for this. 

It should not be easy for the griefers to take advantage of.

Then the problem would BECOME that there's NO straw for compost.

**Comment by HimitsuGato** [comment]
Two words: hay bales.

**Comment by Wotte** [comment]
Or you just put them in tracks so you can walk thought them ..

(I like the torch solution too 🔥)

**Comment by jasonrohrer** [comment]
So the pipeline here is from wheat production, which is used to make loads of foods (pies, bread, tortillas, etc).

I think the easiest solution is to just have straw rot away eventually, if it's not used soon enough.  If you want to make compost with it, do it.  If you just pile it up, it eventually rots away to nothing.

**Comment by jasonrohrer** [comment]
Also nice that "rotting away eventually" can't be griefed, because it's outside anyone's control (unlike a burn pile, which a griefer could initiate against straw that you were intending to keep).

**Comment by jasonrohrer** [comment]
Okay, more details about how this will work:

Seems like only the piles of straw will decay.  If you have a particular plan for straw, keep it out of a pile (like while you're working with it, or keeping a fenced "buffer" of straw for compost).

Piles of straw will decay away after... let's say 2 hours.

But also, manipulating the pile at all (adding, removing straw) will reset this timer.  So if you're actively using a pile (like the main piles used for active composting), they won't ever decay away.  You are "airing" them out by moving the straw around.

I will actually add a state that occurs after 1 hour, where the pile changes visually and becomes damp, but then goes back to normal after some kind of fluffing operation.

If you let the damp pile sit for another hour, it decays away to nothing.

**Comment by jasonrohrer** [comment]
Fixed by 0716c2c92f63e04c08d0e9d2a87b4f12fa5c13d5

**Comment by Wotte** [comment]
It's a really good idea !
