### ISSUE TITLE
Running Paver West stuck into the right tile of Bear Cave

### ISSUE THREAD

**Issue by Wotte** [jasonrohrer/OneLifeData7#1010]
There is a running paver west stuck into a Bear cave tile ( the right side ).

Here a picture : [https://ibb.co/nz5XK0Y](https://ibb.co/nz5XK0Y)

I can't take it off with hand no matter what race i am (I try).
Its happen on actual official server, so you can check it directly.

I have no idea of how it's happen.

**Comment by jasonrohrer** [comment]
It seems like letting the paver itself run out of uses (by picking it up over and over after it runs into things and stops moving) would also end in the same issue, correct?
