### ISSUE TITLE
Request Transition: Charcoal to Kiln

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#1012]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/c8b1694d-c8b8-43cf-bfde-b02d6d69f91c) 
![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/f751c99f-f65d-43e6-bdde-59d7eb42ee9e)

Many a time, I find myself trying to place the basket of charcoal to the adobe kiln (NOT the forge) to find that it's not a possible transition.

It is quite exasperating.

Oftentimes, in most mid to advanced towns, some sort of charcoal factory (see picture below) are the norm.

So you'd often find yourself trying to place your charcoal into the adobe kiln.

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/3852fa7e-3b0a-4ed6-af33-5246d9424472)
(photo source: ohol discord)

**Comment by Forman9** [comment]
OMG yes this is one of the most annoying things haha

**Comment by jasonrohrer** [comment]
I can understand why you'd want to do this.... but....

https://www.reddit.com/r/Pottery/comments/4kmq0u/is_charcoal_fuel_ever_used_in_pottery_kilns/

It really wasn't done, except if throwing in some charcoal at the end to achieve a reducing atmosphere for certain effects (like to change the color of a glaze or whatever).

Charcoal, on the other hand, is much better for forging than plain wood.

Regarding the way towns are set up, with a charcoal factory... that's cool.  But there should probably be a separate pottery area, if there's a lot of pottery being made.

One of the goals of this game is to represent how things are actually done in real life, as much as possible.  Building a fire from scratch takes 20 or so steps, and you actually learn the process that would work in real life, if you were to apply those same steps in real life.  You don't just put some steel together and press a button to make an engine.  You have to machine each and every individual metal part.  And it's a wood-fired kiln, not a charcoal-fired kiln.
