### ISSUE TITLE
Walls not consistent 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1020]
Cannot put boards on painted corner walls to denote what a building is/put up signs.

Cannot put boxes on stone walls like you can adobe walls. 

Would be nice to have the option to make either type of wall so buildings look less goofy. People end up making horizontal walls plaster for boxes on walls and stone vertically because those walls can’t be boxed (without looking bad)

**Comment by jasonrohrer** [comment]
Added shelves to stone walls was easy.

Unfortunately, with the painted walls and signs, there's a combinatoric explosion.  There are 8 sign configurations, with the locked and unlocked versions, and then there are 7 different adobe/plaster/painted wall corners.  That's 56 new combinations.  The transitions could be handled with patterns, but creating the objects themselves would be very tedious and error-prone.  I'm okay with signs being only on stone walls.  I need to focus my energy (which is fleeting) elsewhere.
