### ISSUE TITLE
Escaped Horse Cart Reset timer when charging stuff.

### ISSUE THREAD

**Issue by Wotte** [jasonrohrer/OneLifeData7#1023]
The Escaped horse cart could have the timer of escape reset every time we put or remove a thing from the cart. So the horse is still escaping if you do nothing but it's less annoying for people and make sense that when you come back to a horse to put things into the cart you make sure he stay still at least a bit more.

**Comment by life4ants** [comment]
I love that idea, but I'm not sure if the code is set up for that to work

**Comment by jasonrohrer** [comment]
The horse is supposed to be annoying.  It's a wild horse that you've captured and harnessed up.

But yes, it's true that the code isn't currently set up to "notice" when objects are added/removed from a container and trigger transitions (like resetting a timer) based on that.
