### ISSUE TITLE
Fleeing Rabbit is not biome-locked

### ISSUE THREAD

**Issue by MrMendeleev2** [jasonrohrer/OneLifeData7#1026]
Fleeing Rabbit is not biome-locked right now. 
https://github.com/jasonrohrer/OneLifeData7/blob/bc339e37b2727e539927ed5a459d8c14556016b0/objects/3566.txt#L10

Before https://github.com/jasonrohrer/OneLifeData7/commit/12217772eaaf5b48597305e35d3b1526751af74e it was locked in yellow.
I suppose it was unintentional.
![Screenshot_142](https://github.com/jasonrohrer/OneLifeData7/assets/91346213/a72a4f1b-60eb-43b6-9b11-53dbf515883b)

**Comment by Wotte** [comment]
I had same yesterday
![Screen Shot 07-03-23 at 06 39 PM](https://github.com/jasonrohrer/OneLifeData7/assets/1755160/bd1c761c-61b7-49ba-b97e-7faf0bb4f4e8)

**Comment by Wotte** [comment]
And it's same for escaped horse they are not biome-locked

**Comment by MrMendeleev2** [comment]
https://github.com/jasonrohrer/OneLifeData7/commit/cb43f5a204dfe4895e31fc74cc318897908dcd57
thanks
