### ISSUE TITLE
basket of charcoal decaying to floppy deletes charcoal

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#103]
As title says if a basket goes floppy with charcoal in it the game deletes the charcoal.

**Comment by jasonrohrer** [comment]
There are a bunch of things that behave the same way.  Basket of bones, soil, charcoal, etc.

Not really sure how they should be handled.

I don't want charcoal to "protect" the basket long-term.

And I don't want to make floppy versions of all those things.

Will think about this for a bit.

**Comment by ryanb** [comment]
@jasonrohrer what if the contained item is the new actor of the decay transition? The game could find an empty tile to place the new actor object.

**Comment by trevorhackman** [comment]
Now that baskets don't decay this issue is irrelevant.
