### ISSUE TITLE
Last use of pond refill with bowl of water / Bucket of water into empty tank

### ISSUE THREAD

**Issue by Wotte** [jasonrohrer/OneLifeData7#1030]
Last use of pond could be refill with water (bowl and pouch) and we could add bucket of water to an empty tank to transport more water.

I explain my thought : For people like me who try to make our village survive, village need water, there is two option for water in late game, ask ginger for kerosen or Bring water from pond far south or north, the problem is that clicking a lot to fill buckets with bowl make me use the last use of pond, witch is not we want cause in one week the pond will only refill 1 bowl of water instead of the 20% chance. So if we can put back the last water of a pond, that make us not loose one week of the refill.

And for the bucket of the water refill empty tank, it's only for transport more easily water, not only in the case i have explain. 

**In resume :** 
![image](https://github.com/jasonrohrer/OneLifeData7/assets/1755160/0427e03d-25b6-4d62-bad8-6df089ecf7c1)
Could have reverse
![image](https://github.com/jasonrohrer/OneLifeData7/assets/1755160/a96dbfd3-0758-4a22-ad9a-e1a57e2e79b4)
Could have reverse

Thanks you for reading !

**Comment by cordy-123** [comment]
> 
> I explain my thought : For people like me who try to make our village survive, village need water, there is two option for water in late game, ask ginger for kerosen or Bring water from pond far south or north

You can also make an additional well. There's gonna be a wet spring available at 200 tiles from town.

**Comment by cordy-123** [comment]
> 
> the problem is that clicking a lot to fill buckets with bowl make me use the last use of pond, witch is not we want cause in one week the pond will only refill 1 bowl of water instead of the 20% chance. So if we can put back the last water of a pond, that make us not loose one week of the refill.
> 

Yeah, families DO NOT survive for more than a week.

Exceptions are towns that are well-loved and well-protected by HETUW players, like Content fam, etc. 
Those towns are always supplied with kero since the pro players favor them.

**Comment by Tarr-OHOL** [comment]
This can be closed. You can't put water back into a pond because people would spam click the bowl on the wells/ponds to essentially instantly drain them. I understand adding back in the last water to potentially get more but you're not supposed to get water from ponds/wells after a certain point.

Feels weird to try to pour a bucket back into the tank, if you've got water like that needing stored it's why we have cisterns.

**Comment by Wotte** [comment]
> Yeah, families DO NOT survive for more than a week.
> 

It's true only cause one moment of the day population is low (about 40), that not a reason to not fix the issue for when population is bigger.


> You can't put water back into a pond because people would spam click the bowl on the wells/ponds to essentially instantly drain them. I understand adding back in the last water to potentially get more but you're not supposed to get water from ponds/wells after a certain point.

I said the **Last use** of pond should be refillable, nothing else, that don't cause any problem if that only the last use who have reverse. 
Here what will happen : People use pond like always, just when it's empty, they can put one bowl of water back into it, but they can't put more than one, and they can empty it again with the last one who only give you one bowl of water, i don't see the problem here..



> Feels weird to try to pour a bucket back into the tank, if you've got water like that needing stored it's why we have cisterns.

I don't see what is weird about put water in a tank, that make the water "transportable" (travel-able ?), witch is not possible with cisterns like you've said.

**Comment by Wotte** [comment]
> Yeah, you can't pour water from a bucket into a narrow-necked tank like that. You can dip the tank in the well to fill it, of course.

Oh i get what you mean, you are right : You can probably fill a tank in the cistern then ? if you want make it more real the two last use of cistern you cannot fill cause of the height of the tank ^^ That even a better solution and real ^^
I do not know if you can remove directly 4 use from the cistern to fill the tank and make condition that the cistern need to have at least 4 to fill the tank.


> I think is okay for you to need to be careful here. If you spam click without watching closely, you can fully drain the pond, which kinda "ruins" it. And that's okay.

Yes it's totally fine for me, i just try to find the best solution for people to have the less frustration possible ^^

Thanks for your reply ! It's very appreciated ^^
