### ISSUE TITLE
Request: Sharp Stone for Harvesting Carrots 

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#1036]
_**What is the biggest annoyance in the game?**_ (Excluding griefers.)

A whole 3x3 block of carrots (sometimes it's even two 3x3 blocks) that are about to seed when you already have 5 bowls of carrot seeds.

_**What's even more annoying?**_

The fact that every nearby tile is occupied.

You'd have to pick the carrot, walk 5-10 tiles, drop the carrot, go back and do it all over again. Multiplied by 40+ times.

----

Example photo:

![image](https://github.com/jasonrohrer/OneLife/assets/61180955/76710680-e43d-4085-aa1d-cb9b5010dbe8)

Photo Source: https://discord.com/channels/328215300279500800/328215300279500800/1126309120140652665

----

Even IF there was space to drop the carrots on the tile beside them. (Which oftentimes, there is not.)

NO ONE wants to harvest 45 carrots (9 tiles x 5 carrots). 

That's just not fun, spending 3-5 minutes harvesting carrots. 

That's a CHORE.

----

Another problem with it is using carrots for sprinkles makes for plenty of harvesting work.

Since carrots are in the top 5 most useful crops, it would be nice to be able to use carrots for sprinkles and not have to spend time harvesting 50+ carrots IMMEDIATELY because it's going to seed.

---

**Solution requested:**

Taking a sharp stone to the carrots would dig them up, leaving them in the same tile where they were planted. Just not turning to seeding carrots.

Like how harvesting cabbage and dill works.

----

Yes, I acknowledge that it could be used to 'grief'. So that there are no more carrots left to seed if someone harvested all the carrots by the new method.

But that can also be said about harvested cabbage and dill. Although, of course, carrot is a more important crop, therefore, it would cause a bigger problem.

But the alternative is choosing between having to harvesting 40+ carrots yourself or saying fuck it and letting 9+ more tiles of carrots go to seed cause you can't be fucked to harvest so many carrots.

---

Yes, you could say, just pick all the carrot seeds and place them in bowl and wash them away with water. 

That's even more annoying than picking the carrots.

Because 1. you've lost resources that way (water, soil, and iron) and 2. you actually have to click more that way vs harvesting the carrots.

**Comment by jasonrohrer** [comment]
First of all, I'm never going to change it to automate harvesting of anything.  It's supposed to *feel* mostly like what it feels like in real life to actually do something.  So, for example, there's no "combine 3 different items in a menu and watch a progress bar" crafting in this game.

And picking stuff is tedious.  Like... wouldn't it be great to just click a bush with an empty bowl and get a whole bowl of berries?  But that's not what picking berries feels like.

Regarding carrots going to seed... is part of the problem that they go to seed too fast?

**Comment by cordy-123** [comment]
> First of all, I'm never going to change it to automate harvesting of anything. It's supposed to _feel_ mostly like what it feels like in real life to actually do something. So, for example, there's no "combine 3 different items in a menu and watch a progress bar" crafting in this game.
> 
> And picking stuff is tedious. Like... wouldn't it be great to just click a bush with an empty bowl and get a whole bowl of berries? But that's not what picking berries feels like.
> 

I'm not suggesting that carrots be moved to a different tile automatically.

Ok, maybe I should have used the word "Cut" or "Dug" instead of "Harvest"

I'm suggesting that when you hit a Carrot Row with a Sharp Stone, it will dig out the carrots which stops the Seeding Process:

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/37f54c58-5841-45fc-b205-afd7b64da87f)

In the same way that Dill and Cabbages are cut to stop the Seeding Process.

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/cd0e3540-3fd0-41a9-8d03-3c1dceb98f30)

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/e077ee50-d7f2-48b5-9f87-c3b237ca3324)

**Comment by cordy-123** [comment]
> 
> Regarding carrots going to seed... is part of the problem that they go to seed too fast?


Currently, carrot rows seed at 5 minutes. Which I think is an appropriate time. https://onetech.info/400-Carrot-Row

**Comment by Wotte** [comment]
I think to fit more the reality it's should be a shovel and not just a sharp stone, my grandfather used to do that, leaving the carrot on the ground a day or two after dug them up to make them more conserved.

But i think it's not a big problem, just replace 3 tile by 3 box and put the carrot inside, you can even make a track cart to put 8 bowl of seed in one tile.

But still if you make carrot able to be dig up like potato, it's could be nice.
