### ISSUE TITLE
Being on impassible object and blocked north tiles creates prisons.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#104]
![trapped](https://user-images.githubusercontent.com/43919588/50425582-2b61ad80-0848-11e9-8d36-1e03e91764d0.jpg)

As stated. You can't leave an impassible object through the south side. If anything blocks the north you are trapped and in this case trapped until you die. This issue is the same reason why newcomen prisons work.

**Comment by jasonrohrer** [comment]
How do you end up standing there?  I mean, in screen shot, how did you walk onto those stumps in the first place?

This is working as intended, because when a door slams "in your face," you can't just walk south through it, like a ghost.
