### ISSUE TITLE
cracked (worn out) shears cannot be used on the mango tree

### ISSUE THREAD

**Issue by plasticbrrr** [jasonrohrer/OneLifeData7#1041]
just a tiny issue, but shears that are visually worn out/cracked can't be used on mango trees to make mango tree cuttings. they worked fine on other trees (at least rubber and maple, not sure about others), but not on mangos.

**Comment by cordy-123** [comment]
Yes, a LOT of shear usage have NO Last Use transition. 

You can check "Show more ways..." in https://onetech.info/568-Shears-tool.

The sheer amount of hat and rose combinations alone are mind-boggling.

But even excluding the hat parts, there's still a bunch with no Last Use Transitions.

But yes, a bunch of tree stages don't have Last Use Transitions.

----

This is true as well for the mallet https://onetech.info/467-Mallet-toolMallet.

----

Generally, I just teach the newbie player and say it's too broken.

And give her a newer tool.

---
