### ISSUE TITLE
simplified newcomen

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLifeData7#1042]
The newcomen right now is the most difficult water source to operate, and it tends to kill towns that don't have at least 1 advanced player who both knows how to use it and wants that to be their job.

I'd be worried about balance changes with something drastic like removing the rubber requirement, though ability to know how to make that is a big barrier itself. However, some alternative transition paths to make using the well itself more intuitive might make it easier.

as it is they have to know tire->water bucket->coal->fire to cycle the well.

however I don't think that order needs to be so strict. eg allowing something like 
water bucket->tire ->coal 
or 
coal->water bucket->tire

It'd be a lot of transition combinations, though I think ultimately make its use more discoverable.

**Comment by TwistedHBG** [comment]
If changing this keep in mind this commit https://github.com/jasonrohrer/OneLifeData7/commit/b6bc09547bc068d7958dab0b72fff6adc365ec33

**Comment by jasonrohrer** [comment]
Yeah, I think this is fine as it is.  I mean, it's been this way for years now.  It's supposed to be very hard for a town to survive long term.  Survival is the rare exception, not the rule.
