### ISSUE TITLE
Permanent attacking pit bulls

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1043]
Rarely, I see an attacking pit bull which is "stuck" in the attacking animation. It is not dangerous and cannot be interacted with in any way, but it renders that tile completely unusable.

I suspect the cause may be a missing last transition.

**Comment by oholsuggestions** [comment]
Did you see Bennie the Ketchup dog? I love having a glitched out pitbull, it's a great rp addition haha.

**Comment by jasonrohrer** [comment]
Ah, nice catch!

It does have to do with the last use issue.  If the attacking pitbull is on his very last use, there's no transition to the post-attack phase.  In that case, he should transition to being old directly.
