### ISSUE TITLE
disposing of letters

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLifeData7#1049]
it'd be nice to be able to trash pit them, or kindling them.

quirky has gotten into making signs with full dashes in the middle of nurseries. And it's kind of annoying to dispose of them.

they do kind of pile up when people make the wrong ones too.

**Comment by oholsuggestions** [comment]
Yes, I whole-heartedly agree! 

Plus it would be nice get the ability to shovel it twice to make a deep trash pit. This could be used for grown animal bones, maybe even bb bones? The animal pens are always such a pain to clean up after a griever kills all sheep/pigs.
