### ISSUE TITLE
I can't login and I can't, TOTALLY, can't do a accont

### ISSUE THREAD

**Issue by YouDontNeedToKnowNow** [jasonrohrer/OneLifeData7#105]
HELP ME
I WANT PLAY BUT I CANT LOGIIIIN

**Comment by jasonrohrer** [comment]
Please email me for help:   jasonrohrer AT fastmail DOT fm

**Comment by YouDontNeedToKnowNow** [comment]
So, How I Solve This?

Em sex, 4 de jan de 2019 16:00, Jason Rohrer <notifications@github.com
escreveu:

**Comment by YouDontNeedToKnowNow** [comment]
Oh Sorry I used Gmail to answer but the answer Go to Thais site.

Em sex, 4 de jan de 2019 16:00, Jason Rohrer <notifications@github.com
escreveu:

**Comment by YouDontNeedToKnowNow** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Anyone: Make Shaggy A DLC In Mortal
Kombat 11" e queria saber se você pode ajudar assinando também.

A nossa meta é conseguir 150.000 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/mb7RQJFGtP

Obrigado!
Antonio Carlos Neto
