### ISSUE TITLE
Suggestion RE: Tree planting

### ISSUE THREAD

**Issue by oholsuggestions** [jasonrohrer/OneLifeData7#1050]
Problem: We are unable to plant Willow trees and Bald Cypress trees. These trees do not have a unique droppings, however for decorative purposes it would be lovely if we can plant them as well.

If there is a preference for unique droppings I would suggest dropping two logs for the Bald Cyprus trees ~(costing double the amount of hungry work)~, possibly without the additional firewood. 

I also found[ information](https://uphomely.com/is-willow-wood-good-for-anything/) on how Willow bark has traditionally been used to reduce fevers.  Perhaps we can use that to cure yellow fever quickly? We could mash up its leaves and boil it on coal to make a strong , fever relieving tea.

**Comment by jasonrohrer** [comment]
Yes, those strange pneumatophores that grow up from their roots are really a swamp-only feature.

I'll make both of these cultivatable in the swamp only.  I'll also make them unique in that they don't need water to cultivate (since they're in a swamp already).
