### ISSUE TITLE
QOL stuff

### ISSUE THREAD

**Issue by new2pcs** [jasonrohrer/OneLifeData7#1051]
I see you patched green beans, assuming for QOL. Some ideas here.

- Empty backpack scoop charcoal.

- Skewers stacking even if not weak.

- Stackable rabbits.

- Carrying multiple flat stones.

- Antenna place on table or box.

- Disassemble lathe attachment.

- Fill empty tank with water buckets. (maybe with funnel)

Can't really think of more on the spot, maybe the comments will have more ideas.

**Comment by Forman9** [comment]
Coal being scooped by a pack is a really good idea

I would add that large objects should be able to take up an entire pack slot

Things like:
Axe and other large tools
Wheat/Straw
Reeds
Bottle
Flat stone
....just to name a few

**Comment by jasonrohrer** [comment]
Pile of rabbits already fixed in a12c8ff

**Comment by jasonrohrer** [comment]
Non-weak skewers can't be stacked, b/c there's no way to track their use status individually in the stack.  Some of them could be partly worn out.  I could make it so the stack could only old brand new ones, but that would be confusing.

**Comment by jasonrohrer** [comment]
Lathe head deconstruction happened in 913fe68

**Comment by jasonrohrer** [comment]
Ah... for the other things that could go solo in a backpack...  I'm going to leave those out for now.  That's what the cart is for.

The fact that a pile of soil can go in both the basket and the backpack is in there for a very old reason (from back before baskets existed, I think).  Charcoal is now in there for consistency (because it behaves a lot like soil in how it can be piled).

**Comment by jasonrohrer** [comment]
Piling up meats on the ground, cooked or raw, is just too different from what people would actually do.  That's why you can only do this with the furry dead rabbits, not the skinned or cooked ones.

**Comment by jasonrohrer** [comment]
Dry bean pods can already be "stacked" in a bowl.  Made fresh peppercorn clusters work this way too.

**Comment by jasonrohrer** [comment]
534a10e64ffff8bd36c8292956e7f54f168ebdd0
