### ISSUE TITLE
Bear cave disapear when blocking entrance

### ISSUE THREAD

**Issue by Wotte** [jasonrohrer/OneLifeData7#1052]
Everything in the title and i give video : 

https://github.com/jasonrohrer/OneLifeData7/assets/1755160/ffe4ad5e-4879-4f78-8b77-d5d784c86e74

I don't know if that on purpose or not so i report it ^^

**Comment by jasonrohrer** [comment]
Yes, this is a weird one.  The bear has nowhere to go.  But I think I can fix it so that the bear will land back on its cave and keep the cave there too.
