### ISSUE TITLE
Write on the back of the photo ?

### ISSUE THREAD

**Issue by Wotte** [jasonrohrer/OneLifeData7#1055]
Could be nice to be able to write on the back of the photograph, like "me and my cuz" or we can even write the date of the photo !

Could be a simple Charcoal Pencil on the photo : like writing a letter.

The problem i see to that is that if the picture is showing in the middle of the screen we cant see what our character will say at same moment.

And i don't know if that too much work to show directly the text next to the photo.

**Comment by jasonrohrer** [comment]
Hmm... the writing system is already used for the photographs, which is where the ":A PHOTO BY SALLY SMITH" comes from (that's already stored as writing on the photograph).

Allowing you to add to this text would involve some pretty deep changes.
