### ISSUE TITLE
Psilocybe mushroom's effects lasting into next life.

### ISSUE THREAD

**Issue by Octopentv** [jasonrohrer/OneLifeData7#1056]
Died of old age while under the effects of psilocybe mushroom and was reborn with the effects intact. The effects were essentially permanent(did not go away over time) although stopped after eating another psilocybe mushroom.

**Comment by oholsuggestions** [comment]
Yes, I believe this is intentional. As you noticed the cure is to eat another shroom. But not everybody knows this, which is a fun tidbit to explain to new players. Teach your bbs and teach them well!

**Comment by Octopentv** [comment]
I doubt that, since after eating the shroom in the second you enter another 'trip' where sprites get reshuffled and then it resets once that is done. Not a coder but would guess death doesn't reset the shroom state but reaching the end of a shroom trip does.

**Comment by TwistedHBG** [comment]
This is a know thing, and while it wasn't intentionally added, it was intentionally left in

**Comment by jasonrohrer** [comment]
How did you know that you really died?
