### ISSUE TITLE
Suggestion RE: Animal rugs

### ISSUE THREAD

**Issue by oholsuggestions** [jasonrohrer/OneLifeData7#1057]
Problem: We currently only have one type of rug (bear skin) and can only place it on wooden and stone floors. This limits the ability to create different looking rooms/cities.

Solution: 
1. Adding more rugs i.e. mouflon hide (3), seal skin(3), rabbit fur(6), wool(3), wolf skin(4) and snake skin(12). This could be done by sewing multiple skins with thread and needle, to create a 1 tile rug. It will allow for more diverse city decor, and add another use to these animal skins.

2. Allow these rugs to be placed on pine floors as well.

**Comment by jasonrohrer** [comment]
This is more of a new content suggestion, and not really an inconsistency.

Bear skin rugs are an obvious thing, and the only real use of the bear currently.  That's why they're in there.
