### ISSUE TITLE
forum sticky for bug reporting only links here

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#106]
The "Bug Discussion" forum [sticky note](https://onehouronelife.com/forums/viewtopic.php?id=3984) links to [this page](https://github.com/jasonrohrer/OneLifeData7/issues) twice (to report "Issues with content" and "Issues with the game program itself").

I only just found the other set of bug reporting [here](https://github.com/jasonrohrer/OneLife/issues), and I suspect it was supposed to be linked in that sticky post. 

(So probably my bug reports are in the wrong spot. Sorry bout that.)

**Comment by jasonrohrer** [comment]
Fixed
