### ISSUE TITLE
Camera sometimes eats photo paper

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1060]
Sometimes, when taking a photo, you do not end up getting back an unfixed negative. The camera just returns to the empty state instead, effectively wasting the photo paper you used.

I believe this may be due to a transition that causes the Camera Taking Photograph to decay into an Empty Camera after a few seconds. Perhaps this is leftover from the old camera behaviour?

**Comment by jasonrohrer** [comment]
There is some behavior in place where it waits 10 seconds for a response from the photo server.  If no response arrives (photo server offline or unreachable), then it gives up and the camera will "eat" the photo paper in that case.

This might be a little confusing.  It has to do *something* if the photo server is unreachable.  Maybe it should give you a ruined negative back in that case.
