### ISSUE TITLE
Glass must be removeable and stackable

### ISSUE THREAD

**Issue by Solbusaur** [jasonrohrer/OneLifeData7#1064]
Problem: Glass cannot be stored outside of bowls. The material is not left available for future use without wasting precious bowl space.
It should have the same forge-and-forget option as steel, copper and iron

Solution: Removable from bowls by hand when cold. Can be put back in for forging with tongs of course. Stackable up to six units.

**Comment by Forman9** [comment]
I would add glass should be scrapable
