### ISSUE TITLE
Inconsistent firebrand lighting

### ISSUE THREAD

**Issue by Solbusaur** [jasonrohrer/OneLifeData7#1065]
Problem: Can only relight straight shafts on fires, forges ovens and kilns. Unable to relight on any firing newcomen machinery, pumps or fractional distillers.

**Comment by Forman9** [comment]
I think you should also be able to light a fire brand on another fire brand and directly light tinder (can you?)

**Comment by jasonrohrer** [comment]
Oh, you can already light kindling and tinder
