### ISSUE TITLE
Can't manipulate bottles on tables in certain ways

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLifeData7#1067]
For example, cannot insert a funnel into a bottle on a table.

Maybe this has to do with the +contFoodDish thing.... do we block transitions that don't produce an object with the same +cont tag?  If so, need to fix by adding those tags to all phases of each bottle.

I think we can pour a glass of wine on the table... but need to test this.  This would work because the resulting full wine glass has +contFoodDish, I think.

**Comment by TwistedHBG** [comment]
You can definitely pour a glass of wine on the table, I do it all the time. Ingame as well

**Comment by jasonrohrer** [comment]
You've always appreciated the finer things in life, Twisted!

**Comment by jasonrohrer** [comment]
In testing, it's really the funnel in the bottle that's a problem.  I think that object is permanent and non-containable.

**Comment by jasonrohrer** [comment]
And permanent objects can't be containable, hmmm..
