### ISSUE TITLE
How to build this game

### ISSUE THREAD

**Issue by milan1miki** [jasonrohrer/OneLifeData7#107]
Hi,
I am new to github, i can't find any usefull information about how to build this project. Is there any good forum/thread somewhere or someone who can explain it in one answer?

**Comment by AlecYawata** [comment]
This game released in here.
http://onehouronelife.com/

Or steam
https://store.steampowered.com/app/595690/One_Hour_One_Life/

You have to buy account-key from jason, and connect to server if you want to play with us.


You can build with this information.
http://onehouronelife.com/compileNotes.php?nocounter=1

Or with Windows.
https://onehouronelife.com/forums/viewtopic.php?id=1438
