### ISSUE TITLE
Accidental sprinkler creation is now hard to fix

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1070]
I've noticed it's really common for those working on pumping oil with a diesel engine to accidentally create sprinklers instead of oil spigots, since both are just a fuel injection nozzle + a pipe bent into some shape. This wasn't really an issue before the last update, since you could just hit it with a hammer to get the nozzle back. Now that dismantling sprinklers take two people, however, it leads to the awkward scenario where the person pumping oil has to travel potentially thousands of tiles away to find someone to help them undo their mistake (pumping oil is often a lonely job far from the rest of civilization).

It would be nice if newly created sprinklers could be dismantled without needing two people, similar to how newly created property fences are shaky and can be removed by yourself. It would also be nice if you couldn't accidentally make sprinklers by using a nozzle on a regular pipe and instead need to hammer the pipe into an East-West Pipe first.

**Comment by Forman9** [comment]
I was immediately thinking about that when the update went through

To add, cannibalizing old sprinkler systems for parts (including pipes for oil) is now basically impossible

Having two people would require two players with two trucks (they are often far away) and enough life to make it back to base

**Comment by jasonrohrer** [comment]
Whoops... it was an oversight that nozzle on bare pipe makes a sprinkler.  It also works on the east-west pipe, but it shouldn't work just on the bare pipe.

**Comment by jasonrohrer** [comment]
Let's see if that change is enough to help with the problem.  I can revisit again later, if needed.
