### ISSUE TITLE
Container Dumping vs Placing

### ISSUE THREAD

**Issue by oholseven** [jasonrohrer/OneLifeData7#1072]
Basket of charcoal, bowl of glasswort ash, bowl of sand, these contained items can't be placed on the ground, but have to be exchanged with another item otherwise the contents are dumped.  Any way of making it similar to a bowl of corn kernels or wheat which allow the container to be placed on the ground first?

**Comment by jasonrohrer** [comment]
Water tanks getting filled with funnel is hard to fix cleanly, see here:  https://github.com/jasonrohrer/OneLifeData7/issues/1051#issuecomment-1727805055
