### ISSUE TITLE
Spawning as Eve Should Always Be a Menu Option

### ISSUE THREAD

**Issue by Forman9** [jasonrohrer/OneLifeData7#1073]
The fundamental issue I see with OHOL, is that players are FORCED into limited play scenarios.

Players should be able to VOTE with their birth with respect to where/how they want to play, not be FORCED by certain (same) players who are constantly manipulating game mechanics to force people to play in THEIR scenario.

**Allowing players to Eve when they want will free up the gameplay.**

Another issue is that families are far too large and this is solved by there being more eves (see point 8 below)

As the game exists now, eves just keep going back to old towns and nothing ever changes.
I've witnessed this carry on for literally weeks where there are no new towns to play in.

Some Advantages of this change:

1. Every player can always choose to play by themselves, even on big servers
--> although its possible to do this on small servers gameplay feels limited due to lack of outside activity

2. Always an option to start something new

3. Eve doesn't have to feed kids they don't want to play with
--> When you consider this in the context of trust/curse, players could create white-listed families

4. Eve is leader and can exile players if they start acting badly
5. Less likely that Eves will be inexperienced players and

6. More Eves in the world means more options for players spawning normally
--> This effectively allows players to VOTE with their birth with respect to where/how they want to play

8. Player base will likely be more distributed throughout more families
--> This is good because right now there are often too many players in one family
--> This causes the family to burn through gameplay too quickly (and water/oil) and creates conflicting goals 
      (such as where/how to build structures)

**Comment by TwistedHBG** [comment]
You can already play as an Eve whenever you want by switching to an empty server. Sure, you're not going to get any babies, but that is the same thing that would happen if anyone could become an Eve whenever they wanted because of the way math works - there's no NPCs and every character is a real player, so you need actual people to be your descendants and there's a limited amount of those in the world (and not all of them play OHOL)

**Comment by jasonrohrer** [comment]
Yeah, the eve spawn has been carefully balanced over time to keep existing families alive, etc.

Though everyone would love to be Eve (who wouldn't want to found a family?), the reality is that if everyone was Eve, who would populate the rest of the family tree under Eve?
