### ISSUE TITLE
Planted Sapling Breaks Faster

### ISSUE THREAD

**Issue by Forman9** [jasonrohrer/OneLifeData7#1077]
I noticed this a while back but it appears the planted sapling can only be used to till soil once before breaking.

The wild saplings however can be used multiple times.

**Comment by TwistedHBG** [comment]
This is intended, you shouldn't use skewers to till unless you're just starting out and haven't made a hoe yet.

**Comment by TwistedHBG** [comment]
The reason why they break instantly is because if they had multiple uses you could reset the use count simply by making and removing a home marker or using any other recipe that uses skewers, and there you would have zero reason to ever use hoes as you could just reuse one skewer forever and ever
