### ISSUE TITLE
Domestic Milkweed and Saplings

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1082]
Both of these plants are missing domestic versions. This means that when they are grown and harvested, they do not leave behind a hardened row. This makes them more difficult and expensive to farm, since modern tools like the plow are ineffective. Currently, I think many players do bother to go through the trouble of farming them and just look farther and farther from town to get what they need, which isn't sustainable for large cities.

**Comment by TheMingo888** [comment]
Regarding milkweed specifically, I realize that it and rope in general has already been brought up in similar issues (#321, and more recently #1074, #1075, #1076, #1078). I think the reason for this is that currently, due to farming milkweed being so inefficient, the best way to collect more rope for a town is just to drive a truck north or south a few hundred tiles and gather it from the wild. This isn't very enjoyable gameplay, and it prevents towns from ever reaching a point where they feel "self-sustainable".

In real life, though, we have many such options for making rope and thread. Widely domesticated crops such as flax, cotton, hemp, and jute come to mind. There have been many inventions designed to weave these fibers into rope. In fact, even [straw was widely used for rope](https://en.wikipedia.org/wiki/Saekki) until the invention of synthetic fibers (and cities usually have tons of straw piling up as a waste product).

If making a domestic version of milkweed is too difficult due to its many transitions, perhaps you would consider one of the alternatives above?

**Comment by TheMingo888** [comment]
Whoops, forgot about glasswort, too. A domestic version of it would be nice to alleviate desert farming with plows and sprinklers.

**Comment by DopiePanda** [comment]
This should absolutely be looked into. Having to run sometimes 400+ blocks away from town to find milkweed for thread or a rope is awful, especially for newer players trying to make one of several different recipes requiring string and/or rope.

Better terms for cultivation or natural regeneration would easily solve this.

**Comment by wiogit** [comment]
I've always wondered why I seem to be the only one planting milkweed. I guess the soil cost is why. A town can be starving for rope and then eventually someone with a truck comes by with a bunch of lassos. It feels cheap.

**Comment by jasonrohrer** [comment]
Yeah, I'm still okay with this.  The fact that it takes 2 soil to grow instead of one... I mean, how much food are you consuming to take a long trip to find a bunch in the wild, instead of just growing it?

It's also okay that a few things work differently, or have different constraints around them.  It's cool (to me) that there's a trade-off here, and that the correct play isn't 100% obvious, and that sometimes "the rope man" comes around with a big cart full of wild-harvested rope.

I hear you on the other more advance ways to make rope, like hemp or whatever.  Maybe someday.
