### ISSUE TITLE
Digit Text Options

### ISSUE THREAD

**Issue by Hopie-OHOL** [jasonrohrer/OneLifeData7#1085]
Having to spell out numbers with their long name makes it difficult and confusing to share ages, distances, timings, and coordinates. This is especially difficult when you are young and only have a few letters. People get confused before you’ve finished spelling long numbers.

Example:

“Go -1834, +562”
vs. 
“Go one thousand eight hundred thirty four meters west, five hundred sixty two meters north.”

“Ur” “40”
vs.
“Ur” “fo” “ur” “ty” (starves)

**Comment by jasonrohrer** [comment]
Yeah, this is intentional.  MLA standards (good writing) says you're not generally supposed to mix digits with text.  And comic characters never would have digits mixed into their speech bubbles.

**Comment by Hopie-OHOL** [comment]
> Yeah, this is intentional. MLA standards (good writing) says you're not generally supposed to mix digits with text. And comic characters never would have digits mixed into their speech bubbles.

Hi Jason, thanks for taking a look. MLA format for numbers says that a number longer than one or two words should be written out in digit form. For example, correct formatting would be typing "twenty eight" with words and "1,423" with digits. I've attached a .pdf with number-specific MLA formatting rules.

Comic books also regularly have characters speaking using digits. Attached are two examples-- one from XKCD, one from Calvin and Hobbes. 
[The Rules Regarding the Use Numerals in APA and MLA styles.pdf](https://github.com/jasonrohrer/OneLifeData7/files/12705250/The.Rules.Regarding.the.Use.Numerals.in.APA.and.MLA.styles.pdf)
![XKCD_Digit](https://github.com/jasonrohrer/OneLifeData7/assets/145514068/8f15d3d5-ebde-4a71-8bf3-d2c6e8f90881)
![Calvin_Hobbes_Digits](https://github.com/jasonrohrer/OneLifeData7/assets/145514068/880b6477-fafc-4e74-a8c2-cc0cf5f989b7)
