### ISSUE TITLE
Add Caret 

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLifeData7#1086]
It's getting frustrated if you have a typo in your message, and you have to delete all your message to correct it. Adding carets to players' message boxs will help a lot.

Communication is an important aspect in the game, it should be made as easy as possible. Writing is harder and slower than speaking, so it should be adjust with convenient tools.

**Comment by jasonrohrer** [comment]
You mean so you can move the cursor in what you type with arrow keys?

Given the "simulated paper" complete with erased pencil in that message box, this request is more challenging than it seems to be...

It's also very weird, given the simulation of pencil on paper.... you can't go back and erase a single word or letter in the middle of a pencil sentence without erasing the entire tail of the pencil sentence, leading up to that point.  The pencil words can't just "move backward" magically.

This may seem silly to you, but if you inspect the in-game user-interface carefully, you will discover that every aspect of the UI works exactly as it would work if it were real, physical pieces of paper.  Info doesn't just disappear, it is erased and leaves traces behind.  Pieces of paper slide in and out from view.  You never see text just "flick" out of existence.
