### ISSUE TITLE
Let's Talk About Carts

### ISSUE THREAD

**Issue by selb** [jasonrohrer/OneLifeData7#1089]
#1080 made me think about why carts don't really serve the kind of utility purpose I think you had in mind.

If you craft carts regularly, you end up seeing most of them turned into horsecarts. The problem is that horsecarts don't serve the same utility purpose because of the incessant flee mechanic. It's painful to do involved farming tasks when your horsecart needs constant petting. Petting the horsecart is a reasonable tradeoff when you're covering great distances, but in-town it doesn't make sense, especially since it's harder to grab a horsecart with a ton of items and players around.

Similarly, a horsecart is completely useless if you're fertile because a baby will inevitably force you to abandon it, so you're better off searching in vain for a handcart then giving up and just schlepping items by hand or with a basket despite living in an advanced town.

It would be nice if we could remove carts from horses, or if non-rubberized horsecarts had a harder time fleeing.

**Comment by TheMingo888** [comment]
The other trouble is that both regular and rubberized hand carts decay, so a mature town may have lots of horse-drawn carts, but few to none hand carts as they all fall apart. Attaching the cart to a horse allows "preserving" it but just makes it way more annoying to use around town as the horse always tries to run away.

**Comment by selb** [comment]
To clarify why horsecarts are more annoying in towns than the wilderness: cluttered ground causes flee behavior to cover long distances and stop on unexpected spots, and more players to flee from makes the movement unpredictable. Without a zoom mod, an escaped horse cart on a farm might as well be on the moon, and even with a zoom mod the horse will often move faster than you until it's out of town.

**Comment by cordy-123** [comment]
I would say, I often see a bunch of hand carts more often in Snow fam or sometimes Language fam. Especially if they are far east or west from the Desert fam.

**Comment by cordy-123** [comment]
A great suggestion I read somewhere (sorry to whoever it was, I can't remember where I read it so I can't give credit) was that every time you removed OR placed an item in the horse cart, it would RESET the timer for fleeing.

So it still flees fairly quickly since the flee time is the same. 

But it's not so bothersome when you're actively using it.

**Comment by jasonrohrer** [comment]
Yeah, containers don't go through transitions when stuff is inserted or removed.

I had forgotten that the hand carts decay.  That's kinda vestigial at this point.  I will change that, and also think about a way of letting you remove the cart from the horse.
