### ISSUE TITLE
Fed bear becomes hungry after attacking player

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#109]
According to [Onetech](https://onetech.info/628-Grizzly-Bear), Grizzly Bear (fed) transitions into Hungry Grizzly Bear (attacking) when encountering a player. 

Seems to me that attacking a player should make the bear become fed, not the other way around. Unless it's a "hungry for blood" kind of thing.

**Comment by jasonrohrer** [comment]
Yes, hungry for blood.  I want it to attack multiple people on a rampage.

It only gets fed with mutton.

Also, it simplifies the game logic if a bear becomes hungry again after attacking.
