### ISSUE TITLE
Reopened with additional info: Digit text options

### ISSUE THREAD

**Issue by Hopie-OHOL** [jasonrohrer/OneLifeData7#1093]
Referencing issue #1085 

Hi Jason, thanks for taking a look at my previous issue. I have some additional info regarding digits matching MLA formatting and comic book text. 

MLA format for numbers says that a number longer than one or two words should be written out in digit form. For example, correct formatting would be typing "seventeen" with words and "1,423" with digits. I've attached a .pdf with number-specific MLA formatting rules.

[The Rules Regarding the Use Numerals in APA and MLA styles.pdf](https://github.com/jasonrohrer/OneLifeData7/files/12705367/The.Rules.Regarding.the.Use.Numerals.in.APA.and.MLA.styles.pdf)

This article on grammar tradition has a section on numbers in comic books-- the general rule is that numbers larger than 20, dates, and designations should be written with digits. 

https://blambot.com/pages/comic-book-grammar-tradition

Comic books regularly have characters speaking using digits. Attached are two examples-- one from XKCD, one from Calvin and Hobbes.

![XKCD_Digit](https://github.com/jasonrohrer/OneLifeData7/assets/145514068/9be8fdaf-3f97-4929-8013-89ab9d6a581a)

![Calvin_Hobbes_Digits](https://github.com/jasonrohrer/OneLifeData7/assets/145514068/5028cfa2-61f2-4a12-9039-5c0ae94bc6c0)

With this in mind-- I believe it's reasonable to add digits to OHOL without grammar concerns. It matches MLA, it matches the recommended number formatting for comic styles, and there's ample precedent with popular comics.

**Comment by TheMingo888** [comment]
When it comes to huge numbers, especially beyond 100, it is quite cumbersome to type it all out with words. For example, compare "one thousand seven hundred ninety-four" with "1794". This might seem like a rare problem, but communicating distances (say, to other towns) is a really common problem, so I'd love to see some improvements in this regard.

Since comics have to make speech bubbles fit into small spaces, they take advantage of using digits to deal with large numbers. We have the same problem in OHOL since you can only send so many letters in one message.

**Comment by TwistedHBG** [comment]
This issue was JUST closed yesterday, it's rude to just reopen it because "no uhh actually"

**Comment by jasonrohrer** [comment]
I'm pretty firm about this.  For most day-to-day uses, like asking how many rubber tires we have left or whatever, the numbers are small, and should be spelled out.  If I allow digits, people are going to use them all the time, and it looks ugly and not comic-like.

"We have 2 left, but it would nice to have 3 more."

I can't allow digits while also preventing this.  People will also do stuff like "b4" and such.

For long distances, I see why this is a pain, and not even inline with MLA style guidelines (which I'm aware of, for long numbers, and I don't spell those out in my own writing).

However, if we're talking about distances, it seems like that's what maps are for.  Where's the jungle town?  Here, look at this map that I made.  The person will instantly read the distance from the map (along with getting an arrow over there).

**Comment by Hopie-OHOL** [comment]
Fair enough, thanks for taking a look.
