### ISSUE TITLE
Alternative to track carts as storage

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1097]
Storage is and always has been a big problem. Take clothing as an example. During peak hours, there might be 25 people in a town, resulting in 25 sets of clothing. During low-pop hours, that same town might only have 5 people. This means there needs to be some way to store the extra 20 sets of clothing lest it remain strewn across the farm and kitchen in various piles of bones.

Traditionally, wooden boxes have been used, but they can only hold 4 large items and block movement. Adding the boxes to plaster (or now stone) walls is an improvement, since the walls were already blocking movement. However, this is still not nearly enough, especially when you consider that the maximum size a room can be is only 7 x 7 before it loses the indoor bonus (which is very important for rooms like the nursery which are used to store spare clothes).

The solution most players have been using for a long time has been track carts. They can hold 8 large items and don't block movement, allowing compact storage of large items like clothing. I have also seen them be used in kitchens to hold spare plates and bowls or with baskets to hold 8 * 3 = 24 raw mutton in a single tile (which is necessary given how easy it is for one player to kill literally all of the sheep in a few seconds). The image below shows the nursery of a random town found on onemap.wondible.com. You can check out other towns yourself, and you will find the same pattern everywhere.

![MinecartNursery](https://github.com/jasonrohrer/OneLifeData7/assets/23004012/8e466ef1-8dc1-4262-9480-23112c477c3b)

While track carts work well enough, it would be nice to have something better designed for stationary storage beyond wooden boxes. It could be something specifically designed for clothes or general purpose (since, as I mentioned above, these track carts are used in kitchens and other rooms too). Whatever you decide, it needs to be at least as good as the track carts:
- It should hold at least 8 large items.
- It should not block movement. (If it did, it would prevent compact storage like you can see in the photo above.)
- It should not be prohibitively expensive. Track carts are relatively cheap, just needing a tiny bit of labour to make the spring and lay the track down in the right orientation.

If your solution is not as good as the track carts are, probably nothing much will change. To be clear I am _not_ suggesting the track carts be nerfed, since using them for actual moving storage is already difficult enough (since they only move when a player is near, preventing actual long-distance rail lines).

**Comment by cordy-123** [comment]
https://discord.com/channels/328215300279500800/328215300279500800/953670231572762684

jasonrohrer:
Building a closet today
Is the lack of closets in OHOL an issue?

:D

**Comment by cordy-123** [comment]
Since we are talking clothes organization.

From http://onehouronelife.com/forums/viewtopic.php?id=10871#p109744

wio:
[wio](http://onehouronelife.com/forums/profile.php?id=3456)
"I also find it hard to distinguish unworn clothing by appearance. Except for shorts, just look like wrinkled up sheets. At least it should be more clear by appearance whether something is a shirt or skirt or whatever."

The amount of times I try to put a shirt on my kid and it ends up being a cloak or worse a ghost costume.

**Comment by cordy-123** [comment]
Also from the same forum post:

wio
"Create clothing exclusive storage (e.g. hat racks, shoe lockers, etc.) so it's easy to determine what clothing it stores."

**Comment by jasonrohrer** [comment]
Players are a clever bunch!

Yeah, this is a tough one to fix in a non-stupid way.

The carts do not block movement because they are supposed to be moving objects, and they might move past you, etc.  But actually, for such a large object, it's very silly that you can just walk through it.  I'm sure it looks weird, like you flash through it.  The carts are larger than many other things.

**Comment by SoloAceMouse** [comment]
> The idea of adding some other stationary box that's just as big, but that you can walk right through, is not going to happen.

In this case, could we possibly get a way to store clothing items as small items.

Currently a shirt is a large item, which means it cannot be stored in many containers, nor can it be stacked.
In real life, I can bunch a shirt up into my palm and easily jam four shirts into a backpack.

Perhaps you could allow shirts/pants/skirts/dresses to be folded into a small item like so:
1) Right-click normal shirt -> folded shirt ... a small item (but unequippable)
2) Right-click folded shirt -> normal shirt ... large item (wearable)
The folded items could re-use half of the sprite from item 2890 [https://onetech.info/2890-Skirt-and-Shirt] so no new art is necessary and return to their current sprite when unfolded

I believe this compromise would alleviate storage issues while preserving the system as much as possible.

**Comment by jasonrohrer** [comment]
For the clothing, I think it's fine that they all look like crumpled piles when set down.  A skirt isn't like a flat board when it's not on your body.  When you carry a skirt, or set it on the ground, it's a crumpled pile.
