### ISSUE TITLE
Lacking Transition - Stuck without Kerosene

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#1098]
All the other states of the Kerosene Newcomen Pump, you can either remove the kerosene wick burner or remove the water (by using a tank on the wet pump) to get to a stage where you can remove the kerosene wick burner.

----

But at Kerosene Newcomen Pump with Full Boiler https://onetech.info/2349-Kerosene-Newcomen-Pump-with-Full-Boiler...

... you get stuck and are unable to use the town well if a player misjudged / misplayed while running the pump. 

If they don't realize that there's no kero/oil left in town, the town well is stuck (unable to revert back to the regular Newcomen Pump) until they get more oil from the snow fam.

----

Granted, this is quite a rare instance / stage of the well pump to be stuck at.

I've seen it only a few times in the past few years.

**Comment by Tarr-OHOL** [comment]
This needs reopened. This causes a bug with other necomen machines. See 

https://edge.onetech.info/4913

this bug is was originally happened when you could remove the wick at any point and had to be reverted.
