### ISSUE TITLE
Loose Horses

### ISSUE THREAD

**Issue by oholseven** [jasonrohrer/OneLifeData7#1101]
With biome locking now off for horses, when we find a loose horse in the wilds, we can't contain them anymore.  Juggling a loose horse and your own horse or vehicle is so tedious because of how often the horse bolts, getting in only a few steps between each. 
 Can we revisit the idea of securing them in the wilds when there's no hitch or fence posts around.  I'd rather reclaim our "tamed" (not very disciplined) horses than make them disposable items when they're ditched off-base.

So it turns out unsaddled horses are still biome locked, while "tame" horses are not.  Maybe we just switch that around?  Tame horses will stay in biomes they're placed, because they're tame.  Wild unsaddled horses led out of a desert to a new biome will run free beyond the biome.  Then we can still have a bit of control over these tamed horses, compared to wild.

**Comment by Kaden56** [comment]
Yeah Horses are a pain. Even just upping the time to maybe 1 min before they start to flee would help.

**Comment by jasonrohrer** [comment]
They are supposed to be a pain, for several reasons.  See:

https://github.com/jasonrohrer/OneLife/issues/965

However, I will make them wait a bit longer before running away.  They currently wait 7 seconds.  I will change it to 14 seconds.

**Comment by jasonrohrer** [comment]
Ugg... 14 feels way too long to me, in testing.

I will make it 11 seconds.
