### ISSUE TITLE
Invisible Slots on closed and locked chests

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLifeData7#1102]
![Screenshot (405)](https://github.com/jasonrohrer/OneLifeData7/assets/146253626/332fb210-49c8-477a-b742-f625b8ddd6f1)
You should make it so that the chests when closed have the tag "+slotsInvis" Because when you have items as big as this quiver, (for example,) they stick out and look weird.

**Comment by Tarr-OHOL** [comment]
Doesn’t this unfortunately just make any item in the chest invisible until removed? While I understand the idea behind this suggestion I believe it would require actual changes.

**Comment by Kaden56** [comment]
Nope I emulated this on my private server. a closed chest is a seperate item than an open chest.

**Comment by jasonrohrer** [comment]
Yes, Tarr, I fixed this separately without seeing this issue!

So they will work this way in the next update.

**Comment by jasonrohrer** [comment]
Fixed in e13d43b3da508de380cbd39345760a36a14cf9f8
