### ISSUE TITLE
Issue with the new gestures.

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLifeData7#1103]
When you type a gesture and you do the animation, after a while it switches automatically to a new animation, and then it cycles through the different animations until you walk away. Like if I do /wave then after a couple seconds it switches to /upyours without me doing anything. Then it just cycles.

**Comment by jasonrohrer** [comment]
I'm unable to reproduce this.

If I say /WAVE, it keeps waving forever, as far as I can tell, until I interrupt it with a move or some other gesture.

Can someone post a video of this happening?

**Comment by jasonrohrer** [comment]
Ah, this seems to be an issue with whatever mod you might be using.

These mods re-send emotes every few seconds to keep them live, and it must be doing something weird with the extra animation slots (used for body poses) when it does this.
