### ISSUE TITLE
Awkward Looking Bears

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#1104]
https://onetech.info/648-Bear-Cave-awake

I'm guessing, it's from this change https://github.com/jasonrohrer/OneLifeData7/commit/06e2334a86c756576e5ba63037e91325498a42d8

But now, at bear caves that are blocked by unpassable item, the bear just very awkwardly stays there on the bear cave tile. 
I'm guessing the transition for blocked 'AWAKE' bears to go back inside their caves was accidentally removed during that change?

Used to be if you tap a Bear Cake with 'Waking' Bear and if the cave is blocked by unpassable item, the bear would return back inside its cave immediately.

Now, the strong bear just looks very awkwardly stuck by (example) a tiny pile of stumps. 

![image](https://github.com/jasonrohrer/OneLife/assets/61180955/781913be-3539-4452-96b1-f04e24eb47b3)
![image](https://github.com/jasonrohrer/OneLife/assets/61180955/561ba0b3-a6a1-48c8-b165-cfdf06bd0a43)

**Comment by cordy-123** [comment]
For the past few YEARS, bears would automatically go right back in the cave if their path was blocked .

The change in behavior only happened around 3 weeks ago.

Which is when there was an update to bear cave https://github.com/jasonrohrer/OneLifeData7/commit/06e2334a86c756576e5ba63037e91325498a42d8

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/0d744ae2-d80f-4f32-8ba2-f4e703461cc8)

Presumably some sort of transition was edited or removed? 
(I don't know coding.)

**Comment by jasonrohrer** [comment]
Yes, I just rolled back to right before this change:

https://github.com/jasonrohrer/OneLifeData7/commit/06e2334a86c756576e5ba63037e91325498a42d8

And yes, if the front of the cave was blocked, the bear would make the cave itself disappear.

Now the bear stands on the cave itself, which is also kinda silly.

It should just go back in the cave.
