### ISSUE TITLE
Diagonal gradient dry springs do not regress

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1112]
I believe in #1096 that ShamWish was referring to well-site regression, rather than culling. Item 4085 `Well Site - just regressed` causes the eastward, southward, westward, and northward gradient dry springs to return to natural springs, but the diagonal variants are not reverted.

**Comment by oholseven** [comment]
I've been waiting on this one.  It's even more troublesome on small servers.  Someone spawns in, makes a well, knocks out all diagonal springs, never returns, well collapses, diagonals remain unusable.  They used to reset.  We have diagonal spring markers that point to no well.  We have diagonal dry springs people want to use but they never revert to wet springs after the original well resets.
