### ISSUE TITLE
Adding wick to Newcomen well breaks all newcomers 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1113]
In regards to the recent change: You didn’t overlook this issue previous, this leads to a bug that occurred before. Basically this causes all Newcomen machines to accept the wick. 

https://edge.onetech.info/4913

Update allows any Newcomen to become a kerosene well lol.

**Comment by jasonrohrer** [comment]
Fixed in 46d558fce18500b864c400ca300b4711404e1dfb
