### ISSUE TITLE
Spoon of Icecream

### ISSUE THREAD

**Issue by oholseven** [jasonrohrer/OneLifeData7#1114]
Is it possible to scoop ice cream into one bowl?  Right now if you take a spoon of ice cream, it becomes stuck to the spoon, which can only be thrown on the ground.  Spoon with ice cream can't go on a table, and the ice cream can't be added to a bowl of ice cream or an empty bowl.  So if you need a free spoon, you have to eat that ice cream or go forge another spoon.

**Comment by ShamWish** [comment]
It would be nice to decant the ice cream. If you have 3  bowls of ice cream with one scoop left you should be able to consolidate them into one bowl.
