### ISSUE TITLE
Still able to make indestructible walls with carts

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1117]
The fix for #1116 is not sufficient. It is still possible to make walls out of carts that cannot be deconstructed from one side.

![](https://cdn.discordapp.com/attachments/328215300279500800/1165079629200109598/image.png?ex=65458bf5&is=653316f5&hm=bcb1a3eb498ee6de510f86ea95ba40b637b4bdf959f5616741d551239d0595b1)

In the above image, the weak point is clearly cross track and track end. However, the track end is only accessible from the inside, and the cross track has an irremovable object (ice hole) above it preventing the cart from derailing. The result is that those on the outside are unable to break in.

It is also possible to make the inverse of this design where those on the inside are unable to break out.

This design can be scaled to be as large as desired.

**Comment by Forman9** [comment]
epic hack

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/956f456c-d6a6-4a07-88fa-bedcf66b9855)
Add Ohol Kicks, also yeah whatever he said

**Comment by SoloAceMouse** [comment]
I concur.

If people can make indestructible walls in the game, then bad actors will always have an option for enclosing and denying areas to other players.

Preventing this by making any stationary minecart deconstructible would be prudent.

**Comment by Shadie116** [comment]
> I concur.
> 
> If people can make indestructible walls in the game, then bad actors will always have an option for enclosing and denying areas to other players.
> 
> Preventing this by making any stationary minecart deconstructible would be prudent.

This guy's boring.🙄

**Comment by Shadie116** [comment]
And why is everybody so mad at me for griefing 🙄🙄All I was doing was playing clash of clans

**Comment by Shadie116** [comment]
Jason fix this or I'll teach you TCP/IP from scratch using beginners notes

**Comment by jasonrohrer** [comment]
Nice find!
