### ISSUE TITLE
VISUALS ISSUE: No Ancient Stone Wall Shelves

### ISSUE THREAD

**Issue by SoloAceMouse** [jasonrohrer/OneLifeData7#1120]
![Stone Wall Shelf Issue](https://github.com/jasonrohrer/OneLifeData7/assets/147592460/254ae452-263b-4026-b607-30a31a3a0f95)

Currently, the stone wall shelves [both standard and slot box versions] never become ancient, unlike unadorned walls.

For visual consistency, I request that stone wall shelves are changed to become ancient after 10 hours, to match the normal stone walls.

**Comment by Shadie116** [comment]
Yes I most likely agree, this is possibility

**Comment by jasonrohrer** [comment]
Okay, will do!
