### ISSUE TITLE
Unable to remove items from basket on table

### ISSUE THREAD

**Issue by Meeeeparoni** [jasonrohrer/OneLifeData7#1126]
Currently you have to place the basket on the floor to remove an item and replace the basket on the table

**Comment by Shadie116** [comment]
This happens in real life as well.

**Comment by jasonrohrer** [comment]
Unfortunately, this is a limitation of containers and sub-containers in the game.  A table is a container, and a basket is a sub-container.

You also can't remove items from a basket that is inside a box.

The implementation of sub-containers (and picking specific items from inside a container to grab with the mouse) is already very complicated and error-prone.  Being able to click inside sub-containers would be a monumental change.
