### ISSUE TITLE
Turkey Drumstick cant go on Table

### ISSUE THREAD

**Issue by ShamWish** [jasonrohrer/OneLifeData7#1129]
If you accidently grab a turkey drumstick the only place you can put it is the floor or your mouth. It would be nice if we could just set it on the table.

**Comment by ShadyAbusesComplexWebappsOneFatalFlaw** [comment]
Ok now here me out, Replace the Dr in drumstick with a C

**Comment by jasonrohrer** [comment]
You will grease up the table with that!

I will make it so you can set it on a plate, at least.
