### ISSUE TITLE
Well Griefing

### ISSUE THREAD

**Issue by GreatTits** [jasonrohrer/OneLifeData7#113]
I haven't had the opportunity to try this out myself but I think that if you just add one cut stone to a dry deep well, you will have successfully forced a civ into completing the rest of the structure, whether they want to or not.
![image](https://user-images.githubusercontent.com/45480790/49275197-603c3980-f42f-11e8-870b-c8e49033d0be.png)
(Placing the cut stone onto the well and not able to remove the cut stone)

**Comment by jasonrohrer** [comment]
Well, a dry deep well will currently refill by one unit in 10 hours.

Are you saying you really had plans for this dry well 10 hours from now, and now some griefer ruined it by trying to build a tower there?

**Comment by jasonrohrer** [comment]
Anyway, this was fixed a while back, so now you can remove the blocks from the well.
