### ISSUE TITLE
Remove troll transitions from trash pits.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1131]
Most people don't realize this but a lot of useful items can just be tossed into a trash pit:

Rabbit furs can be tossed in (but not cut furs) - Either for consistency both should go in or neither preference obviously being neither. 
Weak skewers and regular skewers can be thrown away (these stack now and neither should go in)
Needles - These stack now (therefore) no need for these to go in the trash. 
Pine needles - Stack, and probably shouldn't go in (trolls can remove the easy to use flooring used for laying out a farm)

Things that would be great to actually make trash pits useful 

Animal bones - Mouflon/sheep/pig/boar/goose bones. Weird that geese bones despawn and can't be thrown away but rabbit bones can both be thrown away and despawn. 

I'm sure others can think of more this was just stuff off the top of my head.

**Comment by selb** [comment]
Being able to trash raw mutton and pork would be helpful for cleaning up after animal-stabbing griefers.

**Comment by ShadyAbusesComplexWebappsOneFatalFlaw** [comment]
You can't get rid of me, I'm too rat like that.

**Comment by ShadyAbusesComplexWebappsOneFatalFlaw** [comment]
One more thing: Ratons are cute. Check them out rn

**Comment by ShadyAbusesComplexWebappsOneFatalFlaw** [comment]
> Most people don't realize this but a lot of useful items can just be tossed into a trash pit:
> 
> Rabbit furs can be tossed in (but not cut furs) - Either for consistency both should go in or neither preference obviously being neither. Weak skewers and regular skewers can be thrown away (these stack now and neither should go in) Needles - These stack now (therefore) no need for these to go in the trash. Pine needles - Stack, and probably shouldn't go in (trolls can remove the easy to use flooring used for laying out a farm)
> 
> Things that would be great to actually make trash pits useful
> 
> Animal bones - Mouflon/sheep/pig/boar/goose bones. Weird that geese bones despawn and can't be thrown away but rabbit bones can both be thrown away and despawn.
> 
> I'm sure others can think of more this was just stuff off the top of my head.

Quit ur yapping.

**Comment by ShadyAbusesComplexWebappsOneFatalFlaw** [comment]
> Being able to trash raw mutton and pork would be helpful for cleaning up after animal-stabbing griefers.

Or just for tossing away useful food if that's what you're into. @jasonrohrer make it so meat can be composted like irl

**Comment by jasonrohrer** [comment]
Needles still make sense, b/c they can be made in infinite quantities, just like single rabbit bones.

Furs don't make sense, of course!

**Comment by jasonrohrer** [comment]
I think the larger animal bones are too big to go in the trash pit... they must be carried in a basket, and thus can't fit the pattern anyway.

I do see that they take 2 hours to decay away, which is too long.  I will make them all take 30 minutes instead.
