### ISSUE TITLE
Turkey drumstick on plate doesnt leave a bone

### ISSUE THREAD

**Issue by ShamWish** [jasonrohrer/OneLifeData7#1133]
Eating a Turkey Drumstick from a plate won't leave behind a Turkey Leg Bone 
![image-20](https://github.com/jasonrohrer/OneLifeData7/assets/20826969/25bf4717-2622-4268-b563-5c6d18d5454e)

**Comment by ShadyAbusedGithubAgain** [comment]
Jerky Camwich

**Comment by SoloAceMouse** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/147592460/89e9a705-e69d-4ca5-b380-45c9f53240ff)

Yep, the turkey bone deficit starts to add up over the generations until you end up with tons of unusable plates.

**Comment by ShamWish** [comment]
I was hoping we could just put the turkey leg on the table or back on the turkey carcass but instead we got this. The logic that they can't go directly on the table, because it would get greasy, is silly and introduces more inconsistencies into the game. 

Other greasy foods that can go directly on a table:
Cooked goose
Cooked rabbit
Cooked mutton
Cooked mutton with rub
Cooked fish
Cooked shrimp
Cooked garlic shrimp
Cooked peppered shrimp
French fry 
French fry with ketchup
Tortilla chip
Tortilla chip with salsa
Tacos
Burritos

This is just off the top of my head. I'm sure there are more. 
Just let us put the leg on the table. New players who misclick and often end up picking up things they didn't mean to. I only suggested the change to help these players have more places to drop the turkey leg than just the floor.

**Comment by NotSoShady116** [comment]
Jason should really fix this major issue, this could be the end of the game as we know it.

**Comment by ShamWish** [comment]
I was hoping this would have been fixed by now. We're gonna have bugged turkeys on Thanksgiving! I'm gonna cry.

**Comment by jasonrohrer** [comment]
I will fix today!

**Comment by ShamWish** [comment]
Thanksgiving is tomorrow! That would be amazing if it were fixed today. I forsee and influx of turkeys on the horizon.
