### ISSUE TITLE
Decorative bones

### ISSUE THREAD

**Issue by MooseSeven** [jasonrohrer/OneLifeData7#1136]
Now that bones in baskets decay, we can no longer use them for decoration. Please consider providing us with decorative bones for builds like Halloween mazes, witch huts and the like.

**Comment by oholseven** [comment]
Basket of bones was a great item, since we have little else to use as decoration.  If people want the bones to decay, all they need to do is dump them.  Having them decay in a basket seems to ruin the reason we keep them in a basket - for decorative purposes.

**Comment by jasonrohrer** [comment]
Fix came as part of this:

https://github.com/jasonrohrer/OneLifeData7/issues/1130

There's not a specific reason why bones in a basket should decay.  They are being "kept" there and can easily be dumped out.

I will change this back.
