### ISSUE TITLE
Greedy sheep

### ISSUE THREAD

**Issue by MooseSeven** [jasonrohrer/OneLifeData7#1137]
When testing this, it seemed the sheep ate the whole row, leaving nothing behind. 
But on Onetech it looks like they're supposed to eat one carrot out of the row (number of uses 5), eventually leaving a hardened row.
It might be nice if shorn sheep could eat carrots out of rows as well.

https://onetech.info/615-Eaten-Carrot-Row

**Comment by jasonrohrer** [comment]
No, they do eat the whole row.

Just because something has uses doesn't mean that every transition only consumes one use.
