### ISSUE TITLE
Wellsites blocked after opening iron

### ISSUE THREAD

**Issue by MooseSeven** [jasonrohrer/OneLifeData7#1139]
This has happened twice recently in Eve camps:
A ring of stones are placed on a wellsite and iron is opened. Then someone blocks the wellsite before the well is built, forcing the family to move away from their mine(s). This can happen for example if a different family establishes their own well too close, or a secondary well is built. If a stone ring opens iron, the family should not be prevented from building a well there.

**Comment by Shadie116** [comment]
Rat moment

**Comment by Shadie116** [comment]
Never thought of this, we could have used this for griefing back then. Better fix it @jasonrohrer

**Comment by Shadie116** [comment]
When my eve camp was growing our neighbors straight died from us digging our well first

**Comment by jasonrohrer** [comment]
This is normal.  There is some competition for building the first real well in an area.

Also, if you unlocked iron, then the other family can use it also.

Iron is needed to dig the well, after all (shovel), which is why it works this way.
