### ISSUE TITLE
Gesture for AFK players

### ISSUE THREAD

**Issue by DopiePanda** [jasonrohrer/OneLifeData7#1144]
A suggestion from Rin_Crypt:

"Would be nice if Jason added a gesture that automatically starts if you have been inactive for 2 minutes like a sleepy gesture with zzzzz so we know AFKs by a glance"

**Comment by oholsuggestions** [comment]
I would love that! It's frustrating sometimes when you aren't sure if someone is there or not. As much as I love our potato bbs, it'll be lovely to have a bit more information that they're afk.

**Comment by jasonrohrer** [comment]
Yeah, I forgot about that complication.  If you really want to use this to detect AFK babies, it's going to be hard, b/c some baby players are present but just watching, right?

So the only real way to do it is to talk to them.  If they don't respond, they are AFK.

Auto-detecting this with the server would be misleading.
