### ISSUE TITLE
You can eat turkey bone on plate.

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLifeData7#1149]
You can eat the entire turkey bone and the plate. And it counts for a yum/craving.

**Comment by ShamWish** [comment]
I don't want to eat plates Jason. They taste bad.

**Comment by Tarr-OHOL** [comment]
Finally Jason added Pica to the game. Please add other crunchy items to the "food" pool.

**Comment by jasonrohrer** [comment]
Whoops!

**Comment by jasonrohrer** [comment]
Twisted, I know you've been actively campaigning for Pica Rights.  Now, before I fix this, is your moment to shine.

**Comment by TwistedHBG** [comment]
> Twisted, I know you've been actively campaigning for Pica Rights. Now, before I fix this, is your moment to shine.

Don't worry I recorded the weird food video already, fix away!
