### ISSUE TITLE
No buckets of beans?

### ISSUE THREAD

**Issue by Butterbraugh** [jasonrohrer/OneLifeData7#1154]
In the game one hour one life farming and crops play a major role in the lives of players. There is a certain level of realism with the way crops work. Carrots and cabbage go to seed when left unharvested. Wheat grows in stages eventually becoming dry and ready for harvest and processing. Cucumber and tomato vines remain stunted when there is no stake acting as a trellis for them to grow on. Corn needs to be shucked, left in the sun to dry, etc.

Currently there are two cereal crops, wheat and corn, as well as two commodities, palm kernels/crushed palm kernel's that can be processed in some way and piled on the ground with a bowl. These piles can then be scooped up with a bucket and transported.

Currently the bean crop can not be processed and piled in a similar manner. This really does not make sense as beans are a staple crop for many cultures throughout history. As such storage and transportation of dried beans that have been winnowed by the farmer is critical. 
There is also an in-game issue that reflects this when unwanted bean pods and bowls of dry beans generate clutter in precious garden space with no way of consolidating them.

The issue here is one of consistency with game mechanics. As well as an expectation of continuity for realism within the games scope.  

Propose a fix were the "Bowl of Cleaned Dried Beans" game object can be dumped on the ground, piled, and transported via bucket in a similar manner to other dry crops and commodities that are processed with a clay bowl.

**Comment by Shadie116** [comment]
I think this probes for a more proficient storage system to avoid having towns looking like my clothes pile

**Comment by Shadie116** [comment]
PORTUGUESE as well

**Comment by Shadie116** [comment]
@Butterbraugh what if the truth was that you always were the bean.

**Comment by Shadie116** [comment]
The bucket was just a thing you conjured up to justify your actions as a bean, the bucket is just a container to contain others who should be condemned of your sins as a man but also as a bean. Add the bean bucket...
