### ISSUE TITLE
Suggestion: Eve's random skin colour

### ISSUE THREAD

**Issue by oholsuggestions** [jasonrohrer/OneLifeData7#1157]
At the moment skin colour is used to identify which band families belong to. To reflect the reality better, perhaps we could remove race from being a biome restriction. 

A different identifier could simply be a notation by their name when you hover over a player, i.e.

- Snow - Jane Doe - mother
- Nomad - John Doe - cousin
- Jungle - Jenny Doe - no relation
- Desert - Jimmy Doe - uncle

To ensure the diversity of all races Eve's skin colour will be randomized, unless a race has died out. If a certain skin colour isn't currently alive, the next Eve would be guaranteed that skin colour.

This would also help alleviate the awkwardness of the colonization update, where only white families can settle anywhere.

**Comment by Shadie116** [comment]
I'm not too worried about diversity, I just want to give birth anywhere as any race. Basically just asking to rollback the trade bounds system and to make the game more conservative, like how it was back than.

**Comment by Shadie116** [comment]
W rizz
