### ISSUE TITLE
Bear cave fix.

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLifeData7#1159]
This has happened a lot, where someone clicks on a bear cave to check if its in there, and then some time later someone else clicks on it and the bear comes out. The person who clicked on it last normally gets blamed and cursed for "letting a bear out." When they were just checking if it was in there. So my suggestion is after you click on it once and the bear 'wakes up' the bear should go back to sleep after 10 seconds so that someone else who clicks on it doesn't lure it out.

**Comment by Kaden56** [comment]
Also if you could add a new title for a woken bear cave. Like "Awaken bear cave" or something like that so we can see the differences in the two, then that would be cool as well.

**Comment by DopiePanda** [comment]
I second this suggestion. How it is now makes little sense, why does the bear stay awake, is he trying to catch the next ding dong ditcher? 😅

**Comment by Shadie116** [comment]
No there is a natural explanation for this, every bear is cocaine bear from the popular box office slam movie "Cocaine Bear".

**Comment by jasonrohrer** [comment]
Yes, this is a good idea.

I won't put a special label on the half-woken cave, though... because how would you know that?  You can hear him breathing in there faster, or what?

**Comment by Shadie116** [comment]
Download revelations mod cuzzo!
