### ISSUE TITLE
Small Ball of Yarn

### ISSUE THREAD

**Issue by oholseven** [jasonrohrer/OneLifeData7#1161]
This seems to be on my end, as I redownloaded the game and did not experience it.  - Can't pick up the small ball of yarn left or right clicking, must be exchanged with something in order to pick it up whole without tearing it apart into thread balls.  Trying to get confirmation to see if this is a global issue, or just my issue.

**Comment by Shadie116** [comment]
that's normal, don't worry about it

**Comment by Shadie116** [comment]
no way to fix that lol
