### ISSUE TITLE
Beheading Geese is time consuming

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#1166]
People dig up tree stumps in town because they're useless so there's usually maybe 1 or 2 around if you're lucky. Having to stand around and wait for the heads to despawn PER GOOSE is very time consuming if you're trying to make a life farming them. 20 seconds each. 

Maybe despawn faster? Or let us remove the heads again? 

It's not a HUGE problem just one I run into a lot because it's my favorite job. I've wasted many minutes standing around waiting for heads to despawn.

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/6c009524-58b3-4c18-80bc-c1ffc1960504)
Yeah baby, you know it, get ratty you know it YEAH!
