### ISSUE TITLE
Empty wild gooseberry bush + stakes = domestic when stakes removed.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#117]
So I just learned you can stake wild berry bushes and turn them into domestics by staking empty bushes and removing the stakes. 

Seems like a huge oversight to be able to ruin wild berry bushes by converting them over to domestics.

**Comment by jasonrohrer** [comment]
I'm trying to keep the logic simple there.  The only reason wild can be staked is so they can be removed for building and landscaping purposes.

If you stake a bush, you take control of it, and it becomes non-wild.

The logic is simplified by not having to track the "wild" or "domestic" status through all those transitions.

And is this really a griefer tactic?  Ruining wild bushes?

Closing for now.
