### ISSUE TITLE
Egg in boiling water, should be boiled egg

### ISSUE THREAD

**Issue by Rin0de0la0crypt** [jasonrohrer/OneLifeData7#1170]
Easy yum food, gives more verity possible Easter content. I don't know programing but I don't see how this can't just piggy back off of other assets.

**Comment by Shadie116** [comment]
logic == true

**Comment by Shadie116** [comment]
#include <iostream>
#include <string>

int main() 
{

    system("color 6");

    std::string Logic2;

    std::cout << "User, please define logic as true or false\n"; 

    std::cin >> Logic2;

    if (Logic2 == "true")
    {
         system("color 2");
        std::cout << "Jason, please add this";
    }
    else if (Logic2 == "false")
    {
         system("color 4");
        std::cout << "Jason, nooo";
    }
    else
    {
         system("color 4");
        std::cout << "Logic ill-defined";
    }

    getchar();
    return 0;
}

**Comment by Shadie116** [comment]
eggs not boiling is a bug. Eggs boil

**Comment by Shadie116** [comment]
I can prove it XD but I guess you imputed false into the console
