### ISSUE TITLE
Soil and Charcoal

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#1172]
We've had stacks of charcoal for a while, and I think that's improved things.  Less clutter in town.  Firing charcoal became a simple task for players to help out which doesn't make another issue worse (at least up to a certain point).

A basket of soil has 3 units just like a basket of charcoal has 3 units (respectively, units of soil and units of charcoal).  But, they don't both stack.

If someone gets a mushroom craving early, it can make sense to go empty some soil pits so that later generations can satisfy their craving (bad part of the game.... encouraging 10 year olds to think about doing drugs... but I digress).  However, emptying some soil pits is often a solo project, and still feels awkward to me.  Moving all the soil to different spots, and a bit time consuming also.  Solo projects take time away from doing things with other players or doing something close to other players.  I suspect also that emptying soil pits would feel awkward to new players, even if/when we managed to convince them help us move soil out of pits to get the mushroom to start sprouting.

We have several baskets of soil in a compost pile.  A basket of soil has the same number of units as a basket of charcoal.  It would seem more consistent if we could stack soil piles.  Maybe experienced players wouldn't spend as much time out away from newer players.  And maybe when there's a soil pit close to the well, maybe it gets emptied out a bit quicker, dug up, that gets emptied out, we could get one piece of clay a little sooner, and then have another bowl... for someone to eat popcorn in or something.

[Older version](https://github.com/jasonrohrer/OneLifeData7/issues/875)

**Comment by ShamWish** [comment]
I see people digging out soil pits for the road to come through too. Lots of reasons to want stacks of dirt.
would be nice if you could put soil back onto the compost pile if you accidentally click it too.

**Comment by jasonrohrer** [comment]
Yes, this is a good fix.

I hope the subtle distinction is clear here between this and the boiled egg.

While the boiled egg would be quicker for me to implement than soil piles, the way baskets and soil/charcoal currently work is inconsistent.  It's not just about new content, but about making sure the existing content makes sense.
