### ISSUE TITLE
Threshed Wheat With Straw Removed No Longer Movable

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#1173]
It's possible to use a bowl to move wheat off of [threshed wheat](https://onetech.info/297-Threshed-Wheat-straw-removed).

However, it is no longer possible to move [wheat if the straw gets removed](https://onetech.info/297-Threshed-Wheat-straw-removed).   If one threshes wheat, removes the straw, then the wheat will sit there and decay and nothing else.

Rukh Dekarios pointed this out on the discord, and I tested it on a small server, (and onetech furthers confirms this).

**Comment by jasonrohrer** [comment]
Will fix tomorrow AM

**Comment by DougLefelhocz** [comment]
Bean bowl also turns into a plate.  From [BlahWizard](https://clips.twitch.tv/AmericanSparklingPangolinPeanutButterJellyTime-5t10dP1sLyXV-1vk)
