### ISSUE TITLE
Road looks funny

### ISSUE THREAD

**Issue by 3x2xShady** [jasonrohrer/OneLifeData7#1177]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/4cd978e1-1fa9-4c57-bd36-17f16c33088c)
This one road tile was on some type of perk.

**Comment by Shadie116** [comment]
Also stop stalking me tarr, you're being strange as hell that's why I blocked you

**Comment by Shadie116** [comment]
Funny thing: 
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/6b5d8a6b-165a-47f4-be07-5dc553c5af17)
the Louisiana correctional center/prison got a 3 star rating on yelp. XD

**Comment by DougLefelhocz** [comment]
Ha.  The road looks funny.  That gives us a good reason to keep it looking as it looks.  Ha Ha.

**Comment by Shadie116** [comment]
I hate it
![Screenshot 2024-01-30 233221](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/791c6413-093a-4430-a9c1-2c4af45a1e39)

**Comment by Shadie116** [comment]
lol what are these images on my comptuer
