### ISSUE TITLE
Lower the donkey town curse time to at least 6 months or a year.

### ISSUE THREAD

**Issue by 3x2xShady** [jasonrohrer/OneLifeData7#1179]
Based on previous responses there is a non-determinable chance that this will happen. The noise of a bird could change the possibly. A cockroach could change the possibility, a germ. Lower time, and I don't want to be rude but a game that you constantly update will aways have returning players so it's possible to be softlocked

**Comment by DougLefelhocz** [comment]
There is no donkey town curse time.  There exists an amount of time that players who curse another have them cursed for.  People who curse, from what I can tell, do want _their_ curse length to last 5 years.

**Comment by Shadie116** [comment]
I'm still in donkey town and people who are cursed do not want to not be able to play the game they bought

**Comment by DougLefelhocz** [comment]
You are able to play the game in donkey town Shadie.

**Comment by Shadie116** [comment]
The selling point of the game is playing with other people and 90% of the time donkey town is empty because nobody wants to play when they're soft locked in donkey town .

**Comment by Kaden56** [comment]
Yeah and the whole "selling point" of the game is to coexist and help civilization grow. Not to be a jackass and kill everyone and kill sheep and keep people from actually playing the game. Truth of the matter is... No one wants to play with you!

**Comment by Shadie116** [comment]
You're respectful

**Comment by Shadie116** [comment]
And ain't you did the exact same thing, didn't we both stop doing it at the exact same time. You're nothing but a hypocrite. Take the drama somewhere else lil boi

**Comment by Shadie116** [comment]
> Yeah and the whole "selling point" of the game is to coexist and help civilization grow. Not to be a jackass and kill everyone and kill sheep and keep people from actually playing the game. Truth of the matter is... No one wants to play with you!

I don't want your drama, you've been blocked for good

**Comment by Shadie116** [comment]
Really what I'm saying is that all the opera houses fell and nobody wants to be there anymore.  ♪ ♫ ⌑~♬♪܀⊹ ♪♫ ⋆WON'T YOU TAKE ME OUT, DONKEY TOWN!! ♪ ♫ ⌑~♬♪܀⊹ ♪♫ ⋆ There's 15 piles of bones arranged in the formation of an upside-down cross... ♪ ♫ ⌑~♬♪܀⊹ ♪♫ ⋆ON THE GROUND♪ ♫ ⌑~♬♪܀⊹ ♪♫ ⋆

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/55870521-dfc3-4cf8-86e0-216775d3c61e)
