### ISSUE TITLE
Methman Monument plans UNCRAFTABLE

### ISSUE THREAD

**Issue by 3x2xShady** [jasonrohrer/OneLifeData7#1187]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/8c901ae6-27d6-4bf6-a66f-81c008983226)
I got a full belltower but looky here :(

**Comment by Shadie116** [comment]
I'm not going to point 0 to make the first iterations of methman monument. too far and a waste of my likely 84 years left of life

**Comment by Shadie116** [comment]
you can drive to old donkey town but to point 0 is too far. Unless you make the conveyer belt run backwards

**Comment by Shadie116** [comment]
So what I'm really asking is make it easier to craft.
