### ISSUE TITLE
DONKEYTOWN Needs Biome Bands (Desert, Arctic, Jungle)

### ISSUE THREAD

**Issue by Forman9** [jasonrohrer/OneLifeData7#1192]
I've noticed that donkeytown has been improved somewhat.
Now you can have kids there which is good.

This offers a solution to the fact that people always resettle old towns in the main game and never allow for new towns.

The one issue here is that it doesn't seem like you can access the special biomes (desert, jungle, arctic)
This effectively blocks the tech tree once you need rubber (newcomen)

Placing donkeytown in the middle of the map will solve this.

And no, donkeytown would not be reachable (even by car) and if it is, just move it further away so that it isn't.

**Comment by Shadie116** [comment]
![Screenshot 2024-02-27 041448](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/d324dea9-70fb-4569-9ac1-5b08ef01a24c)
yuh me agree

**Comment by Shadie116** [comment]
every donkey will spawn at the donkey town origin is what I think would solve the issue.

**Comment by Tarr-OHOL** [comment]
Donkey town has bands. Either you’re not a donkey, not looking, or don’t know mechanics. 

Thread should be closed as this already exists.
