### ISSUE TITLE
Don't revert the curse radius

### ISSUE THREAD

**Issue by AccountAbandoned** [jasonrohrer/OneLifeData7#1198]
20$ is 20$ I spent 20$ once than my friend got me some money. I don't care what they say, ain't nobody paying 20$ again because they griefed. I'm just being frank. They don't even know that they're playing with griefers when they buy another account. All of my friends pretty much snuck back into society under a different name out of 100s via another account. They're insane I argue

**Comment by Shadie116** [comment]
also I think this whole curse issue was bound to happen and if you revert it the evildoer will just hop back on the account and I might have to find and join him.

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/c467b97a-11e1-4f96-8834-80d3fb0818fb)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/f1e1a921-9dc7-4e01-8dbc-3391140f8571)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/c66df7c6-916a-4d30-9073-89f28a91dc89)

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/1ffddf19-13e1-47f7-b383-903e9046444c)

**Comment by Shadie116** [comment]
why am I fighting a 1 v 12 against your moderation team

**Comment by Shadyverycool** [comment]
this doesn't affect me really though considering I got that new acccccounnttttt🎉🎉🎉🎉🎉🥳🥳🥳🥳🥳 AYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE. Ima just flex the corruption in your face
