### ISSUE TITLE
Inconsistent animal feeding

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#122]
You can feed a domestic lamb, hungry or not, and it becomes a fed lamb. Same for a mouflon lamb. You do not have to wait for them to become hungry. 

But for cow calf, bison calf, piglet, and wild piglet, you must wait until the baby animal becomes hungry to feed it.

**Comment by jasonrohrer** [comment]
Lamb was the first domestic animal, so I put more detail into the logic there.

For the rest of the animals, I realized that having them be feedible before hungry was too much extra work.

I could go back to the lamb and remove that, for consistency....

**Comment by trevorhackman** [comment]
Being feedable before hungry makes things easier for players cause you don't have to wait the time for the animal to become hungry and you have a longer interval to feed the animal before it dies. Things should be consistent, but I'm not sure what your intention is for the difficulty of raising new animals.
