### ISSUE TITLE
Not all Bear Cave objects have blocking properties set

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLifeData7#13]
648 Bear Cave#awake
649 Bear Cave#empty just left

These two objects have:
blocksWalking=0,leftBlockingRadius=0,rightBlockingRadius=0,drawBehindPlayer=1

**Comment by jasonrohrer** [comment]
I'm pretty sure this is intentional, because the bear needs a non-blocking spot to move out of.  I think the game engine can't handle a moving animal standing on a blocking object and moving off of it.

So in that brief moment, you can walk onto the bear cave!  It's a risky move, though...
