### ISSUE TITLE
Slow bug, framerate?

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#132]
https://clips.twitch.tv/CrowdedSparklyTrayOSkomodo

The game was is in slow motion after, not sure exactly how he did it

Version: Steam version

He was having an unknown issue (when the game is open it seems to be causing an issue, maybe related to streaming softwares but havent heard other streamers have that issue) probably alt tabbed to fix issue then on return game was in slow mo

**Comment by gitbirb** [comment]
probably something to do with low framerate + Vsync

**Comment by jasonrohrer** [comment]
Yeah, his vsync probably changed somehow...
