### ISSUE TITLE
Piles of Flint Chips

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#136]
Currently, flint chips are kinda awkward in that, yes, you can stack them... but only on the tile they were originally harvested from, and only so long as one remains on it. It makes little sense, as we can add and remove flint chips from the pile of 4- but only on that tile. Once the pile is depleted, they now only take up individual spaces and cannot be restacked elsewhere.

Given they have a sprite and such already in place, it'd make more sense if we could pile them anywhere, rather than solely on the original tile. They're small items, and it makes little sense to force them to take up an entire tile individually, when piles of them already exist elsewhere.

**Comment by trevorhackman** [comment]
Wooden Disks are kinda similar

**Comment by jasonrohrer** [comment]
Wooden disks are harder to fix because the stacked version doesn't look the same as the single version.
