### ISSUE TITLE
Shot bears create invisible wounds

### ISSUE THREAD

**Issue by CrazyEddieTK** [jasonrohrer/OneLifeData7#137]
As noted on the forum: https://onehouronelife.com/forums/viewtopic.php?pid=42287#p42287

> Did you know dying bears still bite (three arrows in) and don't have a transition for biting people in this state? This leads to invisible wounds should the bear snipe you.

Shot Grizzly Bear 3 and Dying Shot Grizzly Bear 3 need the wounding-people transition. Or, I suppose, remove the Deadly tag, but probably they should still be dangerous until they're actually dead.

**Comment by Stylingirl** [comment]
Same case goes for shot wolves and fed grizzly bears. They are deadly but no coded transition means they're invisible.

**Comment by jasonrohrer** [comment]
Fed griz was fixed earlier.

**Comment by jasonrohrer** [comment]
Actually, shot wolves are okay... just checked and tested.
