### ISSUE TITLE
Radio doesnt work if too close

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#142]
Havent tested morse close and far to each other and radio far apart, but a radio emitter and receiver close to each other dont work

Dont know at which distance it starts working

https://imgur.com/a/usZc6uD

(they are both high frequency)

**Comment by jasonrohrer** [comment]
I definitely tested this before shipping it...

Sounds like radios aren't working at all.... hmm....

**Comment by jasonrohrer** [comment]
I think this was a coordinate offset issue that was fixed a while back.
