### ISSUE TITLE
Endtower marker not working sometimes

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#143]
I was born in a village with 5-6 tier 1 endtower but didnt get any marker, closing and reopening client didnt solve issue

I even heard the endtower bell at one point but didnt get the marker for it

**Comment by jasonrohrer** [comment]
Yes, you only get the marker if you hear the bell.

And if it's too close, you don't get the marker.

Also, you're aware that you need to clear your own home marker before you can see the bell tower or endtower arrows, right?
