### ISSUE TITLE
World Keeps Resetting

### ISSUE THREAD

**Issue by catdavis67** [jasonrohrer/OneLifeData7#144]
The world keeps resetting similar to what happened back in November 14, 2018.  Just wanted to let you know so you can fix it.

Thanks,
Cathy

**Comment by catdavis67** [comment]
Here is more detail from SHE OF THE SANDS on the forums:
"Everything on the server seems to have become frozen in a time loop.

I pick up something on the ground, place it elsewhere, and then it vanishes. 
It reappears back where it was. This occurs for all plants and items, everything but people.

What is very confusing about this bug is that the sprites do not update until you interact with the tiles again.
So, it will look like I still have that object placed on the ground, but can't pick it up. 
Then, I place something on that tile, and the object's sprite updates showing it is no longer there.

I pick a banana from a banana tree and can eat it. A short time passes, and I can pick that same banana from the banana tree.
I was in a village where the server captured a container full of pies. We could just keep taking out more and more pies to eat.
The pies would vanish if we placed them anywhere, but we could hold them and eat them.

I think this bug has been mentioned several times today in different ways of explaining it.

Best Regards!"

**Comment by jasonrohrer** [comment]
All this stuff has been fixed.
