### ISSUE TITLE
Missing transition for shovel's last use with dung with hatchet egg

### ISSUE THREAD

**Issue by Leonard2** [jasonrohrer/OneLifeData7#145]
![](http://0x0.st/zrEP.png)

Compared with simple sheep dung:

![](http://0x0.st/zrEZ.png)

**Comment by betalpha8** [comment]
Also when digging potatoes.

May relate to issue #97

**Comment by TwistedHBG** [comment]
I think this might intended - the last use shovel only has ony use, and you need at least two uses remaining to pick up dung and potatoes.
