### ISSUE TITLE
Treshing wheat can only be done with straight branch and small curved branch

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#154]
Not possible with yew branch, long straight shaft etc.

**Comment by jasonrohrer** [comment]
Yes, to thresh, you really do need a "branchy" branch.  You can just hit it with a club.

Well, looking at historical pictures, they always use a hinged "flail" type stick (like a nunchuk), so I'm probably wrong about the branchy branch, but that was at least my thinking at the time.  And it's true that not all sticks will work.
