### ISSUE TITLE
Draining a water source is actually detrimental,

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#156]
I think the water regen calculations may be off (updated in [version 178](https://onetech.info/versions/178), and seen in [this issue](https://github.com/jasonrohrer/OneLifeData7/issues/79)). The intention was to have 1 bowl of water regen every hour for all water sources, right?

Take for example a pond. The last use takes 1 hour to regen. So 1 hour for 1 bowl. So far, so good.

Then after that, for any other use but the last, there's a 20% chance to regen one use every 12 minutes, so effectively takes 1 hour to regen 1 use. 

The problem then comes, there is also a 20% chance to take a use. Effectively giving 5 bowls for each use. So it actually took 1 hour to regen 5 bowls.

So instead of being equivalent regeneration, draining a water source is actually detrimental. (This assumes ideal conditions, where the regeneration timer is not interrupted by the taking or adding of water.)
These calculations have confused me to no end, so I won't take it personally if I'm mistaken.

**Comment by jasonrohrer** [comment]
You're right about this:  the last use is certain (always drains) where the other uses are not.

I could make the regen time faster from the empty state to compensate.

Deep currently produces one use every 10 hours  (one use is 4 buckets, expected)
Shallow currently produces one use every 1 hour (one use is 16.6 bowls, expected)
Pond currently produces one use every 1 hour (one use is 5 bowls, expected)

Fixing this would mean from empty, they would take:

Deep:  2.5 hours
Shallow:  216 seconds
Pond:   720 seconds
