### ISSUE TITLE
Can drain a pond by poking goose.

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#159]
A Canada goose returning to shore has 20% chance of using water. This holds true whether or not a feather is present.

Incidentally, I also discovered that there is no transition for a goose to return to shore at the lowest water level. As such, the goose will remain swimming indefinitely. This prevents shooting the goose, or regeneration of water, eggs or feathers. (The only actions being to harvest the remaining water, or add water).

**Comment by anlongyi** [comment]
Also, Canada Goose Pond has no transition for adding water if there is no egg. So you have to wait for 20min for an egg, then 12min for a chance to regenerate water.

**Comment by jasonrohrer** [comment]
The thing with an egg is a consequence of the way the engine works.  The pond can only transition to one thing, not two things.  It either grows an egg, or fills up with water.  It currently grows an egg.
