### ISSUE TITLE
Highly asymmetric cost for destroying vs building stone wall

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#160]
https://onetech.info/887-Stone-Wall

It is far more expensive to remove a stone wall than it is to build a stone wall. 
This is because it uses an entire pickaxe. The pickaxe breaks 100% of the time. 

Makes it virtually impossible to remove or modify even small stone buildings as it takes dozens of pickaxes to do, which makes building with stone really bad, and griefing with stone walls very good. 

Stone walls also turn into ancient walls which are impossible to remove. I'm not saying ancient walls are an issue itself, but it makes the problem with the expensive cost of removing regular stone walls far worse. 

Pine walls have the opposite asymmetric problem.

**Comment by jasonrohrer** [comment]
Well, they need to be very hard/expensive to remove, or else they can't be used for security.  That's the point of stone walls:  hard to break.
