### ISSUE TITLE
Came upon a bug

### ISSUE THREAD

**Issue by Profilore** [jasonrohrer/OneLifeData7#162]
[recordedGame000034.txt](https://github.com/jasonrohrer/OneLifeData7/files/2879295/recordedGame000034.txt)
It happend at the end, I tried to swap the sharp stone with the flat rock on the ground and my character started jumping in place, it persisted until i starved, and the game showed the "you found a bug" window.

**Comment by jasonrohrer** [comment]
Thanks!

In the future, please email me when this happens, so I can check the server logs.  Also, if you're on Windows, please send your stdout.txt along with your email.
