### ISSUE TITLE
Domestic Bison and Cow

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLifeData7#163]
Domestic Bison and Cows can't be killed which leads to resulting issues if multiple cows are raised.

**Comment by cordy-123** [comment]
Beef! Beef! :D

**Comment by miskas9** [comment]
you cant kill cows if you are not brown or you are more than 2 minutes away from a brown person 
Mango leaf decays on 2 minutes

**Comment by Tipy1802** [comment]
Burgers and leather clothes will be nice ;)

**Comment by Spodnie** [comment]
Could increase the time before mango leaf decays.

**Comment by jasonrohrer** [comment]
Some future update will have beef, but it's not really a bug that can be fixed for now.  Closing.
