### ISSUE TITLE
game crashes on loading

### ISSUE THREAD

**Issue by DNAmaster10** [jasonrohrer/OneLifeData7#170]
For some reason, whenever i load into the game, when it says loading sprites, it freezes half way through and crashes. My cousin is getting the same problem and it was working fine until we both got the new update. Please help !!!

**Comment by jasonrohrer** [comment]
This was fixed last week.  If you are off-Steam, you may need to do the following:

delete:
sprites/bin_cache.fcz
sounds/bin_cache.fcz
reverbCache/bin_cache.fcz

If you are on-Steam, the newest update will fix this for you.
