### ISSUE TITLE
Threshed Wheat (Straw Removed) Littering issue

### ISSUE THREAD

**Issue by TheArkanum** [jasonrohrer/OneLifeData7#173]
Is it possible to set a despawn time for the Threshed Wheat (Straw Removed)? It is literally dumped everywhere, and never despawns, and not many people turn it into something useful.

Here's the OneTech data for the item:
https://onetech.info/297-Threshed-Wheat-straw-removed

If possible, also to extend the despawn timer for the Straw, cause it goes away so fast, and its actually more useful to make baskets, adobe and such.

**Comment by TwistedHBG** [comment]
You can put it in a bowl, move it anywhere you want, and make pies and bread - people use it all the time. It's very useful and it's easily moved when in the way - despawning is not necessary, and in fact it despawning would probably be a bad thing.
