### ISSUE TITLE
Add more seed bowls

### ISSUE THREAD

**Issue by ryanb** [jasonrohrer/OneLifeData7#180]
Some seeds cannot be added to bowls which is inconsistent with the other seeds.

I would like to see carrot, milkweed, and berry seeds be addable to bowls and plantable like the other seed bowls. This would greatly reduce the clutter they make.

**Comment by TwistedHBG** [comment]
Yes, please. Seeds are tiny items that take up a lot of space, having them all in bowls like corn/squash/cabbage would be wonderful! It would also make seed mechanics more consistent.
