### ISSUE TITLE
Intersecting pump and well

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#183]
https://puu.sh/CSWMi/1e49035b72.png

I imagine this can happen whenever two ponds spawn next to eachother and that these are far from the only two things that can intersect (newcomen machines) but haven't tested it.

**Comment by jasonrohrer** [comment]
There's really no way around this... it's a tile-based game.

I actually don't think that overlap looks that bad....

They are both still functional, at least.
