### ISSUE TITLE
Partial bucket of water looks empty when held

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#184]
The partial bucket must only have a few bowls of water in it. When held looks like an empty bucket. Possibly same issue with partial buckets of other liquids. 

Partial bucket of milk has the same problem.

**Comment by jasonrohrer** [comment]
Hard to know what to do here.... From the view angle in question, it would look empty!  If the liquid was shown near the top, that would look weird for sure.

Thinking about what to do here.

**Comment by jasonrohrer** [comment]
Just spent some time trying to get a "drip" out the bottom looking right, and it's really hard.

Also tried a "splash" out the top, when walking, and that's also hard to get looking good.

I think I'm going to table this for now.

The idea is that you set it down to find out if it's empty.

You are never using it in a part-full state while held anyway, right?  You use it on the ground to dip bowls out of it....

**Comment by trevorhackman** [comment]
Well the problem is if you think the bucket is empty, there are uses for an empty bucket in your hand like grabbing water from a well or using it on a milk cow and then being very confused why it's not working cause it turns out the bucket wasn't empty and then missing the milk window on the cow. I just saw someone do that today.

**Comment by trevorhackman** [comment]
If this is tabled for later, shouldn't you have left it open? Perhaps a flair would be better than closing and forgetting about it.
