### ISSUE TITLE
Bowl/Bucket of Water look the same as Bowl/Bucket of Salt Water

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#185]
As the title says,

I've seen many players get confused by this. Trying to use a bowl or bucket of salt water thinking it's regular water.

**Comment by TwistedHBG** [comment]
I agree that this is a bit annoying, but I'm not sure what the fix would be (or if a fix is really needed). Water looks like water after all.

Maybe if the salt water bowl had actual salt on the edges, or if the salt water was a different shade of blue.

**Comment by trevorhackman** [comment]
Well I think something like a green tint for the salt water could work. Water can vary quite a bit in appearance irl, and salt water is murkier than regular water.
