### ISSUE TITLE
Curses: framers

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#186]
I see this all the time, people are framing others, and ask for curses, offer services for it, 2 lifes, ask it on discord
Now this turns slowly to big brother where you just curse or get cursed, maybe if he goes to donkey town then you wont be cursed
It still wont worth it for him really , as spends 2 lifes to send you away for 1 life or 2
but now with the limits it goes easier and easier over time

i got people who just snipe me out, if they know its me

i accept when its legit, like i closed 2 people in a room (still quite low key griefing), one player born back
and cursed me, so others went along with it

but when i was killed, and then cursed by other people who doesn't even seen me, i didn't do anything other than saying "i will stab you if you are lazy". maybe i will go along with it, its still 2 people problem. i had some lag and died, cant win them all. 
now if you go and kill this framers, you will likely get cursed for killing,but letting them alive will surely get you cursed, as if you play legit, you don't have time to go around asking people to curse people over and over.

so it should be lower time limit to curse the player, and location limit so you cant just curse others 

people who are same lineage and same location can curse

its getting ridiculous that if you post a lifelog within 2 hours after death, people curse you
fabricating evidence, false testimony, the whole curse system turned into justification of personal opinions and longer lineages are taken over by this players who generate drama to gain control
quads ruin the eve runs then even curse the oldest person alive.

if it turns out that you were innocent, arent the guilty supposed to be punished? people throw curses way too often, like 30 times a life, i hardly ever see people who actually ruin stuff getting cursed.

the only defense is to frame someone so the people waste curse point on it.
cursing still cost nothing and people who cant even water a bush, know how to curse others. 

if it accumulates over time, this 10+ curses for nothing arent a bit overkill?
no way to appealing to lift a ban

right now, you are even enforced to curse and kill this people and get cursed by them if you ever say anything. the drama queens take it as legit gameplay to raise kids, do nothing, curse anyone who has problem with it.

**Comment by TwistedHBG** [comment]
I don't think this is an issue. Even if you get falsely cursed you'd need to be cursed by eight different people at the same time to go to Donkey Town, and the odds of that happening are miniscule.

People are not throwing curses '30 times a life' because you can only curse once every two hours of ingame time.

As for people 'sniping' you, I think it's more likely that you're getting cursed because people find the way you play the game disruptive to their enjoyment.

**Comment by laccy** [comment]
and you live off others work while doing nothing
so if they count on you they will be disappointed
if you don't see how that can be annoying than im sorry for you
not all people are equal and not everyone deserves a vote

take for example you, you tried to kill me and got insta punished cause you lack the skill, you go out cursing like you got any moral superiority afterwards

it's more likely that you don't do anything that people can recognize you about, you just talk and some 12 year old people like it

i also find a lot of people distruptive and i got much better vision range, reaction time, even on vanilla
maybe i should be able  to curse anyone who disturbs me
that's not too fun as a game mechanic
neither being followed by butthurt sensitive people who are mad cause i kill their griefer mother or pick a backpack from floor faster than them

im pretty sure i killed the most griefers and sponges and didn't kill people for feeding me a berry or for views, like you do, but they also got the chance to do pvp i na game with pvp and they choose not to, ust shit talk the whole game as an excuse to do nothing in a survival game

so people who don't see how you are disruptive to their enjoyment should see more information about you 
like food produced 0 consumed 300, minutes wasted for others 30+
then they would likely curse you instead
