### ISSUE TITLE
Chests Unremovable after update

### ISSUE THREAD

**Issue by GreatShawn** [jasonrohrer/OneLifeData7#188]
Before the update boxes can be chopped into kindling, but right now after the update you cannot. although you can use an adze on a chest to turn it into a box, the box cannot be destroyed in any way because the transition is removed! So to stop another pandemic of chest-blocking, Jason, please add a transition for removing the box. (Maybe you can also adze a box down to planks.)

**Comment by GreatShawn** [comment]
sorry new to github

**Comment by anlongyi** [comment]
You can just turn it into a [sledge](https://edge.onetech.info/471-Wooden-Sledge) and move it out of the way. And it looks like now you can even [turn it back into a box](https://edge.onetech.info/2741-Wooden-Box-with-Shaft) afterwards.

**Comment by Dodg-e** [comment]
"Can no longer distroy boxes and chest into kindling, but can take chests apart, move boxes as sledges, and take sledges apart.  Fixes #167"

The box can be moved now like the sledge, so blocking is not an issue.

**Comment by jasonrohrer** [comment]
Yes, intentional, b/c they can be moved.
