### ISSUE TITLE
[Reopening issue #190] Snowball (melted) is deadly

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#192]
As was mentioned in issue #190 the melted snowball is deadly. The transition duration was fixed, but it still appears to be deadly looking at onetech.

**Comment by JustinLove** [comment]
Had two incidents of fast, silent mass-murder yesterday.

https://www.twitch.tv/videos/389263569?t=2h16m

https://www.twitch.tv/videos/389263569?t=3h31m

**Comment by jasonrohrer** [comment]
Whoops, I see the problem.  During that brief moment, you can kill people with it, but it makes no "harmless" splat.
