### ISSUE TITLE
Little to no visual indicator on hot adobe oven

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#195]
The visual indicator for a hot adobe oven is very difficult to make out. In full honesty, I never even knew it HAD a visual difference between the plain adobe oven. I see now, looking closely at the sprites on onetech, that the hot adobe oven has charcoal in the bottom of some sort, but that indicator is very difficult to spot in the actual game, especially against the near-black color of the oven interior, against the lighter watercolor biome backgrounds. 

Something easier to spot and recognize would help quite a bit, as right now most only can tell if an oven is hot is by hovering over it to check if it _says_ it's hot. An easier indicator would perhaps be glowing embers in the bottom, rather than black-on-dark? Would also make more sense, I believe.

**Comment by jasonrohrer** [comment]
Well, in my experience with such ovens, you actually sweep it out before using it, so there are no hot coals inside.

The fact that there is black soot left in there is something I wasn't even aware of... but I guess I did that long ago!

The idea is that you can't tell it's hot by looking, just like in real life.  You have to feel it.  With the mouse.
