### ISSUE TITLE
Potatoes still terrible

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#196]
People continued to get killed and berated over even thinking about planting potatoes. You might wonder why, since you halved the shovel usage on them? Because you nerfed it in the same breath, giving it 5 individual 10% chances to deteriorate. This means if we're unlucky, we can waste an entire shovel simply on a single potato row- not to mention the amount of shovels that'll be gone through by producing multiple rows!

The people are still looking for that buff to make them at least decent. Right now potatoes are at the complete bottom of the food pyramid. They're the undisputed worst crop to grow, and only second to tacos as the worst food in regards of cost-vs-benefit. This is horrible, especially for a RAW crop. 

I do understand that there'll always be a meta surrounding food, and that some will always be arguably better than others. I'm not asking for them to be put on top, but they should _at least be usable._ Potatoes irl are one of the easiest to produce crops in the world. I've grown them myself! It should not be this difficult or resource-taxing to grow them compared to other crops in the game. 

Please, reconsider your options with potatoes, for everyone's sake, especially if you ever plan on adding more recipes into the game. A +2 yum bonus is not worth an entire shovel and extra soil when we have 39 other foods that take less to make.

**Comment by trevorhackman** [comment]
This has been fixed
