### ISSUE TITLE
Inconsistent decay time of one hour for gooseberry seed

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#197]
Almost all of the seeds decay in 5 minutes, but the gooseberry seed takes a whole hour to decay. A substantially longer time. 

https://onetech.info/35-Gooseberry-Seed
https://onetech.info/220-Milkweed-Seed
https://onetech.info/1186-Squash-Seeds
https://onetech.info/1206-Cabbage-Seed
https://onetech.info/395-Carrot-Seed-Head
https://onetech.info/223-Wheat-Seed-Head (only 2 minutes here)
https://onetech.info/1119-Corn-Kernel

Also rose seeds don't decay, but I'm not sure if they belong in the same category.

**Comment by jasonrohrer** [comment]
Rose seeds are hard to make, so I'll leave those for now.
