### ISSUE TITLE
Fruiting milkweed turning into Milkweed

### ISSUE THREAD

**Issue by KKSzymanowski** [jasonrohrer/OneLifeData7#2]
Hello,

First of all, thank you for this awesome game and for making it open-source.
I have one issue though, which is kinda annoying: When maintaining a farm of milkweed I sometimes pick up the base Milkweed(not the fruiting one) because it transitions while I'm walking towards it. Because of that the stump disappears and I have to make new soil to fill the place and plant it again.

Is it possible to increase the time it takes for a Fruiting milkweed to transition into Milkweed to lower the chance of harvesting it by accident?

https://github.com/jasonrohrer/OneLifeData7/blob/master/transitions/-1_52.txt
For example:
```diff
- 0 50 20
+ 0 50 60
```

**Comment by UncleGus** [comment]
Just don't pick it unless you saw it turn into fruiting milkweed, so that you know that you have 20 seconds.

**Comment by KKSzymanowski** [comment]
Yeah, you're probably right, I'm just lazy.
