### ISSUE TITLE
Carrot seeds decay in soil and on ground

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#200]
Carrot seeds require being put in a bowl at all times or risk decaying either in the dirt or on the ground. This holdout mechanic from long ago seems out of place in the current game where carrot seeds are the only seed type that will delete their row of dirt if left in the ground long enough.

**Comment by jasonrohrer** [comment]
I'm not seeing that for the dry planted seeds:

https://onetech.info/396-Dry-Planted-Carrots

Carrot seeds now decay in 5 minutes, which is the pattern for all other seeds now.  But since they are rare and limited (unlike other seeds), I will make them last longer.

**Comment by jasonrohrer** [comment]
Please open a new issue if I'm wrong about the planted ones somehow.
