### ISSUE TITLE
Can't store Big Hard Rock or Cut Stones in hand cart or horse-drawn cart

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#201]
Can't carry Big Hard Rock or Cut Stones in a cart.

And yet, you can contain 4 x Split Big Rock pieces, which would be equivalent to 2 x Big Hard Rock in weight.

This is particularly aggravating when a new player unknowingly processes cut stones outside of town, leaving another player to spend their whole life slowly carting cut stones, one by one, back to town, by foot.

**Comment by jasonrohrer** [comment]
Big hard rock is intentional... it's really big.

Will fix the cut pieces.

**Comment by jasonrohrer** [comment]
Actually, I see the problem.  Cut stones come from the entire rock.  Being able to carry four of those in one cart would be kinda crazy.... hmm...  Okay, I'll do it anyway.
