### ISSUE TITLE
Large Fast Fires literally hinder us. 

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#208]
Currently, there are three types of fires in the game: 
- Regular Fires, that give off 8 heat for 60 seconds. 
- Large Slow Fires that give off 12 heat for 4 minutes
- Large Fast Fires that give off 16 heat for 30 seconds.

The first two have consistent usage in current gameplay- regular fires for early heat sources, and large slow fires for a more sustainable heat source. 

But large fast fires have quite literally zero use in gameplay. Not only do they not last long enough to be of any use whatsoever [a meager 30 seconds, in direct comparison to a full minute with a regular fire- using the same resources!] but the heat produced is quite literally damaging to the player. It's nearly as hot as the deserts! 16 heat easily puts one's temperature gauge near the hottest it can display. 

Right now, they're worthless. It has no special qualities to put it above a regular fire, nor is used for anything that a regular fire cannot be used for. More than that, it's actually hindering to players, as both a waste of resources and in terms of heat output. And yet new players continue to make them in eve camps, not realizing their lack of use. 

Honestly, I'd propose just pulling them out of the game. There's no point for them. Utterly none. I'm not sure if you had one in mind when you put it into the game originally, but at this point of the game they're literally _worse_ than the base fire. They're not used for anything, they hurt the player, and they waste resources. 

If not, at least consider lowering the temperature and buffing the timer. They shouldn't be nearly this punishing in terms of resources used vs outcome.

**Comment by CrazyEddieTK** [comment]
This is a good point. Large fast fires are a "noob trap", something that it is always a mistake to make. I don't think it's your intention to have craftable items whose only function is to punish people who don't yet know any better.

**Comment by jasonrohrer** [comment]
Will change them so they don't waste wood.

Don't they heat buildings better than the other ones?  They should.

**Comment by jasonrohrer** [comment]
Anyway, I don't have time to test it now, but I thought I tested it before, and fast fires make buildings warmer than either fire.  Will revisit in a few weeks.

**Comment by JkHowling** [comment]
They make buildings warmer... for literally 30 seconds. What use will that quite literally ever be? Nobody's going to put ANY resource into a 30 second flame, let alone something as constantly used and goes as quickly as kindling. The massive 16 heat is literally unusable for that short of a duration. 

Even a minute wouldn't be enough in a civ advanced enough to have buildings, because why waste 4 kindling to equal the burn length of a single log/firewood? Being warmer isn't a draw at that point of the game, not when there's an option that's not only cheaper but much more beneficial to the players. A slow fire heats a building perfectly fine without wasting resources. A fast fire just squanders resources for little to no payoff.

**Comment by Tarr-OHOL** [comment]
Have you thought about just buffing them to two minutes instead of just one? As of right now it's still incorrect to ever make a fast fire due to hot coals lasting two minutes so it's still better to let the fire burn down to coals and wait rather that move up a tier to hot fast fire  and degrade down to a small fire. 

Otherwise I do almost think it should be removed for being a complete noob trap. New players watch people through logs on the fire and think they're helping by throwing kindling which makes the fire much much too hot and burns too quickly to be any use other than wasting kindling.

**Comment by laccy** [comment]
well jason, i checked out how much bonus buildings give

ideal case you can have smallest 4x4 airspace so if the fire is in corner, that heats up the room
the bonus is applied to the rest
now to have a decent bonus, without radiant fire

the requirement is quite weird
stay 5 tile away from fire (no radiant heat as the fire is any players range)
to have a good bonus of 0.5 naked, it means 1x5 room
which means a fire is 2.5 heat per number of tiles
which is a 1x5 room, as you got in the tutorial

that's quite small
the way rooms should work, is more like a circuit, if its connected, minimum heat should be higher.
also wouldn't be bad either heating with a fireplace attached to a wall or iron fireplace
either give fire other bonus, right now radiant heat is much better
if more than 1 fire, works outside as well, 2 fires on 1x4 tile sides, then diagonal between them is perfect heat on 4 tiles
so either fire should last longer, or heat more or both
this could be archieved with charcoal heating, where we would have 1/3 kindling units
also some charcoal storage for longer heating

**Comment by jasonrohrer** [comment]
Closing this in light of the temp overhaul.  Will revisit later if needed.
