### ISSUE TITLE
Snakeskin doesn't go in small containers (basket, backpack etc)

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#217]
Cant put snakeskin in backpack and basket

**Comment by Tarr-OHOL** [comment]
On that note: If cabbage could go in baskets/bp as well that'd be great. Same issue so I didn't feel like throwing up another thread on stuff that should go in small containers. 

Also steel pipes (since steel rods fit in small containers.)

**Comment by jasonrohrer** [comment]
Fixed
