### ISSUE TITLE
Road making is tedious because of floor stakes

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#219]
Building long roads is tedious and unpractical because it requires to click 4 times on small stakes that move position each transition for just one road tile

Using a mallet on stakes could make floor stakes directly

**Comment by ryanb** [comment]
+1 on this, what about making the floor stake the first transition?

**Comment by jasonrohrer** [comment]
Yes, this is done.  This is an insanely great suggestion.

I mean, even if you're just building a building, there are going to be M x N floor tiles, and only 2M + 2N + 4 walls, right?  Area vs circumference.

So floors are the most common, should be first.  It already makes sense that corner walls are last, b/c they are the most rare.
