### ISSUE TITLE
Reproducible crash in map load

### ISSUE THREAD

**Issue by Dragonling1** [jasonrohrer/OneLifeData7#22]
Escalating the multiple players confirmed issue https://onehouronelife.com/forums/viewtopic.php?pid=34184 to the official bug report level. Please investigate and come back with some fix or workaround at least. Thanks in advance.

**Comment by jasonrohrer** [comment]
An updated client has been posted which should display an error message instead of hanging like this.

Please get the update (it will happen automatically the next time you try to log in), and let me know what file is reported to be missing.

**Comment by jasonrohrer** [comment]
No extra info?  Closing this for now.
