### ISSUE TITLE
Remove Pitbulls; They're just Griefing Tools

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#221]
I get your issue with Pitbulls, and the event in your life that your opinion of them stemmed from. I don't agree with it in the slightest, but I do get it. This isn't about that.

This is more about the fact that, right now, Pitbulls are one of the most common griefing tools in the game- and serve literally no purpose except this. As much as I disagree with your blind view of them irl, they're severely destructive in-game and have no other purpose but to give people the tools to cause damage.

One might say the same about bows, or knives, but- those also have purposes outside of killing. Reasons to be in the game. Dogs as a whole don't, and pitbulls even less so. One only has to look at the recent "Griefers Guide to Pitbulls" forum thread to realize this.

Would it be too much to ask either to remove the aggression factor of them, or just remove them outright? If you hate them so much, maybe they shouldn't be in the game period, rather than solely existing for players to release in buildings- the same buildings you want oh-so desperately to be _required_ in a town.

I get that, to you, it's a "realistic" element of the game according to your personal views, and that you like drama stirred up in the game. But the game shouldn't have elements that are _solely_ for the purpose of griefing. 

I do also understand that it's impossible to griefer-proof a game, and that shouldn't be the goal. You've done a great job at patching out griefer tools in the past, such as being able to move chests and adding the murder cooldown. This would be little different to those- removing a tool that does nothing for the game but aids to griefers.

**Comment by TwistedHBG** [comment]
+1. Pitbulls being easily bred killing machines is not a good mechanic.

**Comment by Dodg-e** [comment]
No?

Actually it would be even better if you could put the pit bull on a rope and use him for protection against stabbing or anyone that comes close to you, could even turn against you if you mistreat it.

Better medicine and official medics would balance any issue with "griefing" murder instead of going case by case and ending up removing bears,wolves,boars etc.

**Comment by jasonrohrer** [comment]
This is a little weird corner of the game that's going to stay...
