### ISSUE TITLE
shears with cut sapling + snowball = deleted shears

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#224]
As title says, hitting someone holding shears with a sapling in them will cause the shears to be deleted and the sapling to be dropped to the ground. Seems weird considering in the past that when something like this happened it would just drop shears with the sapling in them.

**Comment by jasonrohrer** [comment]
Fixed by https://github.com/jasonrohrer/OneLife/commit/1b3cce63bcfa66296760ea17b0c871568a99cfa4
