### ISSUE TITLE
No stacks for onions, tomatoes or peppers

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#229]
No stacks for onions, tomatoes or peppers.

**Comment by TwistedHBG** [comment]
I think stacks for these items would be a great addition.

I also think having a dedicated (ideally portable) storage items for fruit and vegetables, for example a crate, barrel, or big basket would be a great quality of life change. It could work similarly to seed bowls - neutral as long as it's empty, but as soon as you put in an item (for example an onion) it turns into an onion container that can contain a total of ~20 onions, Once it's empty it goes back to neutral storage again.
