### ISSUE TITLE
No chance of getting old boot from net throwing

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#231]
Inconsistent with fishing.

**Comment by trevorhackman** [comment]
Why should it be consistent? They're different kinds of fishing.

**Comment by TwistedHBG** [comment]
I don't think nets should be able to catch a boot. Fishing up a boot is a play on the old cartoon gag, it doesn't make sense to apply it to shrimping as well.

**Comment by jasonrohrer** [comment]
Cartoon gag!  Yes!
