### ISSUE TITLE
Tortilla Chip can't be put in bowl of Tortilla Chips

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#234]
https://onetech.info/2869-Tortilla-Chip

Just logically, seems like you should be able to put the tortilla chip back into the bowl of chips if you want. 

Same issue for French Fry
https://onetech.info/2874-French-Fry

**Comment by jasonrohrer** [comment]
You took a chip, you dipped, you took a bite.... and then you dipped again.  Why not just take one dip and end it?

You want to get all handsy with the chips and fries, and put them back in the bowl?
