### ISSUE TITLE
Snowball + net of shrimp = bugged item

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#235]
Had someone snowball me when I was catching shrimp while in the transition for shrimping. Since the net moved over to the net of shrimp - just caught transition on the ground it became unable to be interacted with.

I suspect this is also what is causing fishing rods to hover in the air around ice ponds as anyone catching a fish getting snowballed should cause the same exact thing to happen.

**Comment by laccy** [comment]
happened to me while holding clay in hand? i just couldn't find the clay after it

**Comment by Dodg-e** [comment]
[url=https://ibb.co/QYNYw4M][img]https://i.ibb.co/F8w8TFz/screen00327.jpg[/img][/url]

Related to :  https://github.com/jasonrohrer/OneLifeData7/issues/54

**Comment by jasonrohrer** [comment]
Fixed https://github.com/jasonrohrer/OneLife/commit/1b3cce63bcfa66296760ea17b0c871568a99cfa4
