### ISSUE TITLE
Can't remove raw rabbit from bowl.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#236]
Once a raw rabbit is place into a bowl the only way to remove it is to place it into a pie crust which can be annoying if you need bowls for other tasks in the village.

Just a QoL thing like all the other items changed to be removed from bowls.

**Comment by trevorhackman** [comment]
Same issue with bowl of carrot

**Comment by jasonrohrer** [comment]
Fixed the rabbit one.

Problem with carrot bowl is it's generic (same object created by wild and domestic carrot), so we don't know which one to let you take out.
