### ISSUE TITLE
Can't remove wheel from Partial Track Cart Kit (1, 2, 3, 4 Wheels).

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#237]
Track Cart kits are rarely made deliberately because they are not useful in general unless you got a finished rail, and it is not uncommon to see started Partial Track Cart Kits because people thought they were making Hand Carts or Wheelbarrows. 

By allowing us to backtrack in some of the earlier steps in making a Track Cart kit, we can preserve some resources that would otherwise not be utilised properly and people would not be punished for not knowing and/or experimenting.

**Comment by jasonrohrer** [comment]
Fixed here:  https://github.com/jasonrohrer/OneLife/commit/1b3cce63bcfa66296760ea17b0c871568a99cfa4
