### ISSUE TITLE
Make sheep dung biodegradable

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#238]
Getting dung from feeding shorn sheep was a great addition, allowing players to have an easier way to make compost without stressing about last sheep having wool.

This, however, has resulted in pens overflowing with poop. It is a pain to clear up space, specially when that costs us precious iron in the form of shovel usage.

Making dung decay over time (5 minutes like dead lambs maybe?) could solve the issue of overflowing poop pens while still allowing enough time for people to use up that dung for compost.

**Comment by laccy** [comment]
should be higher, like 30 min, but i agree

or either convert to something else, like the tile turns into one single soil?

**Comment by TwistedHBG** [comment]
I think it would be great if: A) Alldung-related interactions were switched from a shovel to a new tool, the pitchfork/manure fork, and B) We got a new dung pile object that can 'hold' multiple dung at a time.

If the pitchfork has a durability value make it only use durability when we actually put the dung into compost - that way moving dung one tile would not be a waste of a tool charge.

**Comment by laccy** [comment]
breeding goose from eggs should use the poop
in exchange for dung used this way goose should get a buff
feathers? multi bite omelette? more value for cooked goose? feathers? not sure

other animals fall behind, sheep getting even better

**Comment by trevorhackman** [comment]
Move dung to pigs. Then dung won't be overproduced by people farming wool. And pigs will have a purpose. And give a better pork recipe than tacos, like pork chops. And make cows killable for beef. Then all three animals will be balanced.

**Comment by jasonrohrer** [comment]
Fixed
