### ISSUE TITLE
Shovel has potential to use charges on pick up/drop/use

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#239]
As the title says just picking up and dropping sheep dung will potentially ding a shovel causing it to use one of its five charges. In a previous patch you had removed the same thing from potatoes (potatoes now only use a charge when picking the potatoes from the patch and not upon setting them down)

Was this a possible oversight or did you purposely leave it so moving or using a shovel to make compost would potentially use two charges of the shovel?

**Comment by TwistedHBG** [comment]
I agree that shovels should use durability only when you actually use it to achieve a task - picking up dung/dropping it on the floor should not count.
