### ISSUE TITLE
Remove shovel charge usage when picking dung and dropping it on the floor

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#240]
Moving dung from one tile to another for cleaning up a pen for example is using up to two shovel charges.

Shovel charges should be used only when a "crafting action" is being performed (such as dropping dung on compost, digging a grave or digging up reeds).

i propose removing the charge usage % from the following transitions:
1) Picking up dung with shovel
2) Dropping dung on empty tile with shovel

**Comment by TwistedHBG** [comment]
This sounds great, it would be an amazing quality of life change since right now dung has to stay where it is or it's a waste of a tool for no gain.

**Comment by laccy** [comment]
breeding goose could remove a dung 
right now you could still use a dung once, which makes goose pens just a showcase, not a real thing which could feed people, sure you could feed corn for eggs, and cut some goose for meat
but the time spent on them isn't really worth the food itself

in exchange for dung used like this, goose could receive some other benefit, feathers?

**Comment by jasonrohrer** [comment]
Eh.. moving dung was meant to be hard on the shovel.
