### ISSUE TITLE
Current area ban not mixing well with yum/warmth affecting fertility

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#241]
Ever since the implementation of the current iteration of the area ban, and the yum/warmth affecting fertility, we have experienced some really bad patterns on town life cycles.

Once a town achieves a certain prosperity, it will suddenly experience a cascading population boom (compound effect of clothing + better food diversity + available fertiles versus the rest of the server). This isn't bad by itself, but as the town continues to boom the pool of players able to spawn in there starts to diminish greatly. Players already banned aren't being unbanned fast enough.

Almost as fast as the towns experienced the population boom, they become enormous ghost towns full of infrastructure and resources but without any people. Their population usually consisting of one or two fertile females and a couple children at most, with so much food around they often don't even need to work at all during their lifetimes. Their entire life is spent trying to maximize babies, "organizing" or on some vanity project like making yet another building.

While a town is experiencing birth starvation, there is probably another town experiencing a boom and making sure the town stays starved. Then second town gets starved and a 3rd town gets a boom. A cycle that goes over and over again.

Suggestions:
1) Area ban should last less
2) Make area ban "real time" instead of "gameplay time"
3) Implement some sort of rule to make sure births aren't too concentrated in a single area. (Maybe have areas compete between themselves instead of individual fertiles?)

**Comment by laccy** [comment]
awbz shows the number of fertile relatives and girl kids
now this is a feature i would like to see in game, especially that the main goal of most people is to keep the line alive
people will quit if there are no girl or they see no girls
so some kind of player tracking should be possible to help people find others

i don't think the game knows what is a city
or what is an area
it can track back the family tree to eve, guess this is how awbz mod knows it
now there are cases with twin eves or people finding other cities when families mix
doesn't matter with area ban

the problem i see is: people start coming, you got no food output to sustain them
they are raised for 3-4 minutes, they starve right after if are low or medium skill
no control over veterans that they are girls or boys
the veterans already know this game
you want to enforce your vision? they will suicide anyway
they will run away, they will troll or will grief the city

if a player has lets say 300 hours, let him control his gender, not fully but with 20% extra chance for the preference
lets say Mirelli will always want to be female and she is good at it
I prefer to be male, but i do my best as female if the pop is low, but i will never be a yummer mom standing by the fire, but i would choose female if the server pop is low

i would suggest limits:
max 20 players in an area
max 2 girl kids per female per 10 minutes (counting if they are raised up to age 3.5)
the main problem is when no one is area banned, one female has 3 girls
each girl has 3 more girls, then he population goes exponential for 30 min until everyone is area banned, then you don't have enough girls
a fix of max 2 girls each 10 min would have 2 effects:
it matters if you keep your girls alive
it's blocking you from having more than that
people cant calculate food output and they wont control population

some social engineering
if an elder is 55 year old, give extra chance to the area to have new babies, replacing the elders
if a person is adult, give extra chance to have babies
not sure, maybe average lifetimes? i would limit each family around 10 people per area
lets say 2 adult females 3 girl kids 5 boys
if average age is higher than 20 increase limit to 12
if higher than 30 then 14
up to 20 where elders approach death would boost fertility of the females

this would make sense gameplay wise:
elders need replacement and the kids would have better equipment
if a camp struggling with food issues, more babies coming and toddler workers can fix it

people should help others and keep others alive and deaths should matter
if a camp has already 60 deaths under 30 min, chances are that they don't need more people 
they need time to fix the city
and that happens a lot to me
i do the things which can help people survive, tools, pen, etc. we got 30 min baby boom, annoying and slowing me down, then when im old, im lucky if i see 1-2 females around

just an example: i was at the Bear outpost
i made al tools, we died out, i had one female at camp, and one rabbit hunter somewhere who went old

south city, the original city had low population, a lot of boys for 2 hours, max i seen was 2 fertile females, 4 girl kids
NW city had like 30 people fully staffed
same family, 700 distance between 3 camps,, was there 3 times born in all their cities, taking people left and right
the area ban hurt the outpost cause we had too high pop before the tools
also hurt the main city as we had too many people banned for too long
and the second city had too many people and very high death rate
it makes sense but should be an upper limit to each camp, like 20 people in an area, then if all camps are fully staffed, the rest of people get decreased area bans or go to eve camps, if too many eves, people shouldn't be able to area ban themselves for so long by SID

the main problem is too many eves are running around  and older camps with older people are not getting enough supply of kids but newer camps get too high supply

**Comment by jasonrohrer** [comment]
So much has changed since this was reported.
