### ISSUE TITLE
Groups of griefers need to be balanced

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#242]
Griefing as a group is so strong right now we actually have dedicated griefer groups going around killing towns. Twinning mechanics needs to account for ways to minimize their group advantage.

Suggestions:
1) Don't allow twins to curse: quadruplets can do an extreme amount of damage to a single 
player for no reason, this is extremely unfair for individual players;

2) Apply curse token on everyone on the group: if you curse one twin/triplet/quadruplet then that curse should apply to all of the people born with that player. Griefers being able to "dilute" their curse count allows them to go griefing indefinitely. This change would allow handling groups of griefers in a more consistent way.

3) Combine everyone's current curse score to determine whether or not they spawn in donkey town. If the combined curse score of a group exceeds what would normally cause a player to spawn in donkey town then all of the group should spawn there. This would cause groups of griefers to have to disband earlier and potentially grief individually or in smaller groups, making them easier to deal with.

These will not solve griefing but will make it more manageable by everyone else on the community. And allow players to stop needing to kill twins on sight to stop towns from dying. Normal players who twin are being punished preemptively by the rest of the community because of all the rampant griefing happening right now.

**Comment by laccy** [comment]
kill one, the rest of them should die
this was the original idea but was never implemented

they quit most of times but if not they can easily kill you, heal each other, curse you and convince others to curse

**Comment by TwistedHBG** [comment]
I really like suggestion #3, it seems like an elegant way to make curses matter more with twins (I feel like Jason doesn't want to do #2)

**Comment by jasonrohrer** [comment]
The way curses work has been changed (personal curses) and something close to #3 is happening now (if one is blocked, they are all blocked).
