### ISSUE TITLE
Burn baby, burn? Eves killing kids with new fire

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#243]
The new fast fire lasts longer and has a 80% heat
this means that the baby will overheat and requires a lot of stepping out and in to control heat
and if stays inside fire will starve very fast

the eves are kind of new, they don't know, back before was a waste to do a fire of this kind, now it isn't technicaly worse to put a kindling twice rather than two times one
but the heat output kills the kids very fast
i was raised by chasing my mom all around, then i made fire tools and she starved 5 kids by putting them on a fast fire
as she had some sense of timign when they need to be fed, but with the overheating kids starved way faster

this happened 2-3 times so far and im too young to epxlain to them or take the kid out of fire
also i try to feed them and make a camp
im ok in helping eves to ave a successful run, but it's unintuitive why a fast fire is so bad, it looks like the normal big fire, almost, it's one minute long like the small fire so it's not technically a waste to keep up a fire, but it's bad for raising kids

i had a disconnected girl and i found a good solution: told mom to raise kids near 10-12 wild bushes with a fire, she made double fire and the girl starved before having grandkids, and my efforts on making a farm were ruined

later when im like 30 i explain to them to don't make a large fast fire but seems like everyone is doing this since it changed
with no actual recipe requiring it, and because it's a "don't do"  thing
i think large fast fires should be removed or decreased in heat output to maybe 0.6

**Comment by trevorhackman** [comment]
I don't think this is an issue

**Comment by laccy** [comment]
there is no reason why we got fast fire
the heat bonus even in a room is useless
there is no recipe requiring it
it's hard to explain as a baby that she shouldn't do that

3-4 sisters starving when she tries to raise them up is major issue
they want to stay, they don't suicide or run away

the mom technically kills them without knowing, it's very unintuitive for new players. they see the big fires in other games and they think is better, they don't know the difference

**Comment by Tarr-OHOL** [comment]
Yeah there is definitely not a reason to have fast fires in the game currently. Jason went through before steam release to remove a bunch of noob traps from the game and the fast fire is definitely a clear noob trap. 

Fast fire degrades to small fire after a minute, which then degrades to hot coals for two minutes. It is better to let the fire burn down to coals than to keep a fast fire constantly burning.

**Comment by jasonrohrer** [comment]
It's meant for inside a building, not for standing right on it.
