### ISSUE TITLE
[Unreleased] weird sprites for new clothing

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#245]
Screenshot:
https://prnt.sc/n7oyvp

**Comment by thaulos-bolsens** [comment]
For clarification here is specifically what I meant:
https://prnt.sc/n837cz

**Comment by jasonrohrer** [comment]
This is normal.

It's what it looks like when placed on the ground.  See the way the apron looks, same deal.
