### ISSUE TITLE
Cannot deconstruct Newcomen Engine Tower

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#248]
We got the ability to deconstruct the freestanding blocks a while ago, but once you add a pump beam kit, it and further forms become undeconstructable. 
https://edge.onetech.info/2246-Newcomen-Engine-Tower

Sometimes you want to move an engine to a better spot, and this could be used to grief. Especially if it's put infront of a doorway.

**Comment by Dodg-e** [comment]
The whole https://onetech.info/2243-Multipurpose-Newcomen-Engine should be deconstructable, to be able to move forges and to avoid griefers blocking access to water source, entrances etc.
