### ISSUE TITLE
Missing transition to make Bowl of Plaster

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#257]
Bowl of Plaster can't be made by adding water to bowl of quicklime, it can only be made by adding quicklime to bowl of water. 

https://onetech.info/677-Bowl-of-Plaster

**Comment by Spodnie** [comment]
Irl people add powder into water and not the opposite to make cement or other building stuff, if that matters.
So it works realistically now and I don't mind leaving it like that, even tho it would require 1 less click for us if we had that transition. Not a big deal.

**Comment by jasonrohrer** [comment]
Yes, this was on purpose.

Adding water to powder doesn't work very well in real life.
