### ISSUE TITLE
Aged Mother displays as young

### ISSUE THREAD

**Issue by eadsjr** [jasonrohrer/OneLifeData7#26]
I'm on v58b -> v153.

2nd Generation mother named TINSLEY DOOM appears young throughout mid-life. Unable to have children and reporting 'down to half-pips' on the food meter. Moments later, insta-ages to advanced age. This is visible to both of us.

I just discovered the gameRecording file system, and have been leaving my client open for days at a time. The files are impossibly huge. With no clear way to accelerate or jump to a point I can't provide a relevant snippet. I'm not yet clear on how to trim the files either.

Later, during the same game, as I neared the same age transition, I lost connection.

<img width="1440" alt="screen shot 2018-10-19 at 6 15 33 pm" src="https://user-images.githubusercontent.com/6946712/47248574-eeed7d80-d3d0-11e8-8a87-f90da66b91f1.png">
<img width="1440" alt="screen shot 2018-10-19 at 6 16 02 pm" src="https://user-images.githubusercontent.com/6946712/47248576-eeed7d80-d3d0-11e8-8c76-76a02a55a3d5.png">

**Comment by jasonrohrer** [comment]
Those screens look normal to me.

The mid-life hair-color change in the redhead is very subtle.  You can see that she's pretty hunched over already, though.
