### ISSUE TITLE
Tule Stumps with Basket never decays

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#261]
https://onetech.info/1927-Tule-Stumps-with-Basket

Tule Stumps normally decay in just 1hr, so there's no need to make a Tule Stumps with Floppy Basket, only needs a 1hr transition into basket to be added.

**Comment by Spodnie** [comment]
Pretty unnecessary... Nobody leaves baskets in tule stumps, never seen one.
But if you want to fix it, only tule stump should decay and not basket.

**Comment by Spodnie** [comment]
Harvested tule doesn't decay either, but that's unnecessary to fix it too.

Same with harvested wheat. Wheat stumps decay after 2 minutes only if we pick wheat sheaf.

**Comment by jasonrohrer** [comment]
Yeah, this is fine as-is.
