### ISSUE TITLE
Items that don't stack that should.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#269]
Sharp rocks (other stone types stack see round stones, flint chips)
Copper ingots ( wrought iron, steel bars, etc.)
Zinc ingots (same as above) 
Electrum ingots.

**Comment by futurebird** [comment]
Meats, wheat piles, dung (make it stack like soil), Squash (they would just look nice stacked), onions, tomatoes, eggs (think of food stacked at a fruit and vegetable stand, this would reduce the hate for these items.)

Corn won't work because it has states I think.
