### ISSUE TITLE
Forgotten milkweed seed transition

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#272]
Milkweed seed + fire = empty hand + fire. This is left over from the days when milkweed seeds were permanent. Only seed (really just item) that can be disposed of by means of fire. Seems incongruous.

**Comment by Devroll** [comment]
I think that the milkweed seeds should also be limited. The milkweed seeds as well as wheat seeds are unlimited (not counting saplings) which leads to the spamming problem, so you don’t need to burn the spammed seeds if you limit the seeds, but still have the seeds decay (slower maybe)

**Comment by Spodnie** [comment]
You can use bowl of water to remove bowl of any seed. I do it pretty often to get rid of unnecessary seeds that only make clutter.

I don't think we really need more ways to get rid of seeds.

**Comment by Devroll** [comment]
Uright

**Comment by jasonrohrer** [comment]
Milkweed and wheat seeds are pretty limitless in real life.  There are hundreds of milkweed seeds in each pod, for example.  The corn seeds are also limitless in the game.

Will get rid of that fire transition, though.
