### ISSUE TITLE
Immortal clay nozzle

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#273]
These cannot be disposed of. They can also be repeatedly spammed with only one clay and a skewer. "clay nozzle" and "wet clay nozzle" should be able to be thrown in a trash pit. Very similar to bone needles, which can be thrown away.

**Comment by trevorhackman** [comment]
Wet die has same problem. 

Wet clay nozzle and wet die should decay to avoid infinite clutter

**Comment by jasonrohrer** [comment]
fixed
