### ISSUE TITLE
Only says "tortilla chips"

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#274]
Flour tortillas can't be used to make tortilla chips. Only corn tortillas can be used. The name doesn't specify that it is corn tortilla chips. Maybe seems like it'd be fine to use flour tortillas? Might make it easier to use up onions and peppers.

**Comment by Dodg-e** [comment]
Ashes could be used to make masa dough for tortilla.

**Comment by jasonrohrer** [comment]
I don't think they're ever made with wheat in real life.  And we just call them tortilla chips for that reason.
