### ISSUE TITLE
Inconsistent storage

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#275]
Baskets are inconsistent and exist in container limbo. They can work either like boxes (pure storage) or like carts (transportation). If they are being used for transportation, then the way they work is consistent; but if they are being used for storage, this is where inconsistency begins. They work like carts whether they are being used as carts or boxes. Maybe have them take uses (putting something in or taking something out)? That way they serve as both and are consistent no matter how they are used.

**Comment by FeignedSanity** [comment]
Maybe this would also be a good time to address the frustrating mechanic of having your container randomly explode and randomly jettisoning some your contents because you reached an arbitrary time limit.

**Comment by omlinson** [comment]
Another inconsistency: should be able to place two curved branches in carts / horse carts. I assume it would take less place than a pump beam kit.

**Comment by FeignedSanity** [comment]
"Two curved branches" can already be placed in cart. It's "Two curved shafts that are not containable". I would submit this as it's own issue.
https://onetech.info/2419-Two-Curved-Branches
https://onetech.info/2214-Two-Curved-Shafts

**Comment by jasonrohrer** [comment]
How are they not consistent?

Please explain more?

**Comment by FeignedSanity** [comment]
Baskets weren't acting like other storage items. Boxes, chests, and now the slot box; none of them decay. Since you removed the decay, they now act like other storage, removing this inconsistency. But now they don't behave like any of the transportation containers (carts and backpacks). They worked like backpacks, even when they were used like chests. Now they have the opposite problem.

Basically, my understanding was that storage items (boxes and chests) didn't decay. While transportation items (carts and backpacks) do. Baskets being used as storage (just to hold things) didn't fit this rule. This would lead to confusion when baskets would break while inside a box.

This probably boils down to general confusion on the rules of what decays and what doesn't. Much like the confusion there used to be about what bowls were and weren't containable.

**Comment by jasonrohrer** [comment]
They don't decay anymore.
