### ISSUE TITLE
Fix how yellow fever interacts with clothing.

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#277]
Basically yellow fever and almost no clothing what so ever results in maxed temperature even when in snow. At some point you had it patched where it was possible to not be stuck at maximum temperature and that seemed fine however, we're back to touching mosquitoes = max pip drain rate with barely any clothing on. 

Not sure which temperature patch/change put them back to maximum heat again but it seems a little too punishing to either need to be completely nude OR suffer maximum food loss for touching a hard to see mosquito.

**Comment by hetuw** [comment]
thinks about mosquitoes that annoy me:
- can only survive them while having a yum chain or if someone feeds you
- cant be killed like other wild animals
- hard to see
