### ISSUE TITLE
Two curved shafts not containable

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#283]
Two curved branches are containable, but two curved shafts are not.

_Originally posted by @omlinson in https://github.com/jasonrohrer/OneLifeData7/issues/275#issuecomment-488331807_

**Comment by squeaksvolvo** [comment]
This is a game feature that is not a bug. Inconsistency rewards game knowledge and requires extra planning.

**Comment by FeignedSanity** [comment]
Not every thing in the game is intended to be in the game. A lot of times, it's an oversight or mistake. He has already asked that consistencies be placed here. If you have any further questions, please review his comments posted here: https://onehouronelife.com/forums/viewtopic.php?pid=56452#p56452

Inconsistency is frustrating and not fun. If you're an elitist prick, then I'm sure inconsistency sounds great. But for every one else, it's annoying. He has already fixed many things (like sheep dung from adult sheep) just for the sake of consistency. Just so you are aware before you comment about this on more posts and can revise/delete old ones.
