### ISSUE TITLE
No way to eat skinned seal, wolf, or bear

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#284]
No way to eat skinned seal, wolf, or bear

I don't think it matters, but I also noticed that skinned seal is a clothing item
https://onetech.info/710-Skinned-Seal-no-fur
https://onetech.info/424-Skinless-Wolf (bit of a naming inconsistency, why skinless and not skinned?)
https://onetech.info/658-Skinned-Bear

**Comment by cordy-123** [comment]
Or bisons.

Or domestic cows.

**Comment by Devroll** [comment]
Yeah, and another idea could probably be maggots and things to decompose the animal corpses, and you can grab the grubs as something like fishing bait or animal feed

**Comment by Spodnie** [comment]
Cows meat would be too cheap to produce, for that reason maybe it's good that we can't eat it.

**Comment by Devroll** [comment]
Perhaps having the cow meat be better quality the better condition the cow is in? There’s plenty of diseases that cow meat can give you if not treated properly, and when we have the problem of people giving too many antibiotics to the cows, you know...

**Comment by jasonrohrer** [comment]
People don't generally eat predators in real life (bear, wolf) for good reason.  Likewise, seal is eaten rarely.

Cow is a known gap that is coming in a future update.
