### ISSUE TITLE
Newcomen Pump Tower inconsistency

### ISSUE THREAD

**Issue by Wuatduhf** [jasonrohrer/OneLifeData7#286]
When building a Newcomen Pump Tower for the first time on a well, the transition of placing a rope onto it "destroys" the Stanchion Kit that was used to make the deep well. This should be adjusted to return the Stanchion Kit when the rope is applied, completing the Newcomen Pump. This would mirror the existing transition for Dry Deep wells being changed into Unpowered Pump Head.

Images for reference.

![image](https://user-images.githubusercontent.com/7107685/57114086-3902d480-6d0d-11e9-88c1-042d6fb1cb62.png)

![image](https://user-images.githubusercontent.com/7107685/57114080-2dafa900-6d0d-11e9-974a-09b115d17ad6.png)

**Comment by Ari-ori** [comment]
this makes total sense.

**Comment by jasonrohrer** [comment]
Yes, this is intentional, because the bucket goes "down in the well".  That's how the Newcomen pump works (at least in my mind).  It's using the bucket in there somehow.

Diesel pump works differently.
