### ISSUE TITLE
Non-Canadian Goose vs Omelette

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#287]
Omelette and non-Canadian Cooked Goose are both made from the same thing, a single egg. 
A Cooked Goose takes far more steps, far more time, and a usage of the axe vs the omelette. 
Yet it doesn't give anymore food than omelette. Cooked goose should be more rewarding. How is it that a whole goose doesn't fill you up much more than a single egg?

https://onetech.info/1285-Omelette
https://onetech.info/1273-Dead-Goose
https://onetech.info/518-Cooked-Goose

**Comment by Devroll** [comment]
Then the raised goose should produce more eggs when you feed it, giving more benefit to raising it and keeping eggs for geese, and being able to put an egg in ponds to hatch geese there for feathers, or when you hatch a goose, it makes a feather, allowing farmable feathers if all the geese are griefed.

**Comment by miskas9** [comment]
this can be closed
