### ISSUE TITLE
Wooden Disks can't really be stacked

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#288]
When you make Wooden Disks you get a stack/pile of 4. You can take and add to it, but once the disks are separated they can't form a new stack, which is weird. Wooden Disk should be stackable. 

https://edge.onetech.info/472-Wooden-Disks

**Comment by squeaksvolvo** [comment]
Am I mistaken or is this a feature request and not a bug and should be posted to the subreddit?

**Comment by trevorhackman** [comment]
@squeaksvolvo this place isn't only for bugs, it's for content issues. Wooden Disks being stackable but not stackable is an inconsistency and missing transition for Wooden Disk and certainly does belong here.

Balance issues can come close to feature requests, but they can be posted here as well. They are less likely to be addressed by Jason.
