### ISSUE TITLE
Can't turn a dry pond in to a shallow well

### ISSUE THREAD

**Issue by TheBuildster** [jasonrohrer/OneLifeData7#292]
Hello,

Today I and other players have tried to make a shallow well when the pond was dry. We tried to put the round stones on the pond, but it didn't let us do it. We tried it with mutiple dry ponds and none let us put round stounes on them.
Can someone please help out and fix this problem?

Thank you.

With kind regards,

The Buildster

**Comment by FeignedSanity** [comment]
This is part of this week's update. You can't make wells off of ponds anymore, it has to be on a natural spring.
