### ISSUE TITLE
Left over eaten carrot row transition?

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#296]
Wondering why this was still a thing. I feel like it might've just gotten forgotten about, but carrots are the only thing that can be eaten by another animal. Cows don't eat up corn plants. And why just carrots? Wouldn't it make sense that they'd also eat berry bushes?

**Comment by jasonrohrer** [comment]
Going to leave this alone for now.  It's a legacy thing, mostly.
