### ISSUE TITLE
Inconsistent bowl emptying

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#300]
These items are rather awkward and cumbersome to remove the item from, and are inconsistent with other items stored within bowls:

-Bowl with Limestone
-Bowl with Gold Flakes

The Bowl of Limestone should be updated to coincide with other holdable items that are put into bowls, such as coal/wrought iron, in which right clicking on the bowl while on the ground removes the limestone.

The Bowl with Gold Flakes should be updated to coincide with the other "dumped" unholdable items that are put into bowls, such as palm kernels and threshed wheat, in which a branch is used on it to dump it out onto the ground.

There's also the Bowl with Dice, which can't be placed on the ground without swapping another item, but I don't really see a way to make placing it, rolling it, and walking around with it all possible with only 2 buttons.

**Comment by jasonrohrer** [comment]
Fixed
