### ISSUE TITLE
Can't plant jungle trees

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#302]
Like the other trees you should be able to plant the jungle trees, in particular the rubber and oil trees. Can hurt the viability of a town when no nearby jungle trees or someone cuts down all the nearby jungle trees. Will help the potential viability of any spring location to be able to plant nearby rubber and oil trees. 

Maybe banana trees too?

**Comment by FeignedSanity** [comment]
You can plant mango trees.
https://onetech.info/1868-Dry-Mango-Sapling-Cutting
The other trees spawn frequently enough, but it would be nice. But at that point, why not also let us do rabbit farming?

Pretty sure banana trees are supposed to be a non renewable food source.

**Comment by trevorhackman** [comment]
Bananas were actually originally renewable @FeignedSanity; they were nerfed because it was too much unlimited free food when banana trees regrew banans. So I'm not sure that bananas are supposed to be nonrenewable.
