### ISSUE TITLE
Springs Don't Spawn Above Trees

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#305]
The whole point of the wipe was to regulate where springs spawned.  However, since the update also made it so that "short" objects get blocked by "tall" objects/trees from spawning once again, it turns out that natural springs do NOT spawn in a regular pattern.  I have seen it twice where a spring should exist, as the biome is correct for a spring spawning, but a tree one tile below the intended natural spring blocks it from spawning on server12 shortly after the wipe.

**Comment by Tarr-OHOL** [comment]
Also springs don't spawn if some other natural object takes the tile instead. This means trees/sugarcane/anything can replace the spawn of a spring which leads to areas that should have a spring just don't on the grid.

**Comment by jasonrohrer** [comment]
A, yes... I see that the thing with trees to the south is true in the code.  Hmm...

Not sure about the other issue with other things being there instead.  Code checks for a spring first, and only if it's not there, checks if a different object is there.
