### ISSUE TITLE
Shovel of Dung never decays into Shovel

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#309]
Dung was given a 30m decay timer, but Shovel of Dung wasn't. Shovel protects the dung from decaying. 

https://onetech.info/900-Shovel-of-Dung

**Comment by laccy** [comment]
that's good feature i guess, we still need the dung forcompsot so you can swap an item to put down dung on shovel
also the eggs in it protect from decay and that's kind of useful except that goose decap isn't the pest kidn of job
