### ISSUE TITLE
Fletching doesn't decay

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#313]
Goose Feather decays but Fletching does not

https://onetech.info/144-Goose-Feather
https://onetech.info/146-Fletching

Fletching is just cut goose feather and should decay. Fletching is an unlimited source of clutter since its only use is making an arrow and it doesn't decay 

Fletching also can't go into a trash pit like a feather can.

**Comment by FeignedSanity** [comment]
I think I posted somewhere about fletchings being able to be thrown away. I'd personally go this route because I've always preferred disposal over just magically vanishing into the ether.

**Comment by laccy** [comment]
i had to walk like 200 tiles for new goose feathers so i rather have some 
throwing in the pit would solve the issue but decay isn't the best option
i rather throw tomatoes in pits
