### ISSUE TITLE
Lack of Gameplay Variation

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#320]
As of writing this post, there are quite literally 2 families existing on the big server. The Bee family, and the Blondin family. Both live in very large towns. Both consist of quite literally 30-50 players. 

The variation is simply.. gone. Before, I could spawn into a multitude of scenarios. I could be the firstborn son of a brand new eve. I could be born to an early camp, whose berries were just planted. I could be born to a small village that just got their first sheep, or whose well just went dry. And if I disliked a scenario, I could simply move on.

Now, I have 2 options. Get born into a giant town with dozens of family members, or run and try to start my own camp. Do keep in mind, if I run off to try and 'eve' myself, I am directly competing with dozens of females on the server. It also appears that any baby that /dies from the family I left, also seems to add myself to their skip list, as from my understanding it's now back to the original lineage-based system instead of area-based.

I'd like there to be a balance between gameplay styles. If you're taking away eves entirely, give us the option to properly branch out of a city [new name, and being excluded from the family you left]. And enable these branching-off players to compete with these mega-cities of 30+ females like below. 

![really](https://user-images.githubusercontent.com/26156840/58600166-522d7100-8238-11e9-9234-7134e263dfa2.png)

**Comment by laccy** [comment]
yeah maybe some renounce option, that as long you are naked and outside 200 range of other people, you could renounce the famaily name and choose new if you are fertile woman.
