### ISSUE TITLE
Milkweed/Rope is a major bottleneck

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLifeData7#321]
Buckets, boxes/carts, newcomen assemblies, hatchets (iron is limited... but sometimes rope feels more precious). Fire bow drill if you want to start a splinter camp. Lead and bow/arrows if you want to restore a lost sheep.

These are all places where I regularly hit a rope wall. I had no idea milkweed was such a limiting factor on human development. Sure, its cool that a foresighted person could farm a bunch of milkweed, and it's "our fault for not keeping up", but it rarely lasts long and requires a lot of soil and water, often competing with food.

I did a private server for a bit. The two chores I had to do 2-3 times per play session were gather kindling and restoring the milkweed farm after a round of buckets or something. (And I was living large on buckets compared to most public server towns.) Milkweed was easily my largest farm plot, possibly as large as all other crops combined, though I had it easy with good clothes and constant yum.

Thread was largely ameliorated by sheep, but only for sewing.

**Comment by jasonrohrer** [comment]
I want to leave the milkweed bottleneck in place for now.
