### ISSUE TITLE
Goose breeding isn't worth the time and effort, but it should

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#323]
Now that eggs are protecting the dung from decay, which is a side effect but a good feature, i feel like goose should receive some buff to make it worth while

the main issue is that goose pens arent really worth making
and especially carry dung to a goose pen, so it has to be near the sheep

the decap animation takes very long, around 3-4 sec
which is quite boring.
also cutting off goose head is quite hard, a dig a bush alone level of hard
so to make it decent time, i need to chop off 3 heads on 3 stumps which kinda need to be near each other

the other issue is that stumps decay or got dugged out so you need to go further and further each time or cut new trees all the time
some sort of replacement for stumps would be nice, maybe higher tech a stump could be processed, actually people use stumps for firewood cutting irl and the stump is quite big, portable 
now a fied position box and some permanent stumps would make a permanent station for goose  decap
the food value isn't bad, but maybe the second half of goose could give extra yum
also some sort of other buff
goose feathers could make some clothing or decoration item

sheep breeding has lot of value, goose is just annoying cause doesn't worth the time of making a separate pen for goose as of right now
but a permanet stump like item would fix this
maybe anwill or chopping board, also the choppign board could be used for tortilla and paper? so less flat rock moving
maybe smith could have anwills later on so flat rocks go for graves and roads only

a better reward for breeding goose and maybe more uses for eggs (cakes maybe?) would makea nice minigame and a godo job for newer players

**Comment by trevorhackman** [comment]
#287
