### ISSUE TITLE
List of items that should decay: 

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#328]
Hot Pepper
Tomato
Onion (player grown type)
Dry Bean Pod (shouldn't decay in a bowl)
Goose Egg
Pepper Seed
Wild Tomato Cluster
Wild Pepper
Threshed Wheat - straw removed
Raw Pork

**Comment by trevorhackman** [comment]
Pepper Seed already does decay. Pepper can as a result be gotten rid of by cutting it into seeds and leaving them to decay.
