### ISSUE TITLE
List of items to be dumped in a trash pit

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#329]
When I mean dump for this first section I mean stuff that can be emptied into a trash pit.

Bowl of Carnitas
Bowl of Salsa
Bowl of Ketchup
Bowl of Salt
Bowl of Vermilion Pigment
Bowl of Sand
Bowl of Rust
Bowl of Butter
Bowl of Vinegar
Bowl of Tomato Seed Pulp
Bowl of Palm Kernels 
Bowl of Ultramarine Pigment
Bowl of Indian Yellow Pigment
Bowl of Crushed Palm Kernels
Bowl of Cane Juice
Chopped Onion on Plate
Chopped Tomato on Plate
Chopped Tomato and Onion with Hot Pepper
Bowl of Corn Kernels
Now stuff that should just go in a trash pit.

Arrowheads
Letters
Goose eggs (if they don't decay) 
Fletching
Charcoal Pencil
Blue Rose

I'm sure there are more but these are just things I've seen while scrolling through onetech.

**Comment by jasonrohrer** [comment]
Trash pit is generally not for things that cannot be replaced.
