### ISSUE TITLE
fast roads don't give back rock when built over

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#33]
it's a bit faster and works with stone/wood replacement
should allow with wood/fast road replacement, supposed to be early tech

**Comment by jasonrohrer** [comment]
Not sure what you mean here.

All three types of floor (wood, stone, and road) need to be torn up manually to recover materials.

None of them give back stuff when built-over.

You need to manually tear the floor up if you want the materials back.


In the case of roads as early, cheap floors, that's a good point.  You need a pickaxe to tear them up.  That is later tech.  However, you can't cut boards or stone until you have steel anyway, so you need later tech to build over your early-tech stone-road floors.
