### ISSUE TITLE
Listed by Twisted

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLifeData7#330]
From this thread:

http://onehouronelife.com/forums/viewtopic.php?id=6828

I'll be checking these off and referencing them from commits as I deal with them.  Most of these are content issues, so I'm posting this here.

If you're talking or interacting with someone in town, if either of you move or walk around it's very easy to lose track of them and mistake someone else for them.

If you head out of town with someone it's very easy to lose them.

Crafting a lot of clay/steel items at a kiln/forge can feel a bit awkward if you're mass producing stuff in a big town. Clay especially, steel less so.

Rope is needed for a lot of things, and crafting it en masse takes a lot of room.

Sometimes I want to move animals to a different pen, but the only way to do that is to make a baby and kill the original animal.

If you go bow hunting without a cart, you can't bring both the prey and the bow back - you need to leave the bow behind and then come back for it.

Crafting a large amount of boards for a project takes a very long time and a lot of room.

Roads are very important but they are not very fun to make.

(X) - Making anything with stakes is a bit awkward since the stakes hitbox moves every time they change shape.

Sometimes it's hard to see if the oven is hot or empty.

It always felt weird to me that we get so few logs/firewood from chopping down trees. One log per tree feels especially weird.

Firewood is important for a town but we can only transfer a small amount of it at a time.

Some walls are very simple to make if you have the raw materials which feels simplified, while others are very difficult which feels more realistic.

I don't think I've seen a single Kerosene Newcomen since the update.

I love the look of blue/red plaster walls but you're very unlikely to find enough paint in one life to paint more than a few.

Sometimes you want to move the smithy, but you can't because you can't move the newcomen.

If you build a floor around a oven/kiln you have to destroy it first so you can build the floor below it.

OHOL is supposed to be a game about parenting, but most of the time you don't have to interact with your kids at all. Just feed them for a bit and set them free at the age of three.

Tarr continues:

The only nonlethal defensive/offensive weapon in game both melts after a minute and inflicts cold temperature on the user.

It's easier to fill bowls with nonsense than it is to clear them out which results in nearly unusable bowls.

By the time you can attempt to produce an idea of how a town should look the town is pretty much cemented in stone.

It costs too much to fix mistakes with town design whether it's in resources (pickax to a bust a single wall), time (removing berry bushes), or both.

Food exists in one of three states: Eat it all the time if possible (Pies, bread, milk); eat it if you got it (most foods fall in this category); and don't even make it (salsa, ketchup, potatoes before the buff, both taco types).

Food in general has bad effort to reward ratios with a prime example being an egg vs arctic char. Both give the same amount of pips but one takes much more effort than the other.

Technology in game never seems to truly be an improvement on aspects of the game except when it comes to water tech.

No solid or useful system in place to deal with players acting outside the social norms of the game.

Futurebird continues:

Towns do not feel distinctive enough so when you come to a new town it feels like the same place. It's not like going to a foreign land where the clothing is different and the food is different (the language is different which is nice and helps)--

There aren't ways to store the laws and information that people put in notes that make them useful for the future. You don't even know who wrote it or when. Written notes acts as clutter. But they are valuable some of the time.

It's impossible to tell just how old a building is, or who made it. So you can come in to a town and think your family built it but really someone else did.

**Comment by jasonrohrer** [comment]
I will check these off as I go along.

**Comment by cordy-123** [comment]
Thought of something while reading this: "Sometimes it's hard to see if the oven is hot or empty."

Sauerkraut kinda hard to notice. And it's often ignored, maybe because of that? 
Looks too similar to Empty Clay Crock.

![](https://onetech.info/static/sprites/obj_1241.png)
![](https://onetech.info/static/sprites/obj_1217.png)
https://onetech.info/1241-Open-Fermented-Sauerkraut

**Comment by TwistedHBG** [comment]
It's been a while, and since I'm the one that originally made this post I wanted to go through the list and share my thoughts on the things I mentioned, as some things have been fixed. Keep in mind there are other points in this issue that were pointed out by other users and I will not be commenting on those.

> If you're talking or interacting with someone in town, if either of you move or walk around it's very easy to lose track of them and mistake someone else for them.

This gets better every time new character sprites are added, the /yoohoo and /fam commands also help.

>If you head out of town with someone it's very easy to lose them.

The /yoohoo emote now adds an ! speech bubble that can be seen off-screen, which makes grouping up easier.

>Crafting a lot of clay/steel items at a kiln/forge can feel a bit awkward if you're mass producing stuff in a big town. Clay especially, steel less so.

Mostly fixed with new stacking options.

>Rope is needed for a lot of things, and crafting it en masse takes a lot of room.

Still a problem.

>Sometimes I want to move animals to a different pen, but the only way to do that is to make a baby and kill the original animal.

Animals can be roped now, solved.

>If you go bow hunting without a cart, you can't bring both the prey and the bow back - you need to leave the bow behind and then come back for it.

You can disassemble the bow to take the rope back, so kinda solved?

>Crafting a large amount of boards for a project takes a very long time and a lot of room.

Still takes a lot of room.

>Roads are very important but they are not very fun to make.

Roads are easier to make with stake changes, the biggest problem right now is finding the flat rocks.

>Sometimes it's hard to see if the oven is hot or empty.

Still a problem.

>It always felt weird to me that we get so few logs/firewood from chopping down trees. One log per tree feels especially weird.

Still weird.

>Firewood is important for a town but we can only transfer a small amount of it at a time.

Still a problem.

>Some walls are very simple to make if you have the raw materials which feels simplified, while others are very difficult which feels more realistic.

Solved.

>I don't think I've seen a single Kerosene Newcomen since the update.

I don't think I've seen a Kerosene Newcomen since I made this post almost a year ago.

>I love the look of blue/red plaster walls but you're very unlikely to find enough paint in one life to paint more than a few.

Spawn rate was doubled, so I guess tweaked?

>Sometimes you want to move the smithy, but you can't because you can't move the newcomen.

Solved.

>If you build a floor around a oven/kiln you have to destroy it first so you can build the floor below it.

Still an annoyance.

>OHOL is supposed to be a game about parenting, but most of the time you don't have to interact with your kids at all. Just feed them for a bit and set them free at the age of three.

Worse than before as mothers are punished for interacting with their kids now.

**Comment by jasonrohrer** [comment]
Going to leave firewood alone, because there's no shortage in the world, and I don't want to decrease the amount of deforestation, and I don't want to discourage you to farm trees to make up for it.  Right now, you pretty much never need to farm trees.  If I gave you 2x firewood per tree, you'd really never need to farm trees.
