### ISSUE TITLE
Bug: moving bones causes names to randomly change

### ISSUE THREAD

**Issue by rolandmartial** [jasonrohrer/OneLifeData7#332]
When bones get transported via basket, they sometimes change properties, and the age and name get changed to someone else's in the family line. Bug was unpatched as of Version 237.
 
With video proof, courtesy of Twisted.
https://youtu.be/K2bIVEhAN78?t=2434

40:34-40:37 The name is Boris Troll
41:31-42:00 Name becomes Epic Troll XVIII, and remains that way. Person who previously died is later confirmed to be Boris, and also the death date doesn't match - 244 years old.

Probably unrelated to this memory leak: https://github.com/jasonrohrer/OneLife/issues/322

**Bug section thread:**
https://onehouronelife.com/forums/viewtopic.php?id=6838

**Comment by jasonrohrer** [comment]
Closing this, will focus on the duplicate issue.
