### ISSUE TITLE
List of items that currently can not be moved or removed at all.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#333]
Player made items that cannot be moved/removed, but probably should:

- **Newcomen Engine Tower**
- **Newcomen Engine without Rope**
- **Newcomen Engine without Shaft**
- **Multipurpose Newcomen Engine**
- **Loom**

Natural items that can't be moved/removed but some people think they should:

- **Dry Pond** - Although they do give you a small amount of water, I think the nuisance of having an unmoveable object outweighs the benefit of 1 water unit every two hours, especially since they spawn in swamps which are prime real estate most of the time.
- **Barrel Cactus** - They spawn free food which is great, and they don't get in the way most of the time since deserts are inhospitable, but they can get in the way when you're building roads. When you do have one in town however I think most people prefer the benefit of respawning Cactus Fruit over the slight annoyance of an unremovable object.
- **Snow Bank** - Not that big of a deal since snow biomes are unhospitable, but they can get in the way when building roads. Sometimes you have these near a town and you don't want people using snowballs, but there's no way to move/remove them.
- **Collapsed Iron Mine** - Not very problematic considering iron deposits are very rare and usually far away from towns. I also think they look cool, they tell a bit of a story just by existing.

**Comment by futurebird** [comment]
snow drifts

**Comment by futurebird** [comment]
abandon mine?
though this isn't often a problem I just want to be comprehensive.

**Comment by TwistedHBG** [comment]
> 
> 
> abandon mine?
> though this isn't often a problem I just want to be comprehensive.

Added both, ty

**Comment by jasonrohrer** [comment]
Yes, the mine I will leave for now.... especially since they can be upgraded!

Also, it's a very deep hole...

**Comment by jasonrohrer** [comment]
Okay, these are all done!
