### ISSUE TITLE
inconsistent removal

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#34]
now that fences can be removed with mallet+shovel
should use the same principle to remove boxes, roses and marked graves

first hit it with a modifier
than remove it
for example water the rose than cut it/dig it
hit grave with mallet than dig it
some cases people will click accidentally and its very easy to do so

also chests shouldn't be destroyed only the lid, than drag away the box, this would allow making a cart, not just a kindling from chests, it's a very expensive high tech thing, making it easy to remove makes it almost useless

**Comment by jasonrohrer** [comment]
I may tackle this at some point in the future.  There are a lot of other cases that would need to be dealt with too.

**Comment by RIKennedy** [comment]
+1 - I'd also really like to see the ability to remove a cactus

**Comment by CallMeAce95** [comment]
Just remove the whole biome square why don't you, with a pitchfork. (Dont Starve was my refference for this joke)
