### ISSUE TITLE
Inefficient ball of threads crafting

### ISSUE THREAD

**Issue by Gapisze** [jasonrohrer/OneLifeData7#342]
Using drop spindle on fleece should give a stack of ball of threads, preferably 6. Inefficiet ball of threads crafting causes problems:
1. Tedious work of gathering berries and carrot to craft fleece, feeding and shearing. Fun and difficulty should come from complexity of crafting recipes, not from repetitive work.
2. Excess of dung. People on forum freak about it.

IRL there are sheeps giving enough fleece for 4-5 sweaters. In OHOL you need 6 sheeps to make one. Also, you are producing 12 dungs as byproduct only to make one dress.

**Comment by jasonrohrer** [comment]
Unfortunately, a bunch of other things are balanced along with wool production, like making airplane wings, etc.

There is a certain aspect of "repetitive work" to this game.  The complexity of crafting recipes is not necessarily the point....
