### ISSUE TITLE
Missing transition: Weak skewer + two piles of soil.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#344]
Weak skewer cannot be used to till a two pile of soil which seems to be an oversight considering a weak skewer can till both a three pile and a single pile.

**Comment by AlecYawata** [comment]
Two pile of soil is same object as three pile.
And that have transition of till.
https://onetech.info/1101-Fertile-Soil-Pile
https://onetech.info/1138-Fertile-Soil

So, we don't have any problem.

**Comment by jasonrohrer** [comment]
This is a weird one.  It should work, but it is not working, and I don't know why!

It's showing up in the editor and in OneTech, but not in the game or crafting hints in-game.  I'll keep looking at it.

**Comment by tynswk** [comment]
Copying object and transitions of Soil Pile , I changed its uses to three.
And it worked fine.
video - https://twitter.com/milkweed_ohol/status/1139807088241082368

I think category-based transitions auto-generating doesn't generate the LT transition if the child object has two uses.
