### ISSUE TITLE
Confusing transitions

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#346]
We need to use some bowl of stuffs on bare-ground to remove stuffs.
(example: bowl of carrot, bowl of limestone)
But we can remove them with right click others.
(example: bowl of berries, crucibles)
Please unify their transitions.

**Comment by jasonrohrer** [comment]
Yes, using them on the ground was the old way, before right click was added as an "alt action".

Can you give me a full list of the ones that work the old way and should be fixed?

**Comment by MilkweedOHOL** [comment]
- Bowl of Carrot

- Bowl of Limestone

- Bowl of Raw Pork

- Bowl of Gold Flakes (Should be flippable using branch)

**Comment by Spodnie** [comment]
I'm not sure if it fits here, but to get https://onetech.info/4080-Dumped-Wheat-Bowl we need to use a branch instead of right click on a bowl of wheat when it's lying on the ground.
