### ISSUE TITLE
Charcoal isn't containable

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#348]
It's enough small to contain.

**Comment by jasonrohrer** [comment]
Fixing this is easy... however, I worry that it will cause confusion.

Basket of Charcoal is a distinct item that you get from the kiln.  It is NOT just a basket with charcoal contained.

Currently, you can dump it on the ground or scoop it up again.

But if charcoal was containable as a single piece, you could put three in the basket, one by one, and then confusingly NOT have a "basket of charcoal" that you could use to fire the kiln.

The idea is that if you want to contain it, scoop it up into a basket.

There may be a cleaner way to do all this, but it eludes me.
