### ISSUE TITLE
Shot goose transitions into empty pond

### ISSUE THREAD

**Issue by gsamsom** [jasonrohrer/OneLifeData7#358]
After emptying a pond with a shot goose (with and without arrow) the goose (and arrow) disappear.

Suggested fix:
Add object empty pond with dead goose#arrow
Add object empty pond with dead goose
Add object pond with shot goose#just shot (this way an empty pond with dead goose#arrow can transition into a filled pond with dead goose#arrow without playing the shooting sound)

Remove pond with dead goose and pond with dead goose#arrow from the wetcanadagoosepond category

Add new transitions accordingly

**Comment by jasonrohrer** [comment]
How about if you just can't drain water from a shot goose pond until removing the goose?
