### ISSUE TITLE
Bowl items that should be containable

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#360]
With the Clutter Be Gone update you changed a lot of Bowl items to be containable. The logic behind it was that all non-liquid bowls should be containable, and that makes sense. However a few bowl items were missed, probably because they don't have the word 'Bowl' in their name.

Popcorn
Dry Beans with Chaff
Crucible with Charcoal
Crucible with Iron
Crucible with Malachite
Crucible with Calamine
Crucible with Malachite and Charcoal
Crucible with Calamine and Charcoal
Crucible with Iron and Charcoal
Unforged Sealed Steel Crucible
Unforged Sealed Copper Crucible
Unforged Sealed Zinc Crucible
Forged Steel Crucible
Forged Copper Crucible
Forged Zinc Crucible

**Comment by jasonrohrer** [comment]
Thanks!

**Comment by jasonrohrer** [comment]
FYI, I found a few more along the way:

```
  "Popcorn"
  "Dry Beans with Chaff"
  "Crucible with Malachite and Charcoal"
  "Unforged Sealed Copper Crucible"
  "Forged Copper Crucible"
  "Crucible with Copper"
  "Crucible with Malachite"
  "Crucible with Calamine"
  "Crucible with Calamine and Charcoal"
  "Unforged Sealed Zinc Crucible"
  "Forged Zinc Crucible"
  "Crucible with Zinc"
  "Crucible with Electrum Ore"
  "Unforged Sealed Electrum Crucible"
  "Forged Electrum Crucible"
  "Crucible with Electrum"
  "Crucible with Iron and Charcoal"
  "Crucible with Iron"
  "Crucible with Charcoal"
  "Unforged Sealed Steel Crucible"
  "Forged Steel Crucible"
  "Crucible with Steel"
  "Crucible with Scrap Steel"

```
