### ISSUE TITLE
Rubber and oil palm trees not plantable

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#361]
Every other tree that has a purpose outside of firewood are all plantable (Lombardy, juniper, maple, pine, mango and yew tree).

**Comment by jasonrohrer** [comment]
You want that rubber plantation!

Okay, okay.

**Comment by jasonrohrer** [comment]
I'm not sure that palm and banana can be cultivated via cuttings, so I'm going to skip that for now.  But rubber trees make sense.
