### ISSUE TITLE
Some tools don't have number of uses

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#364]
- spoon

- stomper

- drop spindle

- fire bow drill

- kraut board

- sharp stone

- bone needle

- charcoal pencil

- wooden tongs

- draw plate

(↓maybe the engine doesn't support these items to have uses)
- stone

- flint chip

- week skewer

- knitting needles

- straight shaft

- knife

- bow

**Comment by TwistedHBG** [comment]
I think all of these are fine as they are.

**Comment by jasonrohrer** [comment]
For the most part, tools wearing out are part of the agricultural pressure engine.  Mostly steel tools and farming tools, though some woodworking tools as well.  The woodworking tools can be used to gather wood for fires too.... so it's mostly heating and food.  This is not 100% consistent, but I don't think it needs to be.
