### ISSUE TITLE
Can't dismantle bows and untie shafts

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#365]

**Comment by jasonrohrer** [comment]
This is intentional for bows, because they are substantially transformed.

I'll look into shafts.

**Comment by jasonrohrer** [comment]
As I've thought about this more, I think these transitions are transformational, and I don't just want them to be instantly reversible.  If you actually make a bow or a tied shaft with a real knot and natural fibers, its no small matter to untie them and get your cordage back.  Knots made for building purposes (like making tools) are pretty permanent.
