### ISSUE TITLE
Snowball is still deadly

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLifeData7#369]
From: https://onehouronelife.com/forums/viewtopic.php?pid=65259#p65259

I tried snowball killing and its succeeded.

1. Throw snowball with shift right click.
2. Quick, one more shift right click.
3. You get angry and target will be dead soon.

I want to tell about "just thrown Snow-ball" emot still deadly.
https://onetech.info/2465-Snowball-just-thrown

RecordedGame
https://drive.google.com/open?id=1D0ppJ … DNnh1KPu7v

Reproduction video
https://www.twitch.tv/videos/441609812

**Comment by jasonrohrer** [comment]
AHA!  Thank you for tracking this down.
