### ISSUE TITLE
It's too easy for dogs to die out in a town.

### ISSUE THREAD

**Issue by Rosapetals** [jasonrohrer/OneLifeData7#375]
I grew up with dogs in my city, since nobody else was taking care of them and we barely had any, I did. I also have been the breeder of a town a couple other times before, too. 
I notice, dogs in a city can die out easily regardless of whether or not you teach your children how to properly care for them, since people like to hunt wolves it can be hard to get more, there's only so many wolves within a reachable state unless you want to travel miles and miles. Anywho, when a dog has a litter of puppies all you must simply do to wipe out your towns entire source of  dogs is pick up the puppies and place them on the ground. Sure, if we have carnitas around it'll be easy to take care of this **but who really cares about dogs enough to take the time out of their hour to prevent their downfall?** Okay, maybe I care enough to take the time out of my hour but if I pass the responsibilities down to my children they can just choose to not do it since it benefits them in no way other than fulfilling my dying request. 

It's mostly the children, and others of course, that like to pick up the puppies because 'omg puppies cute!! let me take care of it!", entirely unaware of how fast they are killing all of our dogs at once. Kind of the only solution is to give dogs a use and maybe each breed have their own use as well. I know it's a highly requested things, to give dogs a use, but it's hard to get people to care otherwise.  So, not only will the time you spend getting dogs for your town will be meaningless but it will never last. Or, you could make it work a bit differently, like sheep? Where the dog endlessly produces forever, and, perhaps, when 1-2 puppies of that dog makes it to adulthood then it will become an old dog. This would really help and I hope you consider it.

**Comment by laccy** [comment]
should be fed before picking it up(there is 3 so it's quite hard to do so), until that cant be moved (maybe with leash relocated
maybe some sort of dog house where puppies are on separate tiles and run left and right near their mom but you cant pick it up until you feed them
should stay as puppy for a few years, 10 min would be a small dog following you around then grow a bit
should be named and show owner (the one who fed it first, if dead than could be taken )
