### ISSUE TITLE
Steel scrap requires scrap bowl to recycle

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#376]
I know the scrap bowl is a new feature and all but I think that you should be able to recycle scrap steel without having to mark it as a scrap bowl.

This mean that you now need a knife(to make a pencil) in order to recycle broken tools. I don’t know if that was an intentional part of the change or not. Accidentally putting scrap steel in a bowl doesn’t affect anyone, since steel scrap is just junk before it gets back into steel.

**Comment by Tarr-OHOL** [comment]
Yeah, that's a little rough. Early mess up on tools is actually a giant hassle now that it requires a knife to scrap items.

Also to point out that wick housing + steel rods are not recyclable is a miss on the scraping change.

**Comment by sigmen4020** [comment]
Yea. Maybe the pencil could become craft able with a flint chip too to avoid this problem.
