### ISSUE TITLE
List of steel items that aren’t still able to be recycled.

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#378]
Steel cylinder blank
Precision cylinder
Fuel injection nozzle
Fuel nozzle body
Steel rod
Cam shaft
Crank shaft
Thin steel rod
Drill bit
Wick housing

**Comment by SySheep** [comment]
Thin steel rods need to be able to be recycled cause people often make like 3 of them even though only 1 is necessary

**Comment by laccy** [comment]
drill bit - you technically use 2 copper to make loom and then it's just stays there for nothing
if anyone wants new loom they can make a new one 

generally just the newcommen bottoms are a problem
and maybe that we cannot deconstruct newcommen multipurpose

**Comment by trevorhackman** [comment]
Fuel Injection Nozzle shouldn't be simply recycled as it takes two steel to make.

**Comment by TwistedHBG** [comment]
As of April 14th all of these are scrappable except the Fuel Injection Nozzle, but I imagine that will be solved in issue #718

**Comment by jasonrohrer** [comment]
Subsumed by #718
