### ISSUE TITLE
Why do tamed horses always run away so fast?

### ISSUE THREAD

**Issue by MRCASPER24** [jasonrohrer/OneLifeData7#379]
I understand that a tamed horse will wander around. but once you get off a horse you have about 10 secs before it takes off in a random direction! Whats the point of taming if they act just like wild horses unless hitched to a post. I don't think they should stop moving all together, but maybe a little more time before they just run off or make them significantly slower when they don't have a rider?

**Comment by jasonrohrer** [comment]
It's there on purpose to be funny, and also to motivate you to construct hitching posts in key locations.
