### ISSUE TITLE
Change listed items to be decontructable then recycled:

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLifeData7#380]
https://onetech.info/2376-Diesel-Piston-Head
https://onetech.info/2379-Diesel-Cylinder-Head
https://onetech.info/2380-Diesel-Cylinder-Head-with-Valves
https://onetech.info/2381-Diesel-Cylinder-Head-with-One-Valve
https://onetech.info/2375-Fuel-Injection-Nozzle
https://onetech.info/2348-Kerosene-Wick-Burner

These should need to be deconstructed before being recycled as it's a huge waste for these sort of things to get recycled whole (or in the kerosene wick burner case should just be decontructable in the first place.)

**Comment by jasonrohrer** [comment]
Kerosene wick burner still can't be recycled.  Will fix.
