### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by madebymario** [jasonrohrer/OneLifeData7#382]
Hi Jason, 
I guess you get many ideas for the game. However, this one wanders my mind for quiet some time now. There is a great interaction with your mother at the beginning of the game, it is one of the most tense moments that make this game unique and made me buy it. Will you survive? Is your mother a good person, who is gona take care of you? It builds tension and suspense. I miss this aspect during the later game. My grandfather passed away this january and I witnessed this process of leaving this world. What occured to me is that we need help when we get born and when life is about to end, and the last steps can not be done without the help of others. I think it would be a beautifull thing for the game, if you would have the chance to help the old to stay a little longer in the game. Something in the way of them not being able to feed themselfs for the last 3 years of their life. It became rare for people to notice that their Mother just died or any close relative. Them being helpless for the few last years could bring people more together. 

Just a thought. Great game you are developing and all the best.

**Comment by jasonrohrer** [comment]
It is an interesting idea!
