### ISSUE TITLE
Cannot remove crown from Crowned Wild Horse

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#387]
https://onetech.info/794-Crowned-Wild-Horse

Slapping a crown on a horse doesn't seem transformative and thus you should be able to take the crown off.

**Comment by voy178** [comment]
Suggestion 1: Bribe the horse with a carrot to get crown back.

Suggestion 2: Make all hats wearable for horses and allow us to add saddles and carts.

Suggestion 3: Remove the transition entirely.

**Comment by laccy** [comment]
it should work with monoliths but not with fences
