### ISSUE TITLE
Cannot paint wall using Black Paint

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#393]
The only use of Bucket of Black Paint is making Black Box. They should also able to paint walls.
https://edge.onetech.info/3022-Bucket-of-Black-Paint

**Comment by trevorhackman** [comment]
This is intentional according to - https://onehouronelife.com/forums/viewtopic.php?id=6185

"Yeah, I thought that black walls would be a little much...." - jasonrohrer
