### ISSUE TITLE
Can't turn swords back to rods.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#396]
Actually thought this was a thing in game today when I met Morti. Swords definitely should be able to be turned back into rods and then rods added to the recycle list.

**Comment by gsamsom** [comment]
You can add a War Sword to a Firing Newcomen Roller to make a Steel Rod.
You can't scrap a Steel Rod.

**Comment by Tarr-OHOL** [comment]
Ahh, didn't see it in onetech last time I checked. Forgot it was changed from just normal hammer.

**Comment by gsamsom** [comment]
The fact that Steel Rod is not part of the @ New Scrap Steel Category is maybe a bug though, especially since Steel Pipe is scrap-able.
