### ISSUE TITLE
Letters inconsistency, no numbers?

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#399]
The reason why there are no numbers on notes or speech is that we don't say it out loud, as you said
That's fine by me, but letters are visually shown on a sign, and biggest IRL usage is the KM stones

I like to mark certain positions in the world, and wondibles new map is helping to do so
when you know around which area you are, you can check for a bigger biome with recognizable shape, then the spring is on the grid so you can exactly know the coordinates of it
hope you don't consider this a leak, it isn't easy to find them

i had this idea of marking down coordinates near springs, so eventually people see that where in the world are they
this would be much easier if we could have Numbers along letters,  they are shown on a sign and we don't even pick them up to read them so there is no reason not to have numbers

the letter system has the disadvantage of higher price compared to notes
there is a big discrepancy between prices ranging from 1 to 4 sapling and 2 thread sometimes
this makes it very tedious to make them and despite that, they are also culled together with everything else
i know it sometimes contains obscenity (maybe those kind of notes and signs could be marked by  a few people, that would make it decay), but lot of times it's useful
if the roads withstand the decay, so should some signs (maybe only if locked)

to make letters useful and more common
-we need cheaper letters (same cost 1 sapling per letter)
-we need numbers
-(locked) signs should not decay
-obscene signs could be marked for decay/erase

**Comment by jasonrohrer** [comment]
way stones do this automatically now.
