### ISSUE TITLE
Filling baskets in cart/box directly

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#403]
Is it possible to make it so you can put an object directly in the basket in a cart/box instead of having to remove the basket put the object in and put the basket back in cart?

**Comment by miskas9** [comment]
or ADD the Slotted cart Item

**Comment by jasonrohrer** [comment]
Slotted cart would be possible.  But I don't think it feels quite right, having a bunch of small items rattling around in a cart.

As for adding to baskets directly, the engine doesn't support that.

It may be a bit of a pain, but there is something aesthetically nice about the way you must unload baskets from a cart.  There are a number of things in the game that are like this, like the careful mouse-click needed to pick up a needle.
