### ISSUE TITLE
I HATE the apocalypse!

### ISSUE THREAD

**Issue by MRCASPER24** [jasonrohrer/OneLifeData7#404]
My 60 minute life spent building a nice sized stone house for the future of my village! oh whats that? at age 53 the apocalypse! I get to watch everything I worked on vanish in a flash of light! Oh I built something cool yesterday I wonder if its still around, nope! gone forever.. oh my grandma is gonna show me something cool, nope! shes gonna stab me as a baby to stick a knife into some stupid ritual stone in the jungle and leave me to die! Its happening faster and faster now that people know how.. It goes against the entire point of the game~! How are we supposed to build anything meaningful or care about our family when you know at any moment  you could all be sent back to square one by other players.. Its like you're giving them the ultimate greifer tool. all in the name of adding "drama". i wouldn't mind server wipes every now and then, but this is getting out of hand and ruining the game in my opinion.

**Comment by jasonrohrer** [comment]
This isn't a bug report.

**Comment by MRCASPER24** [comment]
Ok thats fair, but its something that is affecting the game heavily.. I see a lot of players talking about it and speculating but no real explanation. Why does there have to be an Apocalypse?
