### ISSUE TITLE
Wildlife and Items in wrong biomes

### ISSUE THREAD

**Issue by MsBrittany123** [jasonrohrer/OneLifeData7#407]
When playing on other servers (I have checked 8, 9, and 11) I noticed that wildlife and stuff like ponds and ice holes are in the wrong biomes. It looks really bad and it kind of defeats the purpose of the biomes other than the temperature.

I like playing on the other servers but this makes it much less fun
![20190731_200127](https://user-images.githubusercontent.com/52865495/62256189-409a4e00-b3ce-11e9-8917-1a71b7a0aa4c.jpg)
![20190731_200147](https://user-images.githubusercontent.com/52865495/62256190-409a4e00-b3ce-11e9-90e5-884b30978bc3.jpg)

**Comment by jasonrohrer** [comment]
Second-place placement at edges of biomes has been disabled, so this is fixed now.
