### ISSUE TITLE
penguins block fishing for a few seconds

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#41]
i mean it changes it current state of ice hole but for like 10 seconds i couldn't fish when penguin jumped back in the ice hole

**Comment by jasonrohrer** [comment]
Yeah, they're in there eating the fish and scaring everything away.  They'd just eat your worm anyway, right?

But the real reason is a tech reason.  They are in there, and they will come out in a bit.  If you were to fish in there, they would be lost server-side.

**Comment by jasonrohrer** [comment]
Well, I'll make them disappear when you fish.  That's what happens when you dump water in.

**Comment by jasonrohrer** [comment]
Actually, they don't need to disappear.  They can pop out while you're mid-fishing.
