### ISSUE TITLE
Missing transition? Goose feather.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#421]
Not seeing a transition to break the shears or use the last use of a set of shears when getting a feather from a domestic goose. 

https://edge.onetech.info/3136-Shears-with-Goose-Feather

Edit: Being stabbed or dying while holding a shears with goose feather will delete the shears leaving only a goose feather on the ground.

**Comment by trevorhackman** [comment]
Might be better for it to not have a chance to use a usage at all (just like getting saplings from trees) or else shears can be spammed against geese until the shears break.

**Comment by jasonrohrer** [comment]
The thing with dropping only the feather when dying was fixed a while back.

**Comment by jasonrohrer** [comment]
Fixed here:

https://github.com/jasonrohrer/OneLifeData7/commit/2a78d5fac126ebfeb34bee57c0fdb2c191370b68
