### ISSUE TITLE
Adobe destruction in Oven and Kiln removal/griefing

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#424]
When the Oven or Kiln are destroyed, you get rubble. You only recover one adobe from the rubble. It takes two adobe to build the oven, and three to build the kiln. So a 3 year old (can minAge to use pick be higher than 3?) can destroy all ovens and kilns, and it's hard for the town to recover, might not be any adobe left. And if there is spare adobe, they can build that into ovens and kilns and then destroy those. 

Adobe Walls have the same resource destruction problem, but they're rarely built and harder to break.

**Comment by jasonrohrer** [comment]
This has been partly fixed, because you now get 2 hunks of adobe from rubble.  One is still lost for kiln destruction, but not for other stuff.
