### ISSUE TITLE
Removing stone walls is inconsistent with other hard labor.

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#425]
It's inconsistent with other hard labors like cutting trees and digging up/filling in cacti, ponds, snowbanks, etc. It should be changed into hungry work rather than using up an entire pickaxe, as that both continues to prevent players from spam-removing walls, while at the same time not making us waste iron to fix a mistake or take down a badly-placed wall.

**Comment by jasonrohrer** [comment]
Walls are different than trees.  They are meant to be expensive to get through...
