### ISSUE TITLE
Remove hungry work from useless trees.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#426]
Dead tree
Bald Cypress
Willow tree

Argument can also be extended out to doing pine trees as well. There's no real reason these specific trees should cost 10 pips seeing as when someone cuts them down its for the intended reason vs the griefing tactics of cutting down the useful trees.

**Comment by jasonrohrer** [comment]
Did this for pine.  We will revisit this later, perhaps.
