### ISSUE TITLE
Can't make keys without making locks and can't get key from lock and key without locking something

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#430]
https://onetech.info/912-Lock-and-Key-10

If the key to an already locked object is no where to be found, likely destroyed by simply scrapping it, then in order to make another key you actually need to make a whole lock and key set, and lock something else.

**Comment by jasonrohrer** [comment]
This is partly intentional, to slow down the process of locksmithing.

But having to lock something else is probably overkill.
