### ISSUE TITLE
Inconsistency - Pine isn't hungry work, but other useless/firewood trees are.

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#431]
The swamp trees [Willow and Cypress] and Dead Trees in the Desert have literally 0 purpose in the game whatsoever other than to be used as firewood.. yet cutting them down is hungry work, while pine trees [whose main purpose is also for firewood, though it also has another "use" with needles] isn't.

This makes clearing swampland for farming/building tedious and wasteful of resources, especially early on in a camp's life when they already don't have much going for food. There's also no reason for such trees NOT to be cut.. their primary function- clearing space, getting firewood- requires it. There's no griefing strategy to protect with them.

**Comment by trevorhackman** [comment]
This is intentional https://onehouronelife.com/forums/viewtopic.php?pid=73051#p73051
