### ISSUE TITLE
Cannot deconstruct spark terminal

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#436]
https://edge.onetech.info/2601-Spark-Terminal

**Comment by laccy** [comment]
when I made copper rods for loom or grapes, people clicking it made spark terminals and antennas from it, quite annoying

**Comment by cordy-123** [comment]
![unknown (6)](https://user-images.githubusercontent.com/61180955/78920801-8adbdf00-7ac6-11ea-9c69-4c765ada0202.png)

griefed vineyard near zucctown

using antenna trick
