### ISSUE TITLE
Endblock could be made by misclicking.

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#438]
You need to pick the chisel up before making cut stones.
However, when you make A Stone Block, you don’t need it.
So you might make An Endblock by accident.

**Comment by laccy** [comment]
also easy to grief
maybe add another tool for it since we rarely need it, or cycle back to normal cut stone when used chisel again, we got the stones in pair and when someone ruins one, it becomes garbage, lot of work to get new ones
