### ISSUE TITLE
Can't put raw rubber ball back into a bucket

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#439]
You can undo a raw rubber tire by adding it back into a bucket to get a bucket of rubber dough again, but can't do the same with a bowl with raw rubber ball. 

https://onetech.info/2166-Raw-Rubber-Tire
https://onetech.info/2165-Bowl-with-Raw-Rubber-Ball

Also can't do the same with a Raw Rubber Belt

**Comment by jasonrohrer** [comment]
Fixed
