### ISSUE TITLE
Steel items that can't be scrapped, but should.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#440]
**Drill Bit** can't be scrapped. It's only use is to make a Draw Plate, and after the one Draw Plate is made the Drill Bit is largely useless and clutters up the ground.

**Thin Steel Rod** can't be scrapped. It's only use is to make the Drill Bit.

**Steel Rod** can't be scrapped.

~~**Steel Pipe** can't be scrapped.~~

**Cam Shaft** can't be scrapped.

**Crank Shaft** can't be scrapped.

**Wick Housing** can't be scrapped.

**Steel Cylinder Blank** can't be scrapped.

**Precision Cylinder** can't be scrapped.

**Fuel Nozzle Body** can't be scrapped.

**Comment by trevorhackman** [comment]
Steel Pipe can be scrapped.

**Comment by TwistedHBG** [comment]
> 
> 
> Steel Pipe can be scrapped.

Thanks, fixed!

**Comment by TwistedHBG** [comment]
This was fixed with https://github.com/jasonrohrer/OneLifeData7/commit/9ba74e8b1f99afbe3cc2bab38524d82bdf189827
