### ISSUE TITLE
Cant move with WASD keys or arrow keys

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#455]
Since the bug with movement has been fixed it could be a good idea to be able to move with the WASD and arrow keys.

Mouse is fine in cities but when trying to avoid wildlife you have to click 10 times per second to avoid dying.

Moving with mouse often has the issue of clicking on various objects especially big objects like trees, walls etc.

**Comment by jasonrohrer** [comment]
There are a bunch of reasons for this being a mouse-based game.

I will make it so that you need to right-click for bare-hand actions, though, to avoid annoying mis-clicks when walking around
