### ISSUE TITLE
stuff can be thrown over the rift using baskets

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#462]
Puting stuff in basket next to rift and stacking them lauches items accross the rift.

https://cdn.discordapp.com/attachments/328215300279500800/624072939649630234/brian.png

Maybe making the objects bounce on the rift would solve the issue

**Comment by Dodg-e** [comment]
possible solution https://onehouronelife.com/forums/viewtopic.php?pid=73831#p73831

**Comment by jasonrohrer** [comment]
Thanks!

Duplicate of #441
