### ISSUE TITLE
Missing wool legwear

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#463]
https://edge.onetech.info/583-Knitting-Needles

Knitting needles + Huge ball of yarn = Wool Sweater
Knitting needles + Large ball of yarn = Wool Hat
Knitting needles + Small ball of yarn = Wool Booty
Knitting needles + Ball of thread = Does not exist

There's a wool hat piece, chest piece, foot piece, but no leg piece.

**Comment by jasonrohrer** [comment]
Well, you can weave trousers now.  People don't normally knit trousers....
