### ISSUE TITLE
Make small trash pit useful

### ISSUE THREAD

**Issue by aviseu** [jasonrohrer/OneLifeData7#464]
As it stands right now the small trash pit isn't really used at all. Small changes might make it useful again for players.

This is related to the following objects:
https://onetech.info/620-Small-Trash-Pit-with-Stakes-groundOnly
https://onetech.info/617-Small-Trash-Pit
https://onetech.info/618-Filled-Small-Trash-Pit

Fix 1: make number of usages of 617 and 620 consistent. Pit with stakes has 10 usages,  small trash pit has 20.
Fix: 2: Increase number of usages to a number that can have a significant impact in town clutter. 50 suggested.
Fix 3: Increase decay time from 1 minute. This is too little time. 20 minutes?
Fix 4: Remove the following items from having transitions with trash pits (both with and without stakes): rabbit fur, corn kernel
Fix 5: Add the following object transitions:
- Rubber Tree Cutting
- Stakes
- hot pepper
- burnt shrimp
- Dug Wild Pepper Plant
- Dug Wild Tomato Plant
- Bowl of Palm Kernels 
- Bowl of Nitric Acid
- Bowl of Silver Nitrate Solution
- Bowl of Rust
- Bowl of Rust in Salt Water
- Bowl of Ketchup
- Bowl of Sweetened Vinegar
- Bowl of Salsa
- Bowl of Charcoal Powder
- Bowl of Copper Sulfate with Alum and Niter
- Bowl of Copper Sulfate with Alum
- Bowl of Raw Sugar
- Bowl of Bagasse
- Bowl of Vinegar
- Bowl of Cane Juice
- Bowl of Soaking Sugarcane Pulp
- Bowl of Sugarcane Pulp
- Juniper Tree Cutting
- Bowl of Iron Filings
- Bowl with Coherer
- Clay Bowl with Coherer Parts
- Carbon Filament
- Carbon Filament with Wire Leads
- Diode Leads
- Triode Leads
- Cool Glass
- Soda Lime Glass Batch
- Bowl of Soda Lime Mixture
- Bowl of Sand
- Bowl of Soda Ash
- Bowl of Soda Ash Solution
- Bowl of Glasswort Ashes with Filter Paper
- Bowl of Soaking Glasswort Ashes
- Bowl of Glasswort Ashes
- Daniell Cell Anode
- Bowl of Copper Sulfate
- Cut Glasswort
- Dry Glasswort
- Bowl of Saltpeter and Sulfur
- Bowl of Saltpeter
- Dirty filter Paper
- Bowl of Saltpeter Solution
- Ash Niter Solution with Filter Paper
- Bowl of Dissolved Niter with Ashes
- Bowl of Niter Solution
- Candle
- Bowl of Palm Olein
- Bowl of Palm Wax
- Fractionated Palm Oil
- Partial Garland 1 to 6
- Garland
- Turkey Leg Bone (only do it together with Turkey Carcass on Plate please)
- Turkey Carcass on Plate
- Bucket of Liquid Latex
- Bucket of Coagulated Latex
- Bucket of Sulfured Latex
- Bucket of Oiled and Sulfured Latex
- Bowl of Palm Oil
- Bowl of Soaking Palm Kernels
- Bowl of Separating Palm Oil
- Bowl of Crushed Palm Kernels
- Bowl of Roasted Palm Kernels
- Bowl of Palm Kernels
- Bowl of Sulfur
- Blank Card Stack
- Blank Die
- Wet Blank Die
- Burnt Fish
- Bucket of Yellow Paint
- Bucket of Red Paint
- Bucket of Blue Paint
- Bucket of Milk Paint
- Bowl of Mango-Infused Cow Urine
- Bowl of Indian Yellow Pigment
- Bowl of Vermilion Pigment
- Bowl of Ultramarine Pigment
- Mango Leaf
- Yew Tree Cutting
- Pine Tree Cutting
- Poplar Tree Cutting
- Maple Tree Cutting
- Dead Chihuahua
- Dead Schnauser
- Dead Dachshund
- Dead Poodle
- Dead Airedale
- Dead Beagle
- Dead Pit Bull
- Dead Collie
- Dead German Shepherd
- Dead Chihuahua Puppy
- Dead Dachshund Puppy
- Dead Schnauser Puppy
- Dead Poodle Puppy
- Dead Airedale Puppy
- Dead Beagle Puppy
- Dead Pit Bull Puppy
- Dead Collie Puppy
- Dead German Shepherd Puppy
- Dead Wolf Puppy
- Bowl of Wood Pulp
- Bowl of Cooked Wood Shavings
- Bowl of Wood Shavings in Water
- Dead Domestic Calf
- Dead Bison Calf
- Leavened Dough on Clay Plate
- Flint Arrowhead
- Bowl of Salt
- Bowl of Soaked Beans
- Bowl of Soaking Beans
- Bowl of Cleaned Dried Beans
- Winnowed Dry Beans
- Dry Beans with Chaff
- Sprouting Potato
- Split Potato Sprouts
- Dug Teosinte
- Teosinte Seed Head
- Rag Shoe
- Tattered Backpack
- Rag Loincloth
- Rag Shirt
- Rag Hat
- Worm
- Rose Madder Root
- Indigo Bundle
- Bowl of Quicklime
- Bowl of Plaster

**Comment by Davidj361** [comment]
We really need a useful trash pit.

**Comment by laccy** [comment]
stakes can be chopped into kindling, they are useful if there is too many I always chop them
other than occupying a bowl I don't see the reason of that list

my list would be:
any dead animal
any unedible food (burned rabbit or fish)
any seed from wild  (since making them sometimes cost water, some of them are quite valuable, like potato or carrot) also some can be washed out of the bowl so no issues there
painting material is limited so bad idea
tree cuttings decay and they cost something 

duping all those things would just be griefing
the only use I see would be pig pens and sheep pens, bad cow pens (no reason to have multiple cows, other than urine, if you want that just put the bison in small biome), higher timer and uses would be nice

**Comment by jasonrohrer** [comment]
Fixed in:

https://github.com/jasonrohrer/OneLifeData7/commit/f50db415bdae992d67bca263fc4ebc55b356999e

https://github.com/jasonrohrer/OneLifeData7/commit/79b21e1e856c16a3f64c1d773307e8538cc4a062
