### ISSUE TITLE
QoL problems with copper

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#466]
Can't scrap copper parts
Similar to steel items, the ability to scrap copper rod, copper foil, copper pot, copper wire, and copper coil to get your copper back would be useful

These transitions seem like you're just putting stuff together in a non-transformative way, and thus should be reversible

Cannot separate paper and copper foil
https://edge.onetech.info/2533-Foil-and-Paper-Sandwich

Cannot separate copper sandwich
https://edge.onetech.info/2644-Copper-Foil-Carbon-Sandwich

Cannot wipe off carbon
https://edge.onetech.info/2643-Copper-Foil-with-Carbon-Granules

**Comment by jasonrohrer** [comment]
Recycling for clean parts has been added.

The other stuff is considered dirty or spent.
