### ISSUE TITLE
Can't grab bones with backpack

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#468]
A basket can hold bones but a backpack can't. 

A similar case to this is soil, where both basket and backpack can take soil. 

This could remedy the loss of carting bones if you can carry a basket/backpack of bones in your hands with another backpack of bones on your back. I'm not sure if that would cause the same issue with human bones, but at the very least backpacking animal bones should be fine.

**Comment by jasonrohrer** [comment]
Actually, with the way grave identities are tracked, I think it's impossible for bones to be tracked properly in the backpack.
