### ISSUE TITLE
Letters cost too many skewers

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#474]
I would suggest that a letter stock could generate infinite letter stocks the same way property fences do. This would make sign making cheaper while keeping the complex letter crafting.

That is just a suggestion though. You go with whatever you feel is the best solution to this problem.

**Comment by HimitsuGato** [comment]
I am of the opinion that much like the original radio (only able to transmit Morse code), this obfuscation is an endearing quirk of OHOL. Like, complicated and near-impossible to memorize recipes is the exact kind of fun and challenge of the game that I signed up for. I spent a life making signs, it was absurd for sure and took almost my whole life but I was so proud of my effort by the time I was done.

**Comment by jasonrohrer** [comment]
Whoops, those last two commits are for #464 instead.  Typo
