### ISSUE TITLE
Killing geese can be difficult in big towns due to lack of stumps

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#475]
If you want to kill a domestic goose, you need to put it on a tree stump and behead it with an axe. The problem arises when the town has already been alive for a while and there are no disposable trees nearby, which makes killing geese a very slow process.

We should be able to either behead geese on stone blocks or logs, or have the ability to move and 'replant' stumps.

**Comment by Spodnie** [comment]
How about planting a tree in geese farm?

**Comment by TwistedHBG** [comment]
> 
> 
> How about planting a tree in geese farm?

The problem with that is that trees take 90 minutes to grow, and if the stump gets removed or it decays you have to plant another tree all over again.

**Comment by MilkweedOHOL** [comment]
Goose + Stone Block = Goose on Stone Block?
Goose on Stone Block + Axe = Beheaded Goose on Stone Block?

**Comment by Spodnie** [comment]
Maybe stumps shouldn't decay? I would be fine with it
