### ISSUE TITLE
holding dress as child looks odd

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#478]
https://i.ibb.co/QvtBQ8z/screen00125.jpg

https://i.ibb.co/6Ph2P2V/screen00126.jpg

**Comment by trevorhackman** [comment]
Looks odd wearing the dress too, doesn't quite fit

**Comment by jasonrohrer** [comment]
The holding part has been fixed.  The wearing part will have to stay as-is for now...  the dress is big!
