### ISSUE TITLE
You can name your kids Eve now

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#488]
This was probably oversight when adding the new names, but being able to name kids Eve creates a lot of confusion. For one it's harder to identify the family founder in towns now, and it also creates more confusion in the lineage browser.

Lineage founders should have distinguishable name (Eve), which you can't name your children.

Example of a person in 25th gen of a family with the first name Eve:
![image](https://user-images.githubusercontent.com/51952537/66643489-19a69680-ec1f-11e9-949d-4eb4cbf22d4d.png)

**Comment by jasonrohrer** [comment]
Fixed
