### ISSUE TITLE
Pit bulls do not age like other dogs

### ISSUE THREAD

**Issue by HimitsuGato** [jasonrohrer/OneLifeData7#489]
The only case where pit bulls get old and die peacefully is when you feed them and they have babies. This is different than all other dogs.

With other dogs, the movement uses correspond to them aging. They become old as time goes on. With pit bulls the movement uses is them slowly becoming mean. Are we to believe that pit bulls are the only ones that become 'abused' and 'mean' through lack of feeding?

Some players lately have been mass breeding dogs and letting pits clear towns. Maybe these people don't even mean to grief, but just want to breed some puppies. Why should pits be the only ones required to be cared for lest they become violent?

**Comment by jasonrohrer** [comment]
This is okay.  They are different on purpose.
