### ISSUE TITLE
Cant use tank of water to fill newcomen pump and newcomen engines

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#494]
newcomen oil rig, water pump and newcomen engine

**Comment by jasonrohrer** [comment]
I think this is okay.

A full bucket of water can do a lot of things, and I'm not going to go duplicate all of those for the water tank.

The other problem is that the water tank has uses, where the full bucket does not.  So there might be an issue with some of the transitions (like into the cistern).  I'm not sure how the engine handles parallel use counts (water tank going down while cistern goes up).
