### ISSUE TITLE
Babies can erase maps with rubber ball.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#495]
Same goes with paper if not done in permanent writing. Probably makes sense thematically as a child can very well ruin a map or piece of paper but seems kind of silly having a baby erase things.

**Comment by jasonrohrer** [comment]
Yeah, I think this is okay.

The point of them having the ball is to play (the only toy in the game so far).

It's funny that they can "scribble" on written items and ruin them.
