### ISSUE TITLE
Bow saw expend slot without using.

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLifeData7#496]
There is no confirmation, but My skill slot was expended by bow saw, when I pickup from box and return it.
I'm trying to record video, now.

**Comment by AlecYawata** [comment]
https://imgur.com/a/fFXSuBR

**Comment by JkHowling** [comment]
I played a couple lives last night and had similar issues with some. Those were:

-Needle and Thread via placing in a pocket/backpack
-Pad by placing in a medic apron/bowl
-Sword by placing it on a backpack

**Comment by miskas9** [comment]
https://onehouronelife.com/forums/viewtopic.php?pid=78039#p78039

**Comment by AlecYawata** [comment]
Fixed by 
https://github.com/jasonrohrer/OneLife/commit/15b817dea810dbfecd811d949c09ea59676558e0
