### ISSUE TITLE
Visual glitch shoes appearing on random tile when using horse

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#50]
When riding horsecart (maybe horse too) not sure if always or only sometimes there is a visual glitch where the shoes of the person riding the horse appear visually on a random tile

https://imgur.com/a/YXk4EuO

The tile where the boy is standing has the visual of the shoes of the person riding the horse

**Comment by jasonrohrer** [comment]
In my testing, I can reproduce this!   The shoes of the rider ALWAYS appear in the world at (0,0)

So in your case, that must be the spot where you were born, good sir.  (0,0).  And anyone riding a horse in your game will leave their shoes there.

Will fix.
