### ISSUE TITLE
Shelves only buildable on plaster walls

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#505]
They're only able to be set up on basic plaster walls. Impossible to put together a shelve on a wall that has been painted, a non-plastered wall, stone walls, etc. Doesn't really make much sense, especially when stone walls are the most commonly used walls and how much work it takes to make paint [only to find out you can't build a shelf there, or someone comes along and plasters over it again so that they can :( ]

**Comment by jasonrohrer** [comment]
I was avoiding combinatorial explosion there, but there are only two paint colors, so it's not that bad.

The shelves were "fancier" so the weren't buildable on basic adobe walls, and stone walls, I dunno.

The plaster walls kinda seem like the fanciest walls.
