### ISSUE TITLE
Puppies getting stuck sometimes (solved)

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#51]
Sometimes puppies get stuck, cant pick them up, they dont move or age
Not sure if all puppies have same problem but pit bull puppy confirmed

https://imgur.com/a/OTzcRCe

**Comment by jasonrohrer** [comment]
This is probably triggered by a certain action by some player.  Maybe the old "right-clicking face" to drop, which has been fixed.  I'm going to close this for now.  Please re-open if you find a series of actions that can trigger it.  (The right-click-face fix will go live in a few hours).

**Comment by jasonrohrer** [comment]
Actually, clicking on face could only drop non-permanent objects like goose or piglet.  Those are non-permanent so they can go in the basket.  Puppies... not sure what would allow you to drop them without them going through transition.  Re-opening.

**Comment by Dodg-e** [comment]
Found it!

Bugged puppies are made by feeding a hungry puppy on the 8th move.
