### ISSUE TITLE
Remove ability to add water to full shallow well.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#516]
Due to the ability to add water to a full shallow well you're able to spam click a shallow well from full to one charge within 10 seconds depending on your luck. This means within seconds of a well being made you can essentially cause it to need an immediate upgrade.

**Comment by jasonrohrer** [comment]
Steps to reproduce?

Do you need to transfer water back and forth between two wells?

Or use multiple bowls?  Or..

**Comment by jasonrohrer** [comment]
Also, I'm not able to add water to a full shallow well in my test.....  once it becomes full, it stops accepting more water...

**Comment by Tarr-OHOL** [comment]
Ahh I see the issue, I didn't have a full well but the sprite is the same for full well -1 bowl of water.

Regardless the real issue still remains in the fact you shouldn't be able to put water back into a well as this can net or lose charges of water very quickly should someone be spam clicking. Basically water gambling really shouldn't be a mechanic in game as its both uninitiative (I've seen many times in the past where players would put buckets of water in deep wells to "store" it.) and it just comes off as silly (you can flood a pond by taking out a bowl of water and putting the same water back in.)

So it's still possible to quickly drain shallow wells the only requirement is it be at 4 uses instead of 5 (otherwise putting a water in fills it to max) and some bad luck.

**Comment by jasonrohrer** [comment]
So is the suggestion here that once taken out, water should never be able to go back?  Not in a pond or well?

But sometimes you click by accident, and then what?

Maybe clicking by accident is a non-issue?
