### ISSUE TITLE
Soil tilling not working as intended after fix.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#517]
Basically after the fix for more fair arctic farming you can't actually hit two piles of soil unless using a specific thing in any biome what so ever.

One pile is still doable, and three piles are doable but two piles can only be whacked specifically by weak skewers and weak skewers only. The weak skewer transition even goes as far to let you do perfect soil tiles on arctic farming areas even though it's not efficient at all.

So by doing the change it now makes it so soil can only be wasted or iron wasted unless using weak skewers which seems like an accidental oversight.

**Comment by AlecYawata** [comment]
Remainding this commit's changes, I thought "two piles of soil can tilled never" is intention.
https://github.com/jasonrohrer/OneLifeData7/commit/855a516749b9ba7a99a5722b54b085dcb6473908#diff-b47f4fcbcf4e289c4593971b01778073

So, maybe till with weak skewer is bug.
Remove transactions/852_903_LT.txt is way to fix.
I'll try to test it.
