### ISSUE TITLE
Dry Pond can be removed, but not Abandoned Rabbit Hole

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#522]
Rabbit holes are plentiful, regrows and an immovable object. Abandoned Rabbit Holes should logically be removable hunger work in the same way that Dry Ponds are to allow for easier town construction.

**Comment by jasonrohrer** [comment]
This is mostly fixed as part of #538 

However, the abandoned holes are not directly removable (because there's no rabbit to flee).  So you must wait one epoch for the rabbit to return in order to move them.

**Comment by voy178** [comment]
So we have to wait for an eternity before we can complete a building we have all the materials for because there have to be a rabbit in the hole no one wants or will ever miss? That's silly. Hungry work abandoned rabbit holes is much more to the point and what's to say that the rabbit won't settle somewhere even less desirable like inside the building or in the middle of the town right infront of the smithy? There are hundreds of holes everywhere on the map so close by that missing one in town is not gonna be noticeable.
