### ISSUE TITLE
Items that should stack ,but they dont

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#530]
In general small, thin or flat items should stack.
Here is a list of them:
-Needles
-Arrows
-Arrowheads
-feathers
-nondecaying Hats
-Mouflon hide
-Sealskin coat
-Sheep Skin
-coal
-dirty wool pads
-snares
-worms
-sharp stones
-charcoal pencils
-eggs
-peppers
-potatoes
-tomatoes
-onions
-corn
-beans
-Sharp Stones
-empty buckets
-skewers ( supposing that flint will be used to create knitting needles)
-Defaced Bone Pile (stack 6 of them and then setting them to fire with kindling as well would be nice)

**Comment by miskas9** [comment]
-Shoes (pair of shoes at least or 6 stack of them)

**Comment by Cogito** [comment]
> Defaced Bone Pile (stack 6 of them and then setting them to fire with kindling as well would be nice)

Not sure how this fits in the game, but a 'funeral pyre' item would make an excellent addition to role-play.

**Comment by miskas9** [comment]
-rubber tires
-pencils

**Comment by jasonrohrer** [comment]
Tires are kind of a pain, because they already can be stacked in pairs.

Hats are a combinatorial explosion due to all the colors.

**Comment by jasonrohrer** [comment]
Problem with skewers:  there are two different types (weak, non-tilling, and strong tilling)
