### ISSUE TITLE
Babies should be put in bags or "slings"

### ISSUE THREAD

**Issue by mithasorken** [jasonrohrer/OneLifeData7#532]
Hello, as a father and a huge fan of OHOL, I think that the babies should be carried around in a backpack or a "sling" (which is used in several ancient human societies in the real life). so that new mothers wont have to leave all the belongings and carry around the baby. 
thank you.

**Comment by jasonrohrer** [comment]
This is working as intended.

Taking care of a baby in the game is supposed to be a major sacrifice.
