### ISSUE TITLE
Tables missing functionality 

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#539]
This is not really a bug, but it feels kind of weird to me that the only use for tables is making a Feast. It would be nice if they could contain 2 or 3 large items, making them a cheaper and weaker but nicer looking version of the Box.

**Comment by jasonrohrer** [comment]
Yeah.... the problem is differentiating the actions between laying out a feast (which involves setting food on there) and putting stuff into the container.  I'll take a look, though.

**Comment by jasonrohrer** [comment]
As it currently stands, the first two items that you must lay out for the feast (pie and bowl of whipped cream) are both containable.

I could change it so that you have to put the sliced bread (not containable) on there first....

I do worry about confusion here, though.
