### ISSUE TITLE
Spring System is Trouble Waiting to Happen

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#543]
There was recently a rise of wells getting blocked off by waystones as reported by ollj: https://onehouronelife.com/forums/viewtopic.php?id=8765 and also can get observed in Wondible's stream from 4:40 on: https://www.twitch.tv/videos/524570307 .  Even if waystones were made so that they could get moved more easily, there exist other ways to block off a well.  For example, it's possible to build adobe walls around a well.  The old system where ponds could get dug up into wells was more less fragile to this sort of water griefing.

**Comment by jasonrohrer** [comment]
The waystone issue has been fixed.

If someone blocks a spring, can you just walk to find another?

If we want to come up with a list of things can can't be removed, that should be a separate issue.  Adobe walls can be removed currently.

Ancient stone walls cannot be removed, but those take a long time to make.
