### ISSUE TITLE
Steel Rods Fit into a Basket But Steel Pipes Do Not

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#544]
If one uses the bore, one might expect that one can store rods in a basket, and then throw pipes back into the basket after boring the rods.  But, steel pipes don't fit into a basket, and thus one can fail to throw pipes in a basket while the bore clock is quickly ticking down.

**Comment by jasonrohrer** [comment]
It was an oversight.... steel rods are actually too big to look good in the basket!

**Comment by jasonrohrer** [comment]
Ah, what the heck, let them both go in the basket!
