### ISSUE TITLE
Only brown people can kill cows, only gingers can finish sauerkraut. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#545]
Both result in mostly permanent blocked tiles unless someone of the appropriate race show up.

Cows in places like kitchens are annoying.
Half finished sauerkraut wastes both crocks and tiles unless being able to complete.

**Comment by jasonrohrer** [comment]
Sounds like the best way to handle the cows is just to let you move them, right?

I mean, if I let you slaughter them, I need to put the whole beef tree in there.  Holding off on that for now.
