### ISSUE TITLE
Wolf related issues.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#548]
Dead Semi-tame wolf follows dog code and decays after ten minutes unlike a regular dead wolf which never decays. The issue with this is wolf farming is already slow due to old semi-tame wolves not being killable except by age.

Asking to up the dead semi-tame wolf decay time to allow easier harvest of wolf skin. Along with this asking for the ability to shoot old semi-tame wolf to speed up wolf skin harvest time. 

Also asking for the ability to move wolf corpses out of a pen area as the decay time of a skinless wolf is one hour regardless if it was originally tamed or wild. This makes breeding wolves require a lot of space as tiles start being filled up by skinless wolves.

**Comment by jasonrohrer** [comment]
The idea with the dogs is that they are your pets, so it is weird to just shoot them.

Will fix it so you can move the corpses around.
