### ISSUE TITLE
Dyed roses

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#552]
Currently, we can only dye roses blue. But it would be nice to have the option to dye them into any of the available colours (even red if wanting a red rose without the job necessary to grow a new type of rosebush).

It would make RP flower language possible, having certain coloured roses on your hat have a different meaning or occupation, etc.

**Comment by jasonrohrer** [comment]
Hmm...  give him the black rose!

Yes, I'll do this.

> Who's been painting my roses red
> Who's been painting my roses red
> Who dares to taint with vulgar paint
> The royal flower bed
> For painting my roses red
> Someone will lose his head
