### ISSUE TITLE
Bowls of Palm Olein and Palm Oil Don't Fit in a Rubber Tire Horsecart

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#553]
Why is this an issue?

Empty bowls fit in horsecarts.  Palm olein and palm oil both fit inside of a bowl and don't take up more space.  Both types of bowls can get emptied and an empty bowl comes back, without any deformations.  Thus, any decent sense of physics gets lost since a bowl of palm oil and a bowl of palm olein somehow deforms a bowl so that it can't fit into a cart, but the bowl also can get reformed to become empty and exactly having the same structure as it's original empty shape.

**Comment by jasonrohrer** [comment]
No bowls of liquid are currently containable in carts.  They would spill.
