### ISSUE TITLE
[Quick Issue] Pouring saltwater into Ice Hole can revert covered ice holes

### ISSUE THREAD

**Issue by MonsWTF** [jasonrohrer/OneLifeData7#554]
![image](https://user-images.githubusercontent.com/7107685/71680449-bd4fa080-2d4f-11ea-95a5-7b8b2da177bd.png)

This occurs due to the nature of the category **@ Any Ice Hole** and its transition.

![image](https://user-images.githubusercontent.com/7107685/71680507-ea9c4e80-2d4f-11ea-93fa-a4fcd40d9966.png)

![image](https://user-images.githubusercontent.com/7107685/71680529-f851d400-2d4f-11ea-9791-b5eaebd5b318.png)

_Suggested Fix:_ 

This can be fixed by changing the saltwater-dumping process to non-animal occupied Ice Holes and enabling two Pattern categories:

1) Changing **@ Any Ice Hole** to **@Ice Hole Pouring** and **enabling Pattern**.
Adjust the list to contain:
- Ice Hole
- Ice Hole# water dumped
- Ice Hole with Snow Floor

2) Add new Object **Ice Hole with Snow Floor# water dumped**

3) Add category **@ Ice Hole Dumped** and **enabling Pattern**.
Adjust the list to contain: 
- Ice Hole# water dumped
- Ice Hole# water dumped 2
- Ice Hole with Snow Floor# water dumped

4) Remove the above Ice Hole transition

5) Add new Ice Hole Pattern transition to all salt water objects: (or another pattern if you wanna speedline that process)
![image](https://user-images.githubusercontent.com/7107685/71681136-85495d00-2d51-11ea-9449-b01591c949eb.png)

6) Add transition for **Ice Hole with Snow Floor# water dumped** to revert to **Ice Hole with Snow Floor** after 5 seconds.

**Comment by jasonrohrer** [comment]
What a nicely detailed report!  Thank you.
