### ISSUE TITLE
Kerosene Newcomen Pump is Counterproductive to Make

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#558]
A kerosene newcomen pump produces a tank of water with 6 buckets of water.  A diesel water pump produces 7 buckets of water.  Both use one charge of kerosene.  The kerosene wick burner also requires water to get made, suggesting that there's every reason to just complete a diesel engine and install a diesel water pump and use up the water from a charcoal pump as soon as possible skipping the kerosene newcomen pump entirely.  When oil rigs didn't deplete this wasn't an issue, since one just improve water production efficiency by changing a charcoal pump into a kerosense pump.

Were a kerosene newcomen pump produce more buckets of water than a diesel water pump, at least in principle, there would exist some motivation to make one.  Or if oil rigs didn't deplete.

Possibly related: in the big population context all three main races come as required for oil since gingers have to run the rig and rubber is needed for the oil pumpjack.  Thus, the most advanced trading stage comes as required for the kerosene newcomen pump which one would expect would not be the most advanced water technology.

**Comment by jasonrohrer** [comment]
Kero is supposed to be a temporary point that you reach---maybe---on your way to diesel.

Pumping oil is way easier than making a diesel engine.

Thus, once you have oil, you can get more water from your pump, per pumping, while you build the diesel engine.

**Comment by DougLefelhocz** [comment]
Wait, you don't care about families rushing to diesel engines?  You once made a comment about how fast families got to diesel engines:

"All that said, so far, this game has been a pretty lousy embodiment of that thought experiment.  The answer is that people get back to diesel engines in a generation or two!"

https://onehouronelife.com/forums/viewtopic.php?id=8576
