### ISSUE TITLE
Dug rabbits occupy floored tiles

### ISSUE THREAD

**Issue by MaDc0wUSP** [jasonrohrer/OneLifeData7#559]
![3](https://user-images.githubusercontent.com/4856680/71770741-93a19f80-2f30-11ea-8c28-939b62cc1b58.png)
![1](https://user-images.githubusercontent.com/4856680/71770744-99978080-2f30-11ea-9132-35622aa6f723.png)

**Comment by jasonrohrer** [comment]
They dug right through that floor, eh?

**Comment by MaDc0wUSP** [comment]
Yup, haven't tested stone or pine floors if the same thing happens.
