### ISSUE TITLE
Bottles lack broader uses

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#560]
Bottles should be handier at storing other things besides wine, such as:
-Palm oil
-Vinegar
-Sugar
-Salt
-Whole milk
-Skim milk

**Comment by jasonrohrer** [comment]
Fixed in commits:
d3104c426b0f8dfafb5d19aab0353f856cfab566
b9a820e457a4468a8679850705f73e6b2733e12f
22e0ffe5661299099cf3a819c33aeef2b4af0f34
