### ISSUE TITLE
Wine Can't Go Into a Clay Bowl

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#564]
Fluids work in such a way that wine can fit in a clay bowl.

**Comment by jasonrohrer** [comment]
We're a civilized people who drink our wine proper-like.

**Comment by DougLefelhocz** [comment]
The above is a very strange response.  Among other things, a berry in a bowl is a different yum food than eating a berry in one's hand.  Bowls get put to OHOL player's lips rather frequently in other ways also.
