### ISSUE TITLE
Eves Can't Have Ancestors

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#565]
If an Eve could have an ancestor, then a player in one lineage whose lineage died out to an update, could get reborn as an Eve, perhaps not by their choice, and that Eve have an attachment to the pre-update family tree.   So, Eves not having the ability to have ancestors is probably why lineages can't survive updates.

**Comment by jasonrohrer** [comment]
Again, this was an ancient design decision, and I stand by it.

This game is all about continuity.  A lineage means a group of people who directly collaborated across time.  I knew my mother, and she knew her mother, and she knew her mother, etc.

During a server shut-down, continuity is broken.  There's no way to "fake" it in that case.

**Comment by DougLefelhocz** [comment]
Lineages don't require any collaboration.  A lineage already exists (or will exist once relevant death(s) occurs) once a child gets born to a mother.  The child need not collaborate with the mother for a lineage to exist, it can run or suicide.  The mother need not collaborate with the child for a lineage to exist also, the mother can never pick the child up, and a lineage still exists.

Thus, no, lineages don't mean a group of people who directly collaborate across time.
