### ISSUE TITLE
Spoons Can't Get Used for Stew, Kraut, Or Anything Else But Ice Cream

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#566]
Spoons also don't smelt: https://github.com/jasonrohrer/OneLifeData7/issues/339

**Comment by sigmen4020** [comment]
Spoons can be smelted:
https://edge.onetech.info/2795-Spoon
![image](https://user-images.githubusercontent.com/51952537/72072237-c90e0a80-32ed-11ea-836b-db476dc16fb1.png)

**Comment by jasonrohrer** [comment]
This is a weird one.... b/c spoons are relatively high-tech, and stew is somewhat low-tech, right?  Maybe not...

But still, I can't imagine requiring a spoon for stew.

For ice cream, it was funny to require a spoon.

Though I guess it is hard to eat stew without a spoon.

I eat sauerkraut with a fork, though...

I'm going to stew on this one a bit more.

**Comment by Cogito** [comment]
> Though I guess it is hard to eat stew without a spoon.

It is!

Perhaps there could be an item 'soup with spoon' (add spoon to bowl of soup) that gives an extra meal from the soup because you're not wasting any while messily slurping the soup straight from the bowl.

Would also add an extra yummy food, at the cost of having to create and keep track of the spoons.

**Comment by Tipy1802** [comment]
I think you shouldn't be able to eat from a berry bowl without a spoon

Actually no, you shouldn't be able to eat from the bush itself without a spoon!
or drink milk without a wine glass

I mean sure you may be starving but what are we? Barbarians?! Show some manners!
