### ISSUE TITLE
Cannot grow or plant glasswort. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#568]
With the upcoming glass update it would be a good time to allow players to plant glasswort in the desert. 

To put in perspective:
Glasswort has a 3.8% spawn rate in desert biomes 
Sand deposits which have 5~6 uses have an 8.86% spawn rate (sand can also be harvested from dry springs + the empty pit.)
Limestone has a whopping 14.16% spawn rate.

This makes the choke point black people + luck based off deserts. Without talking all the issues with high tech items in game it just makes sense for players to be able to grow glasswort.

**Comment by jasonrohrer** [comment]
Yes, good point!
