### ISSUE TITLE
Rubber stoppers might be too expensive?

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#569]
This is not really a bug, but more of an observation that is more relevant soon with the addition of bottle storage.

One bucket of Rubber Dough can be turned into four rubber items, be they four big rubber tires or four small rubber stoppers. It feels weird to me that you only get one rubber ball from the same amount of rubber that gives you a whole rubber tire, and even weirded that you get one tiny bottle stopper from that same amount.

What if the exchange was instead 1 Rubber Tire = 2 Rubber Balls = 4 Rubber Stoppers or something similar? Even that would feel slightly weird as one tire clearly has much more rubber than four stoppers, but it would make much more sense than the current system.

**Comment by jasonrohrer** [comment]
Good point!
