### ISSUE TITLE
World Keeps Resetting

### ISSUE THREAD

**Issue by catdavis67** [jasonrohrer/OneLifeData7#57]
As of this morning, the world keeps resetting.  Korilian reports on the Bug forum:
"Here's an odd one. While I was playing the World kept resetting. I'd pick milkweed and the plant would instantly respawn. Items would dissapear from my hand and basket. Twice our town completely reset to the way it looked when we arrived (i.e. empty). At that point I decided to kill myself to report the problem."

Mr.XIX confirmed the bug:
"Can confirm this bug. Lived my whole life living of a single berry bush, because it kept resetting smile
Unable to play, because everything you make disappears."

I can also confirm the problem.  Everything was fine last night, this only started happening this morning.  At this point, the game is unplayable.  Just wanted to make sure you were aware of the issue.

Thanks for a great game!
Cat

**Comment by Footech13** [comment]
[stdout0181114.txt](https://github.com/jasonrohrer/OneLifeData7/files/2581259/stdout0181114.txt)
Here's the stdout file from the buggy game, in case you need it.

**Comment by jasonrohrer** [comment]
Server 3 was out of disk space.  This has been fixed.
