### ISSUE TITLE
Sand is a burden to transport

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#570]
Sand, compared with many other materials is a burden to transport, since you can only carry one bowl at a time. This means that with maximal available travelling storage (tire horse cart), you can only transport eight bowls of sand at a time.

**Comment by jasonrohrer** [comment]
Aha!  What about bottles of sand?

So then once you boostrap glass-making, you can start carrying a lot of sand.

**Comment by sigmen4020** [comment]
If it doesn't require it could work.

But I was more thinking along the lines that baskets could be used for sand transportation.

**Comment by jasonrohrer** [comment]
How could it not require a funnel?  Obviously, you can't put sand into a bottle without a funnel.  You really can't put anything into a bottle without a funnel...

Also, have you ever tried to carry sand in a basket?
