### ISSUE TITLE
[Unreleased content] Bottles could be small items instead of large.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#572]
Bottles might make more sense as a small item rather than a large one. Bottles are generally small enough that you can fit them in backpacks, paper bags, or baskets in real life. Most 1L bottles fit into my real life jacket pockets as well and I don't think I have abnormally large pockets.

It would also be really helpful for organization. We could have kitchen shelves filled with several bottles of sugar, salt, and the like.

Inspired by this forum post - https://onehouronelife.com/forums/viewtopic.php?id=8888

**Comment by jasonrohrer** [comment]
Well, the bottles as they appear in the game are pretty big looking.

They actually look okay with 3 in a basket.

But they look pretty terrible with 4 in a backpack.
