### ISSUE TITLE
Can’t seal empty glass bottle

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#574]
Sand retrieval will still be problematic with bottles. Not being able to seal empty bottles with rubber stopper means that you need extra separate storage space for the stoppers. 

Also being able to seal empty bottles would help us keep track of rubber stoppers in general, as on the ground they can be hard to see and locate.

Long story short, you should be able to seal empty bottles with rubber stoppers.

**Comment by jasonrohrer** [comment]
Yes, that's a good point.
