### ISSUE TITLE
Misplaced rabbit hole

### ISSUE THREAD

**Issue by KilianOHOL** [jasonrohrer/OneLifeData7#575]
Shovel + rabbit hole -> funny allocations
![20200110021003_1](https://user-images.githubusercontent.com/48244226/72117552-744eac00-334e-11ea-9e4e-c44092f1b628.jpg)

**Comment by Cogito** [comment]
Should be fixed now according to #559

**Comment by DougLefelhocz** [comment]
Since Jason is a person should we have human bone needles and human leather, which could allow for stitching bellows from remains of naturally deceased humans instead of acting like barbarians forcing cruelty onto rabbits?
