### ISSUE TITLE
Survival Challenges Too Similar

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#577]
The pip drain rate is too similar in too many places due to non-speciality biomes having the same exact temperature.   Also, the food server bonus does not change from life to life leading to predictability with respect to how much food one needs in non-speciality biomes, once one understands how clothing works.

**Comment by Tarr-OHOL** [comment]
Put meme suggestions on the forums and not the github where stuff is actually getting fixed.
