### ISSUE TITLE
Sliced Pumpkin Pie + Wall Shelfs

### ISSUE THREAD

**Issue by Davidj361** [jasonrohrer/OneLifeData7#578]
Sliced Pumpkin Pie can't go on Wall Shelfs

**Comment by sigmen4020** [comment]
Pumpkin pies can’t currently be stored anywhere. Jason says this intentional because pumpkin pies are too mushy:
https://github.com/jasonrohrer/OneLifeData7/commit/6648f50344829af98feaaa9831c69440f90fad0c

**Comment by Davidj361** [comment]
> 
> 
> Pumpkin pies can’t currently be stored anywhere. Jason says this is intentional because pumpkin pies are too mushy:
> [6648f50](https://github.com/jasonrohrer/OneLifeData7/commit/6648f50344829af98feaaa9831c69440f90fad0c)

That's not intuitive to a user being a bug or on purpose design.

**Comment by jasonrohrer** [comment]
A pumpkin pie has no top.... it is a custard pie.  It can't be contained in a backpack or elsewhere like the other pies.

It is meant to be a local feasting food, and not a travel food.
