### ISSUE TITLE
Items that can't go in cart

### ISSUE THREAD

**Issue by Davidj361** [jasonrohrer/OneLifeData7#579]
List of items that can't go in carts:

- Niter
- Bowl of Silver Nitrate Solution
- Bowl of fermented tomato seed pulp
- Bowl of palm oil

**Comment by sigmen4020** [comment]
Niter can go in baskets so it should also be able to go into carts.

Outside of maybe fermented tomato seed pulp the other items wouldn’t necessarily make sense to have in carts. We’re talking about bowls filled to the brim with liquids. They would realistically spill as soon as you move.

**Comment by Davidj361** [comment]
> 
> 
> Niter can go in baskets so it should also be able to go into carts.
> 
> Outside of maybe fermented tomato seed pulp the other items wouldn’t necessarily make sense to have in carts. We’re talking about bowls filled to the brim with liquids. They would realistically spill as soon as you move.

I was using a cart to cleanup and organize a town.

**Comment by DougLefelhocz** [comment]
"Outside of maybe fermented tomato seed pulp the other items wouldn’t necessarily make sense to have in carts. We’re talking about bowls filled to the brim with liquids. They would realistically spill as soon as you move.  They would realistically spill as soon as you move."

Do all bottles fit in carts?

**Comment by sigmen4020** [comment]
> "Outside of maybe fermented tomato seed pulp the other items wouldn’t necessarily make sense to have in carts. We’re talking about bowls filled to the brim with liquids. They would realistically spill as soon as you move. They would realistically spill as soon as you move."
> 
> Do all bottles fit in carts?

All bottles should fit in a cart as long as they are sealed with a rubber stopper.

**Comment by jasonrohrer** [comment]
Yeah, liquid bowls can't go in carts.  They would spill.

Poor them into bottles with stoppers to transport the liquids in carts.
