### ISSUE TITLE
Can only make hatchet when doing A+B, not B+A

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#58]
The hatchet can only be made by using a Sharp Stone on a Tied Short Shaft. I think Tied Short Shaft + Sharp Stone should work as well.

I've been watching a lot of new people play the game for the past few days and a lot of them get stuck at this part in the tutorial.

**Comment by CallMeAce95** [comment]
Not so easy to tie the rope around the rock if you're holding the stick and not the rock imo. Kappa

**Comment by jasonrohrer** [comment]
Well, there are lots of other transitions that only work one way...  it's a core aesthetic of the game (that crafting stuff is done with very specific steps).

So...  I guess I do want people to get stuck there, and be forced to get their head around that.

The hatchet is a borderline case in terms of making sense, for sure.
