### ISSUE TITLE
Two wheels with tires should be usable to make tire handcart

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#582]
Currently putting tires on wheels makes them unusable unless you make a car. Either make it possible to make a tire handcart directly using these wheels, or let us be able to remove the rubber tires from the wheels.

 https://onetech.info/2392-Two-Wheels-with-Tires

**Comment by Tarr-OHOL** [comment]
You can remove the rubber from the tires by separating the two tires into one stacks. 

https://onetech.info/2391-Wooden-Wheel-with-Tire

**Comment by sigmen4020** [comment]
Oops didn't notice that. Well then I'll be closing the issue then, since my contention was already addressed.
