### ISSUE TITLE
Lineages Can't Have Discrete Existence

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#584]

**Comment by sigmen4020** [comment]
What does this even mean? And why are you posting stuff like this on github?

**Comment by TwistedHBG** [comment]
This is not in any way an issue relevant to OneLifeData 7. It's just another one of his spam posts.

**Comment by DougLefelhocz** [comment]
It means that lineages as a discrete set of connected points gets rejected.  Somehow lineages get classified as continuous, even though lineages have family trees, which implies that they are a discrete set of connected points.

**Comment by Tarr-OHOL** [comment]
Shitposting on a shitpost thread.

Can you at least keep the spam to the forums and not where people try to find legitimate issues that need fixed?
