### ISSUE TITLE
Undyed rose hats can't be dyed

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#587]
Undyed rose hats can currently not be dyed. Place a rose on an undyed hat and it will stay undyed forever.

**Comment by Dodg-e** [comment]
maybe ornaments (feathers, roses etc) should be removable, so you can change them+ dye hats if you want

**Comment by sigmen4020** [comment]
That would be a good solution. Don’t need it for feather hats tho, since they can already be dyed.

**Comment by Tipy1802** [comment]
Interesting, feather hats can be dyed but rose hats no...

**Comment by Dodg-e** [comment]
yeah but you cant replace the feather with a rose for example

**Comment by jasonrohrer** [comment]
This has been fixed by letting you remove roses from all hats.
