### ISSUE TITLE
Clutter Griefing Dice, Clay Nozzles 

### ISSUE THREAD

**Issue by JackTreehorn** [jasonrohrer/OneLifeData7#588]
Dice should be able to be put in a trash pit. Wet dice, wet nozzels and dry clay nozzles should decay.

Many times I've found that the town has been griefed by being flooded with these items. Adding decay to these objects will not waste any clay because they don't actually use up any clay to make them.

**Comment by TwistedHBG** [comment]
+1, except I think Dry Nozzles shouldn't decay but instead be trashable same as Dice. They're used to make Stoppers and it's good to keep one around the smithing area.

**Comment by sigmen4020** [comment]
Just wanted to provide an image to showcase that this is indeed a big issue. Picture in the current bell town at the time of posting this. All this is just laying around here being useless after it's been dumped.
![image](https://user-images.githubusercontent.com/51952537/72671974-312dc080-3a53-11ea-911a-13409028c57c.png)

**Comment by JackTreehorn** [comment]
To combine my other threads about clutter I'll name a few items which should either decay or be trashable: -Eggs -Bellows and partial bellows -Wooden Shoes

**Comment by jasonrohrer** [comment]
I think the problem with these small clay items is they are infinite.

Bellows aren't infinite, nor are wooden shoes.

Eggs can be, but they can also be eaten to dispose of them.
