### ISSUE TITLE
None of the new colored wool clothing decays. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#591]
https://onetech.info/3448-Green-Wool-Booty
https://onetech.info/3447-Yellow-Wool-Booty
https://onetech.info/3446-Black-Wool-Booty

https://onetech.info/3443-Yellow-Wool-Sweater
https://onetech.info/3445-Black-Wool-Sweater
https://onetech.info/3444-Green-Wool-Sweater

https://onetech.info/3442-Yellow-Wool-Hat
https://onetech.info/3440-Green-Wool-Hat
https://onetech.info/3441-Black-Wool-Hat

**Comment by DougLefelhocz** [comment]
So what?  What's the in-game issue here?

**Comment by Tipy1802** [comment]
Tarr why ;-;

**Comment by Tipy1802** [comment]
Well it's a payoff for the investment that is dying clothes. Getting black, green or yellow dye is not easy since you need to get other races (a single race can't even make the dyes)
