### ISSUE TITLE
Didn't Get Any Children... Not Even A Bot

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#592]
I used [random.org](https://www.random.org/) to randomly select a server.  I used 0 as the minimum and 15 as the maximum.  The random number I got was 10.  I didn't check the reflector for server population before I played.  I called myself [Eve Human](http://lineage.onehouronelife.com/server.php?action=character_page&id=5810972).  But would my descendants be human also?

I spent my early life thinking I might go club a seal, if it were possible to do so, of course.  I found the remains of some camp with two kilns, bellows, and some crucibles.  I got some skewers, grew some carrots, some onions, grew corns, beans, and squash.  In a game about parenting, wouldn't there be some mouth that needs fed other than mine at some point?  But alas, once I was old I knew, there wouldn't be any children.  I made a hammer, an axe, a shovel, a chisel, a steel file, a bowsaw, and dug up the local spring.  

I didn't even see another character, let alone one that parented.

One must wonder, is there something similar that happens for players when the population decreases for a while during the late night/early morning period PST?  What about during 'children of men' mode during the update periods that happen frequently?  What would have my character's life been like if I had a child with a living person behind it?  What would have my character's life been like if I had a child that had a bot behind it?  Could humans in the future give birth to human-machine hybrid creatures?  Could I have done well enough such that a human-machine hybrid could have survived?

**Comment by jasonrohrer** [comment]
This is a strange report.

You were intentionally playing on an empty server.... and then wonder why there's no one on the server?

This will never be a game about parenting bots...

**Comment by DougLefelhocz** [comment]
"You were intentionally playing on an empty server.... and then wonder why there's no one on the server?"

No, I wasn't intentionally playing on an empty server.  I used a random number generator to select the server.  I also didn't know anything about the server population in particular before I logged on.  Nor did I know if anyone else would join the server while I was playing.

"This will never be a game about parenting bots..."

Then it won't be a game of parenting for some people, as it hasn't been a game of parenting for some people in the past.  You advertise it as a game of parenting.  You also won't get long-lasting lineages, since they die to lack of children.

**Comment by DougLefelhocz** [comment]
Also, Toxic on the discord had said that he had programmed bots and tested them on a custom server.  You don't have a rule against bots as you said before.  It's only a matter of time then until players parent bots, if that hasn't happened already.

**Comment by DougLefelhocz** [comment]
Toxic:

"Yeah I might start again
I still am developing a killing bot"

"And farming"

"Did px shadow finish his bot?"

Testo:

"you are making ohol bots now?
that pretty nice"

Toxic:

"I have been for 3 months now
Not to motivated anymore
It can eat berries and most food and move around
But it isn’t good at farming Rn"

Testo:

"but does it makes stuff?
like build roads?"

Toxic:

"I can make it craft but that’s hard cause people move shit a lot
Yes it builds roads
In a straight line"

"I’m working on my greifing bot Rn tho"

"It eats and hides food + tools"

All on 12/24/2019

**Comment by DougLefelhocz** [comment]
0 was designated for for bigserver2.  1 through 15 were for the rest of the servers.
