### ISSUE TITLE
Sulphur Bottle misnamed as Sand Bottle

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#596]
Item 3715 is called Sealed Sand Bottle, when it is in fact a Sealed Sulhpur Bottle

**Comment by DougLefelhocz** [comment]
Lava informed me of this on this discord... https://github.com/jasonrohrer/OneLife/issues/500  Confirmation of bugs is good Twisted.

**Comment by KilianOHOL** [comment]
Saw that just now as well:
![20200118175733_1](https://user-images.githubusercontent.com/48244226/72667516-cf526400-3a1c-11ea-94b1-f11d7b274167.jpg)
![20200118175737_1](https://user-images.githubusercontent.com/48244226/72667517-cfeafa80-3a1c-11ea-81d0-db442d867a1d.jpg)

**Comment by TwistedHBG** [comment]
Fixed with https://github.com/jasonrohrer/OneLifeData7/commit/af8f1af20a6aaa9bb734b73743efc9b2eb8a97a4
