### ISSUE TITLE
No Children

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#597]
I used [random.org](url) with 0 as the minimum and 15 as the maximum.  0 corresponds to bs2, and 1-15 correspond to servers 1 through 15 respectively.  My roll was 15.  And thus I knew the server number to put in.

So, I hoped onto server15.  And not having checked the reflector I had no idea if it was empty or if I would see anyone.  I tried to name myself 'Eve Robot' but couldn't do so.  I became Eve [Robotham](url).  I digress, but Whatever said this on this discord recently:

"imagine if someone were to make a bot to farm meme score"

I was an Eve.  Could my character club a seal for quick warm clothing or access biomes which can be restricted to players on the basis of their race (or family if only 4 families exist on a server with more than 15 players)?  I hadn't checked the reflector, and new players aren't aware of it, are they?  It turned out that my character could club a seal and did so.  

I made a basket, the three primary tools and started to look for a spot.  I didn't find anything to my liking, and eventually happened upon a camp without anyone else there.

I grew some berries, some corn, some beans, some squash, some onions, and started on the process of growing tomatoes.  I had no children.  I didn't see anyone else parenting either in my entire life either.  Not even a bot.

**Comment by TwistedHBG** [comment]
This github is for issues, not for your spam nonsense. I guess since you have a temporary ban on the forums you've decided to spam here now?

You didn't have children because you were the only person on the server.

**Comment by DougLefelhocz** [comment]
This is supposed to be a game about parenting.  Does it not hold that if you don't get a child and not see any parenting, that there exists an issue in a game about parenting?  How can lack of children combined with not seeing any parenting be suitable in a game about parenting?

I don't see any reason why being the only person on a public server should prevent children from getting born.  Especially since children can be bots.

Also, was I the only person on the server when I was 40 and older?

**Comment by TwistedHBG** [comment]
1. This is the section for Data issues. Stuff like broken sprites, sounds, missing transitions, inconsistencies. Your posts are completely unrelated to any of those.

2. You wilfully modified the base game experience by forcing the game to spawn you on a server that it would never put you on naturally. This is equivalent to you modifying the cows to be lizards and then complaining that there are no cows in your game.

**Comment by DougLefelhocz** [comment]
"You wilfully modified the base game experience by forcing the game to spawn you on a server that it would never put you on naturally. "

No, I didn't force such.  I used a random number generator to select the server number.  0 was for bs2, 1-15 where for servers 1 through 15.  The base game has a settings tab where a custom server can get selected, and all servers are custom servers via that tab.

**Comment by Dodg-e** [comment]
Can someone get banned from posting on github?, maybe that's something to look into

**Comment by DougLefelhocz** [comment]
The above reported an in-game issue.

**Comment by DougLefelhocz** [comment]
Also, I don't think that Twisted, Dodg-e, or Tarr for that matter have used a random number generator to choose a server for them before.

**Comment by Tarr-OHOL** [comment]
If your location is right I'm going to drive up state and have my dog shit on your lawn for shitposting on github Doug.

**Comment by DougLefelhocz** [comment]
Why so much anger and hate when an in-game issue gets reported?

**Comment by sigmen4020** [comment]
This is comparable to complaining that you don't get kids on a private server. You are deliberately going out of your way to join a barren server, and then complain when it's barren. This is not an issue that should be on github.

**Comment by DougLefelhocz** [comment]
No custom servers are not private, they are public.  Again, I didn't check the reflector beforehand, nor during when I played, and used a random number generator to select the server number for me.
