### ISSUE TITLE
Loom Tool Slot

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#599]
When using a rope to move a loom, it counts as learning the loom. Surely just moving the loom shouldn't force you to learn it?

**Comment by TwistedHBG** [comment]
+1

Also, Loom with Warp and Loom with Cloth are not tools. A simple (but still kind of wonky) fix might be to move the tool status to the Loom with Warp. That way using the Loom to create Cloth will still use a tool slot, but moving it won't.
