### ISSUE TITLE
"@ Mallets" should be "@ Mallet"

### ISSUE THREAD

**Issue by UncleGus** [jasonrohrer/OneLifeData7#6]
To be consistent with other names, and since each transition that references it involves only one actual mallet.

**Comment by jasonrohrer** [comment]
Thanks!

Fixed here:

https://github.com/jasonrohrer/OneLifeData7/commit/e76c5379b4dcde19e1651197de14cfc14a4e6aee

**Comment by KKSzymanowski** [comment]
Tip: You can add `Fix #6` to the commit message to automatically close the issue.
It'll look like this: 
![image](https://user-images.githubusercontent.com/13980973/39213832-e15b740a-4812-11e8-9f7a-cc52899bd93b.png)

Here is the documentation on this feature: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by jasonrohrer** [comment]
Great to know!
