### ISSUE TITLE
Biome Restrictions Exist on Server1 With More Than 14 People on It

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#602]
I logged onto server1 deliberately with it having more people on it.  I was [Maya Hughes](http://lineage.onehouronelife.com/server.php?action=character_page&id=5829433).  I ended up meeting the person behind my mother again when she was [Kit Pie](http://lineage.onehouronelife.com/server.php?action=character_page&id=5829399&rel_id=5829425) (she told me she was my mom), but I digress.

I ended up using a shovel to fling some dung onto compost piles, and fired some clay items.  I checked the server count at the time, and there existed more then 15 people playing on server1.  But, as a brunette I couldn't walk in a desert without experiencing the dropsy early in my life.  Later on, I did check the reflector while playing and saw that the server had less than 15 people on it and took advantage of that situation.

But, returning casual players and new players may not or probably do not have any such meta-knowledge of the game also.  For consistency's sake, I would think that just removing biome restrictions on server1 would be preferable.

**Comment by jasonrohrer** [comment]
This is normal.  These restrictions kick into motion on any server that has 15 or more people on it.
