### ISSUE TITLE
Animals passing through closed doors

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#607]
In multiple lives I've seen animals treat doors as if they're not even there and simply pass through them into buildings. It doesn't make sense for animals to go into buildings at all, so shouldn't they treat doors like walls?

Animals I've noticed doing it so far include cows and horses, but I assume it isn't limited to these.

**Comment by sigmen4020** [comment]
I'm pretty sure this is only an issue with specifically spring doors. It might be that you can technically pass through a spring door even if it isn't in an opened state. And since animals don't count as humans, but more like objects, they can pass through without the door opening.

**Comment by jasonrohrer** [comment]
This has been fixed!
