### ISSUE TITLE
Bellows Clutter

### ISSUE THREAD

**Issue by JackTreehorn** [jasonrohrer/OneLifeData7#609]

**Comment by JackTreehorn** [comment]
Griefers are now creating bellows on mass to clutter towns. Partial bellows and full bellows should have recipes to dismantle them into kindling, Pouches may also an issue.

**Comment by Tipy1802** [comment]
I have never seen anything like this

**Comment by sigmen4020** [comment]
I have a suspicion that it's only ever happened this one time:

![image](https://user-images.githubusercontent.com/51952537/73519609-d5274c80-4401-11ea-957a-e6d449773262.png)
