### ISSUE TITLE
Bow Drill Bow, Fire Bow Drill, Rabbit Snare, and Stone Hatchet Don't Deconstruct

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#619]
I had my low pop town griefed.  One of the things the griefer did was to make a bunch of rabbit snares and bow drill bows (before players have a fire bow drill, they have a bow drill bow) from my milkweed farm.  There's little to no use for multiple fire bow drills.  More than one can have it's purposes, but a dozen of them in any context is pointless.

Rabbit snares could theoretically get overdone, and perhaps there's even an argument that stone hatchets can get overdone... or they can get timed poorly when there exists a better immediate use of the rope used to make it.

It would be nice if all three could get deconstructed, or at least the bow drill dow and the fire bow drill.

**Comment by Dodg-e** [comment]
but then griefers deconstruct snares and bow drills to make bows...

And if bows are deconstructible then they make boxes with all the ropes, then carts that decay...

So you dont have anymore snares or bow drills.

Better to have too many snares when you need them then none at all
