### ISSUE TITLE
Boilers, Crude Cylinders, Crude Pistons, and Possibly Even Tanks

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#625]
One of the things that the low pop griefer did was to make around 10 or so boilers.  Watching Twisted's stream I also saw this.

There's no way to recycle any of the wrought iron parts, and it's honestly not many of each wrought iron part that a settlement can use.

**Comment by Tarr-OHOL** [comment]
This is a repost.

https://github.com/jasonrohrer/OneLifeData7/issues/350
