### ISSUE TITLE
Clipping and failure to walk where told

### ISSUE THREAD

**Issue by aalyasenai** [jasonrohrer/OneLifeData7#627]
This is going to be a little bit complicated to explain, so bear with me.
Walking has become extremely difficult. Something is causing the avatars to repeatedly walk in various directions without being controlled. So if you start walking east, your avatar will suddenly pivot, turn around, and run back west for a while, then turn back east and go to where you originally told it to go. And sometimes it will go a very long way before it will finally stop moving. I have plowed face-first into more bears, boars, wolves, and mosquitos in the last couple of days than I can count. It has made the game almost unplayable. There is also a problem with your avatar skipping/clipping from one location to another. It usually happens right after a freeze or a lengthy lag of immobility. All of this is especially disorienting while riding a horse.

**Comment by TwistedHBG** [comment]
IIRC this has been fixed now
