### ISSUE TITLE
Balancing issues since the rift (berries, water, compost, iron)

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#634]
The other day I played in an old town. The town had no iron, no engine well, no soil, some water in buckets, no horses, had some food left, so there was no challenge but no future either.

There were too many bushes, I picked off the ones that were on random positions and 7 other in a group which was planted in the positions were carrots were.

I kept telling people not to fix it, every single toddler ran trough there and dumped soil on one of them. Since it's in a group, they notice those faster than the others in the middle of central bushes.
Hard to change habits, people plant 3x3 and mindlessly plant bushes everywhere, if it's a brown bush, they don't think about removing it, they put soil on it, generally no water. That means that if you want to remove bushes, you can't do it when others are in the city, impossible to tell everyone, and even if you notice others and tell them, the damage is done.

Since a town won't need more than 20 bushes, even veterans with highest APM won't be able to pick all down, soil and water, so it's on a maximum reload speed (ideally every bush grows berries, it's picked off so the timer is reset). So there is no reason planting more of them, it's a waste of soil, water and hoe usage. The only advantage of berries is that they don't require tool use after the initial investment. But it seems that people mistake it with the wild bushes, or from the old videos, they got the idea that bushes will regrow so more is better.

Water mechanics changed. We had too much, and that's why removing bushes wasn't an issue, but ever since the nerfs to reload, distance and upgrades, makes no sense to use water to remove bushes to save water. The engine isn't best but understandable: save up some water to use the Newcomen tools, then you get a lot of water. But spending water to remove bushes is like wasting food. Probably it would still be better to remove some, long term it would be less water usage on bad foodtype. But there is no guarantee that people won't plant it back, seeing that there is an empty spot.
And that's the most annoying thing, sometimes I spend 20-30 minutes cause a toddler dumps soil on it, when it's obvious that it's a road above and below it, so it needs to be removed. The time I wait to go brown, then someone dumps soil, I got to water it, wait, pick off, then remove.

 Possible solutions: change the water to something else. Hard to spend water on badly placed bushes. Shouldn't be simple to remove them so people don't grief it, but any other liquid would be better than clean water. 
Maybe soft nerf berries that they die out after a few uses, similar to Newcomen wells. That would require an item which gradually breaks I guess, like a skewer near bush.
Around 6-8 times would be enough, that would mean that planted bushes get used quite a few times, then they leave a hardened row behind. Would create a bit more work, and people could just pick off bad bushes to remove them.

Other solution might be limiting seeds. Not sure how could that be done, maybe changing the seed model for berries, each bush would give a seed when picked down completely when there is more than 20 in a distance of 30x30 then limit the number of seeds it's giving. I could still be brought from elsewhere, I guess, but maybe would slow down bush planting.

Berry is a staple of cities, and newbies won't survive without it, but it's annoying when old towns are covered in bushes, veterans try to dig ou and others plant it back over and over, after like 30 hours every town has 60 bushes and people wast all the water on them. A few people go out and scrape together a few buckets of water from ponds, and newbies use tat on bushes instead of smith work or pies, stew, things that would yield more pips per water.
And this is so annoying that a lot of people just suicide in towns seeing all the bushes.  Veterans like to optimize cities, and that would require making bush digging less wasteful. If the town looks bad, less veteran babies choose to stay, so even if I try to fix it, I can't cause digging them out is a lot of waste.
Also, people make a lot of drama about it, first, they put soil on the wrong bushes, then get butthurt because you mention it, I even saw people who wanted to kill me for it or kept dumping soil on bushes when I was away for a second. 

The other issue is compost. Calculated that tilling twice one soil, instead of one time two soil actually wasting water. This was when it was still possible to till two, now we can't, but the measurements are still the same. The soil became more expensive compared to water and iron, to a point where saving water became the most important. This also means that making compost is less valuable. This was an activity for veterans to ensure the longevity of the lineage. We were really surprised by the result of double tilling since that was a behaviour only lazy people did before. Since making soil with compost was easy, and tools were important, was really bad to just waste the hoe, but with the cost of iron vs cost of water per kerosene, soil cost is higher if people single tilled. Since compost received nerfs before the water changes, a buff would be in time now.

Making a lot of compost uses more water, and the water needs to use up all that soil is also a lot, so overproducing compost is a bad activity now. 

Tools and iron: since the tool slots, people more often just scavenge the iron from old towns, than to make a mine, I saw so many big towns with an iron when within 40-60 tiles untouched, makes no sense that the town has bell but the veins still untouched near it.

Other than wasting the iron, on bad parts of Newcomen, we got a lot of iron. Not necessarily nerfs, but some sort of iron sink would be needed. Metal bowls and plates? cages or barrels?

The other thing which is weird ever since the rift: we had no choice but use kerosene to mien the iron. But now it's kinda unbalanced that a charge of kerosene can get either a few buckets of water or a tiny amount of iron since we can get iron by travelling a bit further, makes no sense to use the engine to mine for iron, cause it's a waste of kerosene. And that's bad cause it should be a better conversion price for iron to the water. The iron mining engines should be slightly buffed.

**Comment by jasonrohrer** [comment]
This space is for very specific bug reports.
