### ISSUE TITLE
Posse system affects tattoos, I couldn't give people tats unless we were alone.

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#635]
Exactly what the title says. It was REALLY annoying having to walk so far away just to tattoo. Please fix this soon.

**Comment by Tarr-OHOL** [comment]
Can't have a snowball fight either because of the kill change either. It's a sad day when you need three people with snowballs to chuck one.

**Comment by jasonrohrer** [comment]
Fixed
