### ISSUE TITLE
Food pips from eating severely reduced, yum bonus also broken

### ISSUE THREAD

**Issue by csaada** [jasonrohrer/OneLifeData7#639]
Everyone in game right now seems to be having this issue. Eating seems to only give between one and five pips, still scaling with food quality. The yum bonus value is also significantly lower than it should be. I think I got +6 at most after eating pie as an adult with a multiplier of x10 or more.

**Comment by MonsWTF** [comment]
I can say that this wasn't a bug, but a live test on the main server where food values were temporarily reduced. It was restored about one/a few hours later.
