### ISSUE TITLE
Green paint

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLifeData7#641]
Now the final missing color of paint.

**Comment by DiscardedSlinky** [comment]
After you get this done we need the rest of the rainbow, orange and purple (and pink pls)

**Comment by jasonrohrer** [comment]
Well, one step at a time.

The other colors are less-trivial because:

1.  I don't have those hues defined (and I don't want to "eyeball" them... I usually scan actual marker colors to get a color sample, to avoid hue clashes).

2.  Paint mixing is on thing (red + yellow = orange) but dye mixing is a totally different thing.  I'm not sure about the chemistry, etc of actually making orange dye.  And then there's the whole purple snail thing (I'd really want to get that right).  You can read about the chemistry of getting orange and pink from Madder root here:  https://www.jennydean.co.uk/notes-on-madder-dyeing/

**Comment by jasonrohrer** [comment]
Also, note that green dye IS made by mixing other dyes, as pure green dye is rare in nature:

https://en.wikipedia.org/wiki/Natural_dye#Greens
