### ISSUE TITLE
Bowl of vermillon pigment plus bucket of paint makes bucket of blue paint

### ISSUE THREAD

**Issue by MrsDuckGirl** [jasonrohrer/OneLifeData7#642]
Bowl of vermillon pigment plus bucket of paint makes bucket of blue paint instead of bucket of red paint.

**Comment by MrsDuckGirl** [comment]
Same in adding yellow pigment, it makes blue paint.

**Comment by sigmen4020** [comment]
Here’s proof to support this issue:
https://onetech.info/1906-Bucket-of-Yellow-Paint
https://onetech.info/1905-Bucket-of-Red-Paint

Both are uncraftable at the time of writing this.

**Comment by jasonrohrer** [comment]
Whoops!
