### ISSUE TITLE
Dung Buckets don't have a visually distinct 'Full' form

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#644]
Full buckets of Water, Salt Water, Milk, and Skim Milk have a visually distinct 'Full' stage which is its own separate item. The Dung Bucket doesn't have that, and it is not possible to tell whether the bucket is full or not.

Having a separate Full Dung Bucket would also make it possible to have a higher tier of dung storage such as a Manure Box in the future, similar to how Full Water Buckets and Cisterns work.

**Comment by jasonrohrer** [comment]
DUNG CISTERN!
