### ISSUE TITLE
Dung 

### ISSUE THREAD

**Issue by Tipy1802** [jasonrohrer/OneLifeData7#645]
As of 2.3.2020 (as in 3 is the month not the day) Dung boxes got added in unreleased. I apploud you Jason for what this has solved the second shittiest problem in OHOL: dung storage. 

But what about THE shitiest problem in OHOL? Transportation of dung. Sure we can transport dung buckets but that's not enough to satisfy our bodily needs. We need Dung carts to transport dung out of town, dung horse carts to take our beloved dung on our travels and dung track carts to trade dung between towns

We should be able to power newcomen with dung too or maybe use it as a replacement for oil

Also humans should poop too. Just imagine the social challanges! After you eat you poop after a few seconds. People will have to set up a place to store all the poop. If left untouched the poop could consume the whole town so a social problem arises: who will clean up the poop? Convincing someone to clean up the poop will be a great social challenge with lots of social interactions! 

Why do sheep poop human poop? Have you seen how tiny actual sheep poop is?

Also why do only sheep poop? It would be fun to see towns choose pig or cow pens instead. It would be nice for variety

**Comment by jasonrohrer** [comment]
Dung buckets allow hand carts and track carts to carry 40 dung each.... that's quite a lot!
