### ISSUE TITLE
Green paint issue

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#647]
The Onetech recipe currently shows ways of making green paint that doesn’t make sense. You can add yellow pigment to yellow, and red paint to get green paint, if green paint is released as is.

![44EAADD4-B4C8-4EDC-89D8-BABEAD4B2FAE](https://user-images.githubusercontent.com/51952537/75771324-0e791200-5d4a-11ea-8e2c-3fc445e80d94.jpeg)

**Comment by jasonrohrer** [comment]
Dammit!

I just can't shake these pattern glitches with the green paint.

I'll have to have it so that you mix the green pigment first, and THEN make green paint from it.
