### ISSUE TITLE
Glasswort cutting doesn't decay

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#649]
Glasswort Cutting (ID 3702) doesn't decay. All other Cutting items decay after 10 minutes.

Also, using Shears to get Glasswort Cutting doesn't consume a tool slot. I imagine it is the same for other Cuttings but I have not tested it.

**Comment by TwistedHBG** [comment]
Also, using Shears with Glasswort Cutting (ID 3701) to plant the cutting into soil directly without dropping it on the floor first would be a nice QoL change if it is simple to implement.

**Comment by sigmen4020** [comment]
That would be a nice QoL change for every type of cutting.

**Comment by jasonrohrer** [comment]
The tool slot part has been fixed already.
