### ISSUE TITLE
Other food items that should also have the +contFoodDish tag

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#651]
**Tortilla chips
Mango slices**
Glass of wine
Baked bread (not sliced)
Raw bread loaf
Raw pumpkin
Cooked pumpkin pie (not sliced)

I didn't add some of the other foods like sliced pumpkin pie, bread and turkey, since I'm presuming here that they weren't given the tag, because it might cause conflicts with the feast table.

Anyway I've marked the ones I deem most important to have the tag as bold.

**Comment by jasonrohrer** [comment]
Yes, you're right about the feast table.  Sliced pumpkin pie starts that process.
