### ISSUE TITLE
Signs with letters take lifetimes to make

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#652]
The letter system is nice, interesting to make etc.

But to make the letters to write something as simple as "BAKERY" or "TAILOR SHOP" takes a whole life (or even several), with signs you know right away what is what dont need to pick up a note but currently it's underused due to this issue.

The problem is not making the letters themselves, the issue is needing xx ammount of skewers and the whole process of getting them.

Could one skewer/weak skewer give a pile of letter stocks?

**Comment by TwistedHBG** [comment]
+1 to getting multiple letter stocks from a single skewer.

This issue is similar/related to issues #474 and #391 and they could be tackled at the same time.

**Comment by jasonrohrer** [comment]
Yeah, I might make it slightly cheaper...

I really don't want signs all over the place, though.  If you see a sign, it should be something special that someone really worked to create.  The game is not supposed to be a bathroom wall where anyone can write anything.

If you think about this carefully, you'll realize that the cost of a sign must be balanced against its impact.  And the impact of even a single sign is potentially infinite.  It might be there forever, and be seen by an unbounded number of people in the future.

So, that's a lot of power to hand to one person, the maker of the sign.

Drop G is a funny issue.... some quirk of sprite placement that is actually non-trivial to fix.  It's been bugging me for a long time, though.
