### ISSUE TITLE
cant fill empty tank/tank of water with full bucket of water.

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#655]
cant fill empty tank/tank of water with full bucket of water.

**Comment by Spodnie** [comment]
Would be nice if we could do it.
Maybe tank with glass funnel could allow for doing it?

**Comment by Dodg-e** [comment]
On second thought this might enable the transport of huge ammounts of water from far away instead of needing to find local solutions with the players (families) around, so not sure about this one.

**Comment by jasonrohrer** [comment]
This was intentional because the neck of the tank was too small to allow filling.  The glass funnel is a bit tiny.

But also, yeah, for reasons of limiting long-distance water transport.  Otherwise, the cart could hold 24 buckets of water.
