### ISSUE TITLE
Laying a "proposed property fence" above or below a "property fence" makes a snow door

### ISSUE THREAD

**Issue by ninjanick95** [jasonrohrer/OneLifeData7#656]
See pic (sorry for phone quality, print screen doesn't work in fullscreen).

https://i.imgur.com/PZpfdT0.jpg

Imgur link since github was putting it upside-down

**Comment by ninjanick95** [comment]
https://cdn.discordapp.com/attachments/328215300279500800/685557571838541834/20200306_134055.jpg

**Comment by jasonrohrer** [comment]
This has been fixed.  Will go live this week.
