### ISSUE TITLE
Animals escaping through springy doors

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#659]
If I remember correctly, they shouldn't be able to do this.
We had sheep/cow pen connected with kitchen, in the game, and both, sheep and cows, were escaping through springy doors, while they were open when someone was going through.

**Comment by jasonrohrer** [comment]
No, something else was fixed.  Animals used to be able to walk through the CLOSED springy doors.

If the door is open, the animal can get out.  That is working correctly.
