### ISSUE TITLE
Squash seeds that you get from wild squash aren't containable

### ISSUE THREAD

**Issue by ninjanick95** [jasonrohrer/OneLifeData7#666]
Can't go in baskets, backpacks, etc. No other seed has this behavior AFAIK

**Comment by jasonrohrer** [comment]
This is consistent for the other "cluster" seeds, including onion and pumpkin.

Single seeds are containable, however.

It just seems like the cluster would fall apart or get lost in the container.  They CAN go in a seed bowl, however.

For the wild squash, you could put the wild fruit itself in your backpack to bring it home.
