### ISSUE TITLE
Expert way stone marker dissapears before you reach your destination

### ISSUE THREAD

**Issue by Tipy1802** [jasonrohrer/OneLifeData7#672]
What it says 
Same with normal way stones but with them you can make maps at least 
Maybe It goes to the side of home markers and bell markers?
Or maybe it overwrites the home marker till you get a new home marker?
But right now you will not reach your goal (unless black and have horse and the town is near) before the marker dissapears

**Comment by TwistedHBG** [comment]
I think it's fine as the waystone gives you the general direction and the distance. If you go in that direction you're bound to find more expert way stones to refresh your marker as they're fairly common.

**Comment by jasonrohrer** [comment]
Yeah, I'm going to leave the behavior of these a bit "soft" for now, as they already offer a huge leg up over the old system for finding people (no system at all).

They actually point you to a person's exact position, but if the person is out of range, you don't receive updates about their movements anyway, so you might end up walking to where they used to be.

Thus, these expert arrows are more of a "hint" than a bee-line to a destination.
