### ISSUE TITLE
Tutorial Eves suffer from hungry work and can't cut the tree down at the end unless full

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#673]
If they take a long time to do their work they probably won't be able to do it at all with the small amount of yum variety. This could be really confusing for players that are doing everything right but still can't cut it down. 

Maybe make the tree a pine tree?

**Comment by Tarr-OHOL** [comment]
Hilarious. The fact you can master the challenge but fail because of the hungry work at the end. Yeah, just make the tree pine to fix this.

**Comment by DiscardedSlinky** [comment]
That was so not a solution to this issue
