### ISSUE TITLE
Suggestion to get rid of dry bean clutter

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#679]
How about it becomes the same mechanic as collecting green beans? Use a bowl on it and collect them all instead of having to pick them one by one. I myself have accidently clicked the bean plant and have contributed to the clutter. For replanting you could use the bowl of dry beans, or leave one behind in the dirt. I dunno I'm just sick of dry beans everywhere

**Comment by jasonrohrer** [comment]
The green beans is a weird case with no precedent.  See thread here:

http://onehouronelife.com/forums/viewtopic.php?id=9266

Dry beans can be gathered into a bowl, right?
