### ISSUE TITLE
Bananas are too plentiful, making survival in jungles very easy.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#68]
Currently Banana trees are very common within jungles. Each banana tree gives seven bananas, and each banana gives 9 (7+2) food, for a total of 63 food per tree. They regenerate every thirty minutes once fully picked.

Since jungles are very warm, your food decays at a slower rate. You can easily get perfect temp with two or three items of clothing, which means you'll lose one pip every ~20 seconds while in the jungle. If you have perfect temp you will lose three pips per minute, or 90 pips every 30 minutes. That means that three banana trees are enough to sustain two people without any additional effort.

If those same people lose one pip every ~10 seconds for some reason, they need six banana trees to be completely sustainable.

Banana trees are extremely common at the moment, and you'll often see four or five banana trees on your screen at the same time. An average jungle can probably sustain about a dozen people without any additional effort.

Mosquitos and Yellow Fever are supposed to be the balancing factor, but due to: A) the fact that Mosquitos can't be on a tile occupied by another item, and B) the fact that Yellow Fever lasts only 25 seconds and that it's easily survivable as long as your food wasn't too low when you were stung, they don't really pose any danger to an experienced player. You can simply cover the entire jungle in bananas, and you'll be safe.

I am almost always against nerfs, but I think banana trees are too overpowered. My ideas on how to make them more balanced:

- Drasticaly increase the respawn timer of bananas.
  - If banana bunches only respawned every three hours, they would still be an amazing food for a starting village, but they wouldn't be make survival trivial for the following generations.
  - Slightly unrelated, but the same logic could be applied to Mango Trees - it does feel a bit weird that Wild Mango Trees don't ever bear any fruit. If they spawned a new batch of Mangoes every three to four hours they could be a nice satisfying bonus resource. 

- Decrease the frequency of banana trees.
  - Right now, they are everywhere, and finding Banana Trees doesn't feel as exciting as, for example, finding a cluster of Cacti.
  - If they were 1/4th as common finding them would feel great.

- Decrease the amout of food you get per banana.
  - If the food you get from a single banana was decreased by 1 or 2, that would make each banana tree give seven to fourteen less food. A slight nerf, but it would make them more fair.

- Make Mosquitoes more common.
  - Right now it feels like Banana Trees outnumber the Mosquito Swarms ten to one.

- Make Mosquiotes much more common, but use the probabilty system when getting stung to determine whether you get sick.
  - In the last update we got a cool new probability system, it should be utilized more often and getting sick seems like a natural fit.
  - I think giving Mosquitoes a chance to get you sick and a chance to do nothing would be more exciting than the 100% chance we currently have.
  - Sometimes you might get lucky and it'll make for a great moment. Sometimes you might get stung at a bad time and it'll make for a cool story. Imagine a situation where both you and your mother get stung, you're fine but your mother got infected and she died! Now that's drama!

- Add more obstacles to the Jungle that make it harder to navigate.
  - I love that we can't chop down the trees, which makes jungles a hard biome to settle.
  - More obstacles would make it harder to navigate and explore - the Jungle should be dangerous and hard to navigate.
  - Big Mossy Boulders that you can't move or break, and have to walk around.
  - Mossy Fallen Tree Trunks that you have to walk around, but that you can chop down for firewood once you have an Axe.
  - Thick Trees with Lianas/Vines. You can't remove them and you have to go around them, but if you have a knife you can get a rope from them.

- Reduce the amount of bananas you get from a Banana Tree.
  - I don't personally think this is a great solution, bananas feel like a food that you should get a bunch of in one batch and seven seems like a good sweet spot.

This ended up being a bit longer than I intended, my apologies! It was supposed to be just a short snippet indicating that Bananas are too strong, but it became this suggestion monstrosity which wasn't my original intention.

**Comment by Dodg-e** [comment]
Imo nerfing bananas is not a good idea, bananas and the almost perfect temp is what makes the jungle 
 interesting as a biome, but the main problem is it's supposed to be a high risk place to go but current mechanic makes it easy to avoid these dangers

1. Yellow fever more deadly
2. Getting rid of the standing on object trick to avoid mosquitoes and other wildlife
3. Not changing anything about bananas and banana trees

That would make the jungle extremly dangerous but at the same time full of ressources (food), which would make it a high risk high reward place to go, much more interesting than nerfing it to the ground

**Comment by jasonrohrer** [comment]
The standing-on-object trick is, sadly, really hard to fix.

Bananas don't regrow in real life, so they don't regrow in the game either now.  This may be a temporary fix.
