### ISSUE TITLE
Github issues you could close

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#683]
Hi Jason, I was looking through the github issues and found a few that you seem to have already fixed and could be closed to lower the total number a bit.

Here's a list of them:
https://github.com/jasonrohrer/OneLifeData7/issues/444 - You already changed it so it's done by Adze instead of knives now.
https://github.com/jasonrohrer/OneLifeData7/issues/347 - You've done this in the last update.
https://github.com/jasonrohrer/OneLifeData7/issues/317 - I don't think this has been an issue for a while?
https://github.com/jasonrohrer/OneLifeData7/issues/288 - Also recently fixed.
https://github.com/jasonrohrer/OneLifeData7/issues/273 - This was fixed within the last few updates I believe.
https://github.com/jasonrohrer/OneLifeData7/issues/229 - The main issue of this one was resolved but the secondary wasn't, but it's also mentioned elsewhere so i'm not too sure about it.

If you also think these are all resolved you can lower the issues even further.

**Comment by jasonrohrer** [comment]
Thank you!

I was able to close all of these.
