### ISSUE TITLE
Abused objects

### ISSUE THREAD

**Issue by MaDc0wUSP** [jasonrohrer/OneLifeData7#685]
After a few days I came to my low pop town looking like this:
![screen00135](https://user-images.githubusercontent.com/4856680/77325548-cf225d80-6d18-11ea-9603-8e331d6fbd19.png)

It's quite infuriating that there is no way to recover items blocked by ancient walls, many hours of wasted time.
Also all iron was made into non-recyclable boilers and crude pistons.

Pretty easy to see from the logs it was player cd255e1511f1b409b9da1fcff89e2a19098c925d

**Comment by jasonrohrer** [comment]
Unfortunately, the game isn't designed or balanced around long-term solo play.

The servers are not private.  If your stuff wasn't walled in, it could have been stolen or hidden, right?  There really is no way to stop someone from "ruining" the stuff that you build, when you're not there.

The only fool-proof option is to play on a private (or semi-private) server, where you can block untrusted folks from playing there.

The other option is to hide your solo town really well.  But perfect hiding is, of course, impossible.
