### ISSUE TITLE
Potential missing stacks

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#689]
I'm not sure whether this was just missed, or by design, but some items like unprocessed electrum, niter, and alum should perhaps be able to stack? Maybe some other minerals like cinnabar and lapis lazuli should be able to as well. Also some crops that maybe should be able to stack like mangoes, bananas, burdocks, the wild variants of certain foods, pumpkins, squash and cabbage?

**Comment by DougLefelhocz** [comment]
A lot of niter is needed if making both radios and a bell or crows.  If dying gets done at different times also, a fair amount of alum is needed.  Painting walls a lot certain colors requires a fair amount of cinnabar and lapis lazuli.  Wild food in bulk hardly ever seems back, and thus wild food can almost always use stacking.

**Comment by JackTreehorn** [comment]
Stackable empty crocks would be great.

**Comment by jasonrohrer** [comment]
I have a clay crock in real life, and they don't stack (their walls are vertical, just like what I drew).

**Comment by jasonrohrer** [comment]
I mean, I guess they could stack in a tower or pyramid....
