### ISSUE TITLE
Potential issue with iron change

### ISSUE THREAD

**Issue by AcorpBG** [jasonrohrer/OneLifeData7#690]
https://github.com/jasonrohrer/OneLifeData7/commit/150d1622b0175f017fe86380e94861e02833340b
This commit introduce the new change  of no more lose iron but 4 iron per mine.
This will be problematic especially for Eve camps,  as  getting to mining technology needs the following items: 
Hammer,Axe,Chisel,Adze,Froe,file,bow saw,pickaxe
This mean as Eve you need to find 3 mines just to be able to hit the first mine for more iron.
Also there is need for other essential steel tools like the  shovel for the well.
On top of the new baby mechanic, Eves will have hard enough time taking care of babies to even go and look out for 3 iron mines.
I suggest to bump the free iron from mines to 5 or 6 so the number of mines go down to 2.

**Comment by jasonrohrer** [comment]
Mines are located on ley lines, making them easy to find.  Walk a ley line until it crosses a Mountain biome.
