### ISSUE TITLE
Content inconsistency - Iron Mine

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#691]
The content on Onetech related to the iron mine is inconsistent with the commit explaining the new iron change. This is the onetech page:
https://edge.onetech.info/944-Iron-Mine-Hungry-Work-hungryWork10

This is the commits: https://github.com/jasonrohrer/OneLifeData7/commit/150d1622b0175f017fe86380e94861e02833340b https://github.com/jasonrohrer/OneLifeData7/commit/f0f1546aeda592c7838715b1aa2bdd96c4d706b6

These are the inconsistencies between the commits and Onetech page:
  -  According to the commits the iron mine should produce about 21 iron, but according to 
     Onetech you will only ever get 10 iron (5 loose iron, mine only has 5 uses) from a mine.
  -  Hungry work. Onetech says that getting iron from a mine requires hungry work, yet the commits 
      don't mention anything about this. Is this intentional?

**Comment by jasonrohrer** [comment]
Whoops!  Yeah, I had the chance of use on 1.0 for testing, and it got checked in.  Thanks for checking this.  And yeah, they are supposed to be hungry work, too.

**Comment by sigmen4020** [comment]
Is pulling out every piece of iron hungry work? Or is it just digging the mine?
