### ISSUE TITLE
Able to dump items into bad biomes.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#694]
Classic bad biome bug that can be abused to drop items into wrong biome. 

Get on top of horse or car.
Go stand in a bad biome and move to the edge with an item located next to yourself
Swap horse or car with item on a biome you can stand in. 
Proceed to walk which will trigger appropriate disease which forces drop mechanic.
Because you were in a bad biome game auto drops the object into bad biome.

**Comment by jasonrohrer** [comment]
Fixed here:

https://github.com/jasonrohrer/OneLife/commit/d641a848584f7716250a37bcfec565cb96c9493e
