### ISSUE TITLE
Weird object numbering

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLifeData7#695]
Onetech is broken - new content is still in unreleased and some details and objects are missing. So I went to look at the raw data, and saw something odd.

Object ids 7120-7122. nextObjectNumber is 3964 and the last regular object is 3960.

**Comment by jasonrohrer** [comment]
DAMMIT

I was using the editor with "generate dummy objects on" for testing, so I could see them in the editor.  I must have saved some new objects in that state, which caused "inflation" up above the dummy objects.

Of course, all the transitions, etc, reference those too-high IDs now.  Ugg.
