### ISSUE TITLE
Shallow Iron Pit is infinite

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLifeData7#697]
Saw Twisted get a lot out of a mine, so I went onto my local test server. Broke two picks and ate through two feast tables; my mod shows item uses and the pit was still at 10 uses.

Might actually be a code bug (two items with uses) but can't say at this point.

**Comment by jasonrohrer** [comment]
Fixed in f7a938151a4ee34a60d7b0fdf97266c72c9eef7a
