### ISSUE TITLE
Broken steel tools decay

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#699]
https://edge.onetech.info/862-Broken-Steel-Tool-no-wood
https://edge.onetech.info/858-Broken-Steel-Tool

I think these two shouldn't decay these days anymore.
Even tho in most cases 1 hour is enough to make Clump of Scrap Steel, I'm always worried they will decay in a moment.

Just close the issue if you disagree, it's okay.

**Comment by jasonrohrer** [comment]
Yes, this was probably a mistake.  Left over from before they could be recycled.
