### ISSUE TITLE
Can't swap newcomen mechanisms (ex. roller for lathe) after adding water/charcoal to the boiler

### ISSUE THREAD

**Issue by ninjanick95** [jasonrohrer/OneLifeData7#701]

**Comment by Dodg-e** [comment]
Placement by default should be Bucket of water -> Charcoal -> Attachment

Then the attachment would be replacable

**Comment by jasonrohrer** [comment]
The problem with that, dodge, is that the pattern is based on the pump, including the firing step.

So there's no room in that pattern for making the attachment in between charcoal and firing.

I'll have to manually put a removal and re-add step in there for each.
