### ISSUE TITLE
Curse blocking is too powerfull

### ISSUE THREAD

**Issue by Elsayal** [jasonrohrer/OneLifeData7#705]
As stated by Twisted : 
"Cursing a player currently makes them unable to spawn in a 100 tile radius around you. This radius incrases by 100 for each additional living player that has you cursed. It is also increased by T^2, where T is the total number of curses against you, both online and offline.

Babies can only spawn inside homelands, which are defined as a 100 tile radius around the families's well site. Due to the iron changes there is usually only one homeland per family, so four homelands in total on average at any given time. Eves also spawn 50 tiles away from the previous Eve, so any families that do survive are bound to live very close to one another.

If you get cursed by 3 people and all of those people are online, you cannot spawn in a 309 tile radius around any of them. If they are all in different families that means it is actually reasonable likely that the fourth town will be covered as well, preventing you from spawning there.

If someone is a serious troublemaker people will remember their curse code, and they will know to keep an eye out on them if they see them in a future life.

My proposition: leave the T^2 as is, and make the initial curse block 30 tiles, increasing by an additional 30 for every online curse. If 3 people curse you and they are all online you cannot spawn within 99 tiles of them, which makes it unlikely you will spawn in their towns and bother them (and even if you do they will see your curse code and keep an eye out on you), but still gives you the chance to play with the other family and redeem yourself. If someone is a big troublemaker and manages to get to, let's say, 20 curses, they will be blocked from spawning from most locations on the map even if there's only one person online, so there's still safety from serial griefers."

**Comment by jasonrohrer** [comment]
I'm going to simply cut the radius in half now and see how that affects things.

A curse is a promise that the person won't be born near.  30 is pretty close, and might end up with the person born again right in your same village.

50 seems safer.

**Comment by jasonrohrer** [comment]
Fixed in https://github.com/jasonrohrer/OneLife/commit/5b606a8a11acf6d358c58b30622b7a9c17e4cfad
