### ISSUE TITLE
Remove engines from wells and iron veins with two people

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#706]
Would be great if you made it that removing engines from wells and iron veins requires 2 people.
Something like, first person is touching it, then second person has 2 seconds to get it.

This would make sense, because engines are heavy... Maybe too heavy for one person to remove it from a well or iron vein.

This would solve griefing part and additionaly it would be fun to cooperate.

Additionally would be great if you also made that 2 people need to use hammer together(1 or 2 secs) to scrap engine in a scrap box. First person doing it should be stuck and be unable to drop the hammer.
This is actually a little bit magical, so I'm not sure about it, up to you.

**Comment by jasonrohrer** [comment]
You already have property fences, which can be used to protect engines or anything else for that matter.  Cars.  Your favorite rubber-tire horse cart.

I shouldn't be manually "tying things down" for you.

There are some wild resources, like trees, which you can't possibly fence in and protect, so those are hungry work to slow down mass destruction.
