### ISSUE TITLE
Possible Missing Stacks/Bottles

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#707]
In my last report I had mentioned a fair number of crops that were missing stacks, and in that report I forgot to mention cactus fruit and psilocybe mushrooms!

As well as when playing this week, I had noticed that threshed wheat, and flour are not able to go into bottles? Is there a particular reasoning that they aren't able to, when they'd likely have the same consistency as say sugar or salt if you were worrying about the grain size?

**Comment by cordy-123** [comment]
Stacking Steel Piston Blanks please!

Including the ability to "stack them directly with tongs", thanks!
(like clay plates and bowls)

Usually, 2 smiths can do all 10 needed for engine in one go.

But it's a pain to clear out 10 open tiles in an already crowded smithy. 

Thanks!


![](https://cdn.discordapp.com/attachments/691122070465019974/696586502960054333/unknown.png)

**Comment by jasonrohrer** [comment]
The wheat is an uncrushed seed, not a powder.  I'm going to leave that alone for now.  But I will do flour bottles.
