### ISSUE TITLE
Funnel too easy to lose

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#708]
The glass funnel is a requirement when using bottles. Problem is that it’s very easy to lose a funnel, either by someone hiding it to grief, or because it’s really hard to locate because it’s looks and size. It can be very easy to miss amidst all the stuff in towns.

To make bottle storage more reliable there needs to be a way to easily locate a lost funnel. Or at the very least make it easier to find based on its sprite.

**Comment by sigmen4020** [comment]
Biggest problem is that funnels are very hard to locate in full baskets and slot boxes, due to their small transparent sprite.

**Comment by jasonrohrer** [comment]
They are small objects.  There are lots of small objects in the game that can get lost in the same way.

If you want to make sure stuff doesn't get lost, you have property fences to control access.  Pass the fence down to a trusted member of the next generation.
