### ISSUE TITLE
Unsealed bottles don’t go on tables

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#709]
There’s no reason why unsealed bottles shouldn’t be storable on a table. Unsealed bottles with wine and ingredients for food could go on regular tables, while unsealed bottles with chemicals could go on lab tables.

**Comment by jasonrohrer** [comment]
Yes!  good point.

**Comment by jasonrohrer** [comment]
I'll make the unsealed chemical ones go on the lab table only, for consistency.
