### ISSUE TITLE
Can't create account via steam

### ISSUE THREAD

**Issue by Arusina** [jasonrohrer/OneLifeData7#71]
I bought and download the game via steam. When I try to start the game, a message pop up with "The game will try to create a server-side account for you through Steam. This may take a few moments" after clicking okay within one second an Error pop up show up: "Could not create an account for you on the game server." 

What I tried so far: 
* reinstall the game
* change steam language from german to english
* running the exe in adminstration mode
* Turn off firewall/Antivurs program

I still have the same error message. I will add the "log_steamGate.txt".
[log_steamGate.txt](https://github.com/jasonrohrer/OneLifeData7/files/2612615/log_steamGate.txt)

edit info: added deactivation firewall

**Comment by jasonrohrer** [comment]
The steamGate client is failing to connect out to the web.

Any idea why this might be?  Do you access the web through a proxy or have some other networking issue?

The game itself needs access to the web (to fetch the server list, etc.)

**Comment by Arusina** [comment]
When there is no fix available and nobody has a clue, what the problem is, I will return the game to get my money back. I am willing to help and giving you the information you need, but I am not willing to wait another 3 weeks and not able to play. I think everybody can understand that :)

**Comment by jasonrohrer** [comment]
Yeah, I'm just one guy handling everything.

This is a rare problem.  There are many thousands of people who are able to play.

There's something up with your VPN or university web access.  Sadly, there's probably nothing I can do to help, so a refund is probably the best course of action.

**Comment by Arusina** [comment]
There was no problem with the connection. I installed the game on a different computer (and use the same network and again no VPN) and the account was able to create. If someone had the rare problem, here is my solution what works for me:

1. Install the game on a different PC
2. Start the game, let the account create via steam
3. Reinstall the game on the computer you want to use
4. In my case, the one hour one life client still want to register an account (even after he did it already in the second computer), so i copied the whole settings folder from the second computer.

**Comment by Arusina** [comment]
> 
> Yeah, I'm just one guy handling everything.
> 
> This is a rare problem. There are many thousands of people who are able to play.
> 

Just give the people a quick information, that you don't have the time to work on their problem. That is absolutely okay! But I didn't want to do a workaround to give you the option to look for any bugs.
