### ISSUE TITLE
Homeland issues

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#710]
Right now if you take water from a well, it becomes a homeland for your family.
It does not require to stay there. It does not require females (and males can block females from using it? if other families). Tested by returning there, the same family, the girl had kids right away.
Other family members don't get the "home buff" when they enter (not sure on this, we were riding two horses).

Anyway, I think people still didn't figure out, and it's unintuitive, easy to miss.
Possible fix: a reminder of homesick status with occasional emotes and an icon to state that you are infertile, and an arrow to home, so you know what you need to do to change it.

Claiming new home is limited by technology. Empty wells, Newcomen well, empty engine well requires upgrade or items to use them so you can't claim the new outpost without oil/rubber/engine. These camps can be still viable due to having water in cisterns, having kids before upgrading would be optimal compared to wasting time on them.

Claiming a new homeland should be either by setting a home marker close to a well, or using a cistern should also allow to claim them.

Seen several people trying to move into a city made by a black family, but the males were still alive. Next time I saw a girl sitting in the fire, but she wasn't able to fetch water due to not having a rubber, then not having the engine there 

Especially when females are very far from the original home, they should be able to claim abandoned towns.

**Comment by jasonrohrer** [comment]
The homeland only stays there if you have babies there at least once per hour, and it should work for all members of your family, not just you (homelands are on a per-family, not per-player, basis).

I just checked, and it worked for other family members after claiming.

And of course, you can have more than one.

Anyway, you are ALWAYS born in one (b/c your mom wouldn't be fertile otherwise), and you get a notice when you leave.  Players are meant to figure out the fertility connection on their own.

**Comment by laccy** [comment]
okay but that still doesn't answer the tech issue
towns might have 2-4 or even more cisterns which is better than an upgraded well. that is still a viable homeland, but forcing them to interact with a well to claim it isn't always possible. You cannot expect that a town has 24/7 access to rubber or oil. People do it in batches, storing water in a cistern is actually a good thing.

Also at least before this whole engine stealing the good towns made their engine and had a good chance to revive them, bad ones got empty wells and it was more work then reward.  Right now is kind of impossible. And having kids in a new outpost is the first priority, not fixing the water issues which might not even be an issue since cistern got plenty of water. Especially that a pseudo-Eve and her tiny family can get by with little water amount.

Claiming a homeland should be possible even if you got no water in the well. If it's a bad choice then it's a bad choice, since we can't make new cities without iron, at least allow us to claim old ones.

How is it even making sense that you should not upgrade the well so it will be easier to claim ownership to it?
