### ISSUE TITLE
Grapes inconsistent/dead content

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#711]
The food value is very low, and people accidentally click on them. Then it creates a lot of clutter, and people eat them reflexively.

I really liked that grapes were able to walk through.
This allowed using them as pen corners, cow pen fillers.

I guess they could function as walls, this could make some nice niche walls, and block some paths from bears. But with this food value is a major water sink and using them for wine would require glasses (normally only black people have them, and hard to transport them without a stopper).

They can be eaten, but due to the change of losing food bonus, they are horrible 1 pip per 5 water and requires shears to renew them.
Since they require high tech, copper is not something people generally make, and uses a roller and draw plate, even so, it needs fences, so quite hard to make them.
These alone would indicate that grapes should be better than berries. Also quite weird that one piece of berry has more food value than a full grape. 

Would be a decent replacement for berries in late towns. The food value should be around 30ish
so like 6x5. Telling people not to eat them would be hard. Locking it up wouldn't work since accidental misclicks would fill up a lot of space. The timers could be higher on them or require several steps (I was working with grapes, they need to be covered, uncovered, cleaned several times before harvest).

**Comment by jasonrohrer** [comment]
Problem:  grapes require no soil or tilling, only water, to grow, making them superior to almost every other food source.  They do require pruning, but still no soil.

Also, shears have 100 expected uses, hoe only has 50.  So again, grapes would be a mega food source compared to other things.

They aren't really meant to be eaten too much.  People don't eat these types of grapes in real life.  They are meant for wine-making.

**Comment by laccy** [comment]
soil is 1/4th of water if you consider the cost of composting and the biggest cost is water
compost costs 4.5 water and 3.5 soil for 21 bowls of soil so 1 bowl of water turns int to 3.88 soil no even counting the tool usage, already really  slim profit for the work needed 

so 4 bushes make 28 berries which are 84 pips
5 grapes make 1x5x5 grapes which is 25 pips (exchanging that 4 soil for one extra water- but right  now if you offer a bucket of water or 40 soil, nobody takes the soil)
that's 30,36% worth of using the water and soil on berries which don't even need iron to make it
yes that's slightly better than just looking at the water for 25% food value
or say the perk of "not using soil" is 25% better value on food 
that's still very low since the initial value is very low
so to cut even with berries it would need to be around 15 per water(3x5). then the soil saved is rounding it up to 17-20 on berries, still bad food option but if someone eats it's not a big deal, more like wasting time.

same goes to wine, it has a cool effect but the 5 grapes convert into 12 uses which is horrible.
all the technology, tools needed for glasses, rolling copper, fences would indicate they should worth it at least as much as watering and soiling a bush, I know alcohol is not really about nutrition but that's as low as you can get on the "not worth" scale. If the wine is around 25 and the grapes on 15 then is still a bad option compared to almost anything but berries. At 20 and 12 would be literally the same thing.

what's the worst thing that can happen? Do people plant grapes instead of berries? they still gonna need water the same way, they might save the soil, but the soil is made using water.

If it doesn't meant to be eaten, then why the change so they can be eaten? if they can be eaten they should provide a decent value for water. 
<img src="https://i.ibb.co/TKH7KMG/ohol.png" alt="food chart">
this list is from miskas, not sure how he did it or fully on point, most players don't even think about it in-game, but if veterans see that oh Mangoes are so wasteful, they never gonna make it

shears might have 100 uses but they use 2 blades and return half scrap
that's 0.75 iron to 0.66 and cuts even on uses around 32 shears and 32 hoes since you get back less scrap over time

not sure that's an oversight or not, if it uses 2 steel blades, they should give back 2 scraps?

I don't think anyone would even consider the tool usage value is quite low and hard to quantify it in the game, especially that shears can be used on trees or goose and that doesn't guarantee that you get anything out of it

The compost nerfs from 8 to 7 baskets and an average 16 profit on it, made the work less useful.
Using a tool twice on one soil it's more water-efficient than using once on two (I didn't even calculate for 3 but that is 50% worse and some more) 
So the lazy method is the water-efficient method now. At least comparing kerosene usage for iron mining or water production.
Soil would need to be cheaper if players ever try to save on iron by using more soil.
Right now they scavenge all the iron from abandoned towns so they don't have to find new mines or use the engine to mine it. There is no direct conversion from iron to water, especially for non-gingers so water will be always better choice.
