### ISSUE TITLE
Wet Clay Stacking

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#713]
How about stacking:

**Wet** Clay Bowls
**Wet** Clay Plates
**Wet** Clay Crocks

(Also the ability to use **tongs** on the stack)

=====

Based on onetech: https://onetech.info/1217-Clay-Crock

You can't stack Dry Clay Crocks using **tongs**. 
(unlike Dry Clay Plates and Bowls)

Thanks! ^_^

=====

Ability to stack wet clay stuff would help in crowded smithys, which are basically all the smithys.

=====

![unknown (5)](https://user-images.githubusercontent.com/61180955/78649320-dab47d80-78ef-11ea-9421-498e47c183ff.png)

**Comment by Elsayal** [comment]
How do you make crockpot then ?

**Comment by cordy-123** [comment]
Elsayal,

Wet Clay Bowl + Wet Clay Bowl = Wet Clay Crock

onetech.info for all your crafting needs

**Comment by Elsayal** [comment]
What I mean was : when you stack wet clay bowl, you got crockpot. So if you want crockpot, you need to get them from another way.

So : how do you stack wet clay bowl (without making crockpot) ?

**Comment by cordy-123** [comment]
Ah, you are correct. This is a conundrum. 

And I have no answers. XD

**Comment by jasonrohrer** [comment]
Yeah, wet clay stuff will stick together if stacked.

The way it works is intentional.
