### ISSUE TITLE
Easter is coming - of course we need chocolate easter eggs !

### ISSUE THREAD

**Issue by Elsayal** [jasonrohrer/OneLifeData7#714]
As easter is coming next sunday, we definitely need easter eggs. Chocolate tree can be found in Jungle I assume. And maybe we can add some paint to them too. Seeking for eggs, behind tree will be so fun :)

I can't think about anything more important so far.

Anyway, thanks for the awesome game :)

**Comment by jasonrohrer** [comment]
Thanks!

But I really need to focus on bugs an issues here.
