### ISSUE TITLE
Scrap bowl waste

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#718]
There exists traps when using the scrap bowl, especially related to making the Diesel engine. This is the worst offender:

https://onetech.info/2376-Diesel-Piston-Head

Here you gain 1 steel back for an item made with 6 steel, which means that you waste 5 steel scrapping this. All these traps needs fixing.

**Comment by jasonrohrer** [comment]
Can you come up with a full list of them?

**Comment by sigmen4020** [comment]
Here’s a list of the Onetech links with all the traps that waste steel when scrapped:
https://edge.onetech.info/2379-Diesel-Cylinder-Head
https://edge.onetech.info/2380-Diesel-Cylinder-Head-with-Valves
https://edge.onetech.info/2381-Diesel-Cylinder-Head-with-One-Valve
https://edge.onetech.info/2376-Diesel-Piston-Head
https://edge.onetech.info/1002-Duplicate-Lock-and-Key-10

**Comment by cordy-123** [comment]
https://onetech.info/2375-Fuel-Injection-Nozzle

**Comment by cordy-123** [comment]
https://onetech.info/2299-Pump-Valve

**Comment by sigmen4020** [comment]
The fuel injection nozzle can’t be scrapped, so is therefore not a trap. That’s why I didn’t post in on the list. Check the Onetech page again.

I did miss the pump valve though.

**Comment by Spodnie** [comment]
Maybe using a hammer on these in a scrap box would make sense?

But personally I would like it more if we could just disassemble these into parts with right click, so we could scrap piece by piece.
