### ISSUE TITLE
hot rods don't stack

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#719]
With the new ability to stack hot/cold steel pistons, giving us the ability to do the same with rods and pipes would be a great change. This is especially needed for making oil, since you could potentially need a lot of pipes for that.

**Comment by sigmen4020** [comment]
Changed the title to reflect the fact that regular rods and pipes are now stackable. Would still love to see hot rods be stackable as a QoL for oil and engine makers.

**Comment by cordy-123** [comment]
Pouches don't stack :)

**Comment by TwistedHBG** [comment]
It could look something like this, I think it would be pretty cool.

![image](https://user-images.githubusercontent.com/43919541/80022749-ce7a1400-84dc-11ea-8603-c61dcd95588e.png)

**Comment by jasonrohrer** [comment]
Twisted:  YOU'RE HIRED!
