### ISSUE TITLE
Uncurse

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#721]
Just played a life where my daughter was a griefer, she brought a bear to our town. She got caught on it and 2 people cursed her.
We also had a guy in the town who worked hard... He made an engine that we were missing in our well. He saw her bringing the bear too, so he got a knife and stabbed her with our posse help. Someone just cursed him because he thought he stabbed her with no reason. I told him that she deserved dying because she's the griefer, and told him he should uncurse that person... But there is no uncurse command.

Would be nice if we had it, in some cases it could be useful.

**Comment by jasonrohrer** [comment]
Think carefully before cursing.

But one stray curse against someone isn't that big of a deal, I think....
