### ISSUE TITLE
Not enough upgrades

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#722]
People are bored cause there is nothing to do
There are only a few upgrades to wells and veins.
It should be more upgrades, but smaller quantities coming with it. Also possibly combine their output to be required for the other's input. Aka a well would require iron to upgrade, a mine would require water to upgrade. For example, Lvl 1 well would give very low hourly water and some more with a bit of work, a level 1 mine would give some iron. Lvl 2 mine would give more iron but would require half of the production of a level 1 well. If level 2 well is giving more water then upgrading the mine is easier. Jumping 2 levels should be close to impossible, so players would need to upgrade well once to upgrade mine once, the next step could be either of them but then switch.

This would slow down progress in an enjoyable way, where players can only blame themselves not doing the work.  Also would balance out the iron and water costs cause you need them for the other, making iron just as valuable as water, but at times iron would be more important, at times the water would be more important.
Since the mine and well is in same homeland, they could automatically take off from each other.
Example:
iron1 give 3 per hour (each 20 minutes 1)
iron2 give 4 per hour requiring 1 water per hour
iron3 give 6 per hour requiring 2 water per hour
iron4 give 8 per hour requiring 4 water per hour
basically 1*1^n each upgrade 1*1^n-1 requirement up to infinite but each step needs one upgrade and consumption

water1 would give 15 per hour 
water2 would give 20 per hour requiring 3 iron per hour
watter3 would give 25 per hour requiring 4 iron per hour

so players can upgrade one then use the extra production to upgrade the other
20 min intervals so any person can do 2 upgrades a life
it would still lose iron or water if they don't mine it out/don't take out the water for cisterns or food
eventually, it could produce a lot if players claim it.

Upgrades could only be done after the mine is empty for the session of 20 minutes if nobody takes out the resources it won't regenerate since it has no storage on its own.

The minimum hourly income, that can be upgraded instead of one big quantity that just can be taken out. 
This would allow mines to be an industrial zone that worth expanding and extending, buildings near it, workers to spend more time on it. Right now the eve can do the first phase, then one person the next step, maybe 3-4 people can mine out that 77 iron then is gone. Then others got no reason to go there, just to transport the iron. Once the mine needs an engine, its not really a steady income cause the engine can be stolen and without kerosene produces nothing.

Wells: hourly X water, then cleaning/drilling it to get more.
Upgrades could be several stages of adding items to it. Stanchion Kit, extra rope, extra bucket.
This would put the focus on the work, not on resources. After getting the hourly income, cleaning and drilling it deeper. Maybe a ladder to go down then uses a shovel.

Mines could require the same, stanchion kit, then buckets, ropes, elevator, etc. Some resources that players can produce with their income of iron. Even upgrades that require random items, like food or other items, so players don't know what they need for the next upgrade and have to adapt.
Realistically would be weird but let's say the mine has a quest that a well-known engineer could optimize it but he really likes omelettes so you need 3 omelettes to give to him to do it.

Right now you can just empty a well into a cistern and proceed with the upgrade.
If it would give some hourly water, it would allow some milkweed to be planted, to make extra boxes and buckets. It would still need to be emptied each hour or the new recharge is lost.

For newcomen well is a bit weird, but it still could give some free water per hour.
Engine removal is really hurting old cities and makes no sense. Way to easy to grief it and people scavenging old cities is not a good mechanic.
Back before we could revive old cities with an engine, generations of work and care should matter.
The bad cities died out before completing the newcommen or the engine so reviving them was pointless, now is backwards, cause higher-tech means that its easier to ruin the old city.

The age of the city should matter, the work done should matter. An old city should provide some resources hourly or per 20 minutes, so it can be still viable. Right now people just hoard resources left and right and returning to your camp is impossible without taking back the engine they steal and getting kerosene with it, which is kinda the hardest part of the game. Just because a family dies out, doesn't mean the city is worse than the others. Sure it could lose the production cause no workers to gather but in terms of games, it still has more "points" than other cities, it shouldn't be discarded until others reach the same level. Im kinda tired of making nice cities, just to see that others steal every bucket, every tool, every horse when I got back there is empty but a nearby city has all of the items I made.

**Comment by jasonrohrer** [comment]
This is not a bug or issue.
