### ISSUE TITLE
Food values visual representation

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#723]
Right now the player base has to follow all the changes on food and other items, there are returning players who still play the game the same way and you got to explain to them that's not like that anymore.
I even saw someone who made pit stakes. But generally with ponds they leave water or try bowls on big well or similar stuff.

With the change in food values its huge difference between having early game a multi pip pie or even berries, but later they fall way below milk or carnitas.

People would need some visual confirmation on foods like colouring or sizes. If something gives a lot of pips it should be bigger or give off an aura. It was made in hetuw so yum food can blink, quite annoying effect, but I guess not that hard to do something similar. Maybe small pip values could be as green, middle orange and high would be red or something like that.
Maybe holding down a button to bring it up.

This would help players to see if there is any food left in the camp and make a better yum chain.

**Comment by Spodnie** [comment]
Foods with an aura? I don't think it fits in this game.
Soon people will realize that yumming is the best way to go and every food matters, not only these with big pip values.

**Comment by laccy** [comment]
what you mean not fits? more realistic than force fields around biomes
having a decent UI or organized visuals would help the game

yumming is still bad if has no top cap, its not fun to think all game what is the next unique food nor realistic, it's just a meme some players did, and the smarter people did it once then realized it's not worth, forcing it in the current way, would mean that people need to do that dumb life where they walk around just to eat, especially going 2-300 tiles for wild food in a big city is quite dumb
it's about the personal yum, high score, a selfish act, not a village-wide food variety 

with a top cap of 10, and 10 chains of different food would matter and that's easier to chain, produce like you could do 6 main foods and the ret of 20 would cover the other 4

**Comment by jasonrohrer** [comment]
People can see how much a food fills them up by eating it.
