### ISSUE TITLE
Remove weak skewer + weak skewer = knitting needles transition.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#724]
In the midst of this food nerf people are accidentally converting skewers into knitting needles which then requires more skewers to be gathered. This transition isn't really needed as skewer + skewer or weak skewer + skewer results in knitting needles. 

This would remove the accidental case of people either trying to stack or set down skewers used for cooking.

**Comment by miskas9** [comment]
Skewers need to be stackable

use flint chip on 1 skewer to Make Knitting Needles

**Comment by Spodnie** [comment]
I agree. I also tried to make stack of weak skewers and it resulted in knitting needles. It's annoying in tomato farms where we need skewers, but it's not the only case.

Maybe using knife on a skewer could make knitting needles?

Or, if skewers were stackable, using knife on 2 skewers could also do the job.
