### ISSUE TITLE
Even more potential stacks

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#726]
Below is a list of items that could stack or be tweaked to fit in better with already stackable items

-Branches (straight, curved and yew)
-Shafts (long, short, curved and yew)
-Stakes
-Skewers
-Pine needles
-Dug stumps
-Boards (currently only stack up to two)
-Threshed wheat (should stack up to three like soil and sand)
-Flint chips (currently only stack up to four instead of six like most stacks)
-Shrimp
-Artic char
-Straw and reed (hay bales or bundles or put in box)
-Big hard rocks, cut stones and stone blocks
-Vulcanized rubber tires (currently only stack up to two)
-Empty and sealed glass bottles
-Steel pipes and rods

**Comment by sigmen4020** [comment]
There might be a conflict with the basket recipe for potential reed and straw stacks.

**Comment by Sir-Caio** [comment]
They should be combined with something else to create the stack, either a rope or just a box

**Comment by jasonrohrer** [comment]
Some of these things conflict with other things.  There are some recipes that require two branches or shafts (like snowman).  So those things have a pair only, and no stacks.  This is weird, I know.

Other stuff I will fix, though.
