### ISSUE TITLE
Things that still need stacks or piles.

### ISSUE THREAD

**Issue by JackTreehorn** [jasonrohrer/OneLifeData7#729]
Here is a list of the final things that still need stacks or piles. 
Comment on this thread to add more rather than starting your own thread.

-Rabbits
-Dead Geese

Cuts of Meat: (Maybe not needed as it would be bad hygiene to pile cuts of meat on the ground.)
-Skinless Rabbits
-Mutton
-Pork
-Plucked dead geese.
-Turkeys

Random:
-Pile of Bones to make a mass grave. (When you don't care about emotional significance of burial and want to save on shovel uses.)
-Clay nozzels/Dice/Rubber balls/Pencils.
-Rubber Tires

**Comment by sigmen4020** [comment]
Maybe the bone pile could potentially only work with Defaced Bones.

**Comment by Spodnie** [comment]
These are not really needed. I prefer to see these in containers instead of lying in a pile.

**Comment by jasonrohrer** [comment]
Yeah, I think those cooked foods are going to remain pile-free.  You put them in baskets to store them.

Also the little tiny things.

Rubber tires come only in pairs because of the recipe that uses 2 tires.
