### ISSUE TITLE
Bottle stacking visuals look impractical

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#730]
The bottle stacking visuals are really strange imo. Noone would stack bottles in such an unsafe manner. Those bottles would fall down by a single gust of wind. I quickly sketched how bottles could be stacked in Paint and still look natural, and would suggest that bottle stacking look more akin to this than what is currently on Onetech.

My quick Paint sketch:
![image](https://user-images.githubusercontent.com/51952537/79285106-d32b4080-7ebc-11ea-9de6-f576032cb538.png)

Currently on Onetech:
![image](https://user-images.githubusercontent.com/51952537/79285145-fa820d80-7ebc-11ea-9783-261454b6a95c.png)

**Comment by Spodnie** [comment]
![image](https://cdn.discordapp.com/attachments/677300246824484867/699859757502300190/2020-04-15_07_49_27.png)

**Comment by sigmen4020** [comment]
That looks very nice too tbh. Either or would be better than the current sprite.

**Comment by jasonrohrer** [comment]
Hard to tell on OneTech, but they are transparent.

If they overlap, you just see a lot of lines, and they become VERY hard to read visually.

They also look better stacked vertically than you think, because they are transparent.  You can see what's behind them.
