### ISSUE TITLE
inconsistency/balance Pigs dont produce poop when fed

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#733]

**Comment by Spodnie** [comment]
And let it stay like this. Pigs dung would be too cheap since they eat only one corn.

**Comment by miskas9** [comment]
Dung is already TOO cheap cause it comes with mutton and wool. 
Also placing all your apples in one basket is not good from balance and game variety perspective.

**Comment by cordy-123** [comment]
Cows poop too.

**Comment by jasonrohrer** [comment]
Dung overload update

**Comment by jasonrohrer** [comment]
I'm going to leave this alone for now.  There's currently no reason to have more than one cow, and that will be fixed in the future too.... I'll re-examine dung production at that time.
