### ISSUE TITLE
Can't transfer salsa between bowls

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#734]
Would be nice to be able to transfer salsa between bowls, so you can save bowls as more salsa is eaten. This way you wouldn't for example end up with 4 bowls of salsa with just 1 use left, when there are no more tortilla chips to dip. This would also be consistent with how you currently can transfer butter and ketchup between bowls.

**Comment by jasonrohrer** [comment]
Will do!
