### ISSUE TITLE
Trad-able goods and quantities

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#736]
1. Kernels should stack for storage
2. Could we have a way to contain Kernels and anything powder like in great quantities? 
  An item like a Sack that holds 10 of the same kernel item

**Comment by jasonrohrer** [comment]
Seeds, you mean?

There are seed bowls, right?

**Comment by miskas9** [comment]
palm oil kernels, corn kernels, threshed wheat

**Comment by cordy-123** [comment]
miskas, do you mean like a pile?

Threshed wheat can be piled. https://onetech.info/4070-Pile-of-Threshed-Wheat

Corn kernels cannot be dumped or piled.

Palm kernels can be dumped but cannot be piled.

**Comment by miskas9** [comment]
yeap palm kernels and corn kernels must be able to get piled as threshed wheat does. 
AND
All of them + any powder-like item should be able to be stored in a Portable Sack in high quality to improve their logistics and trade.

**Comment by jasonrohrer** [comment]
Sulfur can be bottled for transport and trade.

The oil from palm kernels can also be bottled and transported.  Though I see how you might want to transport the raw material.

However, a palm kernel really is too big to fit in a bottle.  I will make them pile-able and dump-able.

Corn kernels could go in a bottle, I suppose.

**Comment by jasonrohrer** [comment]
The crushed ones can go in a bottle.  But they do need to be roasted first.

**Comment by miskas9** [comment]
Bottles are too delicate to transfer Non-liquid and non-Chemicals Raw materials.
Will be there an Item in the future that would be able to contain Raw materials in greater quantities?

**Comment by jasonrohrer** [comment]
Too delicate?

Anyway, I'm adding buckets of wheat, palm, and corn kernels.  They hold as much as the piles of these things hold (6).

**Comment by miskas9** [comment]
Thanks for the buckets!
Dilicate> bigger chunks of material, in reality, would stick to the bottleneck.  Even the flour that is very powder-like would find it difficult to pass through a bottleneck
