### ISSUE TITLE
Boost water

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#737]
After recent updates the game became fun. We aren't bored, we have tons of things to do, but... We constantly lack water. I see no reason to have that little water anymore especially that we use much more of it now.
Lately I haven't seen any kerosene... I think people stopped making it because it's not too worth doing it, water ends up quickly and kerosene doesn't give too much water, especially that only gingers can make it. Also keep in mind that towns often have 15 and more people, water really disappears so quickly.

I suggest to increase the amount of water in every well stage by two times. Give a few more uses for oil pumpjacks (maybe 7 instead of 5?) and make that every use of kerosene on diesel pumps gives 7 buckets of water.

Using newcomen pumps is annoying... It requires to put lots of work to get only 3 buckets of water(4, but one goes back to the atmospheric core) over and over again. Would be great if instead of doubling the amount of uses for newcomen pumps, you made it that we could get 2 tanks of water from wet newcomen pumps instead of 1.

**Comment by jasonrohrer** [comment]
Don't you get 6 from newc pump?  One goes back in to run it again, so 5 net.

Also, I'm hesitant to change this just yet.

My guess is that players are wasting tons of water (like by having huge berry fields for food production).

Berries are still the most-eaten food by far:

http://onehouronelife.com/foodStats.php

That will change over time as players adapt.

**Comment by Spodnie** [comment]
https://onetech.info/3168-Tank-of-Water-less-full
1 water tank with 4 uses from newc pump and one use goes back.

Yeah, you are right that people waste tons of water.

**Comment by cordy-123** [comment]
> Don't you get 6 from newc pump? One goes back in to run it again, so 5 net.
> 
nope, you get three net.
> 
> Berries are still the most-eaten food by far:
> 
just curious, does the tutorial mention yum at all?

**Comment by jasonrohrer** [comment]
Yes, Tutorial mentions YUM.

Sorry, forgot about water tank, less full!
