### ISSUE TITLE
For your consideration...More possible stacking...

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#738]
For your consideration....

Things that don't stack:
- Rabbit Fur Shoes and Wooden Shoes (and Old Boots) 
(And Snake Boots without Cactus Fruit on them)
---> I think they'd look cute, 2 of them stacked. Like an actual pair of shoes. Or 5/6 of them in a pile, like the usual. Less cute but more efficient space-wise.
- Empty Rabbit Fur Pouches
- Dirty Wool Pads (often cluttered around town)
- Bone Needles (easier to find, also less clutter)
- Wooden Tongs
- Bellows
- Scrap Steel
- Pencils
- Dry Glassworts and (Green) Glassworts
- Pile of 3 or 6 Charcoal
- Empty Tanks

-------------
Piles of Tool Heads.... (in piles of three? or five?)
- Steel Axe Head
- Steel Hoe Blade
- Steel Chisel 
- Steel Adze Head
- Steel Froe Blade
- Steel File Blank
- Steel Blade Blank
- Steel Shovel Head
- Steel Mining Pick Head

-------------
Also can we place Bowl of Gold Flakes in a cart? It's a pain to carry one bowl by hand for a long distance. And you need 2 for the bell. So double the walking. 2 full round trip long walks.
(Haven't actually tried in ~ 2 months, I assume you still can't do it.)

-------------
(https://github.com/jasonrohrer/OneLifeData7/issues/737)
Just in case you haven't read it, from a closed issue: 

Quote from jasonrohrer:
> Don't you get 6 from newc pump? One goes back in to run it again, so 5 net.
> 
nope, you get three net.
With the race restrictions, maybe 5 net would make better sense.

**Comment by jasonrohrer** [comment]
Bowl of gold flakes in cart?  That's been working for ages...

**Comment by jasonrohrer** [comment]
In general, I'm trying to avoid adding stacks for things that are "only made in bulk by accident."

The stacks are for things that are generally made or harvested or used in bulk.

You only need one bone needle.  What good is a stack of them?  It's a way to "get rid" of the extra ones, but there should be some other method of doing that.  Same for pencils.

But you generally have more than one water pouch, and lots of charcoal.


Anyway, I'm just trying to give you my guiding principle here.

**Comment by jasonrohrer** [comment]
I'm not sure about all the steel tool heads.  I'm going to leave those for now... they're not really raw materials in the same way as the other things.

**Comment by cordy-123** [comment]
ok :)
