### ISSUE TITLE
Instant hot coals

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#740]
Could we have 
https://onetech.info/248-Firebrand plus https://onetech.info/300-Big-Charcoal-Pile-3 would make https://onetech.info/85-Hot-Coals-tool , please?

Kinda annoying to wait a whole minute for hot coals right now and we need them quite often. Would be cool if we also could just fire a charcoal pile to get hot coals right away.

I don't know if it would be realistic tho, if you don't like it just close the issue, it's fine.

**Comment by voy178** [comment]
I see the potential for griefing.

**Comment by Wizadroid** [comment]
Yea but it's not like charcoal is impossible to replenish. Maybe needing just a pile of two charcoal pieces or something? Or perhaps giving us a way to smoother a fire down into hot coals instantly?

**Comment by miskas9** [comment]
What is needed is a reliable, fast method to cook food that is not been cooked in the Adobe Oven.
Carnitas, omelets, and Pots. 

https://i.pinimg.com/originals/d8/5a/b9/d85ab9d39587b72579a690ec68420f80.jpg
This is a flat top griddle that can go over a campfire.
There are also smaller, lower to the ground ones, that cook over coals.

**Comment by Spodnie** [comment]
Miskas9, how about cooking geese, rabbits, fish, shrimp, stew, turkey broths, sugared pumpkins?
I'm not sure you could make them with a flat top griddle.

That's why I would prefer to just be able to make instant hot coals instead.

**Comment by cordy-123** [comment]
preferably making it longer to extinguish... instead of 2 mins, it'd be 3 or 4 mins....to make up for the effort of making the charcoal itself (which takes 30 secs to make).

**Comment by Spodnie** [comment]
Cordy-123, that's not really necessary, we can make a few charcoal piles at once, because villages often have more than 1 adobe kiln.

Charcoal storage or bigger piles would be cool but it's not really necessary either, because we can just make a few boxes for storing charcoal in baskets. I mean, if a box could store let's say 10 piles of charcoal that would be super cool, but this issue is not about this :p

**Comment by jasonrohrer** [comment]
Yeah, spodnie, not sure about the realism there.

If you use charcoal in this way IRL, you do have to wait for it to turn into hot coals before cooking with it.

More cooking tech will be coming in the future, so I'll let that future content solve this issue later.
