### ISSUE TITLE
Already fixed issue that can be removed to shorten list

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#743]
https://github.com/jasonrohrer/OneLifeData7/issues/244
https://github.com/jasonrohrer/OneLifeData7/issues/34
https://github.com/jasonrohrer/OneLifeData7/issues/252
https://github.com/jasonrohrer/OneLifeData7/issues/287
https://github.com/jasonrohrer/OneLifeData7/issues/380

**Comment by jasonrohrer** [comment]
Thanks!
