### ISSUE TITLE
Not eating babies still drain mom's hunger

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#746]
If a fertile woman picks a baby that refuses to eat, she still loses a pip. This doesn't make sense.
Fix it pls.

Offtopic:
I get why you made it that we can feed only starving babies, so these 3 minutes aren't that boring for babies.
Idk, to me these 3 minutes weren't really boring, ever. I don't mind them at all, I think you see this as a bigger issue than it really is... But now moms lose their 3 minutes too :/
I remember times when we didn't have so many kids. Moms were showing their kids the village, telling them jokes or talking with them. If we had a good mom, these 3 minutes were a fun time.

This change only encourages to keep babies staying next to fire, so moms don't need to pick them too often.
Please consider going back to old system, current one isn't fun to anyone.

**Comment by TwistedHBG** [comment]
I really hate this change as the only thing it achieves is the exact opposite of its intended effect - it punishes mothers for interacting with their babies. I feel like it kind of went under the radar as it came at the same time as the iron overhaul.

**Comment by miskas9** [comment]
I think the drain is intentional so you have to ask the baby if it is hungry or not instead of you randomly picking it up. 

Sponndi have you any idea how would you make those 3 minutes worth to not to be an AFK bb?

**Comment by Spodnie** [comment]
No, but I don't see this as an issue. I'm not bored during these 3 minutes, especially when having a good mom, and there is no reason to punish mothers too.

**Comment by miskas9** [comment]
I am never bored those 3 minutes ether cause I use my zoom mode to scout the village. 

but Jason wants these 3 minutes you actually do something for your survival and if mothers won't have a cost for picking you up they will spam pick up till you are fed without you even ask for it.

**Comment by Spodnie** [comment]
It's up to mothers whether their babies are bored or not. A good mother would tell them what should be done in the village or just interact with them. This change doesn't help in anything, it does the opposite actually, that's why I posted this issue.

**Comment by jasonrohrer** [comment]
There is a good reason for this.

It may not actually solve the problem, but no other solution is forthcoming for now.

Baby should NEED to communicate to mom to avoid her wasting food and time.

A good baby will tell you when they're actually starving....

I'm really hoping a better thing will come up in the future to make 2-way comms between mother and baby necessary.

**Comment by jasonrohrer** [comment]
Actually, this change also encourages holding your baby the whole time instead of picking it up and down all the time.
