### ISSUE TITLE
Reed Skirt, Straw Hat, Straw Hat with Feather, Old Boots and Sandals don't decay

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#747]
These are really cheap and maybe should decay in some time.
As for sandals they're inconsistent with snake skin boots, while the former doesn't decay the latter does.

PS.: I'm so sorry everyone, it had to be done. I'm reporting this one to the master ;-;

**Comment by voy178** [comment]
Traitor

**Comment by Spodnie** [comment]
Backpacks should also decay :p

**Comment by jasonrohrer** [comment]
Old boot is already old!
