### ISSUE TITLE
Is OHOL too hard?

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#751]
I'm an expert player, to me this game would be fun... But most people can't play it and therefore families are dying too fast and I'm tired playing with noobs. We have 47 players playing rn, at that time we had about 90 a few days ago.
https://cdn.discordapp.com/attachments/703011254666526740/704449544523481088/2020-04-27_23_50_35.png
We constantly lack water, horses, we rarery have a tank of kerosene and even then it lasts only a while.

Please, remove biome restrictions. give us a bit freedom.
And please, increase water amount in every well stage. Would it be that bad if we could survive a bit longer? If poor water decisions wouldn't harm families that badly?
And pls, make 3rd well level (newcomen pump) a bit less annoying. It requires waay too much work just to get 3 buckets of water. Yesterday I spent so much time of my life just making water from our newcomen pump, because someone brought us lots of rubber. At that time I could get about 5 times more water from ponds using a horse. Newcomen pump is really annoying.

**Comment by jasonrohrer** [comment]
We had 90 a few days ago because it was the weekend, peak time.

This is not really a bug report....
