### ISSUE TITLE
Horse thiefs and griefing

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#753]
One of the favourite things to do for me is to get a horse and explore/gather with it.

That's why the most annoying thing is when people take it and won't return it. 
Typical griefer move:
-waits until you eat, steals the horse and runs around with it.
-dumps in a biome you can't access.
-puts it inside a fenced zone.
-takes it and then just goes to make a pseudo eve camp without asking anyone if the family needs an outpost or not.

But who owns the horse? 
If you use the lasso on it and bring it home that's 90% of the job.
If you make the lasso,  the carrot (can be wild)  then you contributed at least. Making the fence takes time and tool slots so also important.
You find it in the wilderness then it's yours. Dead people lose it or dead camps have it, takes time and knowledge to find it.

When it's not yours, or shouldn't be allowed:
When the city has one and people let it outside for common usage, it's kinda rude to take the last one and ride away. 
When you run around with it not gathering anything.
When you lure bears with it.
When you sit on it and take away items from others.
When you run in a city, take the horse, fill it with tools and run away before they react.

One possible solution: feed the horse a bowl of grain then it's in your ownership for 10 minutes. It only follows you because you fed him. This is quite realistic since horses are smart. Also, a bowl of grain can be easily found in the wild and transported with you.
Others can't interact with it unless you allow it.
So if you used lasso or found it, obviously you are the first to interact with it.
Thieves would need to time it so they know when it was fed the last time. They can't just pick it up any time. If people say "I share this" then it becomes public like now. Or if it's not fed for over 10 minutes.
It could even be that they need to be fed inside a fence or an item that you need to make

Poking bear caves with horse cart: it drops you and runs away fast. You need to poke twice so accidents are rare.

Posse aiming at you unmounts you from a horse. Posse aiming at you can disarm you. This can be abused by unmounting your visitor so might be needed a higher posse size number.

Horses should never stay in special biomes for long, or a way to lure them out, like whistling at them.

Horses and horse carts are very valuable and it's the best advantage of black families, yet people steal it right away and relocate it. A person on foot can rarely react to theft.

Other possible solution: when first using a horse you need to use a lasso on it (does not consume it)
and it's slow for the first few minutes. If anyone aims at you with a weapon during this time, you dismount automatically.  Also would not take a skill slot using it once, but when you try to take multiple of them you need a slot at least.

3 possible ownership modes:
1 Privately owned. The first person who feeds it. We can make a fence with a horse fence in it so others can't take it when first tied to it. Each x minutes needs to be fed carrot or bowl of wheat to keep this up.
2 Shared. The owner can share it so others use it. The horse will not leave the homeland, the person trying to take it will dismount at the current homeland edge and the horse runs back to the well.
3 When nobody seen/used it within a time period, becomes lonely and seeks a new owner. It can leave the homeland and becomes private when fed.

**Comment by Sir-Caio** [comment]
What about making horses breedable and die of old age in an hour? Feed a tame horse straw or grain and it will produce a foal, making horses pretty much available for everyone if you breed enough and have the saddles. Unsaddled horses live forever, but riding horses or horse carts die of old age in an hour.
As for the ownership, maybe feeding it a harder to get item, like a bowl of sugar, turns it loyal to you for your life time and never run away, staying in place where you left it. If someone else were to try to ride a loyal horse, they'd be unable to interact with it.
With these changes I could see horse pens showing up in every town through "trade" with desert fams as well as horses becoming more available and convenient overall.

**Comment by jasonrohrer** [comment]
I don't think this is a problem.  Be careful with your horse.  Build property at home around it to limit access and give yourself a safe place to park it.

When you're out riding, don't stop near someone that you don't trust.

**Comment by laccy** [comment]
At home yes but still a chore, but what about visiting others?  I can't build a fence in others home, it's already sketchy that I'm there and got a horse, and if they take it, I can't even protest in another language, they happy to get a horse and chances are they kill me for it. One will always assume that I'm there to make trouble and it's their horse.

When you starve you need to drop down, people waiting for that exact moment. It's childish and annoying and shouldn't be a thing. It's already annoying enough when someone follows you for no reason. Is also unrealistic that a horse just goes away with anyone at full speed after spending so much time with an owner. These people also sneak at you out of the blue to take it with no apparent reason or clue that they will do it.

Obviously you can't trust anyone. Not stopping at all it's not an option. Controlling when they are able to take it should be on the owner's advantage. Also the upgraded/non-upgraded swaps. They can run after you with a normal horse or a non-upgraded horse cart, swap yours and run away. Before you see their name or could tell anything they have gone. So how it's not an issue?
