### ISSUE TITLE
Pens made of only gates

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#756]
Sorry for making another issue, but I'm not sure you read closed issues. You can close it after reading.
https://github.com/jasonrohrer/OneLifeData7/issues/749

I'm worried people will make pens made of only gates if they don't require springs. I would surely do this because of how easy it would be to enter sheep pens from anywhere. It wouldn't be good, I don't really want it to work like this. Consider making fence gates require springs to auto-open.

It would also be consistent with doors.

**Comment by miskas9** [comment]
Will anyone waste 4 springs to make 4 gates, Or use the diagonal fence we already have?

**Comment by miskas9** [comment]
we also need spots to park horses 
people would probably make 4 gates, 1 on every side as we have now. 
I get that you wanna up the cost but 4 irons for a pen would be too much.

**Comment by jasonrohrer** [comment]
Let's just see what happens.  Gates can only go on east-west fences.  Perhaps I'll make them like snow doors, so you can't put them next to each other.

**Comment by Spodnie** [comment]
Oww, I didn't realize gates can be only on east-west fences, probably because nobody used them.
That's kinda bad :c

**Comment by jasonrohrer** [comment]
Oh,  I see... if they try to make gates vertically too?

I actually don't think that will work due to auto-orienting....  the presence of the first gate will make the next fence to the north become vertical, which will forbid a gates from being there.
