### ISSUE TITLE
potato food/iron

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#758]
iron consuption of potato increased 750%
In total it consumes nearly double the Iron of the second most iron dependant food the Stew. 
and produces about 1/5 of its food/iron

make shovel used only once to harvest potatoes
Add transition:
Mature Potato Plants+ shovel = Dug potatos
Then we pick them by hand.

**Comment by jasonrohrer** [comment]
ah, that's a great idea!
