### ISSUE TITLE
Visual bug sprite 2741 gate, possibly doors

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#759]
When the property fence gate is open, the door goes sideways, overhanging to the left side tile. Since the gate opens to bottom left, it should be on the front of the other tiles, but it's in the back causing a weird visual glitch, the wall is across the gate with the gate in the background. Fences don't have much graphics but when paired with different walls, gates really look weird.

might be the same for the NS doors, not sure. Also, it doesn't seem to happen all the time. I will try to screenshot it when I see it again.

**Comment by jasonrohrer** [comment]
Yes, I have seen this before... will look into it.
