### ISSUE TITLE
Crop Signs To Fight Against Berry Fields/Berry Munchers!

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#761]
To help designate fields as Crop Fields.... since there are towns with over 60 Berry bushes...berries being very bad foods since the food overhaul and generational food half-life....and a lot of the water goes to berry fields....this water can be used for much more water-efficient crops/yum foods.....

....could you please add Crop Signs?

Here are some examples I made: 
![](https://cdn.discordapp.com/attachments/691122070465019974/705591354650263562/Untitled_5.png)
![](https://cdn.discordapp.com/attachments/691122070465019974/705581537466515487/Untitled_2.png)

Suggestion:

Blank Paper with Charcoal &writable + Touch a Crop = Paper with Crop Drawing

Paper with Crop Drawing + Short Shaft OR Skewer/Weak Skewer (whichever you decide on) = Loose Crop Sign

Loose Crop Sign + Ground + Mallet = Placed Crop Sign 

- Should be walkable/passable (it is a very small sign)
- Could add that the short shaft or skewer be removable from the drawing (to counter griefing).
- Could add the that the paper with crop drawing be erasable using a rubber ball (to counter griefing).

To remove = Mallet? Idk. Shovel without using a Shovel Charge? (It is, after all, a very small sign.)

Thanks for reading/considering! 

-------------------------------------

P.S. If there is an issue of how can the drawing in the Crop Sign be in multiple colors (using a charcoal pencil), you could make the drawing be a Black and White charcoal drawing or just a Crop Sign with the word 'Tomato' instead of a drawing.

- If making the Crop Sign be just the word 'Tomato', maybe you could make it a command? Idk anything about coding, :D
Blank Paper with Charcoal &writable + ??? '/TOMATO' ??? = Paper with Crop Designation

**Comment by Spodnie** [comment]
I think it would be more realistic to make it if we had colored markers. I mean, you can't draw a red tomato with a black pencil.
The idea is pretty nice tho, could be an update by itself. It's not really an issue but a suggestion, shouldn't these be posted in forums?

**Comment by jasonrohrer** [comment]
This is what fences are for.  Fence your fields to prevent the wrong thing from being planted there, and then pass the ownership to the next generation with instructions for how the field should be used.  Leave a paper note inside the fence to avoid confusion, or even a sign, which would be visible outside the fence.

I.e., you already have the tools at your disposal to do this...
