### ISSUE TITLE
Can't recycle Fractional Distillation Tower. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#762]
https://onetech.info/2336-Fractional-Distillation-Tower

Same for Double Cylinder

https://onetech.info/2335-Double-Cylinder

I believe these are the last two of the items that can't be scrapped in game thus being a means to grief.

**Comment by Spodnie** [comment]
If someone wanted to grief iron, they would steal/hide it and not make these two, I guess,
