### ISSUE TITLE
Dumped bowl of...

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#763]
https://onetech.info/4080-Dumped-Wheat-Bowl
https://onetech.info/2731-Dumped-Iron-Filings
https://onetech.info/4105-Dumped-Corn-Kernels
https://onetech.info/2715-Dumped-Palm-Kernel-Bowl
https://onetech.info/2716-Dumped-Crushed-Palm-Kernel-Bowl

I see these are lost in the new update. I think it would feel better to still have them, because dumping and then picking a bowl feels like two actions and not one.

So for example we would right click on a bowl of wheat to get dumped wheat bowl, and then another click to pick the bowl - this would feel much better IMO.

Maybe I'm wrong, just close the issue if you don't think the same, it's fine.

**Comment by jasonrohrer** [comment]
They feel redundant to me....
