### ISSUE TITLE
Attaching bow to arrow quiver

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#764]
Along with the backpack, we also have the arrow quiver. It would make sense to attach the bow to the quiver to free our hands otherwise it's always better to have a backpack than an arrow quiver when hunting people and animals.

**Comment by Sir-Caio** [comment]
This interaction might clash with loading up the bow when clicking on the quiver with it

**Comment by Spodnie** [comment]
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFYAijJe8QQqXP_-NCYu3upFzbf8mB57Qthq0X4xNdogkkK_-6&s

Here is an image of random quiver. I don't think you could attach a bow to this. Not too realistic.

**Comment by voy178** [comment]
The current model is of a backpack, it should work just fine. The reason we don't put bows on quivers is that we have other means of carrying them IRL.

**Comment by jasonrohrer** [comment]
Yes, it is true that it would interfere... you currently click the quiver with the bow to grab an arrow.  Though maybe I can make it so that you can hang the bow on the empty quiver, or click with a full bow to put both back?

**Comment by voy178** [comment]
@jasonrohrer I think the second option if you mean to do it.
