### ISSUE TITLE
Putting back Raw Pie Crust into bowl with dough

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#765]
Too often when I bake with new players they often put all the dough on plates when I'm trying to make the dough rise to make bread.

Allowing us to correct mistakes and fill up a bowl with dough again would be very helpful.

Sometimes plates are needed for other things and often times there are empty Raw Pie Crusts not being used. Maybe we need it for tortillas, who knows? This would also fix that issue.

**Comment by Spodnie** [comment]
Can't you just tell them to not touch it? I like it how it currently works tbh.

**Comment by voy178** [comment]
You ought to know, Spodnie, that new players never listen they just say "sorry".
