### ISSUE TITLE
Carrying one large tool on backpack

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#767]
Since bows and swords can be carried on your backpack I'd argue that there are some tools that also could benefit from it.

**Steel Axe**, we go out in the forest to collect firewood. Most often we can't carry both the axe and the firewood back to town without abandoning one of them. Axes are not larger nor heavier than swords so it makes sense.

**Steel Pickaxe**, as with the Axe going on mining missions would benefit storage. It follows the same principle as the Steel Axe. When mining gold you should be able to take both the gold and your pickaxe with you as we often see in old-timey depictions of the goldrush miner.

Next follows the other large tools that aren't essential but would be nice. 

Shovel might be needed in town, but stonemasons would be happy to be able to carry rocks back with the shovel. With a cart that's four piles of stone if also packing a chisel and mallet. Efficient for building.

Fishing Pole and the Net are also an item we often see attached to backpacks in media and could benefit the fisherman.

The head farmer of a village might need a handy hoe at all times, or freeing hands to carry buckets of water elsewhere with the hoe, saving two trips. Let's not forget that it could also be a signifier for line of work.

Maybe a horsebreaker need the lasso on his backpack on his journey after horses?

The Steel Adze, Steel Froe and Bow Saw don't necessarily need it since it's town-based items, but maybe could be useful if a settlement has to migrate and want to preserve cart space, or also as a job signifier or saving trips to move large items.

**Comment by Spodnie** [comment]
This isn't an issue and shouldn't be posted here, I think you should post ideas like this on forums, so other people could say what they think about this.
I don't really want people being able to carry tools with them attached to backpacks, could be annoying to search them if we had only one shovel or something and someone was having it with themselves.

**Comment by voy178** [comment]
It certainly is an issue as much as going hunting and not being able to carry the bow back. Going for firewood yet only being able to carry either firewood or the axe. Same thing with pickaxes and gold etc.

The submission is valid as an issue. Jason will be the judge, not you.

**Comment by jasonrohrer** [comment]
I see how it's a slippery slope here...

I think we'll stop at the bow.  The sword and the bow are both weapons.
