### ISSUE TITLE
Decaying fences can't be removed

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#768]
I was 55 and had a paper, a bit later two. I even had a helper who was able to understand why to remove bushes and helped me remove fences since I turned 55 right then.
Even with two papers he wasn't able to sign both because the animation time.

We managed to put removal notice on like 7 fences. We would have needed to remove like a whole line and some more on top corner.

It's very confusing the whole thing, he has to sign, I have to sign, it even times out. 

I was able o put removal on the ones that were fixed like 10 minutes ago but I wasn't able to put on the decaying ones.

By the time I told the guy to not repair since we need more space for kilns, he already repaired 3 of them. 

Since if you remove one, you already can go inside, there is not much reason to be this slow process.

The only time it would need more than one to remove when a griefer would fence it up from outside with several layers.  Those will all turn to corner fences if my guess is correct.

So allow us to mark several tiles faster as an elder, like just putting the removal notice on them when one is removed, or at least corner fences and decaying fences. It shouldn't even time out when they are marked for removal, it should stay there longer so elders can mark it, even better, elders should mark first and that would stay on it and prevent fixing them. If by some chance they want to keep it, they could just build new outside of it so no reason to be so strict on removals.

**Comment by jasonrohrer** [comment]
It times out to prevent one elder from removing fences unilaterally.

When you place the notice, the receipt gets stuck in your hand, and then the notice times out faster than the receipt times out.  Thus, someone else must sign the notice, not you.
