### ISSUE TITLE
Kerosene Wick Burner

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#769]
[Kerosene Wick Burner](https://onetech.info/2348-Kerosene-Wick-Burner) can go only to [Wet Newcomen Pump](https://onetech.info/2234-Wet-Newcomen-Pump), which kinda sucks.
Should also be possible to add it to these stages:
[Dry Newcomen Pump with Torn Seal](https://onetech.info/3262-Dry-Newcomen-Pump-with-Torn-Seal)
[Dry Newcomen Pump](https://onetech.info/2220-Dry-Newcomen-Pump)
[Newcomen Pump with Full Boiler](https://onetech.info/2221-Newcomen-Pump-with-Full-Boiler)

**Comment by TwistedHBG** [comment]
IIRC there was a pattern issue where adding a wick burner to any Newcomen Engine (not just pumps) would create a brand new well on that spot. I think adding only to Wet stages was what solved this problem? I'm not 100% sure.

**Comment by TwistedHBG** [comment]
Here's a relevant commit - https://github.com/jasonrohrer/OneLifeData7/commit/b6bc09547bc068d7958dab0b72fff6adc365ec33

**Comment by jasonrohrer** [comment]
Yeah, unfortunately, this is kinda messy to fix, so I'm going to leave it be.
