### ISSUE TITLE
Rubber stoppers don't stack

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#770]
One town I was just in made a bunch a rubber stoppers without enough bottles and it was a mess. Rubber stopper stacks would be very helpful.

**Comment by Spodnie** [comment]
No need to call it stack nor a pile, they are too smal for this. They could be just laying next to each other on the same tile. Just "rubber stoppers".

Would be cool to have it the same with bone needles.
![](https://cdn.discordapp.com/attachments/703011254666526740/706292205635239976/2020-05-03_01_47_44.png)

It's better than wasting 6 tiles next to a sheep pen, or having them in a basket where they are barely visible.

**Comment by DougLefelhocz** [comment]
Copper rods don't stack even though copper ingots do stack.
