### ISSUE TITLE
Inconsistency/irreversible mistake (Straw) 

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#771]
Straw is one of 2 items that can be combined with themselves to craft a new irreversible item. 

With all those stacks in-game someone would consider that combining the same item will produce a stuck of this item.
But Straw+Straw= Basket and it is irreversible as well. 

Proof of the straw stackless inconsistency is that even me that I play from 2018 I got used so much to the stacks that I was aiming to stack straw for compost but I made the 20th useless basket of the town instead. 

could we have straw to stack and use a sharp stone to make a basket?

**Comment by Spodnie** [comment]
Stack of straw could actually be cool and useful.

**Comment by Tarr-OHOL** [comment]
That really seems weird to rip apart baskets for straw. I'd personally remove this before he does something like make the only basket recipe that noob trap one he added.

**Comment by miskas9** [comment]
Tar I have the same fear as you BUT I am willing to risk it if we can have stacks of straw.

**Comment by Tarr-OHOL** [comment]
And I'm definitely not. Jason specifically added a recipe that takes thread and only thread to make baskets. Ripping baskets apart by no means would be worth forcing baskets to take two milkweed each to make. 

I'd rather grow more wheat or collect wild wheat than be forced to make thread for baskets.

**Comment by miskas9** [comment]
Also, another case of an irreversible item is any state of Big Ball of Yarn

**Comment by jasonrohrer** [comment]
BTW, the reason I'm not making the same change for reeds (allowing you to stack them) is that I'd need to change the tutorial.  Want to leave that alone for now.
