### ISSUE TITLE
Feeding mouflon lamb with rope eats the rope

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#773]
It's not shown in onetech and I'm not entirely sure that this is what's causing the issue, because it only happened once pretty quickly. But someone fed the mouflon lamb I came with and the rope I used vanished. Not sure if this happens with regular lamb, piglets and calves.

**Comment by Tipy1802** [comment]
The rope is tastier than the berry carrot bowl

**Comment by jasonrohrer** [comment]
I can't reproduce this.  I'm pretty sure it was fixed as part of this:

https://github.com/jasonrohrer/OneLife/issues/607
