### ISSUE TITLE
Garland Griefing

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#775]
Can you please add the ability to remove garlands from Pine Trees?
(And, if possible, the ability to remove popcorn and berries from garlands? Although, this is a smaller issue.)

In the images below, you can see 5 Pine Trees in the middle of the farm fields that each have 1 garland.

This is clearly griefing and not an action to spread holiday cheer. If it was for Christmas Tree love, there wouldn't be only one garland per tree.

The only way to get rid of these now...is to waste:

Three threads = 6 milkweed stalks (or waste 3 Needle and Ball of Threads to turn them into 'Needle and Thread' 
12 popcorn (2 corns)
9 berries
Have a ginger person for Fractionated Palm Oil
A few Bowls of Palm Oil for Fractionated Palm Oil (how many depends on how fast you are)
12 more threads (24 milkweed stalks) for the candles

And that's for **ONE** Pine Tree with Garland!

For 5 trees, it'll take:
**_75 threads (or 150 milkweed stalks), 60 popcorn (10 corns), 45 berries, at least 4 bowls of palm oil, and a ginger person._**

**Much easier if you can just remove ANY amount of garlands from a pine tree.**

Thank you.

![](https://cdn.discordapp.com/attachments/704224819230670978/706851808441663519/unknown_4.jpg)
![](https://cdn.discordapp.com/attachments/704224819230670978/706852808011546644/unknown_5.jpg)

**Comment by Spodnie** [comment]
I think someone started it on each tree and hoped someone else will finish it. I don't think it was griefing. Someone who wanted to grief, would do other things than actually spend time working on making these garlands.

**Comment by cordy-123** [comment]
Making a garland is easy.
Needle and Thread on popcorn and berries alternately. Less than 1 min maybe. May 20 secs.

If they are able to spend 2 to 6 minutes (1 min x 6 pine trees), they can do the rest of the garlands and start on the candles.

Definitely griefing. Why does EACH of the trees only have ONE garland each?

**Comment by jasonrohrer** [comment]
Isn't the problem that the trees are stuck, and can't even be removed without making the rest of the garlands and candles?

I.e., it's unchoppable until it's finished.

But yes, I'll let you remove them... that will at least let you consolidate them on one tree if you want.

**Comment by Spodnie** [comment]
Oh, yeah, if these trees are irremovable then I think  that could be the reason why someone did it. Just look how much better this town looks with trees, possibly someone just wanted to decorate the town with trees without worrying someone else would cut them off.
