### ISSUE TITLE
"Weak" players skew the minimum required participants for a Pose.

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#777]
If your last life was a short life then you are not counted toward posse size when you join a posse.

but what if the village has 10 pop and 6 of them have short lives. 
the min pose participants are 5 but only 4 people can count as participants. 

Short life players should not count in the total population bring it down to 4 so a pose can take place.

Also upon starting a posse, an indication +strong+ on the heads of other players would be helpful for the initiator to look for those people and persuade them to join him. 
(it is no use to try convince a player only to find out that he is not counting to your pose afterward) 

PS: /kill reveals the strong members of your community

**Comment by miskas9** [comment]
+strong+ could also appear for everyone instead of only the initiator whenever a pose is initiated.
this way might seek protection from the +strong+ members of their community.

**Comment by Spodnie** [comment]
+strong+ idea is pretty good. But with 5 posse cap I think "weak" people system is now obsolete and could be removed, idk.

I still won't use it tho. 5 posse cap makes it almost impossible to find enough people. In most cases people join posse only when they see someone griefing with their own eyes.
I will just curse griefers and ignore them having hope that they won't do too much damage.

**Comment by Spodnie** [comment]
Changed my mind, "weak" system isn't obsolete, because people would /die to spawn in the same family, which would make it only harder to recognize who is good and who is not.

**Comment by Spodnie** [comment]
Last time when bobo's team attacked brown people, he was a black person and had 2 mates - one black and one white - it was easier to recognize that they are bad. Maybe it should require less people in posse to kill minority race/family in the area?

I was also thinking maybe if leadership update was somehow improved that we would actually start following people and choose our leaders, it could be easier. But improving leadership wouldn't be an easy task I guess. How would people know who to pick as a leader...

**Comment by jasonrohrer** [comment]
This has changed a ton, now that leadership and allies determine posse size.
