### ISSUE TITLE
stacking baskets

### ISSUE THREAD

**Issue by Fiftyllama** [jasonrohrer/OneLifeData7#78]
when spawning as an eve i tried stacking some baskets and they turned into a pile and the baskets cannot be retrieved, i managed to reproduce it in the tutorial.
this was in 175
![bug](https://user-images.githubusercontent.com/45442346/49262908-5b33b600-f440-11e8-9e2a-624ce6e4204d.png)

**Comment by ryanb** [comment]
This has been fixed in v176.
