### ISSUE TITLE
Mushroom effects don't wear off if you disconnect 

### ISSUE THREAD

**Issue by Nika50501** [jasonrohrer/OneLifeData7#782]
Mushroom effects don't wear off if you disconnect and reconnect while you have the effect applied to you, even after you die and get reborn.  Closing and opening the game clears the effect.

**Comment by Tarr-OHOL** [comment]
This is intended.

**Comment by Nika50501** [comment]
Why is that?

**Comment by jasonrohrer** [comment]
How do you know that you really disconnected?  Or that you really died?.....

**Comment by DougLefelhocz** [comment]
> 
> 
> This is intended.

The game is public domain.  It's not intended by the public to have this sort of longstanding bug.

**Comment by Tarr-OHOL** [comment]
> > This is intended.
> 
> The game is public domain. It's not intended by the public to have this sort of longstanding bug.

Why are you making nonsense posts nearly seven months after a thread is closed?

**Comment by DougLefelhocz** [comment]
> 
> 
> > > This is intended.
> > 
> > 
> > The game is public domain. It's not intended by the public to have this sort of longstanding bug.
> 
> Why are you making nonsense posts nearly seven months after a thread is closed?

The game is public domain is a fact.  I do find it likely that the public would think this an issue if they kept in mind that the game is public domain also.  So my comment does have sense to it.  It being closed only reflects what one person thinks.

But hey Tarr, if you want to disempower yourself and say that you can't determine what is a bug and what is nor *for a game in the public domain*, that's on you.  I've now tried to tell you that you have as much right to determine what is and what is not a bug as anyone else.  If you want to cede your decision making ability to someone else, that's on you.
