### ISSUE TITLE
Stack matching shoes in pairs or more

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#783]
Shoes are items that we often like to have in pairs. I believe it would both save a little space and make sense to stack shoes of the same kind together when not in use. Say clogs or old boots, etc. 

Having to find empty tiles for every item when you loot a corpse can be taxing in crowded spaces. Nowadays, people often craft shoes and wear matching pairs. Allowing us to stack matching shoes would save a little bit of frustration seeing how small those items are.

**Comment by jasonrohrer** [comment]
There's actually a decent reason for why they're not stackable...

Each shoe has its own age before becoming a rag shoe.  They're all on separate timelines.  There's only one time variable tracked per tile.  If you stick two different aged shoes together, the separate ages of the two shoes wouldn't be tracked.
