### ISSUE TITLE
having a lot of "Two Rubber Tires" and we aren't able to pile them up. 

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#785]
we usually produce them in Bulk and it would be nice to pile them up. 
I speak about piling them in Pairs as a single rubber will stack with another one.

**Comment by jasonrohrer** [comment]
Yes, this is a reasonable idea, to pile them in pairs.

Though it might be confusing if you try to add another single tier to the pile and cannot, right?

Hmm...

I think there's a way that I can do it... i'll just have to bypass the pile pattern and do it manually.
