### ISSUE TITLE
auto orient doesnt allow horse parking to be build in fence property. 

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#787]
The reaction Amilu speaks for itself.
We wanted the royal fence to have its personal horse so we can send explorers for oil whenever we want to but....

Property fences must not auto orient anything else than property fences.

]https://i.ibb.co/pjkG3V4/fence-issue.png

**Comment by jasonrohrer** [comment]
Yes, I see this problem, hmmm...

It really is best for all these things to auto-orient other things, or else their are ugly visual gaps.

I will add a way to designate a "hitching post" in this situation, so that you can "force" the fence to go back to horizontal.

**Comment by miskas9** [comment]
hitching post will work, thanks!
