### ISSUE TITLE
Cache issue?

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#788]
<img src="https://i.imgur.com/uqAJm0x.png" alt="text">

after a life lived, I get an update, cache refresh then says the server is in process of updating, so basically I need to restart client every time I die or suicide

it happens since version 336, not sure why data version number wasn't updated to 336, I manually edited from 335 to 336 still does this

**Comment by jasonrohrer** [comment]
Is this on or off Steam?

**Comment by jasonrohrer** [comment]
I'm pretty sure this is an isolated issue.  Please email me and we'll diagnose the problem:

jasonrohrer AT fastmail DOT fm

**Comment by laccy** [comment]
off steam awbz full version, had no problem until the update
someone else on discord had the same thing  (guy name abcdefg)
