### ISSUE TITLE
Gates tap out, noobtrap, consumes shaft

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#789]
I was placing some gates since they got to be first if they going to be sideways

first I placed it L jump 2 tiles right then 1 down

when I placed shaft on one it tapped out the other, I thought I just forgot, so I did it again, after the third shaft lost I realized the issue

when fences tap out the others, it should drop the shaft no consume it, similar to mallet hit, I guess that's a simple edit since you got the transition already

<img src="https://i.imgur.com/N53u2e5.jpg" alt="text">
plan was this, the L jump is too close on the right

**Comment by jasonrohrer** [comment]
Ah, good point!
