### ISSUE TITLE
Plucked turkey can be worn as a hat

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#792]
This silly feature has to go. It's unrealistic, dull and serves no purpose.

https://onetech.info/2182-Plucked-Turkey

**Comment by jasonrohrer** [comment]
Really?  It was a bug introduced many years ago, and people loved it, so I adjusted the position of the turkey to make it look good as a hat, and left it in.

Fruit Boot is similar (there was a bug that allowed you to wear fruit as a shoe long ago).
