### ISSUE TITLE
Unable to instantly remove geese from partially full ponds

### ISSUE THREAD

**Issue by Smackum** [jasonrohrer/OneLifeData7#8]
I killed a goose in a half full pond. I then could not remove the arrow. I shot another half full goose pond and couldn't take the arrow out. I could not interact with it at all, couldn't remove the arrow, goose, or draw water.

After a couple minutes, I was able to take the arrow from the goose, but not the goose from the pond. Then several minutes later I was able to remove the goose. 

This issue does not affect full ponds.

![20180428124345_1](https://user-images.githubusercontent.com/38818650/39400400-5f404476-4ae4-11e8-9aee-a452b1b6eed2.jpg)

**Comment by jasonrohrer** [comment]
Can you check if this issue is still present in the most recent update?  I posted an update this morning that fixed some goose pond stuff.

**Comment by Smackum** [comment]
I checked the ponds at every water level and they worked flawlessly.

**Comment by jasonrohrer** [comment]
Thank you!
