### ISSUE TITLE
Last use chisel transitions

### ISSUE THREAD

**Issue by ryanb** [jasonrohrer/OneLifeData7#80]
Not sure if this is an issue with onetech or OHOL. There appear to be several last use chisel transitions which are incorrect.

<img width="405" alt="screen shot 2018-11-30 at 12 00 36 pm" src="https://user-images.githubusercontent.com/161/49312073-d1afd280-f497-11e8-9283-d9536da507af.png">

These are generated with transition `455_932_LA.txt` which results in a broken steel tool when the chisel is applied to a variety of objects. The new target is empty ground so the object disappears.

**Comment by jasonrohrer** [comment]
This is working on my end.

Check for category @ Weak Chisel Breaker

The category is both the target and new target of the transition that makes a broken chisel, so whatever object it filled by (file blank, ingot, etc) remains in place after the chisel breaks.

**Comment by jasonrohrer** [comment]
Oh, I see that it's working in OneTech now...
