### ISSUE TITLE
Cars are dead content, using them is considered as griefing

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#800]
In real life it's possible to drive even 800 miles with only one tanking, some cars can go over 1000 miles
https://www.express.co.uk/life-style/cars/1127043/petrol-diesel-fuel-tank-how-far-most-popular-cars/amp

It would be cool if cars required only one tanking per car in OHOL. It's not like this change would make us have many cars anyways, they would be disappearing anyway, just like it happens with horses, and we couldn't produce many of them anyways because of how much iron they cost.

Please, make cars can run permanently after only one tanking.

**Comment by Arcurus** [comment]
pein mentioned in the forms that cars would need the following buffs to be reasonable to use: 

I hope i remember them right:
The refueling needs a buff. The engine is to easy steal-able and the speed to low.

He suggested to buff them, but limit them to roads (or make them slow off-road).

I would also say that horswagens are currently quite to overpowered compared to other means of transport. They can cross different biomes, they dont need refuel (or?), they dont slow down if loaded with tons of stuff. I dont even know if wild animals are a threat. Crossed close by them that often with horse and up to now did not get an wound once.


I would suggest to give them a nerf with having to eat once in a while to have the full speed and lower the speed if with a full trailer. As an balance the run away time could be doubled.

Also the babel fish people could get some horse buff like movement speed with horse and car X 1,2
then at least they would have something.

**Comment by jasonrohrer** [comment]
I'm not going to tackle horses just now, but I will make cars more usable.
