### ISSUE TITLE
Mine carts are dead content

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#801]
The good things:
-now they can turn
-they can store some items
-hard to remove so it can function as a corner piece for pens (kind of weird one)

The bad:
-expensive on iron, quite long to make
-slow and still requires manual working both sides
-unbalanced: since it is made of wood and iron, it supposed to be able to handle way more stuff, i get that now multiple carts can be placed, still its quite weird to use them
-can't stop it anywhere (i haven't tried it, supposedly they can be stopped by clicking on them now, but that requires manual interaction and that makes worse than wheelbarrows and handcarts since those arent limited to a path)
-the path needs to be fully fixed, finished, or its unusable, hard to extend it 

Possible solutions:
-increase the capacity, 8 or 12 would be needed at least to make up for the inflexibility and slow speed
-give extra abilities like they could have crates in them which would function as baskets when needed, or as large slots when not needed, maybe ability to carry specific items, like large whole stones
-auto-defacing bones. putting bones on carts would be possible, disposing of them this way would always forget the names of bones and able to dump them out easier, kind of a boring thing to mark bones, also uses a slot so nobody ever bothers to get rid of old bones.
-link it to tech, maybe building a mine cart into a mine, would be a requirement for gathering iron or other resources, or just auto dump the mined resources into them so you dont have to put down pick and move it each time you mine it (with a good yum its possible to hit like 5x but you cant cause you got to move the iron first)
-levers: a metal rod that you can attach to any of the rails, it would stop the carts on that position when turned off, and allow them trough when turned on, allowing stops without an instant manual interaction, this would allow spacing out camps, and provide temporary work stations and setting up a chain of work near them without multiple single rail systems and re-stocking different carts
should be cheap, maybe a few of them for a steel bar
-similar but more expensive: end break
would allow being an open-ended rail system, and extend it later, carts would stop at it, and it could be moved forward or backwards as needed, to control the distance the carts go and prevent them from getting destroyed. most cities can gather only a certain distance away, generally depends on the age of city, population, if they got horses and carts. tends to be around 50ish tiles, after that, it takes longer time to bring back resources so people don't really do it, a rail system would help with gathering firewood and go further and further out as needed. bonus would be dumping bones and other garbage on the way back.
-automatic loading and unloading: the end of lines could unload the items inside the cart to a machine or a simple floor tile so people could send it back or a lever that would send back the carts after they are empty. A loading crank or dispenser that would load the stacks placed near the rail onto empty carts. This would allow automatic/semi-automatic work modes saving time. People could move resources to outpost stop gaps then it would collect it to deposits over time.

The best use for them was gathering firewood and getting rid of bones on the way back.
Since it won't automatically load in and back, it requires people both sides and walking there is kind of same time as pushing it with a message or filling them and sending it back. Right now they are an expensive toy with no proper function.

**Comment by miskas9** [comment]
A cart costs 0.056 iron per 10 hours , 0.43  in 76 hours.
A Track cart costs 1.068 iron + 1 iron for every 6 tiles of rails.
