### ISSUE TITLE
Dead bones management,  instead of marking to erase Name, mark to keep it.

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#802]
Marking every bone with a pencil just to through them in the garbage is busywork. 
this busy work is better to affect only those who will actually make a grave from these bones. 
If you care about the name of the dead and make a grave for him you would not mind do this busywork. 
But if you don't and you just want to through them away is tedious.

**Comment by TwistedHBG** [comment]
Marking removes the name data which allows you to put the bones in the cart. There is no way to put bones in a cart and preserve their name data.

**Comment by jasonrohrer** [comment]
Yeah, this is working as intended.

In general, the names and data SHOULD be preserved by default, because then it creates a sense of history to a place.  Even if people casually move bones to one area to get ride of them, walking over there and seeing all the names and times is interesting.
