### ISSUE TITLE
Food bonus for brand new players?

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#806]
I noticed big decreasement in players population lately. I think food changes are too harsh for new players, and people yelling at them "Don't eat damn berries". We don't have time to teach them farming or whatever if we also need to feed them with yum foods.
I don't want players population keep decreasing, I love this game and I don't want it ever dies out.

Could we have a food bonus for brand new players? Like +5 for every food, just for a first few games, not sure how long it should be, probably the same as when they sending to their mothers brand new player notification.
It could be a temporary solution, before you make this game a little bit more newbies friendly.
Is this a good idea?

Recipe book, just like the mobile version of this game has, could be very useful for new players, so they can keep being entertained and experiment with things.
Would be cool if you downloaded mobile version and checked how it works. It could be an update by itself in the future if you like it.

**Comment by Spodnie** [comment]
I'm not sure actually if this is a good idea with this food bonus, but making the game a little bit easier for brand new players maybe would work, idk.

**Comment by jasonrohrer** [comment]
The population hasn't been going down any faster than usual.

https://steamcharts.com/app/595690

I did see Twisted planning to tear up berry farms and make a small private berry farm, so that is good.

**Comment by Arcurus** [comment]
> I did see Twisted planning to tear up berry farms and make a small private berry farm, so that is good.

lol, actually thats bad, started to make a berry saving revolution, even with the gated berries there where near no berries for sheeps, or yumming. Not to mention the noobs who only learned how to eat berries and now simply starve to death....
