### ISSUE TITLE
Cooked Rabbit, Goose, Scrimp and Fish can't be prepared in an oven inconsistency

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#810]
Ever since we got Turkey and roasted Palm Kernels, it stopped making sense that Cooked skewered food items were limited to hot coals when in reality they could be made in an oven to the same effect as proven by Cooked Turkey. Pies, Palm Kernels, Potatoes and Rubber items all get cooked instantly, but we can't cook the skewered items in the same way which makes no sense. Even better would be if a skewer weren't necessary to cook it in an oven since other meats do not require it (except for Shrimps). There is no balance needed since most of the items fade out in terms of usefulness after a few generations.

Having them still available as rough starter foods over hot coals still work in early civs ofc.

Boiling foods and liquids still makes sense over hot coals until we get a tech upgrade stove.

**Comment by Spodnie** [comment]
I like the way it works now, would be too easy if we could cook these foods in hot adobe. The only thing that I don't like is waiting 1 minute for hot coals.

**Comment by miskas9** [comment]
Is it time for a new Iron Grill oven that would bake pies , rabbits, and BEEF? 
https://sea.banggood.com/Multi-function-Stainless-Steel-Fish-Grill-Oven-Out-Door-Grill-Oven-Camp-Grill-Furnace-p-1061440.html?ID=43904&cur_warehouse=USA

**Comment by voy178** [comment]
You are notably conservative, Spodnie. It's a tech upgrade, ofc it should be made easier especially so since there is no real-world explanation as to why not. If Jason didn't want things to get easier with tech upgrades he would not have given us dough tables e.g. which makes burritos and tacos a breeze.

**Comment by jasonrohrer** [comment]
An oven slow-cooks things, and hot coals fast-cook things.  Like broiling vs roasting?  That's supposed to be the distinction.  The skewer foods are in general smaller.  You can't cook a turkey over hot coals, for example.... the outside would burn before the inside got done.

A goose is a stretch, but that's the only one.
