### ISSUE TITLE
Newcomen Machines are too quick

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#814]
If you won't remove the scrapping of an engine, can you at least increase the time any newcomen machine will work for from 20 seconds to anything longer, so that we won't need to use say the bore multiple times because we can't get a dozen pistons in 20 seconds.

**Comment by DougLefelhocz** [comment]
> so that we won't need to use say the bore multiple times because we can't get a dozen pistons in 20 seconds.

I think that was supposed to be 'hammer' not 'bore.

**Comment by jasonrohrer** [comment]
The run-time has been the same for... a very long time.  I'm going to close this for now, unless I heave a bunch of complaints about it.
