### ISSUE TITLE
Scrapping Engines Doesn't Yield A Single Iron

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#815]
You said earlier:

> Why not give people the option of getting the iron out of it to use in other things?

But, it's simply not true that a single iron comes from scrapping an engine, and for the record, an engine is not made of purely steel parts.

**Comment by laccy** [comment]
Lol, exactly one iron :D you will save one piece of charcoal by destroying an engine :D or do you? since it's scrap which needs reheating, while steel does not, so it's negative 2 charcoal just to convert to steel.

Spoonwood go drunk you home.

**Comment by jasonrohrer** [comment]
An engine is made from 17 steel and 1 iron (for the fuel tank), but it gives you 18 steel when scrapped.  You get the rubber belt back.  You should also get 1 piece of scrap iron back and 17 steel.
