### ISSUE TITLE
Cooked Goose on Plate counts as unique Yum food and can't make Oiled File Blank with it

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#816]
Nice that we can, but really shouldn't all meat should require a plate if we were going for consistency because how is cooking mutton with your bare hands different from cooking a goose with your bare hands? But whatever it's not the issue here, it's the extra YUM and lost function of the Cooked Goose as Steel File ingredient.

If we were forced to remove the Cooked Goose from the plate (alternatively not require it in the first place **or or or** just require the skewer if we can't touch it for whatever reason) we would avoid the unique YUM food and the Cooked Goose could be used for Steel File Blank to make Oiled File Blank.

https://edge.onetech.info/518-Cooked-Goose

https://edge.onetech.info/4197-Cooked-Goose-on-Plate-contFoodDish

Thanks for adding it to the list of oven food anyways, it's appreciated.

**Comment by Spodnie** [comment]
I don't like being able to cook geese in ovens at all, but I guess there is no going back once something was added.
At least make it the same yum type for both cooked geese types, pls.

Better be careful what issues you are reporting voy, we may get cooked mutton on plate without being able to remove it from the plate and we won't be able to contain them in slot boxes anymore.

**Comment by voy178** [comment]
You can still insist on using hot coals, Spodnie. No one is taking away your precious hot coal foods, just adding alternatives. The sky will not fall down, I promise.

**Comment by laccy** [comment]
eating it could leave an oily plate and that would be used for files, that's not something you always need.

also add dishwashing after eating so desperate housewives got something to do :D

**Comment by jasonrohrer** [comment]
Yeah, that's true about mutton.

I'll get rid of goose on plate and just allow cooking directly in oven (and still on coals).

**Comment by jasonrohrer** [comment]
The logic for why goose can be cooked on fire and oven (the only food that you can do this with) is that it is a medium-sized food that could go either way.
