### ISSUE TITLE
Cars need new fuel source

### ISSUE THREAD

**Issue by Lava6** [jasonrohrer/OneLifeData7#817]
Running kerosene is not worth it considering that it could be converted into 6 iron or four water. A fuel source likely a byproduct of kerosene would see the use of cars.

**Comment by laccy** [comment]
Yes, diesel oil and benzine are byproducts of oil, kerosene is much cleaner. If there is no conflict, the stacked up "petrol" could be only used by cars so eventually would be used up by cars (and please put an inner tank on cars, no reason to go out with a car without kero now, so it's a one-way ticket to lose it, another noob-trap)

**Comment by jasonrohrer** [comment]
I think this is okay for now.

I do want there to be trade-offs.  If I give you some byproduct of oil refining that piles up if you don't use it in a car, then there is no trade-off.

Horses are obviously still OP vs cars.  I'll fix that in the future.
