### ISSUE TITLE
Ovens are very vulnerable to griefing

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#819]
About one of the simplest yet very annoying things a newbie griefer could do is to add an Adobe to an active Adobe Oven in the kitchen. The process of removing the new Kiln is to bash it with a Pickaxe and waste a bowl of water, and the turnout is one Adobe thus forcing you to find another Adobe to recreate the Oven. 

If the process of removing a kiln consisted of two steps with a Pickaxe, e.g. Kiln to Oven to Rubble, we'd save a lot of time and Griefing it wouldn't be as fun or obstructing. Getting an Adobe for downgrading a Kiln shouldn't be necessary since we wouldn't be getting more than one if we destroyed the whole Kiln anyways.

**Comment by voy178** [comment]
If we wanted to balance the damage done to the pickaxe, maybe split the current cost and redistribute it between the two steps.

**Comment by Lava6** [comment]
Your wrong and this isn’t an issue when destroyed your left with two adobe. You can literally rebuild it immediately.

**Comment by TwistedHBG** [comment]
Yup, Lava6 is right, you get two adobe back from both ovens and kilns, this was changed in one of the recent bug fix updates.

Kilns only give you back two adobe even though they cost three, but I don't think that's that big of an issue (although it would make sense for it to give 3 for consistency's sake, maybe).

**Comment by voy178** [comment]
I don't like to clean up after griefers and I don't understand why you would belittle me for it.
We get to report things that are disruptive, Jason decides what is worth his time and what he wants to do.

**Comment by Spodnie** [comment]
This happens rarery and is easily fixable... Just use a pickaxe and rebuild it. Not worth wasting Jason's time for issues like this.

There are so many things vulnerable to griefing... For example someone could steal something, it would actually do more harm than repairing an oven.

**Comment by jasonrohrer** [comment]
Well, it is true that it wastes one adobe to do this.  I will fix that.
