### ISSUE TITLE
Chests with lock are unbreakable but unusable as common storage

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#82]
Chests with lock or any storage with locks is the best solution for griefers in my opinion because if a griefers wants to block an entrance with a chest with lock we can locksmith it and break it and on the opposite if he wants to destroy all the chests we can put a lock on it

But they are unusable as common storage because they get locked each time they get closed and leaving the chest open is not an option since someone is eventually going to close the chest which will lock it and make it unusable

If it would require the key to be locked then we could open and close it without needing the key and having locked chests would still be possible

Would be nice also if we could recycle the key or turn it into Lock and Key Parts

**Comment by jasonrohrer** [comment]
Well, the point is that it locks.  It's not supposed to be an invincible chest.
