### ISSUE TITLE
The game lost the goal and the interactions at high level

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#821]
The general trend of the game lately was losing the value from player time/work/interaction.

Iron change: eliminates exploration.
Water nerfs: while newbies had a minimal value due to fixing bushes and that could be used for feeding sheep, now they eat way more than they produce and since water is so scarce, the optimal use of it (stew, pies, upgrades) is more important than keeping players working.
Not enough static activities. Maybe pottery, board cutting and stew can be a decent equivalent of getting the resources for a chain of work, the rest of the things can be done in seconds if you got the resources. Generally, the fun part is using resources, not gathering them. Build an adobe house? no adobe. If you get adobe, others use it, that's not fun.

Farming is interactive, it has a timer, some plants even need a constant watch, like carrots, cabbage.
Compared to that, building a house is really simple. too simple even. It does not require much effort, time, just the resources. 

Players became better at the game and no challenging activities are possible. Everybody can smith or make a pen. even a lot more players are able to make oil or engine, the slot limitations prevent that only.

Food is in a good state but everything else is quite a lot nerfed directly or indirectly.

Compost making became water negative, and the soil made requires even more water to be used up, so making too much compost is bad, that was an activity that assured long time survival, generally, even mediocre players survived 9 generations after me, the compost lasted that long. 
Right now you are lucky to have enough water for pies.

Resources fixed amount, outposts are hard to make, everything keeps you at home, forcing to make food and raise kids. People who liked different playstyles are punished by the updates.

Lives are cheap, even cheaper, when slots run out, a lot of players suicide. It's not really an accomplishment anymore to reach 60 years. 

Water is low, middle and top-level resource all the time, means that having no water affects low-level activities. Lo of players do not care where they got the resources from and do not care using it sparingly, but keeping a family alive a bit longer is all about sparing. 

But there are no gates or checkpoints to tech level. While rubber, oil is unknown and can't be planned for it surely, the only thing sure is that the food values go down, water runs out and survival is harder. It feels like we supposed to be motivated by fear of death, that we just trying to stay afloat, while we getting closer and closer to death. 

The engine griefing and stealing is also demotivating for players, hard to motivate yourself to spend a life on it, when it's a matter of seconds that someone will ruin it. And with the disassembling and theft, once your town dies, regardless of how good it looks, it will be scavenged if it doesn't have an engine and kerosene. At least back before, we could build a town that gets used for many centuries even if ou family dies out.

Anyway, it's just a really depressing premise with no win condition, goal or hope that you beat the game and start with a clean slate, 

Generally, I run around the city as a kid, check which tech level we are, dos the town need any tools or did anyone left a job in half. This might work early game, later stages it's just food, which I don't like to do myself, I help to gather for it, but I try to save slots for building and organizing.

Lately, I wasn't able to tell others what they should do. If there is no water, they should get water. But that is a high-level activity and if they have to ask, they won't be able to do it. 

So my issue is: there aren't many activities that create a profit for the time and work invested, that would create a profit. Most jobs use resources so the gathering is way too much needed, but for veterans, processing takes seconds, there is not much reason to give others a job hat you could do alone, other than keeping them occupied, which isn't really helping , its just masks the problem. We need people to be able to be useful, even without knowing what they have to do, following simple instructions they should be able to save time for veterans. Some sort of creating something out of nothing.  Running machines, rcycling resources, any activity that would be needed but one player wouldn't be able to do it. Even if it has timers, like farming. 
For example wood cutting could be a longer process but yield more resources.

**Comment by Arcurus** [comment]
design wise there is no cost other then movement and hungry work, dont know if making activities take some time makes it more boring?

Was thinking about some kind of exhaustion, like if you cut wood / do hard work you get exhausted instead of needing food. the exhaustion goes then slowly down. This would help not so skilled players, because a skilled player can simply YUM to do all the hard work.

**Comment by laccy** [comment]
well, food is upkeep, I feel like we are on an okay spot, I would prefer multiple small chains to 10-15 that would show better how much food your town has, and able to constantly produce, would remove to need for unique food, since it wouldn't matter how you get 15 stacks, only to have it covered for everyone. that would be a nerf to yum, so base values could be a bit higher to compensate for the loss, also to provide a decent timer between eating, lot of portable foods lost their value by not being yum, maybe a mutton pie could be yum for each bite, or at least 2 stacks, so it compensates for the long process of making it.
Alternatively, you could stack up to 15 and get a special action, like an ability to upgrade something, but you lose your stacks. That would be fine because you could restart the yum chain. Like a super hungry work that can only be done with a full chain of 15. This reset would provide a new way of players being useful. Yum up and use your special ability to upgrade things, this would make the number of people more valuable since you can't get more than 3-4 chains completed alone, easily.

exhaustion sounds a good alternative to the stamina bar. then it would make sense to ask others to do a job while you organize and gather. there could be stuff like washing clothes or maybe clean up, things would get dirty and start to decay but you could decrease timers by cleaning them. Tree cutting could be a longer process, a tree could have more phases and the world would be a bit more alive. They could automatically grow to a bigger size, in shorter time, then dry out and leave seeds to plant. That would be heavy workload for the server, so maybe only the ones that are inside homelands and saw in last x minutes. Chopping trees could be slower, the axe could have a slow animation and two-person saws would be faster. After chopping it, it could be that you either use a minecart or a cart, it wouldn't fit in normal carts until further processed. First, you would clean off branches, then cut into logs, and further cut into firewood. Feels abnormal that you get a single shoe out of a whole tree. If a big tree would give 2-3 butt logs, managing forests would be more interactive and skilful. ou still would need to replant them and cut the right time, but you would have more resources out of it. And of course more uses for boards, like board walls and furniture.
They could even decay slowly.  Decayed wood could be repainted or chopped up for firewood.

Big saws could use 2 persons to cut a tree faster, I guess it would need some engine changes, maybe one player would become stuck in animation and the other would click to cut the tree faster.

Timers don't need to be huge, you grow a carrot for 5 minutes, cutting a tree for 30 sec and 10 sec with a saw would be decent if the return is better.. Also would allow higher-tech like chainsaws that are instant but require some oil byproducts to run them.

**Comment by jasonrohrer** [comment]
This isn't really a bug or issue.
