### ISSUE TITLE
Cars need a built in tank

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#822]
Right now, most people use cars once. They fill it with a single charge of kerosene then ride it until it stops. Then they need to walk back to get more or leave it. Most of vets realized they need to put a kerosene tank on it, but that takes away a slot and not a guarantee that it gets back.

There are rare situations where you got a predefined A and B point to go from, city to city. So it doesn't matter how far a car can go. It should stop before it gets too far from a "petrol station". We don't have enough tech to build out refilling stations so the cars should be easier to handle by new people.  

Losing cars was the number 1 reason why people don't make them. Generally, one noob rides away with it and you can never find it.

possible solutions:
-GPS, the cars should signal their locations like bell towers
-Reserve tank: Cars should signal if they don't have enough kerosene to return, even forcefully stop or turn back, or a way to run them very slowly backwards to safety
-Keys: cars would need a way to prevent noobs from accessing. even horse thefts are annoying, cars need a better way of keeping away from unskilled hands.
-Stopping the engine: when used as a travelling device, there is no need to run the engine after arrival. When used as a gathering tool, there is no need to run the engine while loading or unloading. 

Time-based engine won't work, I can be 2 or 10 minutes, doesn't matter, it's wasting resources so it's hard to find a purpose when it uses more resources than it generates.

either distance-based travel or stopping and starting engine.

Another way to prevent losing cars: they should only work on connected roads. This would make roads more important and someone would find them eventually. A town with a small road would have less benefit but less risk of losing it, Connected towns would have better use of it, fast and convenient travel, but they would need to make the investment on the road system.

Removing engines so easily is still a dumb idea.

**Comment by Arcurus** [comment]
cars could have a trailer like the horse wagen then you have lot space for fuel.
i like the idea with cars for roads, they wont get lost that easily. maybe just make them very slow offroad.
Why not apply ownership to cars, horses and engines? Now they are quite easy to steal.

**Comment by jasonrohrer** [comment]
The second tank is an unsatisfying solution to this problem.  It essentially makes the car run twice as long for 2x more fuel?  Or serves as an idiot-proof function, giving you a warning before it runs out of gas completely?

I imagine that most people who know enough to build a car will bring extra fuel along.
