### ISSUE TITLE
corn feed can be stored and stacked but not the Berrycarrot feed. 

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#823]
Mashed Berrycarrot bowls are used in Great quantities but still, they can't be stored or stacked in great quantities.

wool, compost, rabbits, cooks. all need their mashed berrycarrot feed.

**Comment by TwistedHBG** [comment]
This issue goes hand in hand with https://github.com/jasonrohrer/OneLifeData7/issues/808
