### ISSUE TITLE
Inconsistency with tree types

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#824]
I was suggesting pines to become non-hungry work since they don't have branches. That allowed to farm them for easy firewood and logs, even as a kid.

There are two more trees that don't fell in the category of griefing so cutting them shouldn't require hungry work.

Dead trees on the desert provide no branches, and there is no reason keeping them, planting them, they are dead, their only purpose is firewood and logs. 

The other one is sealed slashed rubber tree, after you gain out the latex from it, they can't be cut again so they have no value other than providing cuttings. But that's a good mechanic that players need to keep one only for cuttings, and the rest can be cut anyway, even going a bit further for a few seeds won't be that complex so I see no reason of not cutting them.
Also, griefing them that way wouldn't be too logical since you need a bucket to fill and you need to wait and only cut after that, so basically you do valuable work for others and cutting out a full jungle would ned too many buckets and too much time, so it wouldn't be effective trolling action. The bucket filling can be already done so the cutting part is not only advisable but required if you got limited space and you want a rubber plantation.

Also makes sense logically: when you drain a tree, it dries out and it's easier to cut.

These two trees are biome locked so won't affect everyone, but still, good resources when you visit others. Old towns got an area of 50ish tiles without any tree, and sometimes these trees are sitting there, an easier cutting would make it a valuable resource that other races can help out you with.

**Comment by jasonrohrer** [comment]
The dead tree is a good one.  The tapped rubber tree makes some sense too.

As long as there is some logic behind it, I'm fine with it.
