### ISSUE TITLE
Cant empty a full Feed Mash Bucket without cluttering 6 bowls.

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#825]
ether make it stack on the ground OR make a box with Feed Mash.

**Comment by Arcurus** [comment]
there is a logic error in the Feed Mash Bucket transitions:
A bowl of carrot and Berries cant smash itself, maybe berries can, but a carrot is quite solid, so this transition should be removed.

**Comment by jasonrohrer** [comment]
Arcurus, obviously, it works that way to avoid combinatorial explosion of dealing with both mashed and unmashed bowls.  Once dumped in bucket, it all turns to mush.  That's okay, I think.

I do see how you could use this as a short-cut for other things, like rabbit bait, pies, etc.  The pies is kinda gross, but it's also hilarious (pies from a bucket of slop).

Miskas.... it doesn't really make sense to dump a pile of mashed stuff on the ground and scoop it up later.  You can't dump the bowls on the ground.  That's what the bucket is for.  This stuff is sloppy and wet.  I don't think we need another thing to store it in besides the bucket.
