### ISSUE TITLE
Ball of yarn

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#827]
https://github.com/jasonrohrer/OneLifeData7/commit/8ebce8a7842605c38c41b5064349af8ee223c228
That's cool, but what we usually need are balls of thread.
Could we also split Small Ball of Yarn into balls of thread, please?

**Comment by miskas9** [comment]
yes, that would help a lot.
Yarn is useful only for shrimp Nets cause the Wool clothing is the worst option in terms of Insulation/water/Time efficiency.
