### ISSUE TITLE
Freestanding Newcomen Foundation is unremovable and blocks movement

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#83]
There is no way to remove the Freestanding Newcomen Foundation once placed, and that could be problematic considering it's very easy to place down a block and block movement through that tile forever.

A way to remove it (perhaps by using a tool such as the mallet on it) would be much appreciated.

**Comment by Dodg-e** [comment]
same for the Fractional Distiller

**Comment by trevorhackman** [comment]
Same for the Partial Spark Gap Transmitter and Partial Macaroni Receiver. If not movable, then they should be deconstructable.

**Comment by jasonrohrer** [comment]
The freestanding foundation was fixed a while ago.

Fixing the other things now.
