### ISSUE TITLE
Can't remove chopped tomato from plate

### ISSUE THREAD

**Issue by gsamsom** [jasonrohrer/OneLifeData7#831]
People are able to cut tomatoes on a plate which starts crafting salsa or ketchup. This takes only one action and will render the plate unable to be used.
Both require a brown family member to gather sugar (for ketchup) and palm kernal (for natcho), in order to finish the crafting line and empty the plate/bowls used for them.
Suggested fix: 
Plate with chopped tomato + small trash pit = empty plate

Maybe consider also adding this transition for plate with chopped tomato and onion, bowl of salsa, bowl with ketchup, or any other bowl/plate that has something in it which should be able to get cleaned.

(The inspiration for this report was a town with 30+ plates of chopped tomato)

**Comment by TwistedHBG** [comment]
Another suggested fix - make Chopped Tomato on Plate edible for 5 food, same as tomato, and make it +yum2836 so it shares yum with tomatoes.

Same could be done with Chopped Onion on Plate - edible for 5 food and +yum2855.

**Comment by Tarr-OHOL** [comment]
Surprised this didn't get fixed before hand as it was specifically noted somewhere in one of the posts.

**Comment by cordy-123** [comment]
Yeah, sometimes griefers still do it until now.

Not often though.

Photo below is from may 2023. 

Photo only shows maybe a third or half of the chopped onion plates.

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/4c33e357-1fa1-40e3-a836-090bc7c5309a)

Problem includes:
Chopped Onion on Plate
Chopped Tomato on Plate
Chopped Garlic on Plate
