### ISSUE TITLE
Taking off the head of a tool.

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [jasonrohrer/OneLifeData7#832]
Because of the recent iron changes, which I like. towns may have iron shortages. To make it a bit easier on players you should be able to take off a tool head from the tool and scrap it. This would allow for unnecessary tools to be scrapped. To counteract durability you could make a 1/2 scrap item and for the sprite you could probably just cut the scrap iron in half. But the last part is optional, anyways I just hope there is a way to scrap tools with the stick off all forms of durability to allow some iron to be salvaged.

**Comment by LavaDeath** [comment]
This is such a stupid idea. First of, iron is scrappable after it breaks and it’s just fine to do this. This is literally just making it easier for people to grief tools and there’s no such thing as “unnecessary tools” you are just using this cover to make it okay to scrap all the tools in town. You are an absolute troll. First you tell Jason scrapping engines is a good idea even though it’s ONLY used by greifers like Bobo. Engine scrapping is completely unnecessary just like this is, stop trolling dude.

**Comment by Tarr-OHOL** [comment]
>break tools to make scrap items.

I get the idea of breaking handles to reforge useless extra tools (as I suggested that myself) but enabling people to smash shit into half of it's original worth is a terrible idea. 

My suggestion is to think about the game on a larger scale before making suggestions as your last one significantly made the game worse as a "joke."

**Comment by LavaDeath** [comment]
This has to be the easiest way to get rid of iron completely

**Comment by Arcurus** [comment]
this idea started as a "joke" in the forum, please just close it.

**Comment by Spodnie** [comment]
We don't want nor need scrapping good tools.
QuirkySmirkyIan is a grieffer that suggests things like this to make our experience worse and give more things to do for griefers.
