### ISSUE TITLE
Can't put turkey leg in your backpack

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#836]

**Comment by TwistedHBG** [comment]
I think it's a double-edged sword, On one hand being able to put them in a backpack would be great as they're a good food and they should easily fit, but if people start carrying them around in backpacks who knows where the bones will end up, and no bones means a permanently blocked plate and no broth.

**Comment by Spodnie** [comment]
Yeah, leave it like it is, pls, otherwise we will lose leg bones all the time.

**Comment by jasonrohrer** [comment]
What a funny issue...

My first thought was, "wow, can you imagine actually putting a turkey leg in a backpack?"

Of course, cooked rabbits and other things can go in there.... nice and greasy and warm in there!

The lost leg bone issue is curious....
