### ISSUE TITLE
Plow will walk into an expert biome

### ISSUE THREAD

**Issue by MrXIX-OHOL** [jasonrohrer/OneLifeData7#846]
Which makes it possible for griefers to put it in a place where it is very hard to reach.

Suggested fix: Don't let it walk on an empty tile, but just let it stop on the soil.

**Comment by jasonrohrer** [comment]
Unfortunately, the game engine doesn't allow moving objects to avoid empty tiles...

I think it's okay for it to be able to walk into a bad biome.  If a griefer gets the plow, they can carry it away, after all.  They don't need to run the plow to hide it from you.
