### ISSUE TITLE
Sprinklers can slide if you remove a piece of the pipeline. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#847]
https://www.youtube.com/watch?v=2eCD67JNlJA

Video proof. Basically make a sprinkler system.
Bust a pipe in the line
Remove old pipe and end it to the of the line
????
Profit. 

Also been reported to be able to do the same by just leaving gaps but I was having fun.

**Comment by jasonrohrer** [comment]
Ah... wow, that's a weird one. Thanks for posting!

**Comment by MrXIX-OHOL** [comment]
There are some more problems with them.
Just leave one space open at the end, and after that put something you can use your hand one (for example a tree with branch).
Will post some video's of this in edit.
