### ISSUE TITLE
Do I look old?

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#848]
![](https://cdn.discordapp.com/attachments/703011254666526740/729146553654313090/2020-07-05_03_07_13.png)
It happened to me again, my kid died because I thought I'm feeding it, but I was already over 40yo.
Previous time I had a brand new player, I was telling him things, he was listening, responding and after a while... He died, because I didn't realize I'm over 40yo and can't breastfeed anymore.
It's a common problem, kids die this way from time to time to everyone.

I don't have a good suggestion how to fix this problem... Maybe increase breastfeeding time to 43yo? Decrease fertile time to 37yo? Maybe you will come up with something nice.

**Comment by jasonrohrer** [comment]
Her hair does get visibly gray, but mostly on the top of her head.  So the hat covers it.  The braids get slightly gray.

Communication between BB and mother is supposed to be crucial.  It isn't normally that crucial.  This is actually the one time where it really matters, so players don't expect it to matter.  The baby is supposed to pay attention and tell you that the feeding isn't working.

A very simple fix is just to not allow mothers older than 37 to have BB.  However, I think the "mom's gone dry" moment is a funny one, and I want to leave it in the game.  It's a rare moment, but a nice little detail.
