### ISSUE TITLE
Can learn newcomen related tech by removing attachments.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#857]
Removing attachments when newcomens are filled with water + charcoal attempts to teach them.

1). Fill untooled newcomen with water + charcoal
2). Attach desired attachment
3). Remove attachment to learn tool slot related to it.

Obviously this should not be teaching tool slot.

**Comment by DougLefelhocz** [comment]
Uh... toolslots require a server with 100000 people on it.  It might be worth closing this.

**Comment by Tarr-OHOL** [comment]
This is still an issue if he ever returns to tool slots but I'll close this and make a note about it in my thread about closing out issues.
