### ISSUE TITLE
Two inconsistencies/issues with Paved Roads/Paver

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#863]
Normal roads are easy to make, and they can be removed by one person easily. Rails are hard to make, so they require two people to remove. Paved roads are VERY hard to make, so they should be harder to remove than normal roads.

Perhaps two people and reverberating pickaxes might make sense? Same as rails but with a pick instead of an adze.

The other issue is that it's very easy to mistakenly disable the paver by clicking it. If you want it to stop it temporarily it's enough to just place an item in front of it. Ideally it would require the use of a tool to disable the paver for good, maybe a smithing hammer?

**Comment by SelfSealShelf** [comment]
Disabling the paver is a big issue, I've constantly had to reload the damn thing because it gets turned off, presumably by accident.

**Comment by cordy-123** [comment]
Especially as the paved road is thousand of tiles long. 

No one could stop a griefer from pickaxing it.

Coz no one would be there to see them do it.

Requiring 2 people to pickax the road would make prevent that.

**Comment by jasonrohrer** [comment]
Whoops, forgot to fix the issue with disabling the paver.  Will do that now.
