### ISSUE TITLE
Bison corpses take too long too decay

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#867]
You can currently not gain anything from bison corpses (like beef or leather), so it seems weird that they have to take so long to decay. It currently takes 2 hours for bison corpses to decay, with no other way of removing them:

![image](https://user-images.githubusercontent.com/51952537/88852779-08029f80-d1ef-11ea-9b49-0a8c84faa6bf.png)

**Comment by cordy-123** [comment]
Generally, an experienced player would kill the DOMESTIC bison out in the wild prairie. 

And bring the domestic calf home.

**Comment by jasonrohrer** [comment]
Most of the other animals take 1 hours to decay after being skinned.

This one has the skin on, and it's really huge.

In the grand scheme of things, 2 hours isn't that long.  I also like the idea of someone coming by and seeing evidence of the hunt, generally.
