### ISSUE TITLE
Onion seeds are uncontainable outside of bowls

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#868]
As far as I’m aware this is inconsistent with every other seed in the game, which is seen as a small item that can be stored in bag packs and baskets.

**Comment by sigmen4020** [comment]
Same issue is the case for squash, pumpkin and cucumber seeds.

**Comment by jasonrohrer** [comment]
The idea here is that these are all "seeds" and not a single seed.  You might be able to throw a seed in a backpack... but a clump of seeds would get scattered and lost.

And some of them are "seed heads", which makes sense as a containable item.

I agree that many of the tiny seeds (like tomato, gooseberry, pepper) are ridiculous to thrown in a backpack.... but it's been this way for a long time.
