### ISSUE TITLE
Visually you can’t tell if a mash bucket is full or not

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#869]
This is not just that the sprite for a full mash bucket and partial is the same. A full mash buckets isn’t even called a “full mash bucket”, but rather “mash bucket”, like any other state of the item.

**Comment by cordy-123** [comment]
Can we have a full "Bucket of Corn" say "Full" too? https://onetech.info/4110-Bucket-of-Corn

**Comment by cordy-123** [comment]
Feed Mash Bucket stays visually the same while having 4 to 6 bowls of mash

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/0bd2cbff-a9aa-49b0-a11c-538b193da7a7)

**Comment by cordy-123** [comment]
Bucket of Corn stays visually the same while having 5 to 6 bowls of corn kernels. 
![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/dd167f21-aabe-4424-82ca-bcfa9b00abbe)



----------


Can we have a full "Bucket of Corn" say "Full" too? https://onetech.info/4110-Bucket-of-Corn

**Comment by cordy-123** [comment]
Bucket of Palm Kernels stays visually the same while having 5 to 6 bowls of palm kernels.

![image](https://github.com/jasonrohrer/OneLifeData7/assets/61180955/3316ba33-a280-47dd-962b-8f910f9a7a21)

----------

Can we have a full "Bucket of Palm Kernels" say "Full Bucket of Palm Kernels" too?
