### ISSUE TITLE
Dry beans don't stack

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#871]

**Comment by DougLefelhocz** [comment]
Uh, why don't clay bowls suffice?

**Comment by sigmen4020** [comment]
If bowls sufficed, why do I constantly see a ton of tiles occupied by a single dry bean in any later town. Bean clutter is pretty annoying issue in bigger towns and the lack of bean stacking makes it probably the most annoying crop to farm in the entire game. Why should we not have the ability to stack dry beans like basically any other crop in the game? Why must dry beans be the only crop that has to take up a tile each unless put in a bowl?

**Comment by DougLefelhocz** [comment]
I think your clarification improves your report sigmen.

**Comment by miskas9** [comment]
Bowls are for transportation not for storage.

**Comment by jasonrohrer** [comment]
Yeah, there are loads of transitions built around taking them in and out of bowls.  These are tiny items, similar to how seeds are stored in a bowl, not a pile.  Also, dry beans ARE a seed, used for planting.
