### ISSUE TITLE
Craving Mushrooms as Eve... Also As Male

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#872]
It happens to Eves sometimes that they end up craving mushrooms.  But, they take an hour to grow, and thus can't get eaten by an Eve (and possibly not *some* of her children also) out in the wild or starting up a town from scratch.

Eves might not have any children for various reasons even if living to old age (the server they are on is low pop, the player is in donkey town).  So, the craving can end up entirely meaningless, since it can't get satisfied.

Also, a players craving is by no means necessarily inherited on bs2.  I saw wondible crave a mushroom as a male.  It's not inconceivable that mushrooms wouldn't be obtainable for some male, and thus since males don't pass on cravings, the craving could end up as rather silly information in a village with few people left, or if the male travels somewhere else to perhaps attempt to trade.

Eating is an individualistic behavior in game.  For that reason, cravings not satisfable in principle in a one hour in one life context don't end up making sense, such as craving mushrooms as Eve.

No texture gets added to the game by not being able to do something that the game suggests to you to do.

**Comment by DougLefelhocz** [comment]
The mushroom craving, I feel rather surely, is the worst craving in the game.  Removing it entirely might end up as preferable.  Some players will eat mushrooms regardless, because of the hallucinogenic effect, or because they want to roleplay doing drugs.  So, there's no need to motivate players to consume mushrooms.  Worse, craving mushrooms is like a player wanting a drug, and hallucinogenic drugs aren't good for people as a rule in the real world.  Additionally, the mushroom supply is rather easy to "grief", unlike (almost?) all other foods.

**Comment by Tarr-OHOL** [comment]
Craving mushrooms is made purposeful by Jason as cravings are supposed to be a bonus which you may or may not be able to achieve. 

As such this post should be closed.

**Comment by DougLefelhocz** [comment]
> Craving mushrooms is made purposeful by Jason as cravings are supposed to be a bonus which you may or may not be able to achieve.

I don't think it's Jason intention to make a game that has contradictions with it's philosophy.  I note that it's a one hour game.  If something that appears as a suggestion on the player's screen isn't achievable at least once like cravings sometimes are, then we have a contradiction with the concept that one life is sufficient to have a basic understanding of how the game works.

To put things another way, if a character couldn't satisfy at least one craving no matter what they did, did that character live?  Because one could maintain that such a character only existed, and never lived (so to speak).
