### ISSUE TITLE
Some Turkey stages don't have the +contFoodDish tag

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#873]
Drum Sticks on Plate  (ID 2188)
Drum Stick on Plate (ID 2193)
Turkey Carcass on Plate (ID 2189)
Partial Turkey Bones on Plate (ID 2201)
Turkey Bones on Plate (ID 2200)

This isn't really a big issue but it does cause one awkward interaction - you can take most turkey slices off the turkey while it's on a table, but to take the last slice you need to put it on a floor.

**Comment by J-Ordoniez** [comment]
Up

**Comment by DougLefelhocz** [comment]
Carved turkey fits on a table.  Turkey with drum sticks does not.  It's as if the plate got heavier or something with the last turkey slice removed.

**Comment by oholseven** [comment]
Is this not getting a fix? Turkey needs to remain on the table.  Doesn't make sense that feast table is fine, but turkey platter has to be thrown on the ground.

**Comment by TwistedHBG** [comment]
> Is this not getting a fix? Turkey needs to remain on the table. Doesn't make sense that feast table is fine, but turkey platter has to be thrown on the ground.

It is, it's still an open issue and it hasn't been looked at yet. There's a bunch of issues still open.

**Comment by oholseven** [comment]
Thanks!

**Comment by jasonrohrer** [comment]
This issue is like a fine wine... it gets more hilarious over time.  To take the last slice, you need to put the turkey on the ground.
