### ISSUE TITLE
Tracks Require Two People to Remove

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#876]
There's no way to remove it by oneself.  This makes removing someone else's awkward placement impossible.  It also doesn't make experimenting feasible.

**Comment by TheMingo888** [comment]
I think the current method is suitable and should not be changed. Tracks require some effort to lay and allowing one person to adze them all instantly would allow for yet another form of griefing. Now if only paved roads also required two people to destroy...

**Comment by Tarr-OHOL** [comment]
This is purposeful as a means to stop people from ripping it all up singlehandedly. As such this should be closed.

**Comment by DougLefelhocz** [comment]
>This is purposeful as a means to stop people from ripping it all up singlehandedly. As such this should be closed.

The game is intended to be completely playable (technologically wise) as a single player.  

Solo play is talked about by Jason as supported both in [this thread](https://onehouronelife.com/forums/viewtopic.php?id=4848) and [this update](https://onehouronelife.com/forums/viewtopic.php?id=88).  Single player experimentation with rail tracks isn't feasible since they require two people to remove.

**Comment by J-Ordoniez** [comment]
I wish to add to this discussion, when you add a track over a West-east or over a North-South, you get a crossrail, but when you remove by adze a crossrail, you only get 1 kit use, and not 2.

**Comment by cordy-123** [comment]
this game is supposed to be a social game. just ask another person in your town.
