### ISSUE TITLE
Engines Require Only One Person to Remove

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#877]
I can't imagine a reason useful to a town to remove an engine from a well to begin with.  Who can?  Who has demonstrated that removing an engine from a well could be useful?  Who has demonstrated that scrapping an engine can be useful?  I doubt that a single example of a reason to scrap an engine is known.

But, since they are removable, it would make more sense if required more than one person to do so.

Same goes for scrapping them.

**Comment by FeyFre** [comment]
Bad idea!
It will make harder to fast hide engine once it used on well, but most importantly, it will make very hard to loot dead town. Usually looter person is single, so you need either go in pairs, or wait for some other random looter to help (and how to share it?).
As option, make possible that only family member can remove it, or only from abandoned well.

**Comment by DougLefelhocz** [comment]
The game is about rebuilding from scratch.  Looting dead towns shouldn't even exist.  It might be hard to prevent in an open world, but ideally each town should be self-sufficient so that there was rebuilding from scratch.
