### ISSUE TITLE
Immortal Cow

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLifeData7#88]
Fast milking seems to glitch out cows.
Recreation: https://clips.twitch.tv/AltruisticSilkyMacaroniUnSane

**Comment by jasonrohrer** [comment]
Copying info from other comment:

Cow has number of uses "10".
And it's decrement at
1. Walked
2. Feed water
3. Milked
And "just drank" cow doesn't have transaction when number of uses is zero.
