### ISSUE TITLE
Truck and Race cars can't create roadkill snakes

### ISSUE THREAD

**Issue by MaDc0wUSP** [jasonrohrer/OneLifeData7#880]
https://edge.onetech.info/2401-Snake-Roadkill

We need snake boots.

**Comment by TwistedHBG** [comment]
Car should also be able to kill mosquitoes since they have a windshiel, it's perfect!

**Comment by MaDc0wUSP** [comment]
I opened a separate report for that, but I guess they could be grouped.

**Comment by jasonrohrer** [comment]
This was fixed.... not sure about mosquitoes.
