### ISSUE TITLE
Race car should be able to squish mosquitoes 

### ISSUE THREAD

**Issue by MaDc0wUSP** [jasonrohrer/OneLifeData7#881]
It has a windshield after all, so being able to kill them would make them useful.

**Comment by Arcurus** [comment]
lol yea finally lets kill the dammed mosquitos!

**Comment by Spodnie** [comment]
I don't think you would be able to kill mosquitoes irl with a car, so it doesn't make much sense.
Tho it would be cool to have some kind of insect spray or smth that could kill them.

**Comment by MaDc0wUSP** [comment]
Then you have never driven through a swarm of bugs.
Or see anyone's windscreens that live in more humid climates.
