### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by fearless512** [jasonrohrer/OneLifeData7#882]
So I've played this game on steam before on a different computer but I have a new computer and now it says unable to create account whenever I launch the game. If you could reply back telling me how to fix this it would be greatly appreciated :)

**Comment by AdamLoe** [comment]
I have the same issue but on same computer.
I tried editing server to join one of the less popular ones, but I messed something up, and could not log in to anything no matter what I did. After multiple reinstalls not fixing it, I hard cleared all files from this game, and reinstalled, and now I have this same issue.

**Comment by jasonrohrer** [comment]
There was a glitch where the disk on the server filled up, but it has been fixed.

If you're still having trouble, please email me:  jasonrohrer AT fastmail DOT fm
