### ISSUE TITLE
New players have a hard time spotting certain foods

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#883]
During an influx of new players it becomes notable that some foods aren't as clear as others and will inevitably be overlooked. It's common to witness inexperienced players starve right beside buckets of milk and crocks of stew. Some slight visual changes may marginally help grab their attention and get the message across.

-Similarly to pickle crocks, stew, turkey broth and sauerkraut should display "STEW", "BROTH" and "KRAUT" on the clay crock;
-Additionally, milk buckets, bowls and pouches could display the letter "M", matching the salt water items.

**Comment by TwistedHBG** [comment]
Great points, it would also help us to differentiate stew pots from cooked pumpkin pots.

**Comment by Arcurus** [comment]
isnt there a mod already that highlights food and especially yum food (it gets visually bigger or so)?

That would be really beneficial for players to have. Like that also in reality would function. Food would become lot more visible for you if starving.

**Comment by jasonrohrer** [comment]
Fixed in 4c8c0357f0351b6940d07bde798638c71ccaaaba
