### ISSUE TITLE
KRAUT is a terrible name on crocks

### ISSUE THREAD

**Issue by MaDc0wUSP** [jasonrohrer/OneLifeData7#886]
Kraut(s) is a pejorative term for Germans and shouldn't be used.
Sauerkraut could still be written on the crock using a hyphen.

**Comment by jasonrohrer** [comment]
You're kidding, right?

**Comment by Arcurus** [comment]
Im a German and i just know that foreigners in the past called Germans Krauts, since they in former time ate a lot of Sauerkraut. I for my part im not offended to be called like this, maybe others would be.

**Comment by Tipy1802** [comment]
This is like saying baguettes cant be called baguettes because some people use it as a pejorative term for French
