### ISSUE TITLE
Cannot undig Rabbit Hole growing

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLifeData7#887]

**Comment by cordy-123** [comment]
do you mean 

cannot DIG a rabbit hole growing?


you'd have to wait 1 hour for the rabbit to show up.
https://onetech.info/196-Rabbit-Hole-growing

not a big deal to do so.

**Comment by jasonrohrer** [comment]
Fixed by ec915a2cb64b92a3a53ee2b49608c21b7b6f597a
