### ISSUE TITLE
Outdated tutorial message

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#889]
Since there's no berry bushes in the tutorial anymore, this message makes no sense.

![image](https://user-images.githubusercontent.com/51952537/94352654-28709e00-0068-11eb-96a9-e4ee1c4ba29e.png)

**Comment by TwistedHBG** [comment]
You're using a modded client that hasn't been updated so it's showing the old message. In unmodded the message mentions onions.

**Comment by sigmen4020** [comment]
The screenshot isn’t mine, I just saw it on the Discord figured it’d need changing. I just checked it myself with the vanilla game and you’re right. The message relates to the onions as it should. This issue is something for the mod maker needs to fix and not Jason, so I’ll be closing this issue.
