### ISSUE TITLE
Little view

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#890]
![2020-09-27 07_06_12](https://user-images.githubusercontent.com/56101460/94357647-ef9dec80-009a-11eb-9542-febc60ac6681.png)

In big towns it's so hard to find items that you need with that little sight.
I know this game looks the best when zoomed in maximally, but...
Lately I've been playing stardew valley, their game looks the best when maximally zoomed in too, yet it's possible to zoom in and out whenever needed.
Same in OHOL, I zoom in and out whenever needed (with a mod), it's much easier to smith when zoomed in, but when looking for stuff you would want to zoom out.
If you made it really smooth to zoom (unlike mods where it just jumps to a bigger/smaller zoom), it would look good in youtube videos too.

I mean, don't make it possible to zoom out that much as in mods, but about 2x would be enough.

I know you've been asked for this many times by people and you rejected it, sorry for asking again, but I'm pretty sure much more people would stay with the game if they could see more.

So many nice building and nice towns, and they can't see the beauty of them with that little view.

**Comment by Arcurus** [comment]
yes at least 1 tile more view on yea side in zoom mode would be great to have!

By the way i guess better post this issue here, since it has nothing to do with the data items: https://github.com/jasonrohrer/OneLife

**Comment by jasonrohrer** [comment]
All the graphics were drawn by hand to match this specific screen size.  Zooming out causes shimmering artifacts on all those sharp, hand-drawn pen lines.

I know that most people don't care about this or even notice it, but I do.
