### ISSUE TITLE
Can breastfeed to adulthood if toddler is not dropped

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#90]
If you do not drop a child once they reach toddler age (after which they cannot be picked up), It is possible to sustain another character until they reach adulthood by breastfeeding. So long as the breastfeeder remains fed, and they never drop the held player, this can last until infertility, after which the held player starts losing food bars.

![20181206195552_1](https://user-images.githubusercontent.com/45378452/49867441-a4cbca00-fe5e-11e8-9d83-74c5828f047c.jpg)

**Comment by trevorhackman** [comment]
This is hilarious and shouldn't be fixed

**Comment by jasonrohrer** [comment]
Yes, this has always been there.  It is funny.  Leaving it!
