### ISSUE TITLE
Can sprinklers get the rail track treatment?

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#900]
Sprinkler pipes are much easier to grief than they are to produce and thus fall into a category I'd call "too griefable vs time spent making."

I'd never say making pipes + nozzles is exactly difficult but it takes very little effort to completely recycle the system. In place of the current system of hammer + southern facing sprinkler pipe or hammer + northern facing sprinkler pipe + hammer = steel pipe + nozzle we instead replace it with hammer +  southern facing sprinkler pipe or hammer = southern facing sprinkler pipe vibrating (and same thing with north.)

Southern (or) northern facing sprinkler pipe vibrating + hammer = steel pipe + nozzle.

This would follow how normal fence removal works (minus the fact this is doable by one person) and how rail track removal works by leaving the first person striking the pipe with a hammer stuck and requiring a second person to smack it actually remove it. This makes moving or recycling a sprinkler pipe system a group decision and not the decision of someone looking to scrap or ruin the system in place.

**Comment by SelfSealShelf** [comment]
I don't think this is wise, it would make recuperating the materials from dead towns nearly impossible.

**Comment by cordy-123** [comment]
i'd like to add:

"Can **_SCRAPPING ENGINES_** get the rail track treatment?"

would be great if you would need TWO PEOPLE WITH TWO SEPARATE HAMMERS to scrap engines.

considering that making an engine takes 30-60 minutes while scrapping an engine takes LESS THAN A MINUTE....

**Comment by squishysquid** [comment]
it's not really often the pipes, they just yoink the engine off and scrap that.
