### ISSUE TITLE
Families can't survive nightly lul in player activity

### ISSUE THREAD

**Issue by SelfSealShelf** [jasonrohrer/OneLifeData7#903]
There are some issues with how babies are being assigned in the current version. The main reason families are dying these days is from fertility issues as a village runs out of girls to continue the lineage. This is extremely predictable and can be seen nightly from 12am to 5am central time, when player numbers are lowest. This isn't fun or interesting gameplay, there's no social resources or material resources available to players to solve this.

Currently there are protections in place to ensure the next child born to a family is a girl if there aren't enough girls, but this isn't enough to keep families alive. Peculiarities in how players distribute themselves and influence baby distribution end up compounding during low population times, eliminating one family while another has dozens of players.

Here are some modded screenshots showing this uneven distribution:
https://cdn.discordapp.com/attachments/617192515195502607/781453840397893663/unknown-5.png
https://cdn.discordapp.com/attachments/608093968940531744/781392404376715264/unknown.png

These stats really are typical of what night time players run into. This is caused by a few things:

1. Lineage bans. Not sure if this is still a feature, but in the past I know you would be unable to be born to a family if you'd just played there for a certain time period.

2. Yum/warmth of mother. It's interesting to have some method in players control to have more or less babies, but these shouldn't be used in favor of even distribution during low population situations. 

3. Curses. This is the only thing I think should remain as is. The curse system works OK.

4. /die babies. 

Throughout the course of a night with such a small playerbase there's bound to be some period where all of these line up to screw one family. 

To fix this there needs to be a check on a family's fertility. If they have less than two fertile women or girls under age 14 then they're guaranteed to be assigned the next birth, and it's guaranteed to be a girl. Women or girls outside of their band count as infertile for these purposes. To keep things interesting the check is never made if there are greater than 40 players online, and the family exhausts an invisible token each time this is used. The number of fertility tokens a family gets goes up every few hours up to a cap, and there are a few non-renewable reserve tokens inherited from the eve for that lineage. If two or more families have met the conditions to use their token the birth is assigned at random. If a fertile woman or girl returns to her biome band from outside before the token is used it's deactivated and returned to storage. If all women from that family are out of band while the fertility token is active the next player login is given a 5 second wait period to give them a chance to return.

**Comment by DougLefelhocz** [comment]
Spoons and Krauts lived through a few nights a few weeks ago.  Maybe though too many families were failing due to bad luck on children.

But also, the player count during the aforementioned time period has been higher since/during the influx of players from the Tiktok blurb.

**Comment by SelfSealShelf** [comment]
> Spoons and Krauts lived through a few nights a few weeks ago. Maybe though too many families were failing due to bad luck on children.
> 
> But also, the player count during the aforementioned time period has been higher since/during the influx of players from the Tiktok blurb.

Higher player counts help, but there's still a weird gap of instability in-between when lowpop mechanics kick in and when there's enough people to keep families reproductively stable.

**Comment by DougLefelhocz** [comment]
I think Fines, Lovelys, Marys, and Reds all survived this time period on December 8th, 2020.  I saw that the player count dipped below 50 for a little bit.

The idea of wait periods for players trying to log in sounds frustrating.  Specifically, I would imagine that a new player might find it frustrating to just see a black screen.  Sometimes when I load a game whether it's because my computer is more than 5 years old, or because of the game, or some other cause, it's a bit frustrating to sit there and wait.  But, I do tend to wait, so maybe a wait period wouldn't be as bad I expect for others... it's not so easy to know.

**Comment by Forman9** [comment]
this is true and then griefers steal all the oil at night

**Comment by cordy-123** [comment]
> Women or girls outside of their band count as infertile for these purposes. 

----> this is currently already enforced in the game. if the fertile is OUT of band, currently they dont count towards the minimum amount of fertiles.

**Comment by jasonrohrer** [comment]
I think this issue was dealt with long ago.  Please re-open if there's more info about it in the latest iteration of how things work.
