### ISSUE TITLE
Tip of Flint-Tipped Fire Bow Drill Can't Get Removed With a Knife

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#905]
d3mon1cblack mentioned this to me.  When I think about it, it seems that we would have fine motor control to use a knife to remove a flint chip.  Not sure how many players this one affects though.

**Comment by Tarr-OHOL** [comment]
Fix for this issue. 
[560_474.txt](https://github.com/jasonrohrer/OneLifeData7/files/11241017/560_474.txt)
