### ISSUE TITLE
Removable bear caves

### ISSUE THREAD

**Issue by IIRC-IDK** [jasonrohrer/OneLifeData7#908]
Bear caves serve as a major obstacle in the construction of roads, walls, and etc. Once the bear is killed they really only serve as an obstruction. Being able to remove them and perhaps get some resources from them would promote the hunting of bears and alleviate some headache for builders.

**Comment by Forman9** [comment]
this would be nice

**Comment by Tarr-OHOL** [comment]
Fix for this issue. Pickax to turn empty cave into just pine tree. 
[684_650.txt](https://github.com/jasonrohrer/OneLifeData7/files/11241042/684_650.txt)

**Comment by jasonrohrer** [comment]
Well, they do add visual character to the landscape, though.  And it's nice to have *somethign* that your road has to go around.  The magic paver just requires a few extra re-directions to make it around a bear cave, and then travelers will have some scenery to look it.

I know that many things can be removed... but there are other things that can't be, right?
