### ISSUE TITLE
Clearer Signs To Go West For Solo Wilderness Survival

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#909]
With Steam's Winter Sale (**_starts December 22_**) and Lunar New Year Sale coming soon, there will be an influx of new players. (If you place the game on sale.)

One of the most frustrating things I would think for new players is not knowing to go west to light the torch to spawn in the game for real in the Solo Wilderness Survival and keep respawning as an Eve or wandering aimlessly in this mode, being bored out of their skull. 

If you missed the notification the first time you spawn in that mode, good chance you'll miss it again the next time. The notification is too subtle and since there is only one of it (if you don't go west), very easy to accidentally miss. There are a lot of directions to walk to **other than west** and it would be easy for newbies to miss the notification if there first thought is where is food or omg, I'm an Eve. (Even experienced players sometimes don't notice it and when asked to open gate or exile someone keep saying "Huh, but I'm not leader?" or "Really, I own the gate? Where is it?") 

Maybe a more obvious, clearer sign could be added? 

As the top left notification of going west is VERY easy to miss for newbies, as they are not used to it, or they think they spawned in the real game, and/or are already information overloaded when they get to the Survival mode. 

The simplest solution would be maybe adding something like the signs in the original tutorial. Example, the signs saying "Door" "Hints in Here" "Go North or South". So maybe a "Go West" sign that would be visible as soon as you enter the Survival mode. 

Or some other solution you come up with.

Thank you.

--------------------

[Side note: can you also address the issue of notifications being often missed in the future?] 

[Another side note: Can we have /property or /gate? And the arrow will point us to the nearest gate we own, excluding follower gates. Example, a bunch of times people get gate below 3 y.o., it's not like you can jump out of your mom's arms and run to check where the property is. This is a particular problem if the gate is far away. And by the time you are able to travel, the property arrow has gone away.]

-------------------

Here are just a couple of examples of people having this problem and asking about it on discord. All examples were around the time of the last sale. I would assume more people have this same problem and **_some might give up playing being bored_** of being an Eve with no kids, _**thinking**_ they are spawning in the real game.

"I just got the game can someone tell me how I join people" (link: https://discord.com/channels/328215300279500800/421767430893862914/787944461937672202)

ok so basically in 99% sure i finished the tutorial. I lit the torch and got killed by the snakes. Now, every time i try to join a game it just puts me into a solo world as an adult in the wilderness. Sometimes when I spawn in (but sometimes not) a notification will pop up saying I can bypass this by walking west. So, as far as I know, west is left so I walk left and eventually just starve to death as i walk into the same wilderness i spawned into. I have no idea how to get to play the actual game. 
(link: https://discord.com/channels/328215300279500800/421767430893862914/782639397094293534)

I just got the game I finished the tutorial how do I spawn into a multiplayer game whenever I click login it always spawns me in as a eve (link: https://discord.com/channels/328215300279500800/421767430893862914/782802297549488180)

also is spawning randomly like to a mama
but i spawned in as a big woman is that normal or wat? 
(link: https://discord.com/channels/328215300279500800/421767430893862914/782435968333381632)

Why do I only spawn as an EVE 
(link: https://discord.com/channels/328215300279500800/421767430893862914/781636206739324928)

**Comment by jasonrohrer** [comment]
Fixed.  Please take a look at the new Tutorial 2 map this week, and see if it feels more clear to you.  I added a road and a sign, and some other little tweaks.
