### ISSUE TITLE
Cabbage crock pots are compostable, while pumpkin crock pots are not.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#910]
About a year ago there was a change that made it so cabbage crock pots were compostable, because cabbages are easily grown and shredded but unusable to families without salt readily available. The change: https://github.com/jasonrohrer/OneLifeData7/commit/20b93c13e0728bbadf3b6d003d7809e37b9d1f3b)

Nowadays the same is true for pumpkins. Pumpkins are passively gained from growing squash but they can only be used if you have sugar, which is a resource that can only be gathered/grown by one family. If someone fills a crock pot with pumpkin chunks that crock pot is unusable until you manage to get sugar, and getting sugar is a more complicated process than getting salt.

Relevant Object IDs:

Crock of Raw Pumpkin - 3365

**Comment by DougLefelhocz** [comment]
Even if everyone could access sugar or salt on a server with at least 15 players, the salt or sugar might be far away.  So, this issue has more going for it.

Also, maybe garlic could get turned into compost, even if needing a lot of garlic to make compost?

**Comment by Tarr-OHOL** [comment]
Gotten this transition set up and working. 
[3365_227.txt](https://github.com/jasonrohrer/OneLifeData7/files/11240290/3365_227.txt)
