### ISSUE TITLE
Not enough uses for domestic garlic

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLifeData7#912]
Garlic has few uses and a high produce and seed ratio, making it easy to expand. It is a trap for new players who try to plant it in the same volume as everything else, and a tool for griefers to fill up space and waste resources.

See forum thread for more:  https://onehouronelife.com/forums/viewtopic.php?id=10360

**Comment by cordy-123** [comment]
Or you know just make them edible by themselves. 

Garlic is just a noob trap now or a grief tactic.

**Comment by cordy-123** [comment]
![garlic spongebob by schlmoo](https://user-images.githubusercontent.com/61180955/105490548-e68ef600-5cef-11eb-88d7-5d05f6fa3bf7.png)
![garlic 1](https://user-images.githubusercontent.com/61180955/105490591-f73f6c00-5cef-11eb-8e77-85dd68c27d32.png)
![garlic road](https://user-images.githubusercontent.com/61180955/105490621-fe667a00-5cef-11eb-82be-cc33df5b24f6.png)
![garlic 2](https://user-images.githubusercontent.com/61180955/105490633-03c3c480-5cf0-11eb-9675-94b45a25256f.png)
![garlic](https://user-images.githubusercontent.com/61180955/105490652-0c1bff80-5cf0-11eb-93e1-7e0092be50ed.png)

**Comment by DougLefelhocz** [comment]
Dill is kind of similar from what I've seen, though not as bad.

**Comment by Forman9** [comment]
this is true

**Comment by jasonrohrer** [comment]
It has been edible for a while now, based of these changes:

b4ad60e

9e8d45e
