### ISSUE TITLE
Drink Milk From Glass, Stackable Full Sealed Glass Bottles And Bottles of Slaked Lime

### ISSUE THREAD

**Issue by RosieRandom** [jasonrohrer/OneLifeData7#917]
I just think as we move towards a more fancy OHOL existence, we should be able to pour our milk from a bottle into a glass and drink it.  Bowls are great but glasses are much more sophisticated.

Also Sealed Bottles cannot be stacked once they contain something.  This makes it impossible to make fancy pyramids of your milk bottles (and other containable substances).  It would be nice if once a bottle of something is sealed it could be stacked with other bottles that also hold the same material i.e. pyramid of sealed skim milk bottles and pyramid of sealed whole milk bottles.

Another thing that would be useful would be to make bottles of Slaked Lime it would save space when you are making milk buckets into paint if you could store 4 Slaked Lime in the one spot.  It would also be a nice addition to a modern kitchen where people could store it to make Tacos for when that craving hits.

Thanks for reading
Rosie

**Comment by Forman9** [comment]
slaked lime would be awesome

**Comment by cordy-123** [comment]
how often do you see people IRL drinking milk from WINE glasses? 
(which is the only drinking glass that we currently have in the game)

--------

presumably, the reason that sealed bottles (that contain things inside) is NOT stackable is coz the game would have to figure out if the bottle is half full, quarter full, etc. 

it's the same reason why you can't use a half-full bucket of water on a cistern.

--------

slaked lime bottles would be nice
