### ISSUE TITLE
One hour one life steam key problem

### ISSUE THREAD

**Issue by Vanish-the-Gold** [jasonrohrer/OneLifeData7#918]
Hello! About 3 years ago I bought your game One hour One life. I haven't played the game in about 2 years and it recently came to me that the game is on steam now. I followed the instructions on how to get my steam copy but it says that I already have it activated. Of course that isn't true or I don't rember it and don't know what steam account it got active teď on. Could you possibly help me get the game on steam? Thanks in advance,  Václav

**Comment by TwistedHBG** [comment]
I suggest you contact the dev directly at jasonrohrer@fastmail.fm

This github is for reporting bugs with the game and it's unlikely you'll get quick tech support here.

**Comment by Vanish-the-Gold** [comment]
Heya! I also sent him an email when I created this post but I wasn't sure If he was responding to emails. I got it resolved already. Cheers anyway! <3
