### ISSUE TITLE
Hot Wrought Iron won’t be cool.

### ISSUE THREAD

**Issue by AlecYawata** [jasonrohrer/OneLifeData7#92]
There are no transaction of cool wrought iron.

https://onetech.info/2216-Hot-Wrought-Iron

**Comment by MonsieurWTF** [comment]
+1, also including pics.

To clarify this is Hot Wrought Iron on its own, laying on the ground, missing its "Changes over time" rule. There are 10 second cooling states for HWI when it's 1) Held by Tongs and 2) On a Flat Rock.
![image](https://user-images.githubusercontent.com/7107685/50286110-f8708180-0423-11e9-8afe-8a365760af4e.png)
![image](https://user-images.githubusercontent.com/7107685/50286127-058d7080-0424-11e9-82a6-af70fdfbf338.png)
![image](https://user-images.githubusercontent.com/7107685/50286143-1938d700-0424-11e9-86ad-fa2cb61eac24.png)
