### ISSUE TITLE
Vertical Fences Can't Have Gates

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#920]
Playing in [Beig family](http://lineage.onehouronelife.com/server.php?action=character_page&id=7232642), they had made a vertical fence to separate the pens.  But, movement between the pens required walking all the way up around the kitchen. I tried to put a short shaft on a vertical fence and it wouldn't work.

**Comment by cordy-123** [comment]
Use a rope on the wooden fence to be able to add a short shaft to make a wooden fence gate.
