### ISSUE TITLE
Waystones Inactive on a Server with Between 15 and 30 Players on it.

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#921]
Beep/Eve Troll/iirc-idk requested that waystones not be active on a server with less than 15 players, as I recall, because of concerns about a player targeting another with them.  I think the term he used was "unconventinal griefing"

I just played as [Cher Gaylord](http://lineage.onehouronelife.com/server.php?action=character_page&id=7241160).  The server population was under 30 players the entire time.  Waystones didn't locate anyone.  On the other hand, I did have genetic score changes.

**Comment by cordy-123** [comment]
this issue should be closed.

expert way stones BOTH do not work at:

between 15 to 29 players

between 1 to 14 players.

which is the way jason intended it to be. coz every player can go to (and touch items in) every biome. therefore, expert way stones are NOT needed.
