### ISSUE TITLE
Turkey Leg Bone Doesn't Fit in Horsecart, Basket, Nor Backpack

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#922]
I'd think it would at least fit in a cart, if not fit in a backpack or basket also. They sometimes end up lost in the woods.

**Comment by cordy-123** [comment]
The problem there is if the Turkey Leg Bone becomes containable. 

The more likely scenario is that they will be more "lost" (by newbie players or noob yum chasers) or purposely "lost" (by griefers).

The scenario now is better alternative.

With so many hetuw users playing, finding the Turkey Leg Bone is easy enough as long as it is within 40-60 tiles of the well/town.

Usually, there is no missing pair of Turkey Leg Bone in the town (if you use hetuw mod's search function). 

This will not be the case if it is containable.

**Comment by Sir-Caio** [comment]
Why not change the broth recipe to be made with just the carcass? No leg bones required. Drumsticks could become containable while we're at it for convenience, and leg bones are left as vanishing waste.
