### ISSUE TITLE
Show Last Words on Family Tree

### ISSUE THREAD

**Issue by Mashimaro7** [jasonrohrer/OneLifeData7#926]
I might just be missing something, but is there no way to see last words on the full family tree? It only displays cause of death and age. I think it'd be a nice feature if it showed last words here as well. Cause last words are super fun to look at lol, it'd be fun to go through all the last words of a lineage.

**Comment by cordy-123** [comment]
that "full family tree" you mentioned was made by wondible. 

not the game dev.
