### ISSUE TITLE
Engine Can Get Placed on a Muddy Iron Vein, is Removable, AND Kills Off Iron Unlock

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#929]
I tested this on a low pop server where I had iron unlock to be sure.  I first placed an engine on a muddy iron vein.  I then removed it which collapsed the vein.  I put 10 stones on a nearby spring.  I got iron from some other unlocked vein.  But, there was no iron on the vein where I collapsed the mine after the unlock, nor after digging up the nearby spring into a shallow well.

The combination of a removable engine and it killing off iron unlock, and predictable Eve spawning pattern, makes it possible for one person with an engine to go around and kill off iron unlock ahead of the Eves in an area similar to how Testo did a well tessellation to kill off iron supply for Eves.  With a truck or racecar (neither of which Testo had) and not needing stones to move the engine, it's potentially even quicker to kill off the iron supply in a region ahead of the Eves.

**Comment by jasonrohrer** [comment]
Fixed in e2fccecb44b2e50032265b1c54966915cb962df9
