### ISSUE TITLE
Incorrect (although effectively obsolete) transition from Oil Rig to Newcomen Pump

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#93]
According to [Onetech](https://onetech.info/2303-Firing-Oil-Drilling-Rig), After 15 seconds, Firing Oil Drilling Rig turns into Wet Newcomen Pump.  This shouldn't affect anything as the other two transitions are at 10 seconds.

**Comment by jasonrohrer** [comment]
Onetech bug, I think.
