### ISSUE TITLE
Apoclaypses Reset Tutorial Area

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#932]
I was in a tutorial area during one of the apocalypses during April 1st.  The whole thing vanished, and I just had natural terrain after the apocalypse.  I would think this would be very confusing for a new player going through the tutorial, in addition to possibly frustrating since players would need to run through it again.

**Comment by TwistedHBG** [comment]
I think the ostrich algorithm would be a great way to easily fix this issue

**Comment by DougLefelhocz** [comment]
No apocalypse has happened recently, yes, Twisted.  However, when any past apocalypses happened before, it seems exceedingly likely that players in the tutorial area had their tutorial area vanish similarly, because apocalypses reset everything to nature.  Thus, tutorial areas vanishing is not exceedingly rare when there is an apocalypse.  On the contrary, tutorial areas vanishing should be expected after an apocalypse.

The above also got posted on April 1st, but it was NOT a joke.  Not only do I remember seeing this, but a few days or weeks later I remember reading someone specifically saying that he or she couldn't finish the tutorial area _in a Steam review_.  I also mentioned not finishing the tutorial area in 2022 this year, while reflecting back on 2021 on the Github.

Finally, and I understand that English is not your first language Twisted, but use of "the ostrich algorithm" does NOT fix an issue.  By it's very definition on Wikipedia at least, it's a way of ignoring potential problems.  On the contrary, the issue **remains**.

**Comment by DougLefelhocz** [comment]
> I think the ostrich algorithm would be a great way to easily fix this issue

There have been [two recent apocalypses](https://github.com/jasonrohrer/OneLife/issues/1011) both of which likely enough had some player in some tutorial area.  So, no.
