### ISSUE TITLE
Car running out of fuel drops player into wildlife

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#96]
When the car runs out of fuel it forces the player  out of the car and there is no indication on when the car is going to run out of fuel, which eventually ends up on the player dropping (or  keep walking by clicking, thinking he is still in the car) on a wolf or boar, dying and losing the car in the wilderness

**Comment by trevorhackman** [comment]
Maybe relevant - https://www.twitch.tv/lostscholar/clip/SneakySmoggyDragonfruitKeyboardCat?filter=clips&range=7d&sort=time

**Comment by jasonrohrer** [comment]
I've slowed down the "drop" time after the car stalls from 2 to 4 seconds.  This should help, and reduce the chance of the player clicking by accident.
