### ISSUE TITLE
Can’t put locks on vertical doors

### ISSUE THREAD

**Issue by Rae5175** [jasonrohrer/OneLifeData7#988]
The title says it all! :)

**Comment by cordy-123** [comment]
yes you can.

https://onetech.info/923-Open-Locked-Wooden-Door-vert-10

are you sure that wood door didnt have a steel spring on it?

you have to remove the spring first.

**Comment by Rae5175** [comment]
Doh! Haha! It might have, but I don’t think it did? I’ll try again and get back to you. I’ll feel PRETTY dumb if that’s all it was, but I did ask a few other people to check it too before I emailed you. Lol. At least I won’t be the only one. 😂

**Comment by Rae5175** [comment]
I still can’t put the lock on. Am I doing something wrong still? I wouldn’t be surprised, honestly. Lol. I, embarrassingly, filmed my computer screen with my phone (oof), but I can’t attach the video. I’ll email it to ya.

**Comment by jasonrohrer** [comment]
Just tested, and it's working for both horizontal and vertical doors.

You need a lock blank, then you need to file it a few times to pick which key-type you want (keep filing to go through A, B, C, ... J).  After you've settled on the key-type, then you just pick up the lock-and-key and click the closed door.
