### ISSUE TITLE
Items that can't fit on table or box

### ISSUE THREAD

**Issue by ruanna85** [jasonrohrer/OneLifeData7#996]
- Last turkey slice cannot be picked up with a plate off table
- Turkey with drumsticks cannot be placed on table
- Cleaned soaked beans and soaking beans cannot fit into box
- Glasswort ashes bottle without rubber stopper cannot be put on table
- Bowl of black dye cannot be placed on table
- Peppercorns and charcoal pencils cannot be stacked
-

**Comment by jasonrohrer** [comment]
Turkey bugs were fixed a while back.

Black dye can only go on lab table, not food table... not sure if that was fixed at some point.

**Comment by jasonrohrer** [comment]
Glasswort ash bottle can only be opened on lab table, not food table.

**Comment by jasonrohrer** [comment]
Rule of thumb is that no bowl of liquid can go in box, and they can only go on tables.  Soaking beans are good, but soaked beans no longer have liquid, so this was inconsistent.  Fixed.  Soaked beans can now go in box.

**Comment by jasonrohrer** [comment]
For peppercorns, they are smaller than yellow corn, and a spice, so they can be put into bottles (unlike corn or wheat).
