### ISSUE TITLE
Lack of Marked Grave Options

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#997]
Family comes in many forms. 

Honoring your dead family member should reflect that.

There is a lack of marked grave options.

Here are the ones that are missing imo:

1. Eve (makes finding the Eve grave easier. honors her great contribution by setting her grave apart from others.)
2. Husband and Wife
3. Father
4. Grandmother and Grandfather
5. Cousin
6. Niece and Nephew

Whatever your opinion on roleplay may be, family roleplay IS a central part of the game for SOME players.

The current ones that we ALREADY have are: Mother, Aunt, Uncle, Brother, Sister, Daughter, and Son.

**Comment by QuirkySmirkyIan** [comment]
Jason stated many years ago that Dad's weren't added because he didn't want the game to be some creepy sex simulator. I doubt that husband and wife will be added.

**Comment by jasonrohrer** [comment]
Yeah, there definite aren't "fathers" in the game.  Paternity is intentionally unknown.  Maybe it was the milkman, etc.  Also, most people live around their own family, so any fatherhood would be incestuous.  But Eve and Grandmother and Cousin are nice.  Niece and Nephew too.
