### ISSUE TITLE
UNropeable DOMESTIC mouflon

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLifeData7#998]
Currently, you CANNOT move DOMESTIC mouflons by using a rope.

Which is annoying 

for when you want to upgrade your sheep pen from a more basic version (property fence, etc) to the advanced version (wood fence pen).

for when you want to keep a back-up domestic mouflon (in a property fence with a property gate or elsewhere) because of sheep killers.

-----

Moving the sheep thru using the mechanics of when the animal follows you vs runs away from you (when the domestic mouflon has a baby) is NOT a viable option for moving it across 20 or more tiles coz it will only frustrate you as the mouflon switches states from with child and without. Also, the mouflon reacts to the nearest person. And in a town with plenty of people roaming around. This gets annoying quick.

**Comment by jasonrohrer** [comment]
Yeah, the idea here is that it's still partially wild, and won't allow itself to be roped.  This is intentional.  It's supposed to be a little annoying.
